src/components/VolumeSize/__tests__/__snapshots__/index.js.snap
src/components/VolumeSize/__tests__/index.js
src/components/VolumeSize/index.js

- Bug
When have no maxSize it should not display message isTooBig, same for minSize
1. Change conditions

fix: errors has wrong conditions

---

src/components/Switch/index.js

- Refactor
Clearer code
1. Adds comments
2. Refacto a tiny bit for better understanding and common function

style: adds comment and refacto code a bit

---

package.json
src/components/Link/__stories__/index.stories.mdx
src/components/UniversalLink/__stories__/index.stories.mdx
src/components/UniversalLink/__tests__/__snapshots__/index.js.snap
src/components/UniversalLink/__tests__/index.js
src/components/UniversalLink/index.js
src/helpers/renderWithTheme.js
src/helpers/shouldMatchEmotionSnapshot.js
src/helpers/shouldMatchEmotionSnapshotWithPortal.js
yarn.lock

- Bug
When you are using Link from react router dom or specify Link with as props your Universal Link will not work as expected because props to was not forward to our component

fix(universal-link): add to when using react-router-dom

---

src/components/CreationProgress/__stories__/index.stories.mdx
src/components/CreationProgress/__tests__/__snapshots__/index.js.snap
src/components/CreationProgress/index.js

- Feature
Multiple sizes on Creation Progress
1. Drop redondant styles
2. Add sizes

feat: add multiple creation progress sizes

---

LICENSE

doc(licence): add apache 2.0 licence

---

CODE_OF_CONDUCT.md

docs(code-of-conduct): add code of conduct

---

package.json
src/components/DateInput/__tests__/__snapshots__/index.test.js.snap
src/components/DateInput/__tests__/index.test.js
src/components/DateInput/index.js
yarn.lock

- Bug
Before | After
:-:   | -:

fix(DateInput): capitalize month and day names

---

package.json

docs(package): add licence, homepage, and url field

---

src/components/RichSelectTags/__stories__/index.stories.mdx
src/components/RichSelectTags/__tests__/__snapshots__/index.js.snap
src/components/RichSelectTags/__tests__/index.js
src/components/RichSelectTags/index.js

- Migration
I kinda struggled to have 100% coverage, I don't know why it does not want to include the deletion while the test is executed

feat: port RichSelectTags

---

src/components/CreationProgress/__tests__/__snapshots__/index.js.snap
src/components/CreationProgress/index.js

- Bug
Line width between dots when having long text is broken
1. Add some styles

fix: creationprogress space between lines

---

.github/workflows/ci.yml
package.json

fix: correct node engine version

---

src/components/Link/__tests__/__snapshots__/index.js.snap
src/components/Link/__tests__/index.js
src/components/UniversalLink/__tests__/__snapshots__/index.js.snap
src/components/UniversalLink/__tests__/index.js
src/components/UniversalLink/index.js

- Feature
+ some missing tests :)

feat(UniversalLink): add mailto native support

---

src/components/Checkbox/__stories__/index.stories.mdx
src/components/Checkbox/__tests__/__snapshots__/index.js.snap
src/components/Checkbox/__tests__/index.js
src/components/Checkbox/index.js

- Bug
When changin  `typograhyVariant` the text is not centered anymore but it should be.
1. Edit some styles
2. Add some tests (100%)
3. Add a story

fix: checkbox text alignement

---

package.json
src/components/Stepper/__stories__/index.stories.mdx
src/components/Stepper/__tests__/__snapshots__/index.js.snap
src/components/Stepper/index.js

- Feature
New design for `Stepper` component.
1. Removed side borders for + and - buttons
2. Changed colors and borders
3. Updated story
Basic:
Input hovered:
Input focused:
Side button hover:
Sizes:
Disabled:

feat(stepper): new design

---

src/components/Action/__stories__/index.stories.mdx
src/components/Action/index.js
src/components/ActionBar/__stories__/index.stories.mdx
src/components/ActionBar/index.js
src/components/ActivityIndicator/__stories__/index.stories.mdx
src/components/Alert/__stories__/index.stories.mdx
src/components/Alert/index.js
src/components/Avatar/__stories__/index.stories.mdx
src/components/Avatar/index.js

Documentation on A* components.
1. Changing/Adding Basic Story
2. Documentation on Story
3. Documentation on ArgsTables

docs: add story documentation on a components

---

src/components/Stepper/__tests__/__snapshots__/index.js.snap
src/components/Stepper/__tests__/index.js
src/components/Stepper/index.js

- Bug
When stepper width depends on parent border if you hover input it will change slightly its size (cf. video)
1. Added transparent border when not hovering input removing resize side effect
2. Added input events for unit testing
Before:
https://user-images.githubusercontent.com/15812968/119500710-642f4500-bd68-11eb-9d57-0c9c14dd84e9.mov
After:
https://user-images.githubusercontent.com/15812968/119500730-6a252600-bd68-11eb-88f3-a9d4172a2ecc.mov

fix(stepper): fixed border and added tests event

---

src/components/TextBox/__stories__/index.stories.mdx

- Bug
No TextBox story visible
1. Change Boxer import

fix: textbox story not working

---

src/components/RichSelect/__stories__/index.stories.mdx
src/components/RichSelect/__tests__/__snapshots__/index.js.snap
src/components/RichSelect/__tests__/index.js
src/components/RichSelect/index.js
src/components/RichSelectTags/__tests__/__snapshots__/index.js.snap
src/components/Tags/index.js
src/components/TimeInput/__tests__/__snapshots__/index.js.snap
src/components/UnitInput/__stories__/index.stories.mdx
src/components/UnitInput/__tests__/__snapshots__/index.js.snap
src/components/UnitInput/__tests__/index.js

- Bug
- When in multi mode, select doesn't display the label
- When isSearchable, select display an input which is not vertical aligned
- When selecting an option, select doesn't keep the scroll (documented)
- When disabled, select doesn't display the label
1. Lot of changes in RichSelect styles and props
2. UnitInput test wasn't good so fix it and comment
3. Add isSearchable story

fix: rich select issues

---

src/components/RichSelect/__stories__/index.stories.mdx
src/components/RichSelect/__tests__/__snapshots__/index.js.snap
src/components/RichSelect/__tests__/index.js
src/components/RichSelect/index.js
src/components/Slider/index.js
src/components/Toaster/index.js

- Enhancement
- Scaleway can work with SSR
1. Based on SCW Website and thanks to `yalc`, I successfully add the library to the website.
2. Change when needed call to Client API instead of Node API

feat: ssr safe rendering

---

src/components/CategoryIcon/__stories__/index.stories.mdx
src/components/Chart/__stories__/index.stories.mdx
src/components/Chart/index.js
src/components/Checkbox/__stories__/index.stories.mdx
src/components/Checkbox/__tests__/index.js
src/components/Checkbox/index.js
src/components/Command/__stories__/index.stories.mdx
src/components/Container/__stories__/index.stories.mdx
src/components/Container/index.js
src/components/Counter/__stories__/index.stories.mdx
src/components/Counter/index.js

To have better documentation for all starting C letter components.
⚠️ CreationProgress not include as full refacto is needed ⚠️ 
1. Updated stories
2. Fixed checkbox when progress is true not to be clickable

docs: updated all C components doc

---

src/components/Badge/__stories__/index.stories.mdx
src/components/BorderedBox/__stories__/index.stories.mdx
src/components/BorderedBox/index.js
src/components/Box/__stories__/index.stories.mdx
src/components/Boxer/__stories__/index.stories.mdx
src/components/Boxer/index.js
src/components/Breadcrumbs/__stories__/index.stories.mdx
src/components/Breadcrumbs/index.js
src/components/BulletList/__stories__/index.stories.mdx
src/components/BulletList/index.js
src/components/Button/__stories__/index.stories.mdx
src/components/Button/index.js

Update documentation of all components that start with letter `B`.

docs: updated all B components doc

---

src/components/RichSelect/index.js

- Bug
Restore innerRef prop
1. Add innerRef prop

fix: richselect innerRef

---

src/components/PasswordCheck/__stories__/index.stories.mdx
src/components/PasswordCheck/index.js
src/components/PasswordStrengthMeter/__stories__/index.stories.mdx
src/components/PasswordStrengthMeter/index.js
src/components/Pentagon/__stories__/index.stories.mdx
src/components/PhoneInput/__stories__/index.stories.mdx
src/components/PhoneInput/index.js
src/components/Placeholder/__stories__/index.stories.mdx
src/components/Placeholder/__tests__/__snapshots__/index.js.snap
src/components/Placeholder/__tests__/index.js
src/components/Placeholder/index.js
src/components/Popper/__stories__/index.stories.mdx
src/components/Popper/index.js
src/components/Progress/__stories__/index.stories.mdx
src/components/Progress/index.js
src/components/ProgressBar/__stories__/index.stories.mdx
src/components/ProgressBar/index.js
src/components/ProgressCircle/__stories__/index.stories.mdx
src/components/ProgressCircle/index.js
src/components/ProgressionButton/__stories__/index.stories.mdx
src/components/ProgressionButton/index.js

Refacto documentation of all P components:
- PasswordCheck
- PasswordStrengthMeter
- Pentagon
- PhoneInput
- Placeholder
- Popper
- Progress
- ProgressBar
- ProgressCircle
- ProgressionButton

docs: updated all P components doc

---

rollup.config.mjs

- Refactor
- Eslint warning on sort keys
- Change report.html to index.html in .report directory

chore(lint): sort keys ont rollup config file

---

src/components/DateInput/__tests__/__snapshots__/index.test.js.snap
src/components/Menu/__tests__/__snapshots__/index.js.snap
src/components/Placeholder/__tests__/__snapshots__/index.js.snap
src/components/Separator/__tests__/__snapshots__/index.js.snap
src/components/Separator/index.js
src/components/TextBox/__tests__/__snapshots__/index.test.js.snap

- Enhancement
Add aria role separator 
https://www.w3.org/TR/wai-aria-1.1/#separator
Add aria-orientation
https://www.w3.org/TR/wai-aria-1.1/#aria-orientation

fix(separator): add role and aria-orientation

---

src/theme/colors.js

Adds some colors into SWUI
- Refactor
New colors available into SWUI
1. Add missing colors

refactor: adds extra color into SWUI

---

src/components/Menu/__stories__/index.stories.mdx

Add documentation on each props and story.

docs(menu): add description

---

src/components/Checkbox/index.js
src/components/List/Cell.js
src/components/List/SelectBar.js
src/components/List/SortIcon.js
src/components/List/__stories__/index.stories.mdx
src/components/List/__tests__/__snapshots__/index.js.snap
src/components/List/__tests__/index.js
src/components/List/context.js
src/components/List/index.js
src/components/List/variantExplorer.js
src/components/List/variantProduct.js
src/components/List/variantTable.js
src/mocks/list.js
src/utils/orderBy.js

- Feature
Migrate our List component. Dropped the `card` variant
1. Add List Folder with all it needs
2. Did UT on the component
3. Add an utils too orderBy

feat: add list component

---

.storybook/preview.js
src/__stories__/Test.stories.mdx

docs: add documentation about testing

---

src/components/Icon/__stories__/index.stories.mdx
src/components/Icon/index.js
src/components/IconMessage/__stories__/index.stories.mdx
src/components/IconMessage/index.js
src/components/Image/__stories__/index.stories.mdx
src/components/Information/__stories__/index.stories.mdx

Documentation on i components
1. Documentation on Icon, Image, IconMessage
2. Skipped Information because it will be merged with IconMessage and Alert

docs: add i documentation

---

src/components/DateInput/__stories__/index.stories.mdx
src/components/DateInput/index.js
src/components/Description/__stories__/index.stories.mdx
src/components/Description/index.js
src/components/Dot/__stories__/index.stories.mdx
src/components/Dot/index.js
src/components/DotSteps/__stories__/index.stories.mdx
src/components/DotSteps/index.js

I put `feat` on the title to deply a new version because of merging icon, menuicon and categoryicon which was refactored (need to be implemented on our console)
Documentation on D components

feat: d components documentation

---

.eslintrc
src/components/List/SelectBar.js
src/components/List/__stories__/index.stories.mdx
src/components/List/__tests__/__snapshots__/index.js.snap
src/components/List/__tests__/index.js
src/components/List/index.js
src/components/Pagination/__stories__/ExampleChildren.js
src/components/Pagination/__stories__/index.stories.mdx
src/components/Pagination/__tests__/__snapshots__/index.test.js.snap
src/components/Pagination/__tests__/getPageNumbers.test.js
src/components/Pagination/__tests__/index.test.js
src/components/Pagination/getPageNumbers.js
src/components/Pagination/index.js
src/components/Pagination/usePaginatedData.js
src/mocks/list.js

- Feature
- Add pagination component
- Implement List with the new Pagination component
1. Add Pagination
2. Improve List component
3. Add UT for Pagination and List
url | screenshot | screenshot
url | screenshot | screenshot

feat: add pagination

---

.eslintrc
src/components/Checkbox/index.js
src/components/List/Cell.js
src/components/List/SelectBar.js
src/components/List/SortIcon.js
src/components/List/__stories__/index.stories.mdx
src/components/List/__tests__/__snapshots__/index.js.snap
src/components/List/__tests__/index.js
src/components/List/context.js
src/components/List/index.js
src/components/List/variantExplorer.js
src/components/List/variantProduct.js
src/components/List/variantTable.js
src/components/Pagination/__stories__/ExampleChildren.js
src/components/Pagination/__stories__/index.stories.mdx
src/components/Pagination/__tests__/__snapshots__/index.test.js.snap
src/components/Pagination/__tests__/getPageNumbers.test.js
src/components/Pagination/__tests__/index.test.js
src/components/Pagination/getPageNumbers.js
src/components/Pagination/index.js
src/components/Pagination/usePaginatedData.js
src/mocks/list.js
src/utils/orderBy.js

- Feature
Add list and pagination components
1. Add list
2. Add pagination
url | screenshot | screenshot
url | screenshot | screenshot

feat: add list component (#419)

---

src/components/List/__stories__/index.stories.mdx
src/components/List/__tests__/__snapshots__/index.js.snap
src/components/List/__tests__/index.js
src/components/List/index.js
src/components/Pagination/__tests__/__snapshots__/index.test.js.snap
src/components/Pagination/__tests__/index.test.js
src/components/Pagination/index.js

- Enhancement
Allow you to change the emptyText directly on the List component instead of its body (easier to customize globally).
Add role navigation in Pagination on main Navigation component
1. List change
2. Pagination change
3. Update snaps

feat: add some accessibility, customization on list and pagination

---

src/components/Pagination/index.js

- Bug
No infinite rerender when component is controlled, why its work in unit test ? 🤔 
1. Fix in Pagination by setPage

fix: pagination control infinite rendering

---

src/components/UnitInput/__stories__/index.stories.mdx
src/components/UnitInput/index.js
src/components/UniversalLink/__stories__/index.stories.mdx
src/components/Unselectable/__stories__/index.stories.mdx
src/components/VerificationCode/__stories__/index.stories.mdx
src/components/VerificationCode/index.js
src/components/VolumeSize/__stories__/index.stories.mdx
src/components/VolumeSize/index.js

Documentation on U* and V* components

docs: add u and v components

---

src/components/Menu/Item.js
src/components/Menu/__tests__/__snapshots__/index.js.snap

- Bug
Forward disabled props to Item Menu

fix(menu): disabled props wasn t forward to component

---

src/components/Button/__tests__/__snapshots__/index.js.snap
src/components/Button/__tests__/index.js
src/components/Button/index.js
src/components/Chart/__tests__/__snapshots__/index.js.snap
src/components/List/__tests__/__snapshots__/index.js.snap
src/components/Tooltip/__stories__/index.stories.mdx
src/components/Tooltip/__tests__/__snapshots__/index.js.snap
src/components/Tooltip/__tests__/index.js
src/components/Tooltip/index.js
src/components/TooltipIcon/__tests__/__snapshots__/index.js.snap

- Bug
Tooltip should be displayed near the children
1. Cleanup
2. Bug fix

fix: tooltip display

---

src/components/List/__stories__/index.stories.mdx
src/components/Pagination/__stories__/index.stories.mdx
src/components/Radio/__stories__/index.stories.mdx
src/components/Radio/__tests__/__snapshots__/index.js.snap
src/components/Radio/index.js
src/components/RadioBorderedBox/__stories__/index.stories.mdx
src/components/RadioBorderedBox/__tests__/__snapshots__/index.js.snap
src/components/RadioBorderedBox/index.js
src/components/Range/__stories__/index.stories.mdx
src/components/Reminder/__stories__/index.stories.mdx
src/components/Reminder/__tests__/__snapshots__/index.js.snap
src/components/Reminder/index.js
src/components/RichSelect/__stories__/index.stories.mdx
src/components/RichSelect/index.js

Documentation on R component. **No documentation on Range because this component is totally broken**

docs: r components

---

src/components/Button/__tests__/__snapshots__/index.js.snap
src/components/Chart/__tests__/__snapshots__/index.js.snap
src/components/List/__tests__/__snapshots__/index.js.snap
src/components/Tooltip/__tests__/__snapshots__/index.js.snap
src/components/Tooltip/index.js
src/components/TooltipIcon/__stories__/index.stories.mdx
src/components/TooltipIcon/__tests__/__snapshots__/index.js.snap
src/components/TooltipIcon/index.js

- Bug
Drop flexbox which cause some issues on shire

fix: tooltip flexbox drop

---

.github/workflows/size-limit.yml
package.json
yarn.lock

- Perf
Add workflow to compare bundle size  
First pipeline will not work : https://github.com/andresz1/size-limit-action/issues/33

perf(size): adding size script and workflow

---

src/components/List/index.js

- Bug
List doesn't display Placeholder when loading is finished
1. Changes between loader component and empty component

fix: list empty component

---

src/components/ScrollView/__stories__/index.stories.mdx
src/components/Separator/__stories__/index.stories.mdx
src/components/Slider/__stories__/index.stories.mdx
src/components/Slider/index.js
src/components/Sphere/__stories__/index.stories.mdx
src/components/StateBar/__stories__/index.stories.mdx
src/components/StateBar/index.js
src/components/StatusIndicator/__stories__/index.stories.mdx
src/components/StealthCopiable/__stories__/index.stories.mdx
src/components/Stepper/__stories__/index.stories.mdx
src/components/Stepper/index.js
src/components/Switch/__stories__/index.stories.mdx
src/components/Switch/index.js
src/components/SwitchButton/__stories__/index.stories.mdx

Updated documentation of:
- ScrollView
- Select
- Separator
- Slider
- Sphere
- StateBar
- StatusIndicator
- StealthCopiable
- Stepper
- Switch
- SwitchButton

docs(s): updated all S components docs

---

rollup.config.mjs

- Enhancement
This is to ensure output module is compatible with node > 14

build: add node > 14 target

---

src/components/Boxer/index.js
src/components/Container/__tests__/__snapshots__/index.js.snap
src/components/DotSteps/__tests__/__snapshots__/index.js.snap
src/components/FlexBox/__tests__/__snapshots__/index.js.snap
src/components/FlexBox/index.js
src/components/Label/index.js
src/components/Modal/index.js
src/components/Pentagon/index.js
src/components/Popper/index.js
src/components/ScrollView/index.js
src/components/TagsPoplist/__tests__/__snapshots__/index.js.snap

To be able to show prop of each components in storybook argstable.
1. Fixed all missing props in documentation

docs(storybook): fixed argstable

---

src/components/TabGroup/__stories__/index.stories.mdx
src/components/Table/__stories__/index.stories.mdx
src/components/Table/index.js
src/components/Tag/__stories__/index.stories.mdx
src/components/Tags/__stories__/index.stories.mdx
src/components/TagsPoplist/__stories__/index.stories.mdx
src/components/TagsPoplist/index.js
src/components/TextBox/__stories__/index.stories.mdx
src/components/TimeInput/__stories__/index.stories.mdx
src/components/Toaster/__stories__/index.stories.mdx
src/components/Tooltip/__stories__/index.stories.mdx
src/components/TooltipIcon/__stories__/index.stories.mdx
src/components/Touchable/__stories__/index.stories.mdx
src/components/Touchable/index.js
src/components/Typography/__stories__/index.stories.mdx
src/components/Typography/__tests__/__snapshots__/index.js.snap
src/components/Typography/index.js

Updated documentation of:
- TabGroup
- Table
- Tag
- Tags
- TagsPoplist
- TextBox
- TimeInput
- Toaster
- Tooltip
- TooltipIcon
- Touchable
- Typography

docs: updated all t components documentation

---

src/components/RichSelect/__tests__/__snapshots__/index.js.snap
src/components/RichSelect/index.js

- Bug
Added a background and boxshadow to richSelect so theme apply correctly to it.

fix(theme): fixed background richSelect for theming

---

src/components/Alert/__tests__/__snapshots__/index.test.tsx.snap
src/components/Alert/__tests__/index.test.tsx

fix: correct Alert tests

---

src/components/Typography/index.tsx
src/emotion.d.ts
src/theme/index.ts

Also removed duplicate emotion.d.ts and some unused variables
- Bug

fix(Typography): correct missing event in reakit event handlers

---

package.json

Force en_US.UTF8 english lang for all tests scripts
- Enhancement

chore: force english lang for tests scripts

---

src/components/Button/index.tsx
src/components/Menu/Item.tsx
src/components/Menu/__tests__/__snapshots__/index.tsx.snap
src/components/Menu/__tests__/index.tsx
src/components/Menu/index.tsx
src/components/Popper/__stories__/index.stories.mdx
src/components/Popper/__tests__/__snapshots__/index.tsx.snap
src/components/Popper/__tests__/index.tsx
src/components/Popper/index.tsx
src/helpers/shouldMatchEmotionSnapshotWithPortal.ts

refactor(menu): migration typescript

---

src/components/Dot/__tests__/__snapshots__/index.tsx.snap
src/components/Dot/__tests__/index.tsx
src/components/DotSteps/__tests__/__snapshots__/index.js.snap
src/components/DotSteps/index.tsx

Enhancement
Update the DotSteps styles
Update the new selected / active dot style.
1. Use aria-selected to mark selected dot
2. Use `styled` to customize dot styles
3. Update test snapshots
Before
After

feat(DotSteps): update component dots style

---

src/components/NavigationStepper/index.tsx

To be able to extend it with styled
- Bug

fix: add ability to pass className to NavigationStepper

---

commitlint.config.cjs
package.json

chore(commitlint): use new configuration

---

src/components/Menu/__tests__/__snapshots__/index.tsx.snap
src/components/Menu/__tests__/index.tsx
src/components/Menu/index.tsx

- Enhancement
Content inside menu will not be present on the DOM if the menu is not open.

fix(menu): allow to not render inside menu when it s not necessary

---

src/components/Modal/__stories__/index.stories.mdx
src/components/Modal/__tests__/__snapshots__/index.tsx.snap
src/components/Modal/__tests__/index.tsx
src/components/Modal/index.tsx

- Enhancement
Allows disclosure property to be a React element

feat(modal): makes disclosure a react element if wanted

---

src/components/Popper/__stories__/index.stories.mdx
src/components/Popper/__tests__/__snapshots__/index.tsx.snap
src/components/Popper/__tests__/index.tsx
src/components/Popper/index.tsx

- Enhancement
Adds possibility to give an element to popper disclosure

fix: popper disclosure type

---

src/components/List/__stories__/index.stories.tsx

- Bug
Fix the `List` default story
1. Add missing `data`, `columns` & `children` props

fix(list): default story

---

src/components/FlexBox/index.tsx
src/components/Grid/Col.tsx
src/components/Grid/Grid.tsx
src/components/Grid/Row.tsx
src/components/Switch/index.tsx
src/components/TabGroup/__tests__/__snapshots__/TabGroup.test.tsx.snap
src/components/TabGroup/index.tsx

Some invalid types that I noticed when updating scaleway-ui-wbsite
- Bug

fix: correct some components types

---

README.md

docs: add @emotion/styled to required deps

---

.github/workflows/ci.yml
.github/workflows/pull_request_title.yml

- Enhancement
Add node 17 test, build ci

chore(ci): upgrade node version ci

---

src/components/TooltipIcon/index.tsx

- Enhancement
To be able to change vertical align of tooltip icon.

fix(tooltip-icon): fixed vertical align

---

src/components/Box/index.tsx

fix: add some missing props on XStyled type

---

.github/workflows/ci.yml
.jest/a11y.config.ts
.jest/unit.config.ts
README.md
package.json
src/__tests__/a11y.test.tsx
src/components/Alert/__tests__/__snapshots__/index.test.tsx.snap
src/components/Alert/__tests__/index.test.tsx
src/components/Alert/index.tsx
src/components/Toaster/__tests__/__snapshots__/index.tsx.snap
src/components/Toaster/__tests__/index.tsx

- Refactor
Make alert component more accessible.
1. Added `aria-label={type}` for div wrapping alert component with `role="region"`.
2. Added `aria-hidden="true"` for alert icon
3. Updated a11y testing system in order to be able to receive input parameter. ex: `yarn test:a11y src/components/Alert` will only run Alert a11y tests.
4. Updated readme

refactor(a11y): alert

---

src/components/BarStack/__stories__/index.stories.tsx
src/components/BarStack/__tests__/__snapshots__/index.test.tsx.snap
src/components/BarStack/index.tsx

- Enhancement
Add tooltip and gray background, lighten the second background

feat: add tooltip and background

---

src/__tests__/a11y.test.tsx
src/components/ActivityIndicator/__stories__/index.stories.tsx
src/components/Badge/__tests__/__snapshots__/index.tsx.snap
src/components/Badge/index.tsx
src/components/ExtendedReminder/__tests__/__snapshots__/index.tsx.snap
src/components/RadioBorderedBox/__tests__/__snapshots__/index.tsx.snap

- Enhancement
a11y tests on badge component
1. add role and aria-label

fix: a11y badge tests

---

src/__tests__/a11y.test.tsx
src/components/Counter/__tests__/__snapshots__/index.test.tsx.snap
src/components/Counter/__tests__/index.test.tsx
src/components/Counter/index.tsx
src/components/Icon/__tests__/__snapshots__/index.test.tsx.snap

- Enhancement
Counter to follow a11y
1. add aria-busy management
2. clean useless css

fix: a11y for counter

---

src/components/Alert/__tests__/__snapshots__/index.test.tsx.snap
src/components/Boxer/index.tsx
src/components/CreationProgress/__tests__/__snapshots__/index.test.tsx.snap
src/components/LineChart/__tests__/__snapshots__/index.tsx.snap
src/components/List/__tests__/__snapshots__/index.test.tsx.snap
src/components/PasswordStrengthMeter/__tests__/__snapshots__/index.test.tsx.snap
src/components/ProgressBar/index.tsx
src/components/ProgressionButton/index.tsx
src/components/Reminder/index.tsx
src/components/StateBar/__tests__/__snapshots__/index.tsx.snap
src/components/Toaster/__tests__/__snapshots__/index.tsx.snap
src/components/Typography/index.tsx
src/components/VolumeSize/__tests__/__snapshots__/index.tsx.snap

Also some type fixes
- Enhancement

fix(Typography): avoid passing down color to xstyled

---

src/components/Badge/__tests__/__snapshots__/index.tsx.snap
src/components/Button/__tests__/__snapshots__/index.tsx.snap
src/components/List/__tests__/__snapshots__/index.test.tsx.snap
src/components/Pagination/__tests__/__snapshots__/index.test.tsx.snap
src/theme/__tests__/index.ts
src/theme/colors/index.ts

Fix neutral background color to be darker

fix(theme): updated neutral background color

---

src/components/ActionBar/__tests__/__snapshots__/index.test.tsx.snap
src/components/ActionBar/index.tsx
src/components/ActivityIndicator/__stories__/index.stories.tsx
src/components/ActivityIndicator/__tests__/__snapshots__/index.test.tsx.snap
src/components/ActivityIndicator/index.tsx
src/components/Alert/index.tsx
src/components/Avatar/__stories__/index.stories.tsx
src/components/Avatar/__tests__/__snapshots__/index.tsx.snap
src/components/Avatar/index.tsx
src/components/List/__tests__/__snapshots__/index.test.tsx.snap
src/theme/index.ts

replace deprecated colors with new system
- Refactor
Migrate ActionBar, ActivityIndicator, Alert, Avatar with new theme
1. Update colors to use new theme

refactor: migrate ActionBar, ActivityIndicator, Alert, Avatar deprecated color with new system

---

src/theme/__tests__/index.ts
src/theme/colors/index.ts

my bad I choosed wrong color for border - revert

refactor(theme): revert border colors

---

.eslintrc
src/__stories__/utils/decorators.tsx
src/__stories__/utils/index.ts
src/__stories__/utils/story.ts
src/components/ActivityIndicator/__stories__/index.stories.tsx
src/components/UnitInput/__tests__/__snapshots__/index.tsx.snap
src/components/UnitInput/index.tsx

Proposal to use utils to reduce stories boilerplate.
- Refactor
No significant change in demo stories, but simpler code with less boilerplate.
1. use utils to create stories
2. use utils to create stories decorators
3. use CSF3 stories definition format , see https://storybook.js.org/blog/component-story-format-3-0/

refactor: less stories boilerplate

---

src/components/List/SelectBar.tsx
src/components/List/__stories__/index.stories.tsx
src/components/List/__tests__/__snapshots__/index.test.tsx.snap
src/components/List/__tests__/index.test.tsx
src/components/List/variantExplorer.tsx
src/components/List/variantProduct.tsx
src/components/List/variantTable.tsx
src/components/Menu/Item.tsx
src/components/Menu/__tests__/__snapshots__/index.tsx.snap
src/components/Menu/index.tsx
src/components/Modal/__tests__/__snapshots__/index.tsx.snap
src/components/Modal/index.tsx
src/components/NavigationStepper/__tests__/__snapshots__/index.test.tsx.snap
src/components/NavigationStepper/index.tsx

- Refactor
Use new colors
1. Modifies List, Menu, NavigationStepper and Modal
| url  | <img width="197" alt="Screenshot 2021-12-14 at 13 28 40" src="https://user-images.githubusercontent.com/3360430/146023452-18fb2838-591f-4605-a3d5-b1f9fd1ebbd3.png"> | <img width="176" alt="Screenshot 2021-12-14 at 13 28 32" src="https://user-images.githubusercontent.com/3360430/146023468-a82b1597-8c68-4958-847c-f0c5850c3a58.png"> |
| url  |  <img width="1046" alt="Screenshot 2021-12-14 at 15 03 36" src="https://user-images.githubusercontent.com/3360430/146023570-b7039364-64fb-4194-9336-a341199955c0.png"> | <img width="1292" alt="Screenshot 2021-12-14 at 15 03 18" …

refactor: colors on list menu modal navigationstepper components

---

src/components/Button/__tests__/__snapshots__/index.tsx.snap
src/components/Button/index.tsx
src/components/List/__tests__/__snapshots__/index.test.tsx.snap
src/components/Pagination/__tests__/__snapshots__/index.test.tsx.snap

fix: button color

---

src/components/Dot/index.tsx
src/components/Sphere/index.tsx
src/components/StealthCopiable/index.tsx
src/components/Stepper/__tests__/__snapshots__/index.tsx.snap
src/components/Stepper/index.tsx

- Refactor
New colors for sphere statusindicator stealthcopiable stepper
But had to keep some deprecated for sphere and statusindicator

refactor: colors for sphere statusindicator stealthcopiable stepper

---

src/components/List/__tests__/__snapshots__/index.test.tsx.snap
src/components/List/variantProduct.tsx

- Bug
Wrong color for list expandable border
| url  | <img width="981" alt="Screenshot 2021-12-20 at 12 15 38" src="https://user-images.githubusercontent.com/3360430/146758935-04950d9f-f495-404c-8fb2-70d723d457b7.png"> | <img width="1277" alt="Screenshot 2021-12-20 at 12 15 30" src="https://user-images.githubusercontent.com/3360430/146758952-4f90c53c-97fc-4517-85f4-2fc3115388ac.png"> |

fix: list expandable color

---

src/__tests__/a11y.test.tsx
src/components/StealthCopiable/__tests__/__snapshots__/index.tsx.snap
src/components/StealthCopiable/index.tsx

- Enhancement
Better accessibility on stealthcopiable
1. adds aria-live on button

fix: a11y for stealthcopiable

---

src/components/Switch/__stories__/index.stories.tsx
src/components/Switch/__tests__/__snapshots__/index.tsx.snap
src/components/Switch/index.tsx

- Enhancement
Fix Switch issue and migrate colors
1. Fix weird issue were switch ball is not well palced
2. Migrate to new colors

feat: migrate switch to new colors

---

src/components/Switch/__tests__/__snapshots__/index.tsx.snap
src/components/Switch/index.tsx

- Bug
force `box-sizing:content-box;` otherwise its broken in our console because we have a default rule `box-sizing:border-box;`

fix: box sizing property on switch component

---

.storybook/preview.js
README.md
src/components/Button/__stories__/index.stories.tsx
src/components/DotSteps/__tests__/__snapshots__/index.tsx.snap
src/components/DotSteps/index.tsx
src/components/Grid/Col.tsx
src/components/Grid/Row.tsx
src/components/Grid/__tests__/__snapshots__/index.tsx.snap
src/components/PasswordCheck/__tests__/__snapshots__/index.test.tsx.snap
src/components/Placeholder/__tests__/__snapshots__/index.tsx.snap
src/components/UnitInput/__tests__/__snapshots__/index.tsx.snap
src/components/UnitInput/index.tsx
src/utils/index.ts
src/utils/normalize.ts

- Feature
This is to avoid to some magic fuckery we started doing since the removal of GlobalStyle and have a shared ground of css development 
| url  | <img width="949" alt="Screenshot 2021-12-21 at 17 33 18" src="https://user-images.githubusercontent.com/2802867/146965465-8bbac268-8a8f-4dee-9ba6-dd5a14ec1684.png"> | <img width="948" alt="Screenshot 2021-12-21 at 17 33 13" src="https://user-images.githubusercontent.com/2802867/146965498-6c9901c9-28b2-4a6f-8ac1-d58f0302de6e.png">

feat: provide modern normalize function

---

src/components/VolumeSize/__tests__/__snapshots__/index.tsx.snap

- Bug
Fix failing snapshots introduced with https://github.com/scaleway/scaleway-ui/commit/7d6b719f1603f1035104caa12621c58af48d6fc9 (#1027)

fix: update failing snapshots

---

package.json
src/components/ActivityIndicator/__tests__/__snapshots__/index.test.tsx.snap
src/components/ActivityIndicator/index.tsx
src/components/Button/__tests__/__snapshots__/index.tsx.snap
src/components/Checkbox/__tests__/__snapshots__/index.tsx.snap
src/components/List/__tests__/__snapshots__/index.test.tsx.snap
src/components/NavigationStepper/__tests__/__snapshots__/index.test.tsx.snap
src/components/Pagination/__tests__/__snapshots__/index.test.tsx.snap
src/components/Table/__tests__/__snapshots__/index.tsx.snap
src/components/Tags/__tests__/__snapshots__/index.tsx.snap
yarn.lock

refactor(ActivityIndicator): port circular-progressbar

---

src/__tests__/a11y.test.tsx
src/components/ExtendedReminder/__tests__/__snapshots__/index.tsx.snap
src/components/ExtendedReminder/index.tsx

- Migration
1. Add `role="region"` and `aria-label` to the container
2. Set the badge as `strong`
3. Add `aria-hidden` to the icon
4. Set the title as `em`

refactor(extended-reminder): add a11y

---

src/components/Switch/__tests__/__snapshots__/index.tsx.snap
src/components/Switch/index.tsx

fix(Switch): increase hidden input surface to allow click contact

---

src/components/Switch/__stories__/index.stories.tsx
src/components/Switch/__tests__/__snapshots__/index.tsx.snap
src/components/Switch/index.tsx

- Bug
- Enhancement
Input should not be under the ball
1. Ball is behind the input
2. Make some beautiful styles

fix: switch input

---

src/components/Alert/__stories__/index.stories.tsx
src/components/Checkbox/__stories__/index.stories.tsx
src/components/DateInput/__stories__/index.stories.tsx
src/components/Icon/__stories__/index.stories.tsx
src/components/Menu/__stories__/index.stories.tsx
src/components/Modal/__stories__/index.stories.tsx
src/components/Pagination/__stories__/index.stories.tsx
src/components/PhoneInput/__stories__/index.stories.tsx
src/components/Popper/__stories__/index.stories.tsx
src/components/ProgressBar/__stories__/index.stories.tsx
src/components/RichSelect/__stories__/index.stories.tsx
src/components/Stepper/__stories__/index.stories.tsx
src/components/Switch/__stories__/index.stories.tsx
src/components/TextBox/__stories__/index.stories.tsx
src/components/Toaster/__stories__/index.stories.tsx
src/components/Tooltip/__stories__/index.stories.tsx
src/components/Typography/__stories__/index.stories.tsx
src/theme/__tests__/index.ts

refactor: remove Box(er)? usage in stories

---

src/__tests__/a11y.test.tsx
src/components/Stepper/__stories__/index.stories.tsx
src/components/Stepper/__tests__/__snapshots__/index.tsx.snap
src/components/Stepper/index.tsx

- Refactor
Make stepper more accessible.
1. Changed center touchable into box as button can't have nested interactions + added aria live and role
2. Fixed abbr inside stepper when added + made it not selectable
3. Fixed a11y tests: it was doing an includes(component) which is not properly working as by adding Stepper in tests it was also testing NavigationStepper. I fixed it to be more strict.

refactor(a11y): stepper and a11y tests fix

---

src/components/TabGroup/Tab.tsx
src/components/TabGroup/__tests__/Tab.test.tsx
src/components/TabGroup/__tests__/TabGroup.test.tsx
src/components/TabGroup/__tests__/__snapshots__/Tab.test.tsx.snap
src/components/TabGroup/__tests__/__snapshots__/TabGroup.test.tsx.snap
src/components/TabGroup/index.tsx
src/components/Table/__tests__/__snapshots__/index.tsx.snap
src/components/Table/index.tsx

- Migration
Migrate TabGroup component and Table to the new Design System
1. Migrate components
2. Update snaps
| url  | <img width="1059" alt="Capture d’écran 2021-12-24 à 11 13 28" src="https://user-images.githubusercontent.com/24531136/147343876-9f8350cd-33de-4b04-94fd-9de6e977626a.png"> | <img width="1073" alt="Capture d’écran 2021-12-24 à 11 13 52" src="https://user-images.githubusercontent.com/24531136/147343905-83ec4c1d-b661-42d2-920c-47c42e52aa8a.png"> |
| url  | <img width="1030" alt="Capture d’écran 2021-12-24 à 11 14 26" src="https://user-images.githubusercontent.com/24531136/147343947-43f1e444-d2bd-4cca-b04c-277992ed9d60.png"> | <img width="1051" alt="Capture d’écran 2021-12-24 à 11 14 47" …

feat: migrate tabgroup and table to new ds

---

src/__stories__/Documentation.stories.mdx
src/__stories__/Theme.stories.mdx
src/components/Alert/__stories__/index.stories.tsx
src/components/Badge/__stories__/index.stories.tsx
src/components/Button/__stories__/index.stories.tsx
src/components/Container/__stories__/index.stories.tsx
src/components/Counter/__stories__/index.stories.tsx
src/components/DateInput/__stories__/index.stories.tsx
src/components/Dot/__stories__/index.stories.tsx
src/components/ExtendedReminder/__stories__/index.stories.tsx
src/components/Menu/__stories__/index.stories.tsx
src/components/NavigationStepper/__stories__/index.stories.tsx
src/components/Pagination/__stories__/index.stories.tsx
src/components/PasswordStrengthMeter/__stories__/UncontrolledPasswordStrengthMeter.tsx
src/components/Popper/__stories__/index.stories.tsx
src/components/ProgressBar/__stories__/index.stories.tsx
src/components/ProgressionButton/__stories__/index.stories.tsx
src/components/RadioBorderedBox/__stories__/index.stories.tsx
src/components/Reminder/__stories__/index.stories.tsx
src/components/RichSelect/__stories__/index.stories.tsx
src/components/Separator/__stories__/index.stories.tsx
src/components/Separator/__tests__/__snapshots__/index.tsx.snap
src/components/Separator/__tests__/index.tsx
src/components/StateBar/__stories__/index.stories.tsx
src/components/StatusIndicator/__stories__/index.stories.tsx
src/components/Stepper/__stories__/index.stories.tsx
src/components/SwitchButton/__stories__/index.stories.tsx
src/components/TimeInput/__stories__/index.stories.tsx
src/components/Toaster/__stories__/index.stories.tsx

refactor: remove xstyled shorthand props in stories

---

src/components/VolumeSize/__tests__/__snapshots__/index.tsx.snap
src/components/VolumeSize/index.tsx

- Refactor
Make volume size more accessible.

refactor(a11y): volumeSize

---

src/components/Alert/__tests__/__snapshots__/index.test.tsx.snap
src/components/Alert/index.tsx
src/components/Toaster/__tests__/__snapshots__/index.tsx.snap

- Enhancement
Makes alert content full width so it can allow a button on far right end.
Nothing should change visually for existing content.

fix: alert width to allow dismiss button

---

src/components/Tooltip/__stories__/index.stories.tsx
src/components/Tooltip/__tests__/__snapshots__/index.test.tsx.snap
src/components/Tooltip/index.tsx
yarn.lock

- Bug
White tooltip border incorrect

fix: fixes issue with tooltip border

---

src/components/SwitchButton/__tests__/__snapshots__/index.tsx.snap
src/components/SwitchButton/index.tsx
yarn.lock

- Enhancement
Use new colors in switch button

feat: new colors in switch button

---

src/components/Reminder/__stories__/index.stories.tsx
src/components/Reminder/__tests__/__snapshots__/index.tsx.snap
src/components/Reminder/index.tsx
src/components/RichSelect/__tests__/__snapshots__/index.tsx.snap
src/components/RichSelect/index.tsx
src/components/Slider/index.tsx
src/components/TimeInput/__tests__/__snapshots__/index.tsx.snap
src/components/UnitInput/__tests__/__snapshots__/index.tsx.snap

Update theme colors of Reminder, RichSelect & Slider
- Refactor
some grey level changes
| multi | ![image](https://user-images.githubusercontent.com/62407/147680403-9026d1d8-eeec-43b3-93fa-5cc1aa3b84b5.png) | ![image](https://user-images.githubusercontent.com/62407/147681183-5c442792-ae9f-445c-943d-e3ba01e3e562.png)|
| error  |![image](https://user-images.githubusercontent.com/62407/147676132-eba85222-9637-4a57-9abb-1c6cd776b1de.png) | ![image](https://user-images.githubusercontent.com/62407/147681226-8a729bdb-69e6-4679-a213-8382e04cac56.png)| 
| loading  | ![image](https://user-images.githubusercontent.com/62407/147676036-2442ba79-24a6-4056-9c7d-d7dbaa9f6fd5.png) | …

refactor: update theme colors of Reminder, RichSelect & Slider

---

src/theme/__tests__/index.ts
src/theme/index.ts

fix(theme): ensure createTheme return a Theme type

---

CONTRIBUTING.md
README.md

To add contribution.md where to guide contributors. Updated readme.md to show we are open for contribution.

docs: contribution.md and updated readme

---

src/components/Alert/__tests__/__snapshots__/index.test.tsx.snap
src/components/Alert/index.tsx
src/components/ExtendedReminder/__tests__/__snapshots__/index.tsx.snap
src/components/ExtendedReminder/index.tsx
src/components/Radio/__tests__/__snapshots__/index.tsx.snap
src/components/Radio/index.tsx
src/components/RadioBorderedBox/__tests__/__snapshots__/index.tsx.snap
src/components/Range/__tests__/__snapshots__/index.tsx.snap
src/components/Range/index.tsx
src/components/RichSelect/__tests__/__snapshots__/index.tsx.snap
src/components/RichSelect/index.tsx
src/components/TimeInput/__tests__/__snapshots__/index.tsx.snap
src/components/Toaster/__tests__/__snapshots__/index.tsx.snap
src/components/UnitInput/__tests__/__snapshots__/index.tsx.snap

refactor: remove some extraneous Box

---

src/components/Pagination/__stories__/index.stories.tsx
src/components/Placeholder/Block.tsx
src/components/Placeholder/Blocks.tsx
src/components/Placeholder/BoxWithIcon.tsx
src/components/Placeholder/Donut.tsx
src/components/Placeholder/IconPlaceholder.tsx
src/components/Placeholder/Line.tsx
src/components/Placeholder/List.tsx
src/components/Placeholder/Slider.tsx
src/components/Placeholder/__stories__/index.stories.tsx
src/components/Placeholder/__tests__/__snapshots__/index.tsx.snap
src/components/Placeholder/__tests__/index.tsx
src/components/Placeholder/index.tsx

Usage does not change for most of the component except some props cohesion
- Refactor

feat: rework Placeholder to remove most Box

---

src/components/Radio/__stories__/index.stories.tsx
src/components/Radio/__tests__/__snapshots__/index.tsx.snap
src/components/Radio/__tests__/index.tsx
src/components/Radio/index.tsx
src/components/RadioBorderedBox/__stories__/index.stories.tsx
src/components/RadioBorderedBox/__tests__/__snapshots__/index.tsx.snap
src/components/RadioBorderedBox/__tests__/index.tsx
src/components/RadioBorderedBox/index.tsx

- Enhancement
Aligns Radio component with Checkbox one (font, error, etc)
1. Adds error block
2. Refactor color determination
3. Font management
| url  | <img width="135" alt="Screenshot 2022-01-31 at 17 28 23" src="https://user-images.githubusercontent.com/3360430/151832961-cbef4448-01ae-4b2d-893a-272d7f007f43.png"> | <img width="150" alt="Screenshot 2022-01-31 at 17 28 15" src="https://user-images.githubusercontent.com/3360430/151833000-a54c145a-b09f-4f55-bd9c-0e092c21dfd6.png"> |

fix: aligns radio component with checkbox one

---

src/components/Sphere/__tests__/__snapshots__/index.tsx.snap
src/components/Sphere/__tests__/index.tsx
src/components/Sphere/index.tsx

fix(Sphere): refactor props + remove spread

---

src/components/StealthCopiable/__tests__/__snapshots__/index.tsx.snap
src/components/StealthCopiable/index.tsx
src/components/TooltipIcon/index.tsx

- Enhancement
I have removed line-height and padding so button doesn't make parent div bigger + I changed typing for `tooltip` prop as original tooltip component can receive a ReactNode.

fix(stealth-copiable): added new prop and fixed line-height

---

src/components/Sphere/__stories__/index.stories.tsx

docs: correct Sphere stories

---

src/components/Radio/index.tsx
src/components/RadioBorderedBox/__tests__/__snapshots__/index.tsx.snap
src/components/RadioBorderedBox/index.tsx

fix: some optimisation on Radio and RadioBorderedBox

---

src/__tests__/a11y.test.tsx
src/components/Alert/__stories__/index.stories.tsx
src/components/Alert/__tests__/__snapshots__/index.test.tsx.snap
src/components/Alert/__tests__/index.test.tsx
src/components/Alert/index.tsx
src/components/Avatar/__stories__/index.stories.tsx
src/components/Container/__tests__/__snapshots__/index.tsx.snap
src/components/Container/__tests__/index.tsx
src/components/Container/index.tsx
src/components/ExtendedReminder/__stories__/index.stories.tsx
src/components/TextBox/index.tsx
src/components/Toaster/__tests__/__snapshots__/index.tsx.snap

Alert does not need role or aria-label 
- Enhancement

fix: correct a11y on Alert + correct some errors on unit tests

---

src/components/Tags/index.tsx

- Enhancement
Add className props on Tags Components

fix(tags): add className

---

src/components/Avatar/__tests__/__snapshots__/index.tsx.snap
src/components/Avatar/index.tsx

feat: box-less Avatar

---

.github/renovate.json

chore(renovate): upgrade renovate config managers

---

src/components/Box/index.tsx

fix(types): add missing fontStyle prop in BoxProps

---

src/components/StealthCopiable/__tests__/__snapshots__/index.tsx.snap
src/components/StealthCopiable/index.tsx

- Enhancement
| url  | ![Screenshot 2022-02-23 at 14 28 52](https://user-images.githubusercontent.com/15812968/155329048-411f7ac2-f6a1-43c6-93ae-8a48d1f9271b.png) | ![Screenshot 2022-02-23 at 14 28 06](https://user-images.githubusercontent.com/15812968/155329071-fca06f48-1811-4a3e-a1db-f89c2c771387.png) |

fix: missing min-with for auto with in flex context

---

.github/workflows/deploy-storybook.yml

ci(deploy): fix build image versiong

---

src/components/List/__tests__/__snapshots__/index.test.tsx.snap
src/components/List/__tests__/index.test.tsx
src/components/List/types.ts
src/components/List/variantProduct.tsx

- Enhancement
Allow custom css for expandable inside list
1. forward classname

fix: adds custom css for list expandable

---

src/components/Modal/__stories__/index.stories.tsx
src/components/Popper/__stories__/index.stories.tsx
src/components/RadioBorderedBox/index.tsx

- Bug
Clean up Typescript errors

chore(typescript): fix somes errors typescript

---

.github/workflows/sync-design-tokens.yml
CHANGELOG.md
package.json
scripts/figma-synchronise-tokens.sh
src/theme/tokens/dark.ts
src/theme/tokens/light.ts

- Enhancement
Schedule script wasn't much working + I moved others into color

fix: script and tokens

---

.github/workflows/sync-design-tokens.yml

Forgot to install node modules.

fix: missing yarn install

---

.github/workflows/sync-design-tokens.yml
src/__stories__/components/Colors.tsx

- Bug
1. Fixed forgot typescript errors
2. Fixed CI to run every day of the week at 9:30 excluding weekend
3. Fixed run command trough CI to only prettier design tokens and avoid automatically created PR that is not concerning design tokens

fix: typescript errors and ci

---

src/theme/index.ts

fix: correct theme type

---

src/components/ActionBar/index.tsx
src/components/DateInput/__tests__/__snapshots__/index.test.tsx.snap
src/components/DateInput/index.tsx
src/components/Menu/index.tsx
src/components/Modal/__tests__/__snapshots__/index.tsx.snap
src/components/Modal/index.tsx
src/components/RichSelect/index.tsx
src/components/Tooltip/index.tsx

- Enhancement
background elevated color + overlay color on modal
1. Change some bg colors on elements
2. It should not change anything. Just nicer on dark theme mode

fix: background overlay and elevated colors

---

pnpm-lock.yaml

fix(pnpm): lockfile broken

---

src/components/DotSteps/__tests__/__snapshots__/index.tsx.snap
src/components/DotSteps/index.tsx

- Refactor
on hover on the dots, we have scale transform  
transform time is decreased to .2 second 
| Dot steps  | <img width="638" alt="Screenshot 2022-04-14 at 16 41 20" src="https://user-images.githubusercontent.com/18621012/163414257-b5f7f86a-7735-4a85-a72a-6825bf3648bd.png"> | <img width="638" alt="Screenshot 2022-04-14 at 16 41 10" src="https://user-images.githubusercontent.com/18621012/163414299-95ef9818-6a7c-408a-8dc9-c2a6db4051be.png"> |

refactor: dotsteps component

---

src/components/Stepper/index.tsx

- Enhancement
Optimises a bit Stepper

fix: stepper changes

---

src/components/Notice/index.tsx

- Bug
Removed proptypes and fixed warnings.

fix: removed and fixed notice proptypes

---

src/components/Tags/__tests__/__snapshots__/index.tsx.snap
src/components/Tags/index.tsx

- Bug
Tags component inherit his background from parent causing some issues with dark theme. To fix it I have set a fixed background to the input.
| url  | ![Screenshot 2022-05-04 at 12 12 26](https://user-images.githubusercontent.com/15812968/166663045-c9bfbd5e-1bd9-4c76-9c87-318d649d933d.png) | ![Screenshot 2022-05-04 at 12 12 30](https://user-images.githubusercontent.com/15812968/166663057-b1c4704b-036f-4caf-846c-0d197555f721.png)|

fix(tags): remove inheritance background

---

src/components/Modal/index.tsx

- Bug
Fix children type for Modal component
1. Reimplement children prop type

fix: modal types

---

.github/workflows/ci.yml
.github/workflows/pull_request_title.yml
.github/workflows/sync-design-tokens.yml
.github/workflows/visual-testing.yml
package.json

ci(node): upgrade to node 18

---

src/theme/deprecated/colors.ts

fix: remove unused deprecated colors

---

src/components/StepList/index.tsx

fix: allow classname on steplist

---

src/components/Radio/__tests__/__snapshots__/index.tsx.snap
src/components/Radio/index.tsx
src/components/RadioBorderedBox/__tests__/__snapshots__/index.tsx.snap

- Bug
Fix bug reported by @matthprost  on the SVG when we increase the size of icon 
| url  | 
| <img width="541" alt="Screenshot 2022-06-03 at 16 41 48" src="https://user-images.githubusercontent.com/18621012/171877297-cd94ecce-fe60-40c7-aad0-c79246554cca.png"> |

fix: svg size bug on radio

---

src/__tests__/a11y.test.tsx
src/components/Switch/__stories__/index.stories.tsx
src/components/Switch/__tests__/__snapshots__/index.tsx.snap
src/components/Switch/index.tsx
src/components/SwitchButton/__tests__/__snapshots__/index.tsx.snap
src/components/SwitchButton/index.tsx

- Feature
Fix a11y issues with `Switch` and `SwitchButton`.
- Rename `aria-checked` to `data-checked`
- Not forward not needed props
- Replace `<label />` in `Switch` by a `<div />` and add `aria-label` prop to the `<input />`, since the switch don't have a visible label

feat(Switch, SwitchButton): fix a11y issues

---

src/__tests__/a11y.test.tsx
src/components/DateInput/__tests__/__snapshots__/index.test.tsx.snap
src/components/TextBox/__tests__/__snapshots__/index.test.tsx.snap
src/components/TextBox/index.tsx
src/components/UnitInput/__tests__/__snapshots__/index.tsx.snap

- Bug
- Refactor
accessibility compatibility on Radio and TextBox

test: radio and TextBox accessibility

---

src/components/PieChart/__tests__/__snapshots__/index.tsx.snap
src/components/PieChart/__tests__/index.tsx
src/components/Tooltip/__tests__/__snapshots__/index.test.tsx.snap
src/components/Tooltip/__tests__/index.test.tsx
src/components/Tooltip/index.tsx

- Bug
I'm passing the wrong id into `aria-describedby`, I should pass `generatedId`

fix(tooltip): generatedId into aria-describedby

---

src/components/StatusIndicator/__stories__/index.stories.tsx
src/components/StatusIndicator/index.tsx

Deprecated was missing for StatusIndicator.

fix: status indicator deprecated

---

src/components/Icon/__tests__/__snapshots__/index.test.tsx.snap
src/components/Icon/__tests__/index.test.tsx
src/components/Icon/index.tsx

feat(Icon): add prominence support

---

src/components/Breadcrumbs/__tests__/__snapshots__/index.tsx.snap
src/components/Button/__tests__/__snapshots__/index.tsx.snap
src/components/Link/__tests__/__snapshots__/index.tsx.snap
src/components/Link/index.tsx
src/components/MarkDown/__tests__/__snapshots__/index.tsx.snap

- Enhancement
Force hover and focus style because it is overrided by GlobalStyles in our use cases. Can still be overrided with styled(Link)
1. Force hover styles color and text-decoration

fix: force link styles on hover

---

src/components/Button/__tests__/__snapshots__/index.tsx.snap
src/components/Button/index.tsx

- Bug
Fix button alignement with link variant

fix: button link alignement

---

src/components/Breadcrumbs/__tests__/__snapshots__/index.tsx.snap
src/components/Button/__tests__/__snapshots__/index.tsx.snap
src/components/Button/__tests__/index.tsx
src/components/Button/index.tsx
src/components/Link/__tests__/__snapshots__/index.tsx.snap
src/components/Link/index.tsx
src/components/List/__tests__/__snapshots__/index.test.tsx.snap
src/components/MarkDown/__tests__/__snapshots__/index.tsx.snap
src/components/Menu/__tests__/__snapshots__/index.tsx.snap
src/components/Pagination/__tests__/__snapshots__/index.test.tsx.snap

- Bug
Prevent weird gap and it should work on Safari too

fix: weird gaps in link

---

src/components/Breadcrumbs/__tests__/__snapshots__/index.tsx.snap
src/components/Button/__tests__/__snapshots__/index.tsx.snap
src/components/Link/__stories__/index.stories.tsx
src/components/Link/__tests__/__snapshots__/index.tsx.snap
src/components/Link/index.tsx
src/components/MarkDown/__tests__/__snapshots__/index.tsx.snap

- Bug
Fix link animation.
Before:
https://user-images.githubusercontent.com/15812968/183053882-fde7913d-05b2-44be-b14d-3ffd6ab563cb.mp4
After:
https://user-images.githubusercontent.com/15812968/183053942-06464669-0f45-4c55-8ff9-1faf46e22ecf.mp4

fix(link): animation is broken when text follow

---

src/components/Menu/__tests__/__snapshots__/index.tsx.snap
src/components/Menu/index.tsx

Portal the menu list in order to avoid element stacking issue
- Feature

feat(menu): portal menu list

---

src/components/List/index.tsx
src/components/List/types.ts
src/components/List/variantProduct.tsx

Fix list.ExpandableContent type
- Refactor

refactor: 💡 list.ExpandableContent type

---

src/components/BarChart/index.tsx

Fix BarChart tickValue prop using the Nivo.js related type
- Bug

fix(BarChart): tickvalue prop typing

---

src/components/RadioBorderedBox/index.tsx

- Bug
I change a prop by mistake.

fix: labelDescription parm

---

src/components/Radio/__tests__/__snapshots__/index.tsx.snap
src/components/Radio/index.tsx
src/components/RadioBorderedBox/__tests__/__snapshots__/index.tsx.snap
src/components/RadioBorderedBox/__tests__/index.tsx
src/components/SelectableCard/__tests__/__snapshots__/index.tsx.snap
src/components/SelectableCard/index.tsx

- Bug
Radio was generating a random id based on value and computedName which is useless.
SelectableCard suffered from re-render on scaleway form, I added a useMemo to make it work.

fix: radio and selectablecard

---

.jest/setupTests.ts
src/components/Button/__tests__/index.tsx
src/components/Checkbox/__tests__/index.tsx
src/components/List/__tests__/index.test.tsx
src/components/Loader/__tests__/index.test.tsx
src/components/NavigationStepper/__tests__/index.test.tsx
src/components/Pagination/__tests__/index.test.tsx
src/components/PieChart/__tests__/index.tsx
src/components/Placeholder/__tests__/index.tsx
src/components/Radio/__tests__/index.tsx
src/components/SelectNumber/__tests__/index.tsx
src/components/SelectableCard/__tests__/index.tsx
src/components/Table/__tests__/index.tsx
src/components/Tags/__tests__/index.tsx
src/components/Text/__tests__/index.test.tsx
src/components/Toaster/__tests__/index.tsx
src/components/Tooltip/__tests__/index.test.tsx
src/components/UnitInput/__tests__/index.tsx
src/utils/__tests__/index.tsx

- CI
Instead of mocking random for each specific tests I added it to global configuration as it won't affect others tests.

ci: mock random globally

---

codecov.yml

- CI
My bad this time config is correct.

ci(codecov): correct fix

---

src/components/SwitchButton/index.tsx

- Bug
Also forgot about disabled 😓

fix(SwitchButton): disabled prop

---

package.json
pnpm-lock.yaml

- Chore
Remove unused react-count package.

chore(react-count): remove unused dependency

---

src/components/Toggle/__tests__/index.tsx
src/components/Toggle/index.tsx

- Bug
Toggle is not correctly working as controlled / uncontrolled component.
I forgot so snippet of code to make it work better.

fix(toggle): uncontrolled and controlled behavior are wrong

---

src/components/Toggle/index.tsx

fix(Toggle): add classname

---

src/components/Radio/__tests__/__snapshots__/index.tsx.snap

fix: update ci

---

src/components/List/__tests__/__snapshots__/index.test.tsx.snap
src/components/Placeholder/__tests__/__snapshots__/index.tsx.snap
src/components/Placeholder/index.tsx

- Bug
Make placeholder compatible dark theme

fix(PlaceHolder): make it compatible dark theme

---

.eslintrc
.storybook/components/Page.tsx
src/components/Link/index.tsx
src/components/SelectableCard/__stories__/index.stories.tsx
src/components/SelectableCard/index.tsx
src/components/Tabs/__tests__/index.test.tsx

Remove react import
Add  "plugin:react/jsx-runtime" to eslint
- Refactor

fix(react): remove unused import thanks to new transformer

---

package.json
pnpm-lock.yaml

remove useless require-for-string peer-deps
Remove usel

docs(storybook): remove useless require-for-string peer-deps

---

src/components/LineChart/__tests__/__snapshots__/index.tsx.snap
src/components/LineChart/__tests__/index.tsx
src/components/LineChart/index.tsx

When data was first undefined and then defined, no graph were selected.
I've added a `useEffect` that populates the `selected` state when the data is initialized
- Enhancement

fix(linechart): select chart even when provided asynchronously

---

package.json
pnpm-lock.yaml

Reverts scaleway/scaleway-ui#1845

Revert "docs(storybook): remove useless require-for-string peer-deps"

---

.github/workflows/deploy-storybook.yml
.github/workflows/deploy-website.yml
.github/workflows/teardown_pull_request.yml

- Bug
- Feature
- Enhancement
- Migration
- Refactor
1.
2.
3.

fix: ci for production deployment

---

.github/workflows/deploy-storybook.yml
.github/workflows/deploy-website.yml
.github/workflows/teardown_pull_request.yml

fix(deploy): change namespace id

---

website/src/components/GithubAndDocumentationButtons.tsx

fix(website): documentation url

---

.github/workflows/deploy-storybook.yml
.github/workflows/deploy-website.yml
.github/workflows/teardown_pull_request.yml

- Bug
- Feature
- Enhancement
- Migration
- Refactor
1.
2.
3.

fix(ci): persist deployments in pull requests

---

src/components/Status/__tests__/__snapshots__/index.tsx.snap
src/components/Status/__tests__/index.tsx
src/components/Status/index.tsx

ClassName of status should be on container and not on one of the childrens.

fix(status): classname on container

---

src/components/List/__tests__/__snapshots__/index.test.tsx.snap
src/components/Placeholder/Line.tsx
src/components/Placeholder/__tests__/__snapshots__/index.tsx.snap
src/components/Tooltip/helpers.ts

fix(Placeholder): set max-width on Line to avoid overflow

---

src/components/List/__tests__/__snapshots__/index.test.tsx.snap
src/components/Placeholder/__tests__/__snapshots__/index.tsx.snap
src/components/Placeholder/index.tsx

feat(Placeholder): drop Box

---

.storybook/preview.tsx
src/components/Menu/__stories__/index.stories.tsx

- Enhancement
To remove decorators from Storybook code snippet that is shown as example. I made this setting global so we won't have to set it every time.

docs: remove decorators from code snippets - global configuration

---

.eslintrc
src/components/Menu/__stories__/FunctionDisclosure.tsx
src/components/Menu/__stories__/Variants.tsx
src/components/Toggle/__stories__/index.stories.tsx

- Enhancement
Writing story should be easier. Allow underscore as Story params to make Storybook show beautiful code snippets
1. Customize eslintrc

fix: improve story writing

---

src/components/DateInput/__tests__/__snapshots__/index.test.tsx.snap
src/components/Expandable/__tests__/__snapshots__/index.tsx.snap
src/components/Expandable/index.tsx
src/components/RichSelect/__tests__/__snapshots__/index.tsx.snap
src/components/RichSelect/index.tsx
src/components/TextBox/__tests__/__snapshots__/index.test.tsx.snap
src/components/TextBox/index.tsx
src/components/TimeInput/__tests__/__snapshots__/index.tsx.snap
src/components/UnitInput/__tests__/__snapshots__/index.tsx.snap

Remove `Box` and `BoxProps` from `Expandable`
- Refactor

refactor(expandable): remove box

---

src/components/SelectNumber/__stories__/index.stories.tsx
src/components/SelectNumber/__tests__/__snapshots__/index.tsx.snap
src/components/SelectNumber/index.tsx

Remove `Box` from `SelectNumber`
- Refactor

refactor(selectnumber): remove box

---

src/components/Tabs/Tab.tsx

fix(tabs): incorrect tab type

---

src/components/Modal/__tests__/__snapshots__/index.tsx.snap
src/components/Modal/index.tsx

- Bug
- Feature
- Enhancement
- Migration
- Refactor
1.
2.
3.

fix(modal): make sure close button is in front of content

---

src/components/Toggle/__stories__/index.stories.tsx

Toggle were not toggling on storybook
- Bug

fix(toggle): fix not toggling on storybook

---

src/components/Table/__stories__/Hoverable.stories.tsx
src/components/Table/__stories__/Loader.stories.tsx
src/components/Table/__stories__/Playground.stories.tsx
src/components/Table/__stories__/Template.stories.tsx
src/components/Table/__stories__/index.stories.tsx
src/components/Table/__tests__/__snapshots__/index.tsx.snap
src/components/Table/index.tsx

Fixed cash on storybook story of table due to last changes. @chambo-e I had to revert to keep function that return a styled, it seems like storybook doesn't want a styled as component in their stories.
Also I updated stories to be formatted correctly.

docs(Table): fixed table crashing story and updated to new way

---

src/components/BarChart/__stories__/FormattedValuesAndTooltip.stories.tsx
src/components/BarChart/__stories__/MultiSeries.stories.tsx
src/components/BarChart/__stories__/Playground.stories.tsx
src/components/BarChart/__stories__/PositiveNegative.stories.tsx
src/components/BarChart/__stories__/Template.stories.tsx
src/components/BarChart/__stories__/index.stories.tsx
src/components/BarStack/__stories__/Playground.stories.tsx
src/components/BarStack/__stories__/Template.stories.tsx
src/components/BarStack/__stories__/WithMax.stories.tsx
src/components/BarStack/__stories__/index.stories.tsx
src/components/BarStack/__stories__/mockData.ts

- Refactor
Rewrite stories for BarChart and BarStack. Badge was already done.

refactor(BarChart,BarStack): rewrite stories

---

src/components/Breadcrumbs/__stories__/OnClick.stories.tsx
src/components/Breadcrumbs/__stories__/Playground.stories.tsx
src/components/Breadcrumbs/__stories__/Selected.stories.tsx
src/components/Breadcrumbs/__stories__/Template.tsx
src/components/Breadcrumbs/__stories__/To.stories.tsx
src/components/Breadcrumbs/__stories__/Variants.stories.tsx
src/components/Breadcrumbs/__stories__/index.stories.tsx

- Refactor
Rewrite stories for `Breadcrumbs`

refactor(Breadcrumbs): rewrite stories

---

src/components/SelectNumber/__stories__/index.stories.tsx
src/components/SelectNumber/__tests__/__snapshots__/index.tsx.snap
src/components/SelectNumber/index.tsx

- Enhancement
Allows SelectNumber to have unlimited max value.

fix(SelectNumber): max value undefined makes it unlimited value

---

src/components/Tag/__stories__/Disabled.stories.tsx
src/components/Tag/__stories__/Icons.stories.tsx
src/components/Tag/__stories__/Loading.stories.tsx
src/components/Tag/__stories__/OnClose.stories.tsx
src/components/Tag/__stories__/Playground.stories.tsx
src/components/Tag/__stories__/Template.stories.tsx
src/components/Tag/__stories__/Variants.stories.tsx
src/components/Tag/__stories__/index.stories.tsx
src/components/Tags/__stories__/Playground.stories.tsx
src/components/Tags/__stories__/Template.stories.tsx
src/components/Tags/__stories__/index.stories.tsx
src/components/TagsPoplist/__stories__/Multiline.stories.tsx
src/components/TagsPoplist/__stories__/Playground.stories.tsx
src/components/TagsPoplist/__stories__/Template.stories.tsx
src/components/TagsPoplist/__stories__/Threshold.stories.tsx
src/components/TagsPoplist/__stories__/index.stories.tsx

docs: rewrite `Tag`, `Tags` and `TagsPoplist` stories

---

README.md
src/components/Grid/Col.tsx
src/components/Grid/Grid.tsx
src/components/Grid/Row.tsx
src/components/Grid/__tests__/__snapshots__/index.tsx.snap
src/components/PasswordCheck/__tests__/__snapshots__/index.test.tsx.snap

refactor(grid): remove box props

---

.github/workflows/teardown_pull_request.yml

We don't have to delete storybook site as we are using Chromatic now.

ci: fix teardown workflow

---

src/components/RichSelect/__tests__/__snapshots__/index.tsx.snap
src/components/RichSelect/index.tsx
src/components/TimeInput/__tests__/__snapshots__/index.tsx.snap
src/components/UnitInput/__tests__/__snapshots__/index.tsx.snap
src/components/UnitInput/index.tsx

- Refactor
Remove Box and spread usage for `RichSelect`.

refactor(RichSelect): remove Box

---

.storybook/preview.tsx
src/__stories__/components/ThemeWrapper.tsx
src/components/CopyButton/index.tsx
src/components/Snippet/__stories__/LongMultiline.stories.tsx
src/components/Snippet/__stories__/LongSingleLine.stories.tsx
src/components/Snippet/__stories__/Multiline.stories.tsx
src/components/Snippet/__stories__/Playground.stories.tsx
src/components/Snippet/__stories__/Prefixes.stories.tsx
src/components/Snippet/__stories__/SingleLine.stories.tsx
src/components/Snippet/__stories__/Template.stories.tsx
src/components/Snippet/__stories__/index.stories.tsx
src/components/Snippet/__tests__/__snapshots__/index.tsx.snap
src/components/Snippet/__tests__/index.tsx
src/components/Snippet/index.tsx

- Feature
Snippet component to display part of code or commands. There is a single line mode, multiline mode and you can add prefixes (command line or line number). In multiline mode snippet will show a extend button to display all code.

feat(Snippet): new component

---

src/components/PasswordCheck/__tests__/__snapshots__/index.test.tsx.snap
src/components/PasswordCheck/index.tsx

| url  | <img width="1024" alt="Screenshot 2022-11-02 at 21 18 28" src="https://user-images.githubusercontent.com/2802867/199594908-b593fb90-73c1-4222-bf85-bc035181dd42.png"> | <img width="1024" alt="Screenshot 2022-11-02 at 21 18 10" src="https://user-images.githubusercontent.com/2802867/199594901-699ef898-86d3-4943-8c5d-cf34ac772f9b.png">

feat: modernize PasswordCheck with Text + remove Grid

---

src/components/List/LoadingPlaceholder.tsx
src/components/List/__tests__/__snapshots__/index.test.tsx.snap

Introduced by https://github.com/scaleway/scaleway-ui/pull/2013

fix(list): fix visual regression where gap is too large when list is loading

---

src/components/PieChart/Tooltip.tsx
src/components/PieChart/__stories__/Content.stories.tsx
src/components/PieChart/__stories__/EmptyLegend.stories.tsx
src/components/PieChart/__stories__/Legends.stories.tsx
src/components/PieChart/__stories__/Playground.stories.tsx
src/components/PieChart/__stories__/PopperDetails.stories.tsx
src/components/PieChart/__stories__/Strikethrough.stories.tsx
src/components/PieChart/__stories__/Template.stories.tsx
src/components/PieChart/__stories__/index.stories.tsx
src/components/Placeholder/__stories__/Block.stories.tsx
src/components/Placeholder/__stories__/Blocks.stories.tsx
src/components/Placeholder/__stories__/Box.stories.tsx
src/components/Placeholder/__stories__/Donut.stories.tsx
src/components/Placeholder/__stories__/Line.stories.tsx
src/components/Placeholder/__stories__/List.stories.tsx
src/components/Placeholder/__stories__/Playground.stories.tsx
src/components/Placeholder/__stories__/Slider.stories.tsx
src/components/Placeholder/__stories__/Template.stories.tsx
src/components/Placeholder/__stories__/index.stories.tsx
src/components/SelectNumber/__stories__/Disabled.stories.tsx
src/components/SelectNumber/__stories__/DisabledTooltip.stories.tsx
src/components/SelectNumber/__stories__/Events.stories.tsx
src/components/SelectNumber/__stories__/Playground.stories.tsx
src/components/SelectNumber/__stories__/Sizes.stories.tsx
src/components/SelectNumber/__stories__/Steps.stories.tsx
src/components/SelectNumber/__stories__/Template.stories.tsx
src/components/SelectNumber/__stories__/Text.stories.tsx
src/components/SelectNumber/__stories__/index.stories.tsx

- Refactor
reorganize and improve PieChart, Placeholder and SelectNumber stories

refactor: reorganize and improve PieChart, Placeholder and SelectNumber stories

---

src/components/Checkbox/__tests__/__snapshots__/index.tsx.snap
src/components/Checkbox/__tests__/index.tsx
src/components/Checkbox/index.tsx
src/components/LineChart/__tests__/__snapshots__/index.tsx.snap
src/components/List/__tests__/__snapshots__/index.test.tsx.snap
src/components/Radio/__tests__/__snapshots__/index.tsx.snap
src/components/Radio/index.tsx
src/components/SelectableCard/__tests__/__snapshots__/index.tsx.snap
src/components/SwitchButton/__tests__/__snapshots__/index.tsx.snap

- Enhancement
I remove most of `aria-checked` that were not useful + I removed reakit. This impact `SelectableCard` and `SwitchButton`.

fix: radio and checkbox properties and removed reakit usages

---

src/components/Button/__tests__/__snapshots__/index.tsx.snap
src/components/Button/index.tsx
src/components/DateInput/__tests__/__snapshots__/index.test.tsx.snap
src/components/List/__stories__/Animated.stories.tsx
src/components/List/__tests__/__snapshots__/index.test.tsx.snap
src/components/Menu/__tests__/__snapshots__/index.tsx.snap
src/components/Modal/__tests__/__snapshots__/index.tsx.snap
src/components/Pagination/__tests__/__snapshots__/index.test.tsx.snap
src/components/PaginationV2/__tests__/__snapshots__/index.test.tsx.snap
src/components/Tabs/__tests__/__snapshots__/index.test.tsx.snap
src/components/Tag/__tests__/__snapshots__/index.tsx.snap
src/components/Tags/__tests__/__snapshots__/index.tsx.snap
src/components/TextBox/__tests__/__snapshots__/index.test.tsx.snap

- Refactor
Remove Box and related props from Button components

refactor(Button): remove box

---

src/components/Tags/__tests__/__snapshots__/index.tsx.snap
src/components/Tags/__tests__/index.tsx
src/components/Tags/index.tsx

- Bug
Focus the input after calling `onChange`

fix(Tags): focus input after onChange

---

src/components/Snippet/__stories__/LongMultiline.stories.tsx
src/components/Snippet/__tests__/__snapshots__/index.tsx.snap
src/components/Snippet/index.tsx

- Bug
Snippet should not have prefix as default value, it should be specified when to display prefixes.

fix(Snippet): no prefix as default value

---

src/components/StepList/__stories__/index.stories.tsx
src/components/StepList/__tests__/__snapshots__/index.tsx.snap
src/components/StepList/index.tsx

feat(StepList): allow complex children

---

src/components/PasswordStrengthMeter/__stories__/Playground.stories.tsx
src/components/PasswordStrengthMeter/__stories__/Template.stories.tsx
src/components/PasswordStrengthMeter/__stories__/UserInputs.stories.tsx
src/components/PasswordStrengthMeter/__stories__/index.stories.tsx
src/components/Pentagon/__stories__/Color.stories.tsx
src/components/Pentagon/__stories__/Playground.stories.tsx
src/components/Pentagon/__stories__/Size.stories.tsx
src/components/Pentagon/__stories__/Template.stories.tsx
src/components/Pentagon/__stories__/index.stories.tsx
src/components/ProgressBar/__stories__/Cap.stories.tsx
src/components/ProgressBar/__stories__/Playground.stories.tsx
src/components/ProgressBar/__stories__/Progress.stories.tsx
src/components/ProgressBar/__stories__/Template.stories.tsx
src/components/ProgressBar/__stories__/Variants.stories.tsx
src/components/ProgressBar/__stories__/index.stories.tsx

- Refactor
Refactor PasswordStrengthMeter, Pentagon and ProgressBar stories
1. Refactor stories

refactor: passwordStrengthMeter pentagon and progressBar stories

---

src/components/Toaster/__stories__/Playground.stories.tsx
src/components/Toaster/__stories__/Template.stories.tsx
src/components/Toaster/__stories__/Variants.stories.tsx
src/components/Toaster/__stories__/index.stories.tsx
src/components/Toaster/index.tsx

- Enhancement
I added more option to toaster container, such as `className`, `position`, `newestOnTop`, `limit` and `id`.
I also updated stories to match our new way of doing.

feat(toaster): add more options and update stories

---

.storybook/components/DocsContainer.tsx
.storybook/preview.tsx
README.md
package.json
pnpm-lock.yaml
src/__stories__/Changelog.stories.mdx
src/__stories__/ComponentState.tsx
src/__stories__/ComponentsState.stories.mdx
src/__stories__/Documentation.stories.mdx
src/__stories__/HowToMakeBreakingChanges.stories.mdx
src/__stories__/Index.stories.mdx
src/__stories__/components/ThemeWrapper.tsx
src/components/Grid/Col.tsx

- Enhancement
I added changelog and get started documentation based on README.md and CHANGELOG.md. I also added a new page "Components State" that will automatically get all stories of all components and shows which ones are deprecated.

docs: add readme changelog and component state

---

src/__tests__/a11y.test.tsx
src/components/Slider/__stories__/Playground.stories.tsx
src/components/Slider/__stories__/Template.stories.tsx
src/components/Slider/__stories__/index.stories.tsx
src/components/Slider/index.tsx
src/components/Sphere/__stories__/Halved.stories.tsx
src/components/Sphere/__stories__/Playground.stories.tsx
src/components/Sphere/__stories__/Template.stories.tsx
src/components/Sphere/__stories__/Text.stories.tsx
src/components/Sphere/__stories__/index.stories.tsx
src/components/StateBar/__stories__/LabelValue.stories.tsx
src/components/StateBar/__stories__/Playground.stories.tsx
src/components/StateBar/__stories__/Progress.stories.tsx
src/components/StateBar/__stories__/Unlimited.stories.tsx
src/components/StateBar/__stories__/index.stories.tsx

- Migration
Update stories about the following components : Slider, Sphere, StateBar

refactor(Slider,Sphere,StateBar): migrate stories

---

src/components/Menu/Item.tsx
src/components/Menu/__tests__/__snapshots__/index.tsx.snap
src/components/Tabs/__tests__/__snapshots__/index.test.tsx.snap

- Refactor
Replace all css by styled into menu.item.

refactor(menu): replaced css by styled

---

src/components/VerificationCode/__stories__/Error.stories.tsx
src/components/VerificationCode/__stories__/Fields.stories.tsx
src/components/VerificationCode/__stories__/InitialValue.stories.tsx
src/components/VerificationCode/__stories__/OnComplete.stories.tsx
src/components/VerificationCode/__stories__/Placeholder.stories.tsx
src/components/VerificationCode/__stories__/Playground.stories.tsx
src/components/VerificationCode/__stories__/Template.stories.tsx
src/components/VerificationCode/__stories__/Type.stories.tsx
src/components/VerificationCode/__stories__/index.stories.tsx

Rewrite VerificationCode stories

refactor(VerificationCode): rewrite stories

---

src/components/Button/__stories__/Disabled.stories.tsx
src/components/Button/__stories__/Extend.stories.tsx
src/components/Button/__stories__/Icon.stories.tsx

- Refactor
Use Template in Button stories where possible

fix(Button): use Template in stories when possible

---

.storybook/preview.tsx
package.json
pnpm-lock.yaml
src/components/Toggle/__stories__/ComplexLabel.stories.tsx
src/components/Toggle/__stories__/Disabled.stories.tsx
src/components/Toggle/__stories__/Label.stories.tsx
src/components/Toggle/__stories__/LabelPosition.stories.tsx
src/components/Toggle/__stories__/Playground.stories.tsx
src/components/Toggle/__stories__/Sizes.stories.tsx
src/components/Toggle/__stories__/Template.stories.tsx
src/components/Toggle/__stories__/Tooltip.stories.tsx
src/components/Toggle/__stories__/index.stories.tsx
src/components/Toggle/index.tsx
src/components/TooltipIcon/__stories__/Colors.stories.tsx
src/components/TooltipIcon/__stories__/Playground.stories.tsx
src/components/TooltipIcon/__stories__/Sizes.stories.tsx
src/components/TooltipIcon/__stories__/Template.stories.tsx
src/components/TooltipIcon/__stories__/index.stories.tsx
src/components/UnitInput/__stories__/CustomOptions.stories.tsx
src/components/UnitInput/__stories__/Disabled.stories.tsx
src/components/UnitInput/__stories__/Playground.stories.tsx
src/components/UnitInput/__stories__/Sizes.stories.tsx
src/components/UnitInput/__stories__/Template.stories.tsx
src/components/UnitInput/__stories__/index.stories.tsx

- Refactor
Migrate stories Toggle TooltipIcon and UnitInput

refactor: rewrite stories toggle tooltipicon unitinput

---

src/components/RichSelect/__stories__/LoadingExample.stories.tsx
src/components/ScrollView/__stories__/Playground.stories.tsx

- Refactor
Take last feedbacks on https://github.com/scaleway/scaleway-ui/pull/2080 after merging in this PR

fix(RichSelect, ScrollView): clean stories

---

src/__stories__/theme/colors.stories.mdx
src/components/Alert/__stories__/Icon.stories.tsx
src/components/Alert/__stories__/Title.stories.tsx
src/components/Alert/__stories__/Variants.stories.tsx
src/components/Alert/__stories__/index.stories.tsx
src/components/Alert/__tests__/__snapshots__/index.test.tsx.snap
src/components/Alert/__tests__/index.test.tsx
src/components/Alert/index.tsx
src/components/Container/__stories__/Header.stories.tsx
src/components/Toaster/__tests__/__snapshots__/index.tsx.snap
src/components/Toaster/index.tsx

- Refactor
Replace `type` prop by `variant` prop in Alert component.

refactor(alert): type to variant prop

---

src/components/ActionBar/__tests__/__snapshots__/index.test.tsx.snap
src/components/ActionBar/index.tsx
src/components/List/__tests__/__snapshots__/index.test.tsx.snap

- Bug
Children should be in a block not flex
1. Change display
2.
3.

fix: action bar display

---

src/components/ListV2/ListContext.tsx
src/components/ListV2/__tests__/index.test.tsx
src/components/ListV2/index.tsx
src/components/ListV2/types.ts

- Bug
Typing was wrong dont need to extend Record<string, unknown> instead just check on idKey that T is extending it
1. Improve typing
2.
3.

fix: typing of new list

---

package.json
pnpm-lock.yaml
src/__stories__/components/Colors.tsx
src/components/BarStack/__tests__/__snapshots__/index.test.tsx.snap
src/components/BarStack/index.tsx
src/components/Button/__tests__/__snapshots__/index.tsx.snap
src/components/Button/index.tsx
src/components/DateInput/__tests__/__snapshots__/index.test.tsx.snap
src/components/List/__tests__/__snapshots__/index.test.tsx.snap
src/components/Pagination/__tests__/__snapshots__/index.test.tsx.snap
src/components/PaginationV2/__tests__/__snapshots__/index.test.tsx.snap

- Enhancement
Removed Polished that we barely use and our usages could be replace by hexa code for transparency: https://gist.github.com/lopspower/03fb1cc0ac9f32ef38f4
| url  | ![Screenshot 2022-12-09 at 17 20 36](https://user-images.githubusercontent.com/15812968/206746429-b3a10f29-ba74-4faf-9bd8-c6fe990839ab.png) | ![Screenshot 2022-12-09 at 17 20 39](https://user-images.githubusercontent.com/15812968/206746464-fc2ea9bc-850b-4b8d-a816-9984b8870f2f.png) |

refactor: remove polished dependency

---

src/components/Menu/Item.tsx
src/components/Menu/__tests__/__snapshots__/index.tsx.snap
src/components/Menu/index.tsx
src/components/Tabs/__tests__/__snapshots__/index.test.tsx.snap

- Bug
Menu bordered radius was wrong on items and color of the arrow was also wrong in dark theme.
| url  | <img width="369" alt="Screenshot 2022-12-13 at 09 15 45" src="https://user-images.githubusercontent.com/15812968/207262735-f8f83d11-8c3c-482a-91b6-aceebe8848b6.png"> | <img width="380" alt="Screenshot 2022-12-13 at 09 15 04" src="https://user-images.githubusercontent.com/15812968/207262767-e2b538ac-0dcd-4925-90de-0a351825629d.png"> |

fix(menu): border radius and color on dark mode

---

src/components/Label/__tests__/__snapshots__/index.tsx.snap
src/components/Label/index.tsx
src/components/Text/index.tsx

- Enhancement
I updated Label component in order to follow tokens.

fix(label): update label properties

---

src/components/Tags/__tests__/__snapshots__/index.tsx.snap
src/components/Tags/__tests__/index.tsx
src/components/Tags/index.tsx

Revert https://github.com/scaleway/scaleway-ui/pull/2034/
It's causing issues when `onChange` is triggered: the input is always focused and we can't escape it

fix(Tags): revert focusing input onChange

---

src/components/Button/__tests__/__snapshots__/index.tsx.snap
src/components/Button/index.tsx
src/components/Menu/__tests__/__snapshots__/index.tsx.snap

- Bug
Fix `Button` hover bug when using `href` and `target="_blank"`
Before:
https://user-images.githubusercontent.com/43268759/208443774-930c1fb1-1528-4294-afd7-1cd522a32a44.mov
After:
https://user-images.githubusercontent.com/43268759/208443641-36a78a08-c452-4bc4-bef9-53372ac94eb0.mov

fix(Button): remove Link animation when using href

---

packages/form/src/__stories__/Changelog.stories.mdx
packages/form/src/__stories__/Introduction.stories.mdx
packages/form/src/components/CheckboxField/__stories__/index.stories.tsx
packages/form/src/components/DateField/__stories__/index.stories.tsx
packages/form/src/components/Form/__stories__/Playground.stories.tsx
packages/form/src/components/Form/__stories__/index.stories.tsx
packages/form/src/components/RadioField/__stories__/index.stories.tsx
packages/form/src/components/RichSelectField/__stories__/index.stories.tsx
packages/form/src/components/SelectNumberField/__stories__/index.stories.tsx
packages/form/src/components/SelectableCardField/__stories__/index.stories.tsx
packages/form/src/components/Submit/__stories__/index.stories.tsx
packages/form/src/components/SubmitErrorAlert/__stories__/index.stories.tsx
packages/form/src/components/TagsField/__stories__/index.stories.tsx
packages/form/src/components/TextBoxField/__stories__/index.stories.tsx
packages/form/src/components/TimeField/__stories__/index.stories.tsx
packages/form/src/components/ToggleField/__stories__/index.stories.tsx

Refactor the documentation of form packages

docs(form): re-organizition of stories title

---

packages/form/src/components/TagsField/__tests__/__snapshots__/index.spec.tsx.snap
packages/form/src/components/TagsField/__tests__/index.spec.tsx
packages/form/src/components/TagsField/index.tsx
packages/ui/src/components/Tags/index.tsx

- Bug
initialValues of a Form was not spread to the Field

fix(tagsFields): initialValues was not working

---

packages/form/src/components/Form/__stories__/Playground.stories.tsx
packages/form/src/hooks/__tests__/useOnFieldChange.spec.tsx
packages/form/src/hooks/useOnFieldChange.ts

- Refactor
Change the order of the condition parms and callback parms and add condition = true 
```
useOnFieldChange(
'name',
condition,
callback,    
),
```
```
useOnFieldChange(
'name',
callback,
condition
),
```

fix(useOnFieldChange): change order of params condition and callback

---

packages/form/src/components/Submit/index.tsx

- Feature
Add the props `iconSize` to the Submit component

feat(submit): add icon size

---

packages/form/src/components/Form/index.tsx

fix(form): pass className to correct component on Form

---

lerna.json
package.json

Let's try to add emoji in changelog

fix: add emoji in changelog

---

.github/renovate.json

Fix https://github.com/scaleway/scaleway-ui/issues/2173

fix(renovate): remove matchManagers & matchPackageNames

---

packages/form/src/components/RichSelectField/index.tsx

Add `cutomStyle` prop on `RichSelectField` 
- Bug

fix: add custom style attribute on richSelectField

---

packages/form/src/components/RichSelectField/__tests__/__snapshots__/index.spec.tsx.snap
packages/form/src/components/TimeField/__tests__/__snapshots__/index.spec.tsx.snap
packages/ui/src/components/RichSelect/__tests__/__snapshots__/index.tsx.snap
packages/ui/src/components/RichSelect/index.tsx
packages/ui/src/components/TimeInput/__stories__/index.stories.tsx
packages/ui/src/components/TimeInput/__tests__/__snapshots__/index.tsx.snap
packages/ui/src/components/TimeInput/index.tsx
packages/ui/src/components/UnitInput/__tests__/__snapshots__/index.tsx.snap

- Bug
TimeInput has required icon in wrong position, after the separator.
| url  | <img width="1021" alt="Screenshot 2023-01-05 at 11 32 04" src="https://user-images.githubusercontent.com/15812968/210762430-6e85a384-c4e6-4887-8e29-45c0451fbeb4.png"> | <img width="1023" alt="Screenshot 2023-01-05 at 11 32 17" src="https://user-images.githubusercontent.com/15812968/210762457-b2cece17-37d6-481f-a036-78344623351f.png"> |

fix(TimeInput): required icon correct position

---

packages/form/package.json
packages/ui/package.json
website/package.json

docs(form): update git repository

---

packages/ui/src/__stories__/theme/darkMode.stories.mdx

We had feedback about dark theme documentation. Example is wrong and not very clear. Here is a better version.

docs: improve dark theme documentation

---

packages/ui/src/components/Slider/__tests__/__snapshots__/index.tsx.snap
packages/ui/src/components/Slider/__tests__/index.tsx
packages/ui/src/components/Slider/index.tsx
packages/ui/src/components/VerificationCode/__tests__/__snapshots__/index.tsx.snap
packages/ui/src/components/VerificationCode/__tests__/index.tsx

- Enhancement
Trying to improve code coverage on VerificationCode and Slider
1. Adding unit tests

test: improve code coverage on verification code and slider

---

packages/ui/src/components/DateInput/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/Text/__tests__/__snapshots__/index.test.tsx.snap

Fix CI failing (tests) since https://github.com/scaleway/scaleway-ui/pull/2192

chore: fix ci

---

packages/form/src/components/Submit/__tests__/__snapshots__/index.spec.tsx.snap
packages/form/src/components/SubmitErrorAlert/__tests__/__snapshots__/index.spec.tsx.snap
packages/form/src/components/TagsField/__tests__/__snapshots__/index.spec.tsx.snap
packages/form/src/components/TextInputField/__tests__/__snapshots__/index.spec.tsx.snap
packages/form/src/components/ToggleField/__tests__/__snapshots__/index.spec.tsx.snap
packages/ui/src/components/Button/__stories__/Extend.stories.tsx
packages/ui/src/components/Button/__tests__/__snapshots__/index.tsx.snap
packages/ui/src/components/Button/index.tsx
packages/ui/src/components/DateInput/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/List/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/Menu/__tests__/__snapshots__/index.tsx.snap
packages/ui/src/components/Modal/__tests__/__snapshots__/index.tsx.snap
packages/ui/src/components/Pagination/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/PaginationV2/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/Tabs/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/Tag/__tests__/__snapshots__/index.tsx.snap
packages/ui/src/components/Tags/__tests__/__snapshots__/index.tsx.snap
packages/ui/src/components/TextInput/__tests__/__snapshots__/index.test.tsx.snap

- Enhancement
Before
https://user-images.githubusercontent.com/2802867/209998029-67fce1f9-fc2b-4f2d-872f-62fab8925e09.mp4
After
https://user-images.githubusercontent.com/2802867/209998052-f0a030d6-0c0e-463e-a5f4-392a2e04e816.mp4

fix(Button): proper layout on extend buttons

---

packages/form/src/index.ts

- Enhancement
export Field from react-final-form

chore(form): export Field from react-final-form

---

packages/form/src/components/Submit/__tests__/__snapshots__/index.spec.tsx.snap
packages/form/src/components/SubmitErrorAlert/__tests__/__snapshots__/index.spec.tsx.snap
packages/ui/src/components/Button/__tests__/__snapshots__/index.tsx.snap
packages/ui/src/components/Button/index.tsx
packages/ui/src/components/List/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/Menu/__tests__/__snapshots__/index.tsx.snap
packages/ui/src/components/Pagination/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/PaginationV2/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/Tabs/__tests__/__snapshots__/index.test.tsx.snap

- Bug
Button stack had wrong direction.

fix(Button): stack has direction column by default

---

packages/ui/src/components/SelectInput/__tests__/__snapshots__/index.tsx.snap
packages/ui/src/components/SelectInput/index.tsx
pnpm-lock.yaml

- Bug
Required icon of SelectInput was 8px while others components are 10px.
| url  | <img width="1020" alt="Screenshot 2023-02-09 at 14 12 24" src="https://user-images.githubusercontent.com/15812968/217823946-b04a135b-3cd3-4894-90f0-52d978b40e99.png"> | <img width="1040" alt="Screenshot 2023-02-09 at 14 12 17" src="https://user-images.githubusercontent.com/15812968/217823904-3d713bfa-5784-49a6-b55a-2d5450d47da0.png">  |

fix(SelectInput): required icon to be 10px

---

packages/ui/src/components/Toggle/index.tsx

- Bug
Add `forwardRef` to the Toggle component.

fix(toggle): add forward ref

---

packages/form/src/components/CheckboxField/__tests__/__snapshots__/index.spec.tsx.snap
packages/themes/src/themes/console/index.ts
packages/ui/src/components/Checkbox/__tests__/__snapshots__/index.tsx.snap
packages/ui/src/components/Checkbox/index.tsx
packages/ui/src/components/LineChart/__tests__/__snapshots__/index.tsx.snap
packages/ui/src/components/List/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/ListV2/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/SelectableCard/__tests__/__snapshots__/index.tsx.snap

- Enhancement
Checkbox container radius was hard written, instead it should take it from the theme.

fix(Checkbox): to use radii from theme

---

packages/form/src/components/SelectInputField/__tests__/__snapshots__/index.spec.tsx.snap
packages/form/src/components/TimeField/__tests__/__snapshots__/index.spec.tsx.snap
packages/ui/src/components/SelectInput/__tests__/__snapshots__/index.tsx.snap
packages/ui/src/components/SelectInput/index.tsx
packages/ui/src/components/UnitInput/__stories__/index.stories.tsx
packages/ui/src/components/UnitInput/__tests__/__snapshots__/index.tsx.snap
packages/ui/src/components/UnitInput/index.tsx

- Enhancement
- Disabled option was missing a border making the component strange on disabled state, I fixed it.
- When there is only one option, we disable the SelectInput as the user won't be able to change it anyways.
| url  | ![Screenshot 2023-02-16 at 10 49 13](https://user-images.githubusercontent.com/15812968/219334460-3c5929bd-5866-4a45-a2e5-81e3d21b50cb.png) | ![Screenshot 2023-02-16 at 10 49 19](https://user-images.githubusercontent.com/15812968/219334500-2a87a145-3d2b-4541-b746-7c0747d1a694.png)  |
| url  | ![Screenshot 2023-02-16 at 11 00 59](https://user-images.githubusercontent.com/15812968/219334518-48f91fa6-d1aa-4a9b-90d1-ff9beecefff8.png) | ![Screenshot 2023-02-16 at 11 01 …

fix(unitInput): add border to disabled state and disable when there is only one option

---

packages/form/src/components/NumberInputField/__tests__/__snapshots__/index.spec.tsx.snap
packages/ui/src/components/NumberInput/__tests__/__snapshots__/index.tsx.snap
packages/ui/src/components/NumberInput/index.tsx

- Bug
Due to new icon color I didn't update icon in NumberInput leading to design incoherence.
| normal  | ![Screenshot 2023-02-27 at 12 33 19](https://user-images.githubusercontent.com/15812968/221553519-a96a49dc-db92-41cc-8135-d60751ee89f5.png) | ![Screenshot 2023-02-27 at 12 33 23](https://user-images.githubusercontent.com/15812968/221553531-c067b49a-63ad-4e1b-b50b-a8196c4bd967.png) |
| disabled  | ![Screenshot 2023-02-27 at 12 33 29](https://user-images.githubusercontent.com/15812968/221553545-831608ab-3de5-4c05-b8fa-528d38a30c4e.png) | ![Screenshot 2023-02-27 at 12 33 33](https://user-images.githubusercontent.com/15812968/221553577-f5198964-e50b-474d-815f-ad4cb8e5beff.png) |

fix(NumberInput): colors of icons and hover were wrong

---

packages/themes/src/themes/console/dark.ts
packages/themes/src/themes/console/light.ts
scripts/figma-synchronise-tokens.sh

- Feature
New Product and Category icons that will be use for icons on projects. I updated the script to generate both light and dark themes.

feat: new product and category colors

---

packages/ui/src/components/ListV2/HeaderCell.tsx
packages/ui/src/components/ListV2/__tests__/__snapshots__/index.test.tsx.snap

- Bug
A sorted color must be in color Primary
| url  | ![Capture d’écran 2023-03-01 à 15 16 57](https://user-images.githubusercontent.com/8116991/222166561-2c96960a-3162-414c-95f7-3ba8eae7c43d.png) | ![Capture d’écran 2023-03-01 à 15 17 10](https://user-images.githubusercontent.com/8116991/222166558-aa7b1a22-1d99-4169-88f7-60679a59b2ef.png)
|

fix(ListV2): restore sorted column color

---

packages/ui/src/components/ListV2/Body.tsx
packages/ui/src/components/ListV2/HeaderCell.tsx
packages/ui/src/components/ListV2/HeaderRow.tsx
packages/ui/src/components/ListV2/Row.tsx
packages/ui/src/components/ListV2/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/ListV2/__tests__/index.test.tsx
packages/ui/src/components/ListV2/index.tsx

Restore name attribute on ListV2 select checkbox (for both selectAll or select specific row), changing to `name="list-select-checkbox"`

fix(ListV2): restore list-radio name attr on checkboxes

---

packages/form/src/components/TextInputField/__tests__/__snapshots__/index.spec.tsx.snap
packages/ui/src/components/Notice/__tests__/__snapshots__/index.tsx.snap
packages/ui/src/components/Notice/index.tsx
packages/ui/src/components/TextInput/__tests__/__snapshots__/index.test.tsx.snap

| url  | <img width="1154" alt="Screenshot 2023-03-06 at 11 11 23" src="https://user-images.githubusercontent.com/2802867/223081089-761a5d19-1b89-4b6e-900a-6008c63af5f8.png"> | <img width="1154" alt="Screenshot 2023-03-06 at 11 11 26" src="https://user-images.githubusercontent.com/2802867/223081097-55b73899-d229-42bb-ac8f-efdeb7bf6e5f.png"> |

feat(Notice): rework component to remove markdown handling

---

packages/form/src/components/DateField/index.tsx
packages/form/src/hooks/useValidation.ts
packages/ui/src/__stories__/Properties/Properties.tsx
packages/ui/src/__tests__/a11y.test.tsx
packages/ui/src/components/Badge/index.tsx
packages/ui/src/components/BarChart/index.tsx
packages/ui/src/components/BarStack/index.tsx
packages/ui/src/components/Breadcrumbs/index.tsx
packages/ui/src/components/DateInput/index.tsx
packages/ui/src/components/LineChart/CustomLegend.tsx
packages/ui/src/components/LineChart/index.tsx
packages/ui/src/components/List/SelectBar.tsx
packages/ui/src/components/PasswordStrengthMeter/index.tsx
packages/ui/src/components/PieChart/index.tsx
packages/ui/src/components/Sphere/index.tsx
packages/ui/src/components/Stepper/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/Stepper/__tests__/index.test.tsx
packages/ui/src/components/TagList/index.tsx
packages/ui/src/components/TimeInput/__stories__/Controlled.stories.tsx
packages/ui/src/components/VerificationCode/index.tsx
packages/ui/src/helpers/__tests__/index.ts
packages/ui/src/theme/index.ts

First PR to prepare for upcoming eslint config update

fix: correct non scalar default arguments as props

---

packages/ui/src/components/Toaster/__stories__/Variants.stories.tsx
packages/ui/src/components/Toaster/__tests__/__snapshots__/index.tsx.snap
packages/ui/src/components/Toaster/index.tsx

- Enhancement
- Fix toaster position according to new design specs
- Added a shadow to toaster
- Fixed stories snippets
| url  | <img width="1029" alt="Screenshot 2023-03-07 at 14 14 58" src="https://user-images.githubusercontent.com/15812968/223433764-b4016158-ba52-42c5-aa3e-4748dcd9de11.png"> | <img width="1028" alt="Screenshot 2023-03-07 at 14 15 04" src="https://user-images.githubusercontent.com/15812968/223433811-6c3e0114-168b-4344-b1c7-09fb6d7e3d90.png"> |

fix(toaster): improve placement and fix stories snippet

---

pnpm-lock.yaml

fix: broken lockfile

---

packages/form/src/components/DateField/__tests__/__snapshots__/index.tsx.snap
packages/form/src/components/SelectInputField/__tests__/__snapshots__/index.spec.tsx.snap
packages/form/src/components/Submit/__tests__/__snapshots__/index.spec.tsx.snap
packages/form/src/components/TextInputField/__tests__/__snapshots__/index.spec.tsx.snap
packages/form/src/components/TimeField/__tests__/__snapshots__/index.spec.tsx.snap
packages/ui/src/components/DateInput/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/Expandable/__stories__/MinHeight.stories.tsx
packages/ui/src/components/Expandable/__stories__/NestedExpandable.stories.tsx
packages/ui/src/components/Expandable/__stories__/index.stories.tsx
packages/ui/src/components/Expandable/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/Expandable/__tests__/index.test.tsx
packages/ui/src/components/Expandable/index.tsx
packages/ui/src/components/Modal/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/SelectInput/__tests__/__snapshots__/index.tsx.snap
packages/ui/src/components/SelectInput/index.tsx
packages/ui/src/components/Snippet/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/Snippet/index.tsx
packages/ui/src/components/TextInput/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/TextInput/index.tsx
packages/ui/src/components/TimeInput/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/UnitInput/__tests__/__snapshots__/index.test.tsx.snap

- Refactor
The old component needed the prop `height` in order to make a smooth animation. In fact we need a height to set it to `max-height` to make an smooth animation.
Most of the time we do not set `height` as it is variable to the children size and we do not always know the children size. In most case the animation will look like this:
---
Expandable became intelligent and measure the size of its children. No need to give a property `height` anymore, we can calculate the size of the children automatically and pass it directly to the `max-height` in CSS. This way the animation is way more smooth.
**But that's not all!** 
Expandable is also handling an Expandable within an Expandable. It seems nothing at first but I can assure you it's not that easy. When a parent Expandable has a …

refactor(Expandable): smart expandable

---

packages/ui/src/components/Carousel/__tests__/__snapshots__/index.tsx.snap
packages/ui/src/components/PasswordStrengthMeter/index.tsx
packages/ui/src/components/ProgressBar/index.tsx
packages/ui/src/components/ProgressionButton/index.tsx
packages/ui/src/components/Radio/index.tsx
packages/ui/src/components/SelectInput/index.tsx
packages/ui/src/components/SelectableCard/index.tsx
packages/ui/src/components/Separator/index.tsx
packages/ui/src/components/Snippet/index.tsx
packages/ui/src/components/Stack/index.tsx
packages/ui/src/components/Status/index.tsx
packages/ui/src/components/StepList/index.tsx
packages/ui/src/components/Stepper/index.tsx
packages/ui/src/components/SwitchButton/index.tsx
packages/ui/src/components/Table/index.tsx
packages/ui/src/components/Tabs/index.tsx
packages/ui/src/components/Tag/index.tsx
packages/ui/src/components/TagInput/index.tsx
packages/ui/src/components/TagList/index.tsx
packages/ui/src/components/Text/index.tsx
packages/ui/src/components/Toaster/index.tsx
packages/ui/src/components/Toggle/index.tsx
packages/ui/src/components/Tooltip/index.tsx
packages/ui/src/components/UnitInput/index.tsx
packages/ui/src/components/VerificationCode/index.tsx

- Enhancement
Add className and data-testid on every components

feat(components): add className and data-testid - Part 2

---

.changeset/rare-hotels-try.md
.changeset/renovate-5f3df58.md
.changeset/renovate-c4aba14.md
.changeset/renovate-f0bc6fd.md
.changeset/stupid-knives-impress.md
packages/form/CHANGELOG.md
packages/form/package.json
packages/themes/CHANGELOG.md
packages/themes/package.json
packages/ui/CHANGELOG.md
packages/ui/package.json
website/CHANGELOG.md
website/package.json

Revert "chore: release (#2388)"

---

.changeset/config.json

- Chore
Update changeset config to avoid bumping Scaleway ui and Form with same version.

chore(changeset): update config

---

.changeset/wet-waves-marry.md
packages/themes/src/themes/console/dark.ts
packages/themes/src/themes/console/light.ts
scripts/figma-synchronise-tokens.sh

- Enhancement
Add gradient into theme.

feat: new gradient colors

---

.changeset/tasty-fireants-smell.md
packages/ui/src/components/ListV2/Row.tsx
packages/ui/src/components/ListV2/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/ListV2/__tests__/index.test.tsx

- Bug
When clicking on the expandable content of a ListV2 Row, the row should not collapse. It's especially important if there are clickable elements inside

fix(ListV2): click of expanded content do not collapse the row

---

.changeset/thick-tips-explain.md
packages/ui/src/components/Card/index.tsx

- Bug
ForwardRef is missing in Card component.

fix(Card): add forward ref

---

.changeset/beige-tips-explain.md
packages/ui/src/components/Card/__tests__/__snapshots__/index.tsx.snap
packages/ui/src/components/Card/index.tsx

- Bug
This prevent React error that enforce writing html attribute in lower case.

fix(Card): rename data-is-active attribute to match React rules

---

packages/ui/src/components/Table/__stories__/index.stories.tsx

I update the documentation of Table which was wrong.

docs(Table): fix description

---

README.md
packages/themes/README.md
pnpm-lock.yaml

New README for Theme and updated the main one to include it.

docs: update readme to scaleway theme information

---

.changeset/dull-mugs-serve.md
packages/form/src/components/TagInputField/__tests__/__snapshots__/index.spec.tsx.snap
packages/ui/src/components/TagInput/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/TagInput/index.tsx

- Refactor
I added a border on hover (like we do for other inputs on `TagsInput` component. I also added missing pointer `text`.
Before:
After:

refactor(TagsInput): hover state and pointer cursor

---

packages/ui/src/__stories__/ComponentState/ComponentState.tsx

- Bug
Fix component state page on storybook.

docs: fix component state page

---

.changeset/pretty-points-report.md
packages/form/src/components/SubmitErrorAlert/__tests__/__snapshots__/index.spec.tsx.snap
packages/ui/src/components/Alert/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/Alert/index.tsx
packages/ui/src/components/Toaster/__tests__/__snapshots__/index.test.tsx.snap

- Bug
I fixed a useless Stack left and changed typing of `buttonText`.

fix(Alert): useless stack and wrong typing for buttontext prop

---

.changeset/rude-dogs-study.md
packages/ui/src/components/Alert/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/Banner/__tests__/__snapshots__/index.tsx.snap
packages/ui/src/components/ButtonV2/__tests__/__snapshots__/index.tsx.snap
packages/ui/src/components/ButtonV2/index.tsx

- Bug
Fix the ButtonV2 font-weight

fix(ButtonV2): font

---

global.d.ts
packages/form/src/__stories__/Changelog.stories.mdx
packages/ui/src/__stories__/Changelog.stories.mdx
packages/ui/src/__stories__/Changelog/Changelog.stories.tsx
packages/ui/src/__stories__/Changelog/index.stories.mdx
packages/ui/src/__stories__/Properties/Properties.tsx

I regrouped all changelog page in one main page on storybook to make it easier to navigate between them.
https://user-images.githubusercontent.com/15812968/233990509-d8ff3004-e6f2-42fb-8c3d-a2b7087af535.mov

docs: make changelog page global for all packages

---

.github/workflows/release.yml

- CI
Added `provenance` env for npm
https://github.blog/2023-04-19-introducing-npm-package-provenance/

ci: add pnpm provenance parameter

---

.github/workflows/release.yml

ci: fix permissions again

---

.changeset/fair-seals-serve.md
packages/ui/src/components/Alert/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/Alert/__tests__/index.test.tsx
packages/ui/src/components/Alert/index.tsx

- Enhancement
Added new prop `disabled` into `Alert`.

fix(alert): add disabled prop

---

packages/ui/src/components/Banner/__stories__/index.stories.tsx

Moved Banner into other category.

docs(Banner): move banner into other category in storybook

---

.changeset/rich-pumpkins-cry.md
packages/form/src/components/CheckboxField/index.tsx
packages/form/src/components/DateField/index.tsx
packages/form/src/components/NumberInputField/index.tsx
packages/form/src/components/RadioField/index.tsx
packages/form/src/components/SelectInputField/index.tsx
packages/form/src/components/SelectableCardField/index.tsx
packages/form/src/components/TagInputField/index.tsx
packages/form/src/components/TextInputField/index.tsx
packages/form/src/components/TimeField/index.tsx
packages/form/src/components/ToggleField/index.tsx

- Feature
Add data-testid to all fields.

feat: add data-testid to fields

---

.changeset/short-bats-divide.md
packages/form/src/components/Submit/__tests__/__snapshots__/index.spec.tsx.snap
packages/form/src/components/SubmitErrorAlert/__tests__/__snapshots__/index.spec.tsx.snap
packages/form/src/components/TagInputField/__tests__/__snapshots__/index.spec.tsx.snap
packages/form/src/components/TextInputField/__tests__/__snapshots__/index.spec.tsx.snap
packages/ui/src/components/Alert/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/Banner/__tests__/__snapshots__/index.tsx.snap
packages/ui/src/components/Button/__tests__/__snapshots__/index.tsx.snap
packages/ui/src/components/Button/index.tsx
packages/ui/src/components/DateInput/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/List/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/Modal/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/Pagination/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/PaginationV2/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/PaginationV2/index.tsx
packages/ui/src/components/Tag/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/TagInput/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/TextInput/__tests__/__snapshots__/index.test.tsx.snap

- Bug
- Restore aria-current on Pagination v2
- Make sure Button with icon only are perfect square (problem was only with Button outlined)

fix: restore Pagination aria-current

---

.changeset/great-roses-design.md
packages/form/src/components/CheckboxField/__tests__/__snapshots__/index.spec.tsx.snap
packages/form/src/components/RadioField/__tests__/__snapshots__/index.spec.tsx.snap
packages/form/src/components/SelectableCardField/__tests__/__snapshots__/index.spec.tsx.snap
packages/ui/src/components/Checkbox/__tests__/__snapshots__/index.tsx.snap
packages/ui/src/components/Checkbox/index.tsx
packages/ui/src/components/LineChart/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/List/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/ListV2/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/Radio/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/Radio/index.tsx
packages/ui/src/components/SelectableCard/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/SwitchButton/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/SwitchButton/index.tsx
packages/ui/src/components/TableV2/__tests__/__snapshots__/index.test.tsx.snap

- Refactor
The radio component can be use without a displayed label, the aria-label prop have been added to ensure accessibility.

refactor(Radio): change label

---

.changeset/hungry-worms-appear.md
packages/form/src/components/TextInputField/__tests__/__snapshots__/index.spec.tsx.snap
packages/ui/src/components/TextInput/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/TextInput/index.tsx

- Bug
fix the number type input arrow position

fix: fix the number type input arrow position

---

.changeset/sour-months-teach.md
packages/ui/src/index.ts

fix: add Banner to exports

---

packages/ui/README.md

I updated the readme to include all information about theme type and emotion.

docs: update readme of scaleway ui for emotion type declaration

---

.changeset/curvy-brooms-shop.md
packages/ui/src/__stories__/ButtonMigration/Sizes.tsx
packages/ui/src/components/Button/__tests__/__snapshots__/index.tsx.snap
packages/ui/src/components/Button/index.tsx

- Feature
- Enhancement
Add a xsmall size button

feat(Button): add xsmall size

---

.changeset/nasty-pens-refuse.md
packages/ui/src/components/Row/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/Row/index.tsx

- Feature
Add `justify-content` property to Row.

feat(Row): add justify-content property

---

packages/form/src/components/TextInputField/__tests__/__snapshots__/index.spec.tsx.snap
packages/ui/src/components/TextInput/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/TextInput/index.tsx

fix(textinput): style issue on padding

---

packages/form/src/components/CheckboxField/index.tsx
packages/form/src/components/Form/index.tsx
packages/form/src/components/RadioField/index.tsx
packages/form/src/components/SelectableCardField/index.tsx
packages/form/src/components/Submit/index.tsx
packages/form/src/components/TagInputField/index.tsx
packages/form/src/components/TextInputField/index.tsx
packages/form/src/providers/ErrorContext/index.tsx
packages/ui/src/__tests__/a11y.test.tsx
packages/ui/src/components/BarStack/index.tsx
packages/ui/src/components/Breadcrumbs/index.tsx
packages/ui/src/components/Carousel/index.tsx
packages/ui/src/components/Modal/index.tsx
packages/ui/src/components/Pagination/index.tsx
packages/ui/src/components/PasswordStrengthMeter/index.tsx
packages/ui/src/components/SelectInput/index.tsx
packages/ui/src/components/Separator/index.tsx
packages/ui/src/components/Status/index.tsx
packages/ui/src/components/TagInput/index.tsx
packages/ui/src/components/TagList/index.tsx
packages/ui/src/components/TextInput/index.tsx
packages/ui/src/components/TimeInput/index.tsx
packages/ui/src/components/VerificationCode/index.tsx

- Refactor
import JSX type from React instead of global

refactor(types): import JSX from react

---

.changeset/many-cooks-dress.md
packages/ui/src/components/PasswordStrengthMeter/__stories__/Estimate.stories.tsx
packages/ui/src/components/PasswordStrengthMeter/__stories__/index.stories.tsx
packages/ui/src/components/PasswordStrengthMeter/index.tsx
pnpm-lock.yaml

- Feature
Add the possibility to make async estimate func

feat(passwordstrengthmeter): add async estimate method

---

.changeset/renaming-deprecated-ultraviolet.md

Updated changeset message to be more precise.

docs: update changeset

---

.github/workflows/release.yml

Temporarly provenance as the package name changed.

fix: remove provenance

---

packages/ui/src/components/Button/__stories__/AsLink.stories.tsx
packages/ui/src/components/Menu/Item.tsx
packages/ui/src/components/Table/__stories__/ColumnInfo.stories.tsx
packages/ui/src/components/TagInput/index.tsx
packages/ui/src/components/VerificationCode/index.tsx

- Refactor
Remove some lint warnings

chore: remove few lint warnings

---

packages/ui/README.md

Fix Global auto closing example in README

docs(ui): fix auto closing global in readme

---

.changeset/renovate-677554e.md

Renovate generated wrong changeset

docs: fix changeset

---

packages/ui/src/__stories__/ButtonMigration/Variants.tsx

Fixed matching sentiments from primary to info in button migration

docs: fix variant link new matching sentiments

---

.github/workflows/teardown_pull_request.yml

ci: revert teardown

---

README.md

Fixed versioning information and links to documentation so it will work on storybook too.

docs: update readme versioning and link to documentation

---

.changeset/gold-parents-itch.md
packages/ui/src/components/Modal/__tests__/index.test.tsx
packages/ui/src/components/Modal/index.tsx

- Bug
forward click event on disclosure function or component

feat(modal): forward onClick events based on disclosure component

---

.changeset/modern-tools-think.md
packages/form/src/components/Submit/__tests__/__snapshots__/index.spec.tsx.snap
packages/ui/src/components/Button/__tests__/__snapshots__/index.tsx.snap
packages/ui/src/components/Checkbox/__tests__/__snapshots__/index.tsx.snap
packages/ui/src/components/Loader/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/Loader/index.tsx
packages/ui/src/components/Tag/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/TagInput/__tests__/__snapshots__/index.test.tsx.snap

- Bug
Loader active animation was not working anymore because css refused to accepted keyframes object as value

fix(Loader): active animation

---

.changeset/selfish-spies-pretend.md
packages/ui/src/components/Menu/__tests__/index.test.tsx
packages/ui/src/components/Menu/index.tsx
packages/ui/src/components/Modal/index.tsx

- Feature
retrieve click event on disclosure function or component

feat(menu): retrieve onClick events on disclosure component

---

.changeset/modern-pears-call.md
packages/form/src/components/SelectInputField/index.tsx
packages/ui/src/components/SelectInput/index.tsx

- Bug
Add validate to `SelectInputField` component.

fix(SelectInputField): add validate

---

.changeset/two-cats-raise.md
packages/form/src/components/NumberInputField/__tests__/__snapshots__/index.spec.tsx.snap
packages/form/src/components/Submit/__tests__/__snapshots__/index.spec.tsx.snap
packages/form/src/components/SubmitErrorAlert/__tests__/__snapshots__/index.spec.tsx.snap
packages/form/src/components/TagInputField/__tests__/__snapshots__/index.spec.tsx.snap
packages/form/src/components/TextInputField/__tests__/__snapshots__/index.spec.tsx.snap
packages/ui/src/components/Alert/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/Banner/__tests__/__snapshots__/index.tsx.snap
packages/ui/src/components/Button/__tests__/__snapshots__/index.tsx.snap
packages/ui/src/components/Button/index.tsx
packages/ui/src/components/DateInput/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/Modal/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/NumberInput/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/Pagination/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/Tag/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/TagInput/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/TextInput/__tests__/__snapshots__/index.test.tsx.snap

- Bug
Add `tabIndex` prop to `Button`

fix(Button): add `tabIndex` prop

---

.changeset/violet-weeks-appear.md
packages/ui/src/components/Button/index.tsx

- Enhancement
Missing props in Button

fix(button): fix aria props

---

.changeset/hungry-meals-trade.md
packages/themes/src/index.ts

Missing import of darker theme in themes package.

fix(themes): export all themes

---

packages/ui/README.md

The readme missing an important information about the font and which one to import.

docs: add font import explanation

---

.changeset/eighty-eagles-exist.md
packages/icons/src/components/index.ts

Fixed missing export for Icons package.

fix(icons): missing exports

---

.changeset/tough-windows-drive.md
packages/icons/src/components/ProductIcon/Icons.tsx
packages/icons/src/components/ProductIcon/__tests__/__snapshots__/index.tsx.snap

Fix serverless db product icon name

fix(icons): change product icon name for serverless db

---

.changeset/great-schools-bathe.md
packages/form/src/components/Submit/__tests__/__snapshots__/index.spec.tsx.snap
packages/form/src/components/Submit/index.tsx
packages/form/src/components/SubmitErrorAlert/__tests__/__snapshots__/index.spec.tsx.snap

As part of the new theme colors we are changing usages for buttons from success to primary.

fix(form): update submit sentiment to default instead of success

---

.changeset/fluffy-queens-punch.md
packages/ui/src/components/DateInput/index.tsx

- Bug
Here is the related issue: https://github.com/Hacker0x01/react-datepicker/issues/3834

fix(DateInput): fix component

---

.changeset/odd-shrimps-speak.md
packages/form/src/components/Submit/index.tsx

- Bug
Forward fullwidth to submit

fix(submit): forward fullwidth into submit

---

packages/icons/src/components/Icon/index.tsx

fix(icons): add correct type

---

.changeset/silent-grapes-heal.md
packages/form/src/components/Submit/index.tsx

- Enhancement
Adds onClick to Submit component

feat(submit): adds onclick prop

---

.changeset/config.json

fix: fast fix

---

packages/ui/src/components/TagList/__tests__/index.test.tsx

refactor(tooltip): remove useless test code

---

.changeset/renovate-509aab4.md
.changeset/renovate-aaf9567.md
.changeset/renovate-f7cc756.md

There is an issue with changeset and examples folder.

fix: renovate files to remove examples

---

.changeset/wicked-falcons-lick.md
packages/ui/src/components/Modal/Disclosure.tsx
packages/ui/src/components/Modal/__stories__/WithDisclosureFunction.stories.tsx
packages/ui/src/components/Modal/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/Modal/index.tsx
packages/ui/src/components/Modal/types.ts

- Bug
Fix modal with disclosure function not assigning the correct ref and props.

fix(Modal): disclosure function

---

.eslintrc
jest-axe.d.ts
package.json
packages/form/src/components/SubmitErrorAlert/__tests__/index.spec.tsx
packages/form/src/hooks/__tests__/useValidation.spec.ts
packages/form/src/providers/ErrorContext/index.tsx
packages/ui/src/__stories__/Properties/Properties.tsx
packages/ui/src/components/Alert/__tests__/index.test.tsx
packages/ui/src/components/LineChart/CustomLegend.tsx
packages/ui/src/components/Link/__tests__/index.test.tsx
packages/ui/src/components/List/Row.tsx
packages/ui/src/components/Menu/__tests__/index.test.tsx
packages/ui/src/components/ProgressBar/__stories__/UncontrolledProgressBar.tsx
packages/ui/src/components/Toaster/__tests__/index.test.tsx
packages/ui/src/helpers/__tests__/index.ts
pnpm-lock.yaml

- Enhancement
Add `eslint-plugin-prettier` & `eslint-config-prettier` to use Prettier formatting rules with ESLint. Also fix all the formatting issues.

chore: add eslint-plugin-prettier

---

packages/ui/src/__stories__/theme/colors.stories.mdx
packages/ui/src/components/Alert/index.tsx
packages/ui/src/components/Banner/index.tsx
packages/ui/src/components/BarChart/Tooltip.tsx
packages/ui/src/components/Card/__stories__/IsActive.stories.tsx
packages/ui/src/components/Checkbox/index.tsx
packages/ui/src/components/LineChart/CustomLegend.tsx
packages/ui/src/components/LineChart/Tooltip.tsx
packages/ui/src/components/List/__stories__/Selectable.stories.tsx
packages/ui/src/components/Modal/__stories__/HideOnClickOutside.stories.tsx
packages/ui/src/components/Modal/__stories__/HideOnEsc.stories.tsx
packages/ui/src/components/NumberInput/index.tsx
packages/ui/src/components/Table/HeaderRow.tsx
packages/ui/src/components/Table/Row.tsx
packages/ui/src/components/Table/__stories__/Selectable.stories.tsx
packages/ui/src/components/Toaster/__stories__/Sentiments.stories.tsx
packages/ui/src/components/Toaster/__stories__/index.stories.tsx
packages/ui/src/components/Toaster/index.tsx

- Refactor
I removed deprecated usages from our components to be up to date.

refactor: removed deprecated usages

---

.changeset/hungry-spoons-hear.md
packages/ui/src/components/MenuV2/__stories__/WithModal.stories.tsx
packages/ui/src/components/MenuV2/index.tsx
packages/ui/src/components/Modal/Dialog.tsx
packages/ui/src/components/Popover/__tests__/index.test.tsx
packages/ui/src/components/Popover/index.tsx
packages/ui/src/internalComponents/Popup/index.tsx

- Bug
Handle close/show event properly do not have waterfall effects
1.
2.
3.

fix: event workflow not consistent

---

packages/icons/src/components/ProductIcon/__tests__/__snapshots__/index.tsx.snap

Fix unit testing failing on main

fix: unit testing failing on main

---

.changeset/fluffy-poems-bathe.md
packages/plus/src/components/ContentCard/__tests__/__snapshots__/index.test.tsx.snap
packages/plus/src/components/ContentCard/index.tsx

- Enhancement
Minor fix on ContentCard to take full height.

fix(ContentCard): main stack to get all height

---

packages/plus/src/components/ContentCard/__tests__/__snapshots__/index.test.tsx.snap
packages/plus/src/components/ContentCard/index.tsx

fix: content card

---

.changeset/three-brooms-kiss.md
packages/icons/src/components/ProductIcon/Icons.tsx
packages/icons/src/components/ProductIcon/__tests__/__snapshots__/index.tsx.snap

- Enhancement
New ProductIcon `file` and `folder`

feat(ProductIcon): new file and folder

---

.changeset/plenty-teachers-wonder.md
packages/plus/src/components/ContentCard/__tests__/__snapshots__/index.test.tsx.snap
packages/plus/src/components/ContentCard/index.tsx

- Enhancement
Replaced title variant from body strong to body stronger

fix(ContentCard): replace title variant from body strong to body stronger

---

packages/plus/src/components/ContentCard/__tests__/__snapshots__/index.test.tsx.snap

CI is failing because of unit testing on main branch.

ci: fix content card unit testing failing

---

.changeset/famous-beds-develop.md
.github/renovate.json
codecov.yml
packages/plus/package.json
packages/plus/src/components/CodeEditor/CodeEditor.tsx
packages/plus/src/components/CodeEditor/__stories__/Playground.stories.tsx
packages/plus/src/components/CodeEditor/__stories__/Template.stories.tsx
packages/plus/src/components/CodeEditor/__stories__/index.stories.tsx
packages/plus/src/components/CodeEditor/__tests__/__snapshots__/index.tsx.snap
packages/plus/src/components/CodeEditor/__tests__/index.tsx
packages/plus/src/components/CodeEditor/index.ts
packages/plus/src/components/index.ts
pnpm-lock.yaml

- Migration
New component Code Editor

feat(code-editor): add code editor to ultraviolet/plus package

---

.changeset/brave-crabs-press.md
packages/ui/src/components/Popover/index.tsx
packages/ui/src/components/Popup/index.tsx
pnpm-lock.yaml

- Bug
There was an issue when the popover had a SelectInput and you click on select input option it was closing the popover.
Also I added ref into Popover component.
Before: 
https://github.com/scaleway/ultraviolet/assets/15812968/6e28dacd-ee3c-4fbe-a234-5ff52be6240c
After:
https://github.com/scaleway/ultraviolet/assets/15812968/d6da283a-f92c-485d-88bf-0eb8ce5372fd

fix(Popup): popup component to change event on mousedown and add ref into popover component

---

.changeset/fair-boxes-carry.md
packages/form/src/components/DateField/__stories__/Playground.stories.tsx
packages/form/src/components/DateField/__tests__/__snapshots__/index.tsx.snap
packages/form/src/components/DateField/index.tsx
packages/ui/src/components/DateInput/__stories__/Controlled.stories.tsx
packages/ui/src/components/DateInput/__stories__/Exclude.stories.tsx
packages/ui/src/components/DateInput/__stories__/Range.stories.tsx
packages/ui/src/components/DateInput/__stories__/index.stories.tsx
packages/ui/src/components/DateInput/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/DateInput/__tests__/index.test.tsx
packages/ui/src/components/DateInput/index.tsx

update design and add range date
- Feature
For the reference, check the figma https://www.figma.com/file/XHoO4V9LOFEFkAZsocYJ83/Ultraviolet%3A-Core-Components?type=design&node-id=7493%3A121027&mode=design&t=KHeUecaJBVlUWfK4-1 ant the ticket https://jira.infra.online.net/browse/DS-579

feat(dateinput): update design and add range date

---

.changeset/olive-humans-call.md
.storybook/preview.tsx
packages/plus/src/components/ContentCard/__tests__/__snapshots__/index.test.tsx.snap
packages/plus/src/components/ContentCard/index.tsx

- Bug
ContentCard text is not applying color when version is link.
Problem:

fix(ContentCard): color on title and description

---

.changeset/funny-seals-develop.md
packages/plus/src/components/ContentCardGroup/Card.tsx
packages/plus/src/components/ContentCardGroup/SkeletonCard.tsx
packages/plus/src/components/ContentCardGroup/__stories__/Custom.stories.tsx
packages/plus/src/components/ContentCardGroup/__stories__/Description.stories.tsx
packages/plus/src/components/ContentCardGroup/__stories__/Loading.stories.tsx
packages/plus/src/components/ContentCardGroup/__stories__/Playground.stories.tsx
packages/plus/src/components/ContentCardGroup/__stories__/Subtitle.stories.tsx
packages/plus/src/components/ContentCardGroup/__stories__/Template.stories.tsx
packages/plus/src/components/ContentCardGroup/__stories__/index.stories.tsx
packages/plus/src/components/ContentCardGroup/__tests__/__snapshots__/index.test.tsx.snap
packages/plus/src/components/ContentCardGroup/__tests__/index.test.tsx
packages/plus/src/components/ContentCardGroup/index.tsx
packages/plus/src/components/index.ts

- Feature
add a new component `ContentCardGroup` to package ultraviolet/plus

feat: new component ContentCardGroup

---

package.json
pnpm-lock.yaml

Fix ci due to dependencies of ts-node by jest.

fix: jest ts node version

---

.changeset/fifty-actors-hug.md
packages/plus/package.json
pnpm-lock.yaml

Remove not used packages in ultraviolet/plus

chore: remove useless packages

---

.changeset/weak-sheep-mate.md
packages/plus/package.json

Fix location of the index in dist in package json

fix: package json dist index location

---

.changeset/long-mirrors-jam.md
packages/illustrations/package.json
packages/illustrations/rollup.config.mjs
packages/illustrations/src/__stories__/List.tsx

- Bug
Bundle was broken due to a change on our side, this is the fix for it.

fix(illustrations): fix bundle and story

---

.changeset/late-crabs-exist.md
packages/ui/src/components/Popup/helpers.ts

- Bug
Fix popup to add parent scroll on positioning

fix(Popup): to add parent scroll on popup positioning

---

.changeset/olive-penguins-enjoy.md
packages/ui/src/components/NumberInput/__tests__/index.test.tsx
packages/ui/src/components/NumberInput/index.tsx

- Bug
- Refactor
Handle null value in NumberInput.

feat(numberinput): handle null value

---

.changeset/fifty-beds-pump.md
packages/plus/src/components/index.ts

Add missing export on estimate cost.

fix(EstimateCost): add missing export

---

.changeset/hungry-sheep-dance.md
packages/plus/src/components/EstimateCost/Components/Item.tsx
packages/plus/src/components/EstimateCost/EstimateCostContent.tsx
packages/plus/src/components/EstimateCost/OverlayComponent.tsx
packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Item.spec.tsx.snap
packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Region.spec.tsx.snap
packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Regular.spec.tsx.snap
packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Stepper.spec.tsx.snap
packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Strong.spec.tsx.snap
packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Unit.spec.tsx.snap
packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Zone.spec.tsx.snap
packages/plus/src/components/EstimateCost/__tests__/__snapshots__/index.spec.tsx.snap
packages/plus/src/components/EstimateCost/componentStyle.ts
packages/plus/src/components/EstimateCost/constants.ts
packages/plus/src/components/EstimateCost/index.ts
packages/plus/src/components/index.ts

- Enhancement
I fixed some style for the EstimateCost migration and exported default locales which is helpful to know the keys and values.

fix(EstimateCost): fix style and export default locales

---

.changeset/nine-jokes-bow.md
packages/plus/src/components/EstimateCost/Components/Region.tsx
packages/plus/src/components/EstimateCost/Components/Zone.tsx
packages/plus/src/components/EstimateCost/EstimateCostContent.tsx
packages/plus/src/components/EstimateCost/types.ts

- Bug
Added missing props on estimate cost for the migration.

fix(EstimateCost): add missing props

---

.changeset/lemon-lamps-bake.md
packages/ui/src/components/Tabs/TabMenu.tsx
packages/ui/src/components/Tabs/__tests__/__snapshots__/index.test.tsx.snap

- Refactor
Migration of Menu to MenuV2 into Tabs component.
1. Go in deployed storybook version and go to Tabs component
2. Check that the tabs with "More" menu works especially stories "With Menu" and "Show Case"
3. You can also checkout this branch locally, build it and test it on other projects that uses ultraviolet ui

refactor(Tabs): use menu v2

---

.changeset/polite-nails-build.md
packages/form/src/components/SelectableCardField/__tests__/__snapshots__/index.spec.tsx.snap
packages/ui/src/components/SelectableCard/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/SelectableCard/index.tsx
packages/ui/src/components/SwitchButton/__tests__/__snapshots__/index.test.tsx.snap

- Bug
Selectable card with type radio doesn't need the pointer event none. I also added one more date for being able to target the whole selectable card instead of the input.

fix(SelectableCard): fix type radio

---

.changeset/warm-parents-crash.md
packages/form/src/components/CheckboxField/__tests__/__snapshots__/index.spec.tsx.snap
packages/form/src/components/CheckboxGroupField/__tests__/__snapshots__/index.spec.tsx.snap
packages/form/src/components/RadioField/__tests__/__snapshots__/index.spec.tsx.snap
packages/form/src/components/RadioGroupField/__tests__/__snapshots__/index.spec.tsx.snap
packages/form/src/components/SelectableCardField/__tests__/__snapshots__/index.spec.tsx.snap
packages/ui/src/components/Checkbox/__tests__/__snapshots__/index.tsx.snap
packages/ui/src/components/Checkbox/index.tsx
packages/ui/src/components/CheckboxGroup/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/CheckboxGroup/index.tsx
packages/ui/src/components/LineChart/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/List/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/Radio/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/Radio/index.tsx
packages/ui/src/components/RadioGroup/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/SelectableCard/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/SwitchButton/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/Table/__tests__/__snapshots__/index.test.tsx.snap

- Enhancement
When radio is displayed in a group and with row direction we don't have the correct spacing.
| url  | <img width="1024" alt="Screenshot 2023-12-20 at 18 08 38" src="https://github.com/scaleway/ultraviolet/assets/15812968/c2a72aa9-70c3-4b04-8007-41d33c4074bb"> | <img width="1026" alt="Screenshot 2023-12-20 at 18 08 43" src="https://github.com/scaleway/ultraviolet/assets/15812968/316ed4f4-6166-41f7-974c-833048817891"> |
| url  | <img width="1039" alt="Screenshot 2023-12-20 at 18 09 39" src="https://github.com/scaleway/ultraviolet/assets/15812968/10fa945b-d613-4e26-aefb-f4f7ac618c43"> | <img width="1048" alt="Screenshot 2023-12-20 at 18 09 43" src="https://github.com/scaleway/ultraviolet/assets/15812968/400d84 …

fix: groups radio and checkbox to have better spacing in row

---

.storybook/components/Page.tsx
.storybook/preview.tsx
README.md
packages/icons/CHANGELOG.md
packages/ui/src/__stories__/Properties/Properties.tsx

- Fix storybook documentation some pages were not working anymore and some design were broken
| url  | <img width="1041" alt="Screenshot 2024-01-04 at 10 43 46" src="https://github.com/scaleway/ultraviolet/assets/15812968/8f7e2506-a92a-404f-9384-f99b040e7eca"> | <img width="1051" alt="Screenshot 2024-01-04 at 10 43 52" src="https://github.com/scaleway/ultraviolet/assets/15812968/b764b25f-4eec-4965-b620-2856b2a588df"> |
| url  | <img width="1090" alt="Screenshot 2024-01-04 at 10 54 17" src="https://github.com/scaleway/ultraviolet/assets/15812968/95fd0c46-5f70-4d27-a5cd-e8b5c98f3f5f"> | <img width="1082" alt="Screenshot 2024-01-04 at 10 54 49" src="https://github.com/scaleway/ultraviolet/assets/15812968/98f …

docs: fix storybook and add more readme

---

.changeset/strange-fishes-matter.md
packages/form/src/index.ts

- Feature
Add more exported types of react-hook-form

feat(form): add more exported types

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/component_request.yml

Add component request issues on github

Docs/refactor GitHub issues

---

packages/ui/src/components/NumberInputV2/__stories__/index.stories.tsx

Remove useless comment on NumberInputV2 story.

docs: fix number input docs

---

packages/ui/src/components/NumberInputV2/__stories__/LabelDescription.stories.tsx

Small change on number input documentation.

docs: fix number input doc to be more precise

---

packages/ui/src/__stories__/migrations/MigrationNumberInputV2.stories.mdx
packages/ui/src/components/NumberInputV2/__stories__/Step.stories.tsx

Add some more information about NumberInput usages on min max props with step.

docs: improve number input doc

---

.changeset/honest-teachers-do.md
packages/ui/src/components/Tabs/TabMenuItem.tsx
packages/ui/src/components/Tabs/__tests__/__snapshots__/index.test.tsx.snap

- Refactor
Some part of the menu v1 was left in the code I removed them.

refactor(Tabs): remvoe fully menu from tabs

---

package.json

I removed emoji from conventional commit as we don't use them in our commits.

docs: remove emoji from conventional commit

---

.changeset/rotten-terms-repeat.md
packages/form/src/components/SelectInputField/__tests__/__snapshots__/index.spec.tsx.snap
packages/form/src/components/TimeField/__tests__/__snapshots__/index.spec.tsx.snap
packages/form/src/components/TimeField/index.tsx
packages/plus/src/components/EstimateCost/__tests__/__snapshots__/CustomUnitInput.spec.tsx.snap
packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Item.spec.tsx.snap
packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Region.spec.tsx.snap
packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Regular.spec.tsx.snap
packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Stepper.spec.tsx.snap
packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Strong.spec.tsx.snap
packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Unit.spec.tsx.snap
packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Zone.spec.tsx.snap
packages/plus/src/components/EstimateCost/__tests__/__snapshots__/index.spec.tsx.snap
packages/ui/src/components/SelectInput/__tests__/__snapshots__/index.tsx.snap
packages/ui/src/components/SelectInput/index.tsx
packages/ui/src/components/TimeInput/__tests__/__snapshots__/index.test.tsx.snap

- Enhancement
- Fix `SelectInput` required icon to stay with danger sentiment
- Fix `TimeField` to pass `noTopLabel` prop
| url  | <img width="971" alt="Screenshot 2024-02-01 at 15 49 24" src="https://github.com/scaleway/ultraviolet/assets/15812968/d1beff24-2ba7-4184-b00b-5a1a08f9b6aa"> | <img width="965" alt="Screenshot 2024-02-01 at 15 49 36" src="https://github.com/scaleway/ultraviolet/assets/15812968/e60bc6d8-1c85-4f05-a567-b55c88ba24b8"> |

fix: time field and select input

---

.changeset/giant-shoes-add.md
packages/plus/src/components/EstimateCost/Components/NumberInput.tsx
packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Stepper.spec.tsx.snap

- Bug
The number input in estimate cost doesn't allow to clean completly it's content, I fixed it by using number input v2.
Before:
https://github.com/scaleway/ultraviolet/assets/15812968/65b94142-e8e9-4b64-ab97-22cc23b7fabb
After:
https://github.com/scaleway/ultraviolet/assets/15812968/f4f0d660-9050-4fec-9f8e-fb1b304ebe7b

fix(EstimateCost): number input to be fully editable

---

.changeset/silver-hounds-melt.md
packages/plus/src/components/EstimateCost/EstimateCost.tsx
packages/plus/src/components/EstimateCost/OverlayComponent.tsx
packages/plus/src/components/EstimateCost/__tests__/Regular.spec.tsx
packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Regular.spec.tsx.snap

fix(estimate): alert title not forwarded properly

---

.changeset/modern-clocks-repair.md
packages/form/src/components/TagInputField/__stories__/Required.stories.tsx
packages/form/src/components/TagInputField/__tests__/__snapshots__/index.spec.tsx.snap
packages/form/src/components/TagInputField/__tests__/index.spec.tsx
packages/form/src/components/TagInputField/index.tsx
packages/ui/src/components/TagInput/__stories__/Disabled.stories.tsx
packages/ui/src/components/TagInput/__stories__/Error.stories.tsx
packages/ui/src/components/TagInput/__stories__/Helper.stories.tsx
packages/ui/src/components/TagInput/__stories__/LabelDescription.stories.tsx
packages/ui/src/components/TagInput/__stories__/Placeholder.stories.tsx
packages/ui/src/components/TagInput/__stories__/Playground.stories.tsx
packages/ui/src/components/TagInput/__stories__/ReadOnly.stories.tsx
packages/ui/src/components/TagInput/__stories__/Size.stories.tsx
packages/ui/src/components/TagInput/__stories__/Success.stories.tsx
packages/ui/src/components/TagInput/__stories__/Template.stories.tsx
packages/ui/src/components/TagInput/__stories__/Tooltip.stories.tsx
packages/ui/src/components/TagInput/__stories__/index.stories.tsx
packages/ui/src/components/TagInput/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/TagInput/__tests__/index.test.tsx
packages/ui/src/components/TagInput/index.tsx

- Enhancement
Update `TagInput` & `TagInputField` to follow new Ultraviolet specifications

feat: update tag input component

---

.changeset/pretty-buses-count.md
packages/ui/src/components/Toaster/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/Toaster/index.tsx

- Bug
Some fixes and new props on `<ToastContainer />` component:
- added `className` and `autoClose` props
- remove custom css in ToastContainer
- fix ToastContainer width

fix(Toaster): width and new props

---

.changeset/strange-apes-care.md
packages/form/src/components/SelectableCardField/__tests__/__snapshots__/index.spec.tsx.snap
packages/ui/src/components/SelectableCard/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/SelectableCard/index.tsx
packages/ui/src/components/SwitchButton/__tests__/__snapshots__/index.test.tsx.snap

- Refactor
I changed a bit SelectableCard to follow design specs. First, the component won't be inline anymore that's why I changed it to take full width. I added also 4px padding between the label and content of the SelectableCard as defined in the specs.
| url  | <img width="1036" alt="Screenshot 2024-02-19 at 17 22 40" src="https://github.com/scaleway/ultraviolet/assets/15812968/da26489e-5202-4d27-9881-9cdab593aa48"> | <img width="1041" alt="Screenshot 2024-02-19 at 17 22 50" src="https://github.com/scaleway/ultraviolet/assets/15812968/576db62b-2201-4b51-ad14-f33cdcfc15d8"> |

refactor(SelectableCard): to take full width and have better spacings

---

.changeset/blue-geese-serve.md
packages/ui/src/components/Toaster/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/Toaster/index.tsx

- Bug
The text in `Toaster` should be `bodySmallStrong`
1. Font-size in the componet : `body`-> `bodySmallStrong`

fix(Toaster): font size to bodysmallstrong

---

.changeset/quiet-elephants-explain.md
.changeset/seven-tomatoes-appear.md
packages/form/src/components/SelectableCardField/__tests__/__snapshots__/index.spec.tsx.snap
packages/ui/src/components/SelectableCard/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/SelectableCard/index.tsx
packages/ui/src/components/SwitchButton/__tests__/__snapshots__/index.test.tsx.snap

- Bug
Fix `<SelectableCard />` to remove gap when no label is set
| url  | <img width="972" alt="Screenshot 2024-02-22 at 15 03 33" src="https://github.com/scaleway/ultraviolet/assets/15812968/a0573d50-6c37-492b-83fb-f4df9c0a28fa"> |  <img width="958" alt="Screenshot 2024-02-22 at 15 06 24" src="https://github.com/scaleway/ultraviolet/assets/15812968/ae43f913-c9a8-40b2-993a-48c886421559"> |

fix(SelectableCard): to remove gap when no label is set

---

.changeset/lucky-yaks-fry.md
packages/plus/src/components/ContentCard/__tests__/__snapshots__/index.test.tsx.snap
packages/plus/src/components/ContentCardGroup/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/List/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/Skeleton/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/Skeleton/index.tsx
packages/ui/src/components/Table/__tests__/__snapshots__/index.test.tsx.snap

- Enhancement
Fix `<Skeleton />` component to have `aria-busy`

fix(Skeleton): add aria-busy property

---

.changeset/famous-stingrays-exist.md
packages/ui/src/components/Notification/__stories__/Children.tsx
packages/ui/src/components/Notification/__stories__/Playground.stories.tsx
packages/ui/src/components/Notification/__stories__/Template.stories.tsx
packages/ui/src/components/Notification/__stories__/index.stories.tsx
packages/ui/src/components/Notification/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/Notification/__tests__/index.test.tsx
packages/ui/src/components/Notification/index.tsx
packages/ui/src/components/index.ts

- Feature
New component `Notification` added to Ultraviolet UI.
1. Define a new component
2. Add the component to Storybook
3. Tests for the component

feat: new component Notification

---

packages/ui/src/components/TextInputV2/__stories__/index.stories.tsx

For some reason the text input v2 stories were disabled

docs: fix text input v2 documentation

---

package.json
pnpm-lock.yaml

- DevDeps
We don't use it so why keeping it

chore: remove react router dom

---

.changeset/strange-peaches-do.md
packages/illustrations/package.json

- Hotfix
Fix missing import in package.json

fix(illustrations): missing export in package json

---

.changeset/eight-books-build.md
packages/ui/src/components/TagList/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/TagList/__tests__/index.test.tsx
packages/ui/src/components/TagList/index.tsx

- Enhancement
Add prop `popoverPlacement` on `<TagList />` component

fix(TagList): add popover placement on tag list

---

.changeset/eighty-rocks-pull.md
packages/form/src/components/DateField/__tests__/__snapshots__/index.tsx.snap
packages/form/src/components/TextInputFieldV2/__tests__/__snapshots__/index.spec.tsx.snap
packages/ui/src/components/DateInput/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/TextInputV2/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/TextInputV2/index.tsx

- Bug
React doesn't like uppercase data attributes.

fix(TextInputV2): lower case readonly data attribute

---

.changeset/poor-coats-develop.md
packages/ui/src/components/Expandable/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/Expandable/__tests__/index.test.tsx
packages/ui/src/components/Expandable/index.tsx

- Enhancement
I added prop `animationDuration` on `<Expandable />` component in order to customize it for navigation.

feat(Expandable): add animation duration

---

.changeset/violet-oranges-warn.md
packages/ui/src/components/Separator/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/Separator/index.tsx

- Enhancement
Change separator color from border to border weak

feat(Separator): change border color to weak

---

.changeset/lemon-lizards-explode.md
packages/ui/src/components/Avatar/index.tsx

- Bug
Fix the problem when you are multiple space and trim for component Avatar

fix(Avatar): fix multiple space and trim for initials

---

.changeset/brown-feet-impress.md
packages/form/src/components/TimeField/__tests__/__snapshots__/index.spec.tsx.snap
packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Unit.spec.tsx.snap
packages/ui/src/components/SelectInput/__tests__/__snapshots__/index.tsx.snap
packages/ui/src/components/Separator/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/Separator/index.tsx
packages/ui/src/components/TextInput/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/TimeInput/__tests__/__snapshots__/index.test.tsx.snap

- Enhancement
Change `<Separator />` color from `border` to `borderWeak`

fix(Separator): change color from border to border weak

---

.changeset/curvy-buses-smile.md
packages/form/src/components/CheckboxField/__tests__/__snapshots__/index.spec.tsx.snap
packages/form/src/components/CheckboxGroupField/__tests__/__snapshots__/index.spec.tsx.snap
packages/form/src/components/DateField/__tests__/__snapshots__/index.tsx.snap
packages/form/src/components/Form/__tests__/__snapshots__/index.spec.tsx.snap
packages/form/src/components/Form/index.tsx
packages/form/src/components/KeyValueField/__tests__/__snapshots__/index.spec.tsx.snap
packages/form/src/components/NumberInputField/__tests__/__snapshots__/index.spec.tsx.snap
packages/form/src/components/NumberInputFieldV2/__tests__/__snapshots__/index.spec.tsx.snap
packages/form/src/components/RadioField/__tests__/__snapshots__/index.spec.tsx.snap
packages/form/src/components/RadioGroupField/__tests__/__snapshots__/index.spec.tsx.snap
packages/form/src/components/SelectInputField/__tests__/__snapshots__/index.spec.tsx.snap
packages/form/src/components/SelectableCardField/__tests__/__snapshots__/index.spec.tsx.snap
packages/form/src/components/SelectableCardGroupField/__tests__/__snapshots__/index.spec.tsx.snap
packages/form/src/components/Submit/__tests__/__snapshots__/index.spec.tsx.snap
packages/form/src/components/SubmitErrorAlert/__tests__/__snapshots__/index.spec.tsx.snap
packages/form/src/components/TagInputField/__tests__/__snapshots__/index.spec.tsx.snap
packages/form/src/components/TextAreaField/__tests__/__snapshots__/index.spec.tsx.snap
packages/form/src/components/TextInputField/__tests__/__snapshots__/index.spec.tsx.snap
packages/form/src/components/TextInputFieldV2/__tests__/__snapshots__/index.spec.tsx.snap
packages/form/src/components/TimeField/__tests__/__snapshots__/index.spec.tsx.snap
packages/form/src/components/ToggleField/__tests__/__snapshots__/index.spec.tsx.snap
packages/form/src/components/ToggleGroupField/__tests__/__snapshots__/index.spec.tsx.snap
packages/form/src/providers/ErrorContext/__tests__/__snapshots__/index.spec.tsx.snap

- Feature
Add no validate to form.

feat(Form): add no validate to form

---

.changeset/blue-readers-add.md
.changeset/fuzzy-apricots-turn.md
packages/form/src/components/CheckboxGroupField/__stories__/PartiallyRequired.stories.tsx
packages/form/src/components/CheckboxGroupField/__stories__/index.stories.tsx
packages/form/src/components/CheckboxGroupField/__tests__/__snapshots__/index.spec.tsx.snap
packages/form/src/components/CheckboxGroupField/index.tsx
packages/ui/src/components/CheckboxGroup/__stories__/Required.stories.tsx
packages/ui/src/components/CheckboxGroup/__stories__/index.stories.tsx
packages/ui/src/components/CheckboxGroup/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/CheckboxGroup/index.tsx

- Enhancement
- Fix `<CheckboxGroupField />` to make all checkbox of the group as required when set `required` prop
- Fix `<CheckboxGroupField.Checkbox />` to have prop `required` and allow partial requirement for the group to be valid
- Fix `<CheckboxGroup.Checkbox />` to have prop `required`

fix(CheckboxGroup): to allow partial and total required

---

.changeset/cuddly-ants-bathe.md
packages/ui/src/components/Skeleton/index.tsx

- Enhancement
Add `data-testid` and `aria-label` into `<Skeleton />` component

fix(Skeleton): add aria label and data test id

---

.changeset/bright-clocks-compete.md
.changeset/good-crabs-marry.md
packages/plus/src/components/Navigation/components/Item.tsx
packages/ui/src/components/Expandable/index.tsx

- Bug
- Fix `<Navigation />` to have correct color for `<Navigation.Item />` that has sub items
- Fix `<Expandable />` component to have correct `visibility` set in css

fix(Navigation): some minor fixes

---

.changeset/new-rats-walk.md
packages/plus/src/components/Navigation/components/Item.tsx

- Bug
Fix `<Navigation />` active item with wrong color

fix(Navigation): active items with wrong color

---

.changeset/moody-dryers-cover.md
packages/form/src/components/SelectInputField/__stories__/index.stories.tsx
packages/ui/src/components/SelectInput/__tests__/__snapshots__/index.tsx.snap
packages/ui/src/components/SelectInput/__tests__/index.tsx
packages/ui/src/components/SelectInput/index.tsx

- Bug
Fix type error when child is null or undefined.

fix(SelectInput): null child type error

---

.changeset/sweet-donuts-promise.md
packages/ui/src/components/ProgressBar/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/ProgressBar/index.tsx

- Enhancement
Add new sentiment `danger` to `<ProgressBar />` component

feat(ProgressBar): new sentiment danger

---

.changeset/eight-ants-kneel.md
packages/plus/src/components/Navigation/Navigation.tsx
packages/plus/src/components/Navigation/NavigationContent.tsx
packages/plus/src/components/Navigation/components/Item.tsx

- Bug
Fix `<Navigation />` category icon and add `id` prop

fix(Navigation): category icon on active and id prop

---

.github/renovate.json

- Enhancement
To group `@testing-library` packages together in order to have a clean update without errors.

ci(renovate): group testing library update together

---

codecov.yml

Fix codecov to only check package @ultraviolet/ui

ci: fix codecov to only check ultraviolet ui

---

.changeset/forty-terms-run.md
packages/ui/src/components/SelectInputV2/SearchBarDropdown.tsx
packages/ui/src/components/SelectInputV2/__tests__/__snapshots__/index.test.tsx.snap

- Bug
Autofocusing the searchbar should not scroll to top. I add a temporary fix because @matthprost is working on `Popup` and will make a fix on this component. We will can put autoFocus back and drop my fix :)
1. Use a ref for the Search bar input
2. Add an useEffect and setTimeout to focus it after Popup styles computation
3.

fix(SelectInputV2): autofocus searchbar

---

.github/workflows/pull_request_title.yml

- Enhancement
Fix github action title.

ci: fix check title github action

---

.changeset/friendly-cougars-brush.md
packages/illustrations/package.json
packages/illustrations/src/__stories__/List.tsx
packages/illustrations/src/index.ts

fix(build): illustrations exports

---

.changeset/tough-moons-listen.md
packages/plus/src/components/Navigation/components/Item.tsx

- Bug
Fix `<NavigationComponent />` to have correct empty state, pin / unpin to be div instead of button and fix on click on pin / unpin

fix(Navigation): some fixes

---

.github/workflows/size-limit.yml
packages/illustrations/package.json
packages/plus/package.json

- Bug
CI is red because of size limit that is not working properly. I made a fix to test each packages individually and fix the size limit per packages.

ci: fix size limit by testing each packages individually

---

.changeset/tasty-colts-fold.md
packages/form/src/components/SelectInputFieldV2/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/MenuV2/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/Popup/helpers.ts
packages/ui/src/components/Popup/index.tsx
packages/ui/src/components/SelectInputV2/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/Tabs/__tests__/__snapshots__/index.test.tsx.snap

- Enhancement
Reduce margin between popup and the trigger button.

fix(Popup): reduce margin between trigger button and popup

---

.changeset/strange-pots-sort.md
packages/form/src/components/SelectInputFieldV2/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/MenuV2/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/Popover/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/Popup/index.tsx
packages/ui/src/components/SelectInputV2/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/Tabs/__tests__/__snapshots__/index.test.tsx.snap

- Bug
- Feature
- Enhancement
- Migration
- Refactor
1.
2.
3.

fix: autofocus popup

---

packages/icons/README.md
packages/ui/README.md

Fix some of the documentation.

docs: add some more info

---

.changeset/twenty-shrimps-talk.md
packages/plus/src/components/Navigation/Navigation.tsx
packages/plus/src/components/Navigation/NavigationContent.tsx
packages/plus/src/components/Navigation/NavigationProvider.tsx
packages/plus/src/components/Navigation/__stories__/Playground.stories.tsx
packages/plus/src/components/Navigation/components/Item.tsx
packages/plus/src/components/Navigation/components/PinnedItems.tsx
packages/plus/src/components/Navigation/constants.ts
packages/plus/src/components/Navigation/types.ts

- Enhancement
Some fixes on `<Navigation />`:
- Rename of `onClickExpand` to `onExpandChange` on `<NavigationProvider />`
- Add new prop `onToggleExpand` on `<Navigation />` => this function will be triggered on click on the expand/collapse button

fix(Navigation): more fixes on how we handle toggle change

---

.changeset/flat-bats-bow.md
packages/form/src/components/SelectInputField/__tests__/__snapshots__/index.test.tsx.snap
packages/form/src/components/Submit/__tests__/__snapshots__/index.test.tsx.snap
packages/form/src/components/TextInputField/__tests__/__snapshots__/index.test.tsx.snap
packages/form/src/components/TimeField/__tests__/__snapshots__/index.test.tsx.snap
packages/plus/src/components/EstimateCost/__tests__/__snapshots__/CustomUnitInput.test.tsx.snap
packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Item.test.tsx.snap
packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Region.test.tsx.snap
packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Regular.test.tsx.snap
packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Stepper.test.tsx.snap
packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Strong.test.tsx.snap
packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Unit.test.tsx.snap
packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Zone.test.tsx.snap
packages/plus/src/components/EstimateCost/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/Expandable/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/Expandable/__tests__/index.test.tsx
packages/ui/src/components/Expandable/index.tsx
packages/ui/src/components/SelectInput/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/Snippet/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/TextInput/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/TimeInput/__tests__/__snapshots__/index.test.tsx.snap

- Enhancement
Slight performance improvement on `<Expandable />` component to remove class generation when open and close
Before:
https://github.com/scaleway/ultraviolet/assets/15812968/0aff03b2-53aa-49a1-b1a9-57267d33c2de
After:
https://github.com/scaleway/ultraviolet/assets/15812968/ecb9d46d-d03e-41f8-b93c-e0f8f8f98331

fix(Expandable): slight performance improvement on expandable

---

.changeset/quick-terms-collect.md
packages/plus/src/components/FAQ/__tests__/__snapshots__/index.test.tsx.snap
packages/plus/src/components/SteppedListCard/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/Card/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/Card/index.tsx

- Enhancement
`<Card />`: add flex to have full height card aligned into a Row.

fix(Card): add flex to card

---

.changeset/seven-ghosts-smell.md
packages/illustrations/package.json
pnpm-lock.yaml

- Bug
Correct usage of deps for Illustrations

fix(illustrations): remove @utils/test from deps

---

.changeset/flat-suns-shake.md
packages/ui/src/components/Stepper/Step.tsx
packages/ui/src/components/Stepper/__stories__/Disabled.stories.tsx
packages/ui/src/components/Stepper/__stories__/Example.stories.tsx
packages/ui/src/components/Stepper/__stories__/Interactive.stories.tsx
packages/ui/src/components/Stepper/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/Stepper/__tests__/index.test.tsx
packages/ui/src/components/Stepper/index.tsx

- Bug
Index of steps will start at 0 instead of 1

fix(Stepper): index start at 0

---

.changeset/yellow-panthers-sort.md
packages/ui/src/components/Avatar/index.tsx
packages/ui/src/components/List/__tests__/index.test.tsx
packages/ui/src/components/SelectInputV2/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/Table/__tests__/index.test.tsx
packages/ui/src/components/TagInput/index.tsx
packages/ui/src/components/VerificationCode/index.tsx

- Refactor
Improve typing on Avatar, List, Table, TagInput and Verification code. Those fixes reduce the number of error when remove `"noUncheckedIndexedAccess": false` in tsconfig file.

refactor(ts): better typing on avatar, tag input, verification code

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/component_request.yml
.github/ISSUE_TEMPLATE/design_token_request.yml
.github/ISSUE_TEMPLATE/documentation_improvement.yml
.github/ISSUE_TEMPLATE/icon_request.yml
.github/ISSUE_TEMPLATE/pattern_request.yml
.github/workflows/ci.yml
.github/workflows/illustrations-update.yml
.github/workflows/illustrations-upload.yml
package.json
pnpm-lock.yaml

ci: fix github action name

---

packages/form/README.md
packages/icons/README.md
packages/illustrations/README.md
packages/plus/README.md
packages/themes/README.md
packages/ui/README.md

- Bug
- Feature
- Enhancement
- Migration
- Refactor
1.
2.
3.

docs: minor changes on readme

---

.changeset/many-olives-beg.md
packages/form/src/components/SelectInputFieldV2/__tests__/__snapshots__/index.test.tsx.snap
packages/form/src/components/UnitInputField/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/SelectInputV2/SelectBar.tsx
packages/ui/src/components/SelectInputV2/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/SelectInputV2/index.tsx
packages/ui/src/components/UnitInput/__tests__/__snapshots__/index.test.tsx.snap

- Bug
Add label to SelectInputV2 combobox.

fix(SelectInputV2): add label to combobox

---

.changeset/stale-jars-compare.md
packages/form/src/components/NumberInputFieldV2/__tests__/__snapshots__/index.test.tsx.snap
packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Stepper.test.tsx.snap
packages/ui/src/components/NumberInputV2/__stories__/Step.stories.tsx
packages/ui/src/components/NumberInputV2/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/NumberInputV2/__tests__/index.test.tsx
packages/ui/src/components/NumberInputV2/index.tsx

- Bug
`NumberInputV2`:
- if the value is out of the min / max range, the input will automatically be the min / max value on blur when controlled (fixed)
- now supports float numbers

fix(NumberInputV2): handles float and fix onBlur

---

.changeset/sweet-ties-wink.md
packages/plus/src/components/Navigation/components/Item.tsx

- Bug
Navigation items will not lose focus when space pressed

fix: navigation loses focus

---

packages/themes/public/style/dark.css
packages/themes/public/style/darker.css
packages/themes/public/style/light.css
packages/themes/src/themes/console/dark.ts
packages/themes/src/themes/console/darker.ts
packages/themes/src/themes/console/light.ts
scripts/figma-synchronise-tokens.mjs

- Feature
New elevation tokens to be added + update of the script to avoid conflict between 2 different `other` object.

feat(tokens): new elevation tokens

---

.changeset/beige-planes-build.md
packages/ui/src/components/Stepper/Step.tsx
packages/ui/src/components/Stepper/__stories__/Example.stories.tsx
packages/ui/src/components/Stepper/__stories__/WithAnimation.stories.tsx
packages/ui/src/components/Stepper/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/Stepper/__tests__/index.test.tsx
packages/ui/src/components/Stepper/index.tsx

- Bug
Animation style fixed
| |      |    
| :--- | :--------: |
| Before  |  <img width="839" alt="Capture d’écran 2024-06-24 à 16 08 44" src="https://github.com/scaleway/ultraviolet/assets/106706307/ecefe744-3d74-4341-a1e5-26585f149e82">| 
| After  | <img width="839" alt="Capture d’écran 2024-06-24 à 16 08 34" src="https://github.com/scaleway/ultraviolet/assets/106706307/67cbdb31-7138-43ee-984e-cbf1c4a1a68f"> | screenshot |

fix(Stepper): animation

---

.changeset/twelve-geckos-cross.md
packages/ui/src/components/List/Cell.tsx
packages/ui/src/components/List/Row.tsx
packages/ui/src/components/List/__stories__/Example.stories.tsx
packages/ui/src/components/List/__stories__/PreventClick.stories.tsx
packages/ui/src/components/List/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/List/__tests__/index.test.tsx
packages/ui/src/components/List/constants.tsx

- Bug
| url  | <img width="960" alt="Screenshot 2024-06-25 at 15 17 45" src="https://github.com/scaleway/ultraviolet/assets/15812968/79531a12-8866-47dc-94c6-a1e30ba9329f"> | <img width="952" alt="Screenshot 2024-06-25 at 15 17 53" src="https://github.com/scaleway/ultraviolet/assets/15812968/9979b48c-1109-4905-8922-c422a1898890"> |

fix(List): expand button to have correct sizing

---

.aws/cors.json
.github/workflows/illustrations-upload.yml
.prettierignore
package.json

- Feature
Add cors policy to the right bucket

fix(cors): bucket issue

---

.changeset/yellow-rivers-happen.md
packages/form/src/components/SelectInputFieldV2/__tests__/__snapshots__/index.test.tsx.snap
packages/form/src/components/UnitInputField/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/SelectInputV2/Dropdown.tsx
packages/ui/src/components/SelectInputV2/SelectBar.tsx
packages/ui/src/components/SelectInputV2/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/SelectInputV2/__tests__/index.test.tsx
packages/ui/src/components/SelectInputV2/index.tsx
packages/ui/src/components/UnitInput/__tests__/__snapshots__/index.test.tsx.snap

- Feature
SelectInputV2 : New prop `tooltip`

feat(SelectInputV2): new prop tooltip

---

.dockerignore
.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/component_request.yml
.github/ISSUE_TEMPLATE/design_token_request.yml
.github/ISSUE_TEMPLATE/documentation_improvement.yml
.github/ISSUE_TEMPLATE/icon_request.yml
.github/ISSUE_TEMPLATE/pattern_request.yml
.github/workflows/changesets-renovate.yml
.github/workflows/ci.yml
.github/workflows/deploy-storybook.yml
.github/workflows/illustrations-update.yml
.github/workflows/illustrations-upload.yml
.github/workflows/pull_request_title.yml
.github/workflows/release.yml
.github/workflows/size-limit.yml
.github/workflows/sync-design-tokens.yml
.github/workflows/teardown_pull_request.yml
.storybook/preview.tsx
Dockerfile
README.md
codecov.yml
package.json
pnpm-lock.yaml
pnpm-workspace.yaml

- Enhancement
Migrate from chromatics to container deploy

feat(deploy): use container deployment instead of chromatics

---

.github/workflows/deploy-storybook.yml

- Bug
- Feature
- Enhancement
- Migration
- Refactor
1.
2.
3.

ci(deploy): deploy only on branch & main

---

.github/workflows/deploy-storybook.yml

- Enhancement
Improvement deployement stability for main to have more cpus and min scale set to 1.

ci: fix min scale and cpu usage for deployement

---

.github/workflows/deploy-storybook.yml

ci: fix ci

---

.changeset/clever-hotels-behave.md
packages/ui/src/components/List/Row.tsx
packages/ui/src/components/List/__stories__/Expandable.stories.tsx
packages/ui/src/components/List/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/List/__tests__/index.test.tsx

- Enhancement
Add `expanded` prop on `<List.Row />` allowing the user to add an external button to expand or collapse rows

fix(List): add expanded on list row

---

.changeset/angry-meals-wave.md
packages/form/src/components/RadioField/__tests__/__snapshots__/index.test.tsx.snap
packages/form/src/components/RadioGroupField/__tests__/__snapshots__/index.test.tsx.snap
packages/form/src/components/SelectableCardField/__tests__/__snapshots__/index.test.tsx.snap
packages/form/src/components/SelectableCardGroupField/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/Radio/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/Radio/index.tsx
packages/ui/src/components/RadioGroup/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/SelectableCard/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/SelectableCardGroup/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/SwitchButton/__tests__/__snapshots__/index.test.tsx.snap

- Bug
`<Radio />`: fix selected disabled color
| :--- | :--------: | :--------: |
| url  | <img width="112" alt="Capture d’écran 2024-07-05 à 11 17 27" src="https://github.com/scaleway/ultraviolet/assets/106706307/07d62251-cd03-4b0c-95a7-37ee879ca1b9"> | <img width="112" alt="Capture d’écran 2024-07-05 à 11 17 31" src="https://github.com/scaleway/ultraviolet/assets/106706307/9f91d811-dc84-4b8b-8abe-e3fb393bc44a"> |

fix(Radio): disabled checked radio color

---

.changeset/tough-items-exist.md
packages/form/src/components/RadioGroupField/__tests__/__snapshots__/index.test.tsx.snap
packages/form/src/components/SelectableCardField/__tests__/__snapshots__/index.test.tsx.snap
packages/form/src/components/SelectableCardGroupField/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/Checkbox/index.tsx
packages/ui/src/components/Radio/index.tsx
packages/ui/src/components/RadioGroup/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/SelectableCard/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/SelectableCard/index.tsx
packages/ui/src/components/SelectableCardGroup/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/SwitchButton/__tests__/__snapshots__/index.test.tsx.snap

- Enhancement
`<SelectableCard />` component to have label taking 100% width while using radio and checkbox

fix(SelectableCard): label to take full width in radio and checkbox

---

.changeset/lazy-squids-train.md
packages/ui/src/components/List/ListContext.tsx
packages/ui/src/components/List/Row.tsx
packages/ui/src/components/List/__stories__/Expandable.stories.tsx

- Bug
Prop `expanded` not working properly on first render.

fix(List): prop expanded not working properly

---

.changeset/beige-ladybugs-kiss.md
packages/ui/src/components/Modal/Disclosure.tsx
packages/ui/src/components/Modal/index.tsx
packages/ui/src/components/Modal/types.ts

This reverts commit 3a97e744a0a955eae9dc0e9c831a98647e0be068.

revert(modal): revert focus on close modal

---

.changeset/sweet-apricots-beam.md
packages/form/src/components/DateField/__tests__/__snapshots__/index.test.tsx.snap
packages/form/src/components/SelectInputFieldV2/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/ActionBar/index.tsx
packages/ui/src/components/DateInput/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/DateInput/index.tsx
packages/ui/src/components/MenuV2/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/MenuV2/index.tsx
packages/ui/src/components/Modal/Dialog.tsx
packages/ui/src/components/Modal/__stories__/Template.stories.tsx
packages/ui/src/components/Modal/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/Notification/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/Notification/index.tsx
packages/ui/src/components/SelectInputV2/Dropdown.tsx
packages/ui/src/components/SelectInputV2/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/Tabs/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/UnitInput/__tests__/__snapshots__/index.test.tsx.snap

- Refactor
Update elevation tokens on many components to have a better render in dark and darker themes
| url  | <img width="345" alt="Screenshot 2024-06-26 at 11 02 04" src="https://github.com/scaleway/ultraviolet/assets/15812968/af086419-d6ce-4155-9346-ffef8ffe0498"> | <img width="349" alt="Screenshot 2024-06-26 at 11 02 10" src="https://github.com/scaleway/ultraviolet/assets/15812968/e0a02d1c-602e-4cec-b326-3598e873fbc8"> |
| url  | <img width="784" alt="Screenshot 2024-06-26 at 11 06 54" src="https://github.com/scaleway/ultraviolet/assets/15812968/685cb18d-f9be-417e-92c4-f3ea441cf93a"> | <img width="791" alt="Screenshot 2024-06-26 at 11 06 59" src="https://github.com/scaleway/ultraviolet/assets/15812968/3567517d-c14e …

refactor: update elevation tokens usages on many components

---

.github/workflows/deploy-storybook.yml
.github/workflows/teardown_pull_request.yml

- Enhancement
A better cold start on storybook

feat(container): add sandbox version

---

.changeset/funny-ghosts-argue.md
packages/ui/src/components/SearchInput/index.tsx
packages/ui/src/components/SearchInput/types.ts

- Bug
Add missing props on SearchInput.

fix(SearchInput): add missing props

---

.changeset/fifty-chicken-float.md
.changeset/twenty-olives-hunt.md
packages/form/src/components/SelectInputField/__tests__/__snapshots__/index.test.tsx.snap
packages/form/src/components/Submit/__tests__/__snapshots__/index.test.tsx.snap
packages/form/src/components/TextInputField/__tests__/__snapshots__/index.test.tsx.snap
packages/form/src/components/TimeField/__tests__/__snapshots__/index.test.tsx.snap
packages/plus/src/components/EstimateCost/__tests__/__snapshots__/CustomUnitInput.test.tsx.snap
packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Item.test.tsx.snap
packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Region.test.tsx.snap
packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Regular.test.tsx.snap
packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Stepper.test.tsx.snap
packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Strong.test.tsx.snap
packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Unit.test.tsx.snap
packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Zone.test.tsx.snap
packages/plus/src/components/EstimateCost/__tests__/__snapshots__/index.test.tsx.snap
packages/plus/src/components/Navigation/NavigationContent.tsx
packages/plus/src/components/Navigation/NavigationProvider.tsx
packages/plus/src/components/Navigation/__stories__/Playground.stories.tsx
packages/plus/src/components/Navigation/__stories__/index.stories.tsx
packages/plus/src/components/Navigation/components/Item.tsx
packages/ui/src/components/Expandable/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/Expandable/__tests__/index.test.tsx
packages/ui/src/components/Expandable/index.tsx
packages/ui/src/components/SelectInput/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/Snippet/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/TextInput/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/TimeInput/__tests__/__snapshots__/index.test.tsx.snap

- Enhancement
- On `<Expandable />` component, when prop `animationDuration` is set to 0 it will remove the animation of the component
- Add `animation` prop on `<NavigationProvider />` to disable all animations on Navigation

fix(Navigation): add a prop to disable animation if needed

---

.github/workflows/teardown_pull_request.yml

Should fix deployement teardown issue on github action.

ci: fix remove storybook deployement

---

README.md

This reverts commit 3a97e744a0a955eae9dc0e9c831a98647e0be068.

docs(yalc): add documentation issue

---

.changeset/fresh-bags-burn.md
packages/form/src/components/TagInputField/__tests__/__snapshots__/index.test.tsx.snap
packages/form/src/components/TagInputField/__tests__/index.test.tsx
packages/form/src/components/TagInputField/index.tsx

- Enhancement
Add support of `regex` on `TagInputField` component

fix(TagInputField): add regex prop

---

.github/workflows/deploy-storybook.yml

Fix storybook deployment to correctly set dns only on main branch

ci: fix dns deployement

---

.github/workflows/deploy-storybook.yml

ci: increase vcpu for deployement

---

packages/plus/src/components/Navigation/NavigationContent.tsx
packages/plus/src/components/Navigation/__tests__/__snapshots__/index.test.tsx.snap
packages/plus/src/components/Navigation/__tests__/index.test.tsx
packages/plus/src/components/Navigation/components/Item.tsx
packages/plus/src/components/Navigation/components/PinnedItems.tsx

- CI
Add tests for Navigation.

ci: add unit testing on navigation

---

.github/workflows/ci.yml

ci: fix dns

---

.changeset/smooth-camels-press.md
packages/form/src/components/SliderField/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/Slider/__stories__/CustomScale.stories.tsx
packages/ui/src/components/Slider/__tests__/__snapshots__/doubleSlider.test.tsx.snap
packages/ui/src/components/Slider/__tests__/__snapshots__/singleSlider.test.tsx.snap
packages/ui/src/components/Slider/components/DoubleSlider.tsx
packages/ui/src/components/Slider/components/Options.tsx
packages/ui/src/components/Slider/components/SingleSlider.tsx
packages/ui/src/components/Slider/styles.ts

- Bug
There was an issue with slider and it's options positions. When in a narrow space (like a modal) the options under were not correctly set.

fix(Slider): option positioning

---

.changeset/good-horses-vanish.md
packages/plus/src/components/Navigation/NavigationProvider.tsx
packages/plus/src/components/Navigation/__stories__/Playground.stories.tsx
packages/plus/src/components/Navigation/__tests__/__snapshots__/index.test.tsx.snap

- Bug
Animation of the navigation has been set to false by default while it shouldn't.

fix(Navigation): enable back animaiton by default

---

.changeset/polite-crabs-obey.md
packages/form/src/components/SubmitErrorAlert/__tests__/__snapshots__/index.test.tsx.snap
packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Regular.test.tsx.snap
packages/ui/src/components/Alert/__stories__/Link.stories.tsx
packages/ui/src/components/Alert/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/Alert/__tests__/index.test.tsx
packages/ui/src/components/Alert/index.tsx

- Feature
New sentiment `neutral` on `<Alert />`

feat(Alert): new sentiment neutral

---

.changeset/red-buckets-bow.md
packages/form/src/components/CheckboxField/index.tsx
packages/form/src/components/RadioField/index.tsx

- Bug
Radio field and checkbox field not spreading correctly data-testid.

fix: radio and checkbox field to spread data testid

---

.changeset/shaggy-camels-sell.md
packages/ui/src/components/index.ts

fix(AvatarV2): missing export

---

packages/ui/package.json

ci: fix size

---

.github/workflows/ci.yml

There is still an issue with the deployment of container serverless on main

ci: fix deployment

---

.changeset/nervous-pears-cross.md
packages/themes/package.json

It seems that the last update failed so I made manual one.

chore: manual update ultraviolet theme

---

.changeset/brown-flies-shake.md
packages/plus/src/components/ContentCardGroup/Card.tsx
packages/plus/src/components/ContentCardGroup/__tests__/__snapshots__/index.test.tsx.snap
packages/plus/src/components/ContentCardGroup/__tests__/index.test.tsx

- Enhancement
Add titleAs and subtitleAs to ContentCardGroup

feat: add titleAs and subtitleAs to ContentCardGroup

---

.changeset/empty-berries-sort.md
packages/form/src/components/SelectInputFieldV2/index.tsx

- Bug
Fix `SelectInputFieldV2` `onChange` prop type.

fix(SelectInputFieldV2): fix onChange type

---

.changeset/mighty-glasses-shop.md
packages/form/src/components/RadioField/__tests__/__snapshots__/index.test.tsx.snap
packages/form/src/components/RadioGroupField/__tests__/__snapshots__/index.test.tsx.snap
packages/form/src/components/SelectableCardField/__tests__/__snapshots__/index.test.tsx.snap
packages/form/src/components/SelectableCardGroupField/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/Radio/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/Radio/index.tsx
packages/ui/src/components/RadioGroup/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/RadioGroup/index.tsx
packages/ui/src/components/SelectableCard/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/SelectableCardGroup/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/SwitchButton/__tests__/__snapshots__/index.test.tsx.snap

- Bug
1. Fix tooltip placement on radio.
2. Fix label color on disabled radio.
| url  |  ![Screenshot 2024-08-06 at 10 01 21](https://github.com/user-attachments/assets/311b5048-a455-4db1-9bee-6fc08835a8ba) | ![Screenshot 2024-08-06 at 10 02 02](https://github.com/user-attachments/assets/0b184576-cfe2-4778-ba60-0fa1e5bc7966) |
| url  | ![Screenshot 2024-08-06 at 09 59 30](https://github.com/user-attachments/assets/fd8edab6-3845-4f6e-9ca0-e99c0c881a2c) |  ![Screenshot 2024-08-06 at 09 58 49](https://github.com/user-attachments/assets/2de96f5a-01d0-4a07-b3f0-8f9c477dd385) |

fix(RadioGroup): tooltip placement and disabled text color

---

.changeset/shy-clouds-serve.md
packages/plus/src/components/Navigation/NavigationContent.tsx
packages/plus/src/components/Navigation/NavigationProvider.tsx
packages/plus/src/components/Navigation/__stories__/Playground.stories.tsx
packages/plus/src/components/Navigation/__tests__/__snapshots__/index.test.tsx.snap
packages/plus/src/components/Navigation/components/Group.tsx
packages/plus/src/components/Navigation/components/Item.tsx
packages/plus/src/components/Navigation/components/PinnedItems.tsx
packages/plus/src/components/Navigation/constants.ts

- Enhancement
- decrease animation time per two
- add onToggle props to PinnedItems to keep the state.
Before:
https://github.com/user-attachments/assets/f8154c37-95f3-42ab-8e9e-243f43485a98
After:
https://github.com/user-attachments/assets/34a8c262-e049-4bce-a3ad-03b879e00ca0

fix(navigation): animation time is way tooooooooo long

---

.changeset/tasty-peas-rule.md
packages/plus/src/components/Navigation/components/PinnedItems.tsx

- Bug
- Feature
- Enhancement
- Migration
- Refactor
1.
2.
3.

fix(navigation): pinned items toggle forward

---

.changeset/green-buses-return.md
packages/plus/src/components/Navigation/NavigationContent.tsx
packages/plus/src/components/Navigation/NavigationProvider.tsx
packages/plus/src/components/Navigation/__stories__/Playground.stories.tsx
packages/plus/src/components/Navigation/__tests__/__snapshots__/index.test.tsx.snap
packages/plus/src/components/Navigation/components/Item.tsx

DS 954
- Bug
onClick | onToggle was not forward to the MenuItem component

fix(Navigation): issue on click not forward on MenuItem component

---

.github/workflows/ci.yml
.github/workflows/teardown_pull_request.yml

fix(teardown): env was wrongly set for registry during teardown

---

.github/workflows/teardown_pull_request.yml

- CI
We shouldn't check if the branch is being main when doing teardown as it will always be main. The branch is deleted once merged so the github action is executed on main. I remove zone DNS as this will never be executed on main container or it will mean we did a mistake.

ci: fix teardown

---

.github/workflows/teardown_pull_request.yml

ci: fix small mistake

---

.github/workflows/teardown_pull_request.yml

fix: teardown wrong env var

---

.changeset/chilled-elephants-repair.md
packages/form/src/components/SelectableCardField/index.tsx
packages/form/src/components/SelectableCardGroupField/index.tsx
packages/form/src/components/TextInputFieldV2/index.tsx
packages/form/src/components/ToggleField/index.tsx
packages/form/src/components/UnitInputField/index.tsx

- Bug
Fix some onChange type and value.

fix: onChange type and value for some fields

---

packages/icons/src/components/CategoryIcon/__stories__/List.stories.tsx
packages/icons/src/components/Icon/__stories__/Name.stories.tsx
packages/icons/src/components/ProductIcon/__stories__/List.stories.tsx

Improve icon, categoryIcon and productIcon documentation.
| url  | ![Screenshot 2024-09-09 at 17 00 55](https://github.com/user-attachments/assets/abd59faa-1eef-4040-8363-6c666cbefd7f) | ![Screenshot 2024-09-09 at 17 01 01](https://github.com/user-attachments/assets/d4a84139-548e-4de4-9998-37b7cc2fd9f7) |
| url  | ![Screenshot 2024-09-09 at 17 01 08](https://github.com/user-attachments/assets/ea0631de-c815-41bd-b247-e51ab14492c2) | ![Screenshot 2024-09-09 at 17 01 15](https://github.com/user-attachments/assets/188785c4-9576-4e6a-a8ea-7fb169701b62) |
| url  | ![Screenshot 2024-09-09 at 17 01 24](https://github.com/user-attachments/assets/2aa64a7b-792c-45c2-9d84-dc0b9441d126) | ![Screenshot 2024-09-09 at …

docs(Icons): improve storybook documentation

---

.changeset/shiny-crabs-visit.md
packages/plus/src/components/FAQ/__tests__/__snapshots__/index.test.tsx.snap
packages/plus/src/components/FAQ/index.tsx

- Bug
Small issue on FAQ product icon not being found
| url  | <img width="1043" alt="Screenshot 2024-09-10 at 15 22 32" src="https://github.com/user-attachments/assets/e91bbd18-93d4-4df0-abff-f38c2f6c3d8f"> | <img width="1041" alt="Screenshot 2024-09-10 at 15 22 37" src="https://github.com/user-attachments/assets/765cda8b-57eb-4479-a5c8-a2ebfbba9bcb"> |

fix(FAQ): product icon not working properly

---

.changeset/honest-mayflies-lay.md
packages/plus/src/components/ContentCard/__tests__/__snapshots__/index.test.tsx.snap
packages/plus/src/components/ContentCard/__tests__/index.test.tsx
packages/plus/src/components/ContentCard/index.tsx
packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Regular.test.tsx.snap

- Enhancement
new prop `headingTag` to change tag of header

feat(ContentCard): content card custom heading tag

---

.storybook/components/DocsContainer.tsx
.storybook/components/globalStyle.ts

- Bug
We apply global style on storybook and it influence the render of some components such as Card.
| url  | <img width="1080" alt="Screenshot 2024-09-12 at 10 19 28" src="https://github.com/user-attachments/assets/1b20526e-a798-4b5b-8a0b-36626f0ab9fe"> | <img width="1041" alt="Screenshot 2024-09-12 at 10 19 34" src="https://github.com/user-attachments/assets/fa2b4d29-91f3-4fc5-9fac-f8a348ff4048"> |

docs: fix storybook headers

---

.changeset/weak-buckets-appear.md
packages/form/src/components/CheckboxGroupField/__stories__/NotRequired.stories.tsx
packages/form/src/components/CheckboxGroupField/__stories__/index.stories.tsx
packages/form/src/components/CheckboxGroupField/__tests__/__snapshots__/index.test.tsx.snap
packages/form/src/components/CheckboxGroupField/index.tsx

- Bug
- Missing props `required`
- Field is required while no required prop is passed

fix(CheckboxGroupField): missing required prop and make form required while not

---

.changeset/serious-emus-relate.md
packages/form/src/components/SelectableCardField/index.tsx

fix: add illustration to selecatble card field

---

packages/form/src/components/SelectInputFieldV2/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/SelectInputV2/Dropdown.tsx
packages/ui/src/components/SelectInputV2/__stories__/OptionalInfo.stories.tsx
packages/ui/src/components/SelectInputV2/__stories__/resources.tsx
packages/ui/src/components/UnitInput/__tests__/__snapshots__/index.test.tsx.snap

- Bug
Allow to add button into disabled state and make options as div with role option and correct tabIndex instead of a button.

fix(SelectInputV2): to allow button on disabled option

---

.changeset/kind-shrimps-cry.md
packages/ui/src/components/Modal/ModalProvider.tsx
packages/ui/src/components/Modal/__stories__/NestedModal.stories.tsx
packages/ui/src/components/Modal/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/Modal/components/Dialog.tsx

- Bug
Fix `<Modal />` component to always display the one behind and fix flacky animation
Before:
https://github.com/user-attachments/assets/de371373-9a68-47d5-b6fd-46427ad9a826
After:
https://github.com/user-attachments/assets/0adbd8cc-eb3d-4627-bc2a-7fbfd433bc06

fix(Modal): minor changes

---

.changeset/plenty-pigs-train.md
packages/ui/src/components/List/Row.tsx
packages/ui/src/components/List/__stories__/Expandable.stories.tsx
packages/ui/src/components/List/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/List/__tests__/index.test.tsx
packages/ui/src/components/Row/__stories__/Padding.stories.tsx
packages/ui/src/components/Row/__stories__/index.stories.tsx
packages/ui/src/components/Row/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/Row/__tests__/index.test.tsx
packages/ui/src/components/Row/index.tsx

- Feature
- `<Row />`  New prop `padding` to set a custom padding
- `<List.Row />` : New prop `paddingExpandable` to set a custom padding inside the expandable content

feat(Row): change padding on Row and List.Row

---

.github/renovate.json

- CI
Auto merge all updates that are non major, if there is an issue the CI should detect and block the merge. Anything that is minor and non breaking can be merged safely.

ci: automerge non marjor updates

---

.changeset/fifty-ears-clean.md
packages/ui/src/components/Modal/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/Modal/components/Dialog.tsx

- Bug
The modal doesn't scroll with long content due to overflow hidden not being well applied.

fix(Dialog): bug with scroll

---

.github/CODEOWNERS

Adding the codeowner file in github

docs: add code owner file

---

.changeset/kind-eyes-grow.md
packages/ui/src/components/CopyButton/__tests__/index.test.tsx
packages/ui/src/components/CopyButton/index.tsx
packages/ui/src/components/Snippet/index.tsx

- Enhancement
New prop `onCopy` on components `<CopyButton />` and `<Snippet />`

fix: add on copy prop on snippet and copy button

---

.github/CODEOWNERS

fix(codeowner): add groups to form

---

.changeset/dull-buses-boil.md
packages/form/src/components/SliderField/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/Popup/helpers.ts
packages/ui/src/components/Slider/__tests__/__snapshots__/doubleSlider.test.tsx.snap
packages/ui/src/components/Slider/__tests__/__snapshots__/singleSlider.test.tsx.snap
packages/ui/src/components/Slider/components/DoubleSlider.tsx
packages/ui/src/components/Slider/components/SingleSlider.tsx
packages/ui/src/components/Slider/constant.ts
packages/ui/src/components/Slider/styles.ts

- Bug
- Fix `<Slider />` not to have min or max width and take full width when it can
- Fix `<Popup />` to have better arrow positioning
| url  | <img width="1057" alt="Screenshot 2024-10-22 at 11 28 47" src="https://github.com/user-attachments/assets/66e1bcc5-1733-4d16-a50b-88d24838d468"> | <img width="1044" alt="Screenshot 2024-10-22 at 11 28 51" src="https://github.com/user-attachments/assets/4b953894-9d1a-460d-a42e-fbda36d03769"> |

fix: slider and popup to work better

---

.changeset/gorgeous-monkeys-remember.md
packages/ui/src/components/Meter/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/Meter/index.tsx

- Bug
Fix `<Meter />` to remove extra margin bottom

fix(Meter): remove extra margin bottom

---

.changeset/many-bananas-greet.md
packages/plus/src/components/EstimateCost/__tests__/__snapshots__/CustomUnitInput.test.tsx.snap
packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Item.test.tsx.snap
packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Region.test.tsx.snap
packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Regular.test.tsx.snap
packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Stepper.test.tsx.snap
packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Strong.test.tsx.snap
packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Unit.test.tsx.snap
packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Zone.test.tsx.snap
packages/plus/src/components/EstimateCost/__tests__/__snapshots__/index.test.tsx.snap
packages/plus/src/components/EstimateCost/componentStyle.ts
packages/plus/src/components/EstimateCost/constants.ts

- Enhancement
Make EstimateCost more responsive using % instead of fixed px/

fix(EstimateCost): make it more responsive

---

.changeset/lemon-lizards-sell.md
packages/plus/src/components/ContentCard/__stories__/Examples.stories.tsx
packages/plus/src/components/ContentCard/__tests__/__snapshots__/index.test.tsx.snap
packages/plus/src/components/ContentCard/index.tsx

- Enhancement
Fix `<ContentCard />` to add space between body text and button
| url  | <img width="975" alt="Screenshot 2024-11-12 at 16 03 16" src="https://github.com/user-attachments/assets/93cba4f1-c960-4a96-81ee-4c411bc7b5f4"> | <img width="990" alt="Screenshot 2024-11-12 at 16 05 44" src="https://github.com/user-attachments/assets/4aab5d3f-f946-4964-bd89-5b8c48ad1870"> |

fix(ContentCard): space between body and button

---

.changeset/sixty-pens-report.md
packages/form/src/components/TextAreaField/__tests__/__snapshots__/index.test.tsx.snap
packages/form/src/components/TextAreaField/index.tsx
packages/ui/src/components/TextArea/__stories__/AutomaticRows.stories.tsx
packages/ui/src/components/TextArea/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/TextArea/__tests__/index.test.tsx
packages/ui/src/components/TextArea/index.tsx

- Bug
`<TextArea />` and `<TextAreaField />` : new prop `autoExpandMax`
We have 3 cases : 
- `rows = x` : the input will have a **fixed height**, equals to the height of x rows
- `maxRows = x`: the input size will fit the content. When there are x+1 rows, it will stop to grow (**upper bound** in number of rows)
- `maxRows = x` and `rows = y` : the input will have a min-height of y (**lower bound**) and max-height of x (**upper bound**)

fix(TextArea): row auto behavior

---

.changeset/calm-icons-dance.md
packages/form/src/components/SliderField/index.tsx

- Bug
Fix `<SliderField />` to check if value exists avoiding errors

fix(SliderField): check if value exists

---

.changeset/eighty-lizards-search.md
packages/form/src/components/SelectableCardField/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/SelectableCard/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/SelectableCard/index.tsx

- Bug
Remove weak color on children of selectable card.

fix(SelectableCard): content not to have weak color

---

.changeset/hip-dancers-end.md
packages/ui/src/components/List/ListContext.tsx
packages/ui/src/components/List/Row.tsx
packages/ui/src/components/List/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/List/__tests__/index.test.tsx
packages/ui/src/components/Table/Row.tsx
packages/ui/src/components/Table/TableContext.tsx
packages/ui/src/components/Table/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/Table/__tests__/index.test.tsx

- Enhancement
`<List />` and `<Table />` : hold shift to multiselect when they are selectable

feat: shift click for multiselect

---

packages/plus/src/components/Navigation/Footer.tsx
packages/plus/src/components/Navigation/Header.tsx
packages/plus/src/components/Navigation/NavigationContent.tsx
packages/plus/src/components/Navigation/__tests__/__snapshots__/index.test.tsx.snap
packages/plus/src/components/Navigation/components/Item.tsx

- Enhancement
I segmented navigation into multiple files to increase readability and added some aria label where it needs to improve testing.

fix(Navigation): segment components in sub components

---

packages/ui/src/__stories__/Tools/ThemeGenerator/ThemeResult/Demo.tsx
packages/ui/src/components/List/__stories__/Example.stories.tsx
packages/ui/src/components/MenuV2/__stories__/WithModal.stories.tsx
packages/ui/src/components/Meter/__stories__/Playground.stories.tsx
packages/ui/src/components/Notification/__stories__/Children.tsx
packages/ui/src/components/PasswordStrengthMeter/__stories__/Estimate.stories.tsx
packages/ui/src/components/PasswordStrengthMeter/__stories__/ForbiddenInputs.stories.tsx
packages/ui/src/components/PasswordStrengthMeter/__stories__/Playground.stories.tsx
packages/ui/src/components/Popover/__stories__/AdvancedUsage.stories.tsx
packages/ui/src/components/Popover/__tests__/index.test.tsx
packages/ui/src/components/SelectableCard/__stories__/Children.stories.tsx

Remove deprecated usages inside our storybook documentation to prepare for the V2.

docs: remove deprecated usages from documentation

---

.changeset/quick-cheetahs-kick.md
.changeset/swift-jobs-shout.md

ci: fix changeset

---

packages/fonts/package.json

ci: fix font package version

---

.changeset/purple-mice-design.md
packages/form/src/components/DateField/__stories__/index.stories.tsx
packages/form/src/components/DateField/index.tsx

- Bug
Fix date field not showing any values
Before:
https://github.com/user-attachments/assets/548a6720-805d-432e-b692-9b51f837d325
After:
https://github.com/user-attachments/assets/e4ce2f20-7e60-40d4-9793-794ed574e867

fix(DateField): not showing any value in range mode

---

Dockerfile
turbo.json

Fix infinite building issue in deploy step

ci: fix deploy

---

.changeset/gentle-cars-clean.md
packages/ui/src/components/List/Row.tsx
packages/ui/src/components/List/__tests__/__snapshots__/index.test.tsx.snap

- Bug
Disabled state doesn't work on a row of a list.
| url  | <img width="966" alt="Screenshot 2024-12-20 at 15 50 36" src="https://github.com/user-attachments/assets/9bd2a5dc-acf2-46bd-b810-749211e75743" /> | <img width="969" alt="Screenshot 2024-12-20 at 15 50 42" src="https://github.com/user-attachments/assets/31eeb2f0-de78-4a5b-9246-9cb40e7111ef" /> |

fix(List): disabld state not properly working

---

.changeset/serious-planets-prove.md
packages/ui/src/components/Table/TableContext.tsx

fix(Table): provider react 19 issue

---

.changeset/giant-jobs-remember.md
packages/ui/src/components/Breadcrumbs/__stories__/AdvancedUsage.stories.tsx
packages/ui/src/components/MenuV2/MenuContent.tsx
packages/ui/src/components/MenuV2/__stories__/Group.stories.tsx
packages/ui/src/components/MenuV2/__stories__/Searchable.stories.tsx
packages/ui/src/components/MenuV2/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/MenuV2/__tests__/index.test.tsx
packages/ui/src/components/MenuV2/components/Group.tsx
packages/ui/src/components/MenuV2/helpers.ts
packages/ui/src/components/Tabs/__tests__/__snapshots__/index.test.tsx.snap

- Enhancement
In MenuV2 we introduced search capabilities but I completely forgot about the fact that each items can be in a Group.
This version improve the search engine and add `labelDescription` from the `MenuV2.Group` component. 
https://github.com/user-attachments/assets/96ddc20f-5336-498b-8a7d-bcb543951459

fix(MenuV2): better search with groups and label description

---

.changeset/renovate-4e60c7b.md

There is a changeset that should not be there.

fix: remove useless changeset

---

.changeset/soft-flowers-deliver.md
packages/icons/src/components/Icon/Icon.tsx
packages/icons/src/components/Icon/__stories__/Size.stories.tsx

- Feature
New size `xsmall` (0.75rem) for icons

feat(Icon): new size xsmall

---

.changeset/cyan-bulldogs-matter.md
.github/workflows/theme-upload.yml
packages/themes/README.md

- Enhancement
Add themes into s3 so anyone can import the themes as follow:
```html
<link rel="stylesheet" href="assets.scaleway.com/themes/light.css"> 
// OR
<link rel="stylesheet" href="assets.scaleway.com/themes/dark.css"> 
// OR 
<link rel="stylesheet" href="assets.scaleway.com/themes/darker.css"> 
```

ci(themes): add theme in s3 and make it available via edge services

---

.changeset/quiet-pants-serve.md
packages/plus/src/components/SteppedListCard/SteppedListContainer.tsx
packages/plus/src/components/SteppedListCard/__stories__/WithoutToggleButton.stories.tsx
packages/plus/src/components/SteppedListCard/__stories__/index.stories.tsx
packages/plus/src/components/SteppedListCard/__tests__/__snapshots__/index.test.tsx.snap
packages/plus/src/components/SteppedListCard/__tests__/index.test.tsx

- Enhancement
add new prop showToggleOption to SteppedListContainer

feat: add new prop showToggleOption to SteppedListContainer

---

Dockerfile

- Bug
Deploy is not working, related issue:
https://github.com/pnpm/pnpm/issues/9029#issuecomment-2629817478

ci: fix corepack issue

---

.changeset/smooth-lamps-notice.md
packages/ui/src/components/SearchInput/index.tsx

- Bug
Fix condition with explicit undefined for value update

fix(searchinput): fix condition with explicit undefined for value update

---

.changeset/fifty-cycles-smell.md
packages/ui/src/components/Table/Cell.tsx

- Bug
Wrong type on Table.Cell does not include all the sentiments.

fix(Table): cell to have all available sentiment as type

---

.changeset/chilled-lobsters-poke.md
packages/form/src/components/TextAreaField/__tests__/__snapshots__/index.test.tsx.snap
packages/form/src/components/TextInputFieldV2/__tests__/__snapshots__/index.test.tsx.snap
packages/form/src/components/UnitInputField/__tests__/__snapshots__/index.test.tsx.snap
packages/form/src/components/VerificationCodeField/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/DateInput/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/Label/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/Label/index.tsx
packages/ui/src/components/ProgressBar/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/TextArea/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/TimeInputV2/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/UnitInput/__tests__/__snapshots__/index.test.tsx.snap

- Bug
"\*" was part of the label and should not

fix(Labe): required

---

.changeset/real-worms-punch.md
packages/form/src/components/UnitInputField/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/UnitInput/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/UnitInput/index.tsx

- Bug
Fix unit input styling (width of the unit part, font sizes and add a background-color instead of transparent)

fix(UnitInput): styling

---

package.json
pnpm-lock.yaml

Fix code editor documentation
There is an issue with a jsdom dependency nwsapi: https://github.com/dperini/nwsapi/issues/139
There was a regression in the API.

docs: fix code editor in storybook

---

.changeset/big-trees-sip.md
packages/icons/src/components/Icon/Icon.tsx
packages/plus/src/components/ContentCard/__tests__/__snapshots__/index.test.tsx.snap
packages/plus/src/components/ContentCardGroup/__tests__/__snapshots__/index.test.tsx.snap
packages/plus/src/components/Navigation/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/Avatar/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/ExpandableCard/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/List/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/SearchInput/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/SelectInput/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/Snippet/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/Table/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/Tabs/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/TextArea/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/TimeInputV2/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/UnitInput/__tests__/__snapshots__/index.test.tsx.snap

- Refactor
Current default size in Icon is deprecated I changed it to use our tokens instead.

refactor(Icon): remove fixed size by using normal one

---

.changeset/four-spoons-laugh.md
packages/ui/src/components/Banner/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/Banner/index.tsx

- Bug
Wrong image size on a banner in small size
| url  | <img width="946" alt="Screenshot 2025-03-04 at 15 46 24" src="https://github.com/user-attachments/assets/ac2f61ec-9cb7-422a-99dd-61932e7e75e3" /> | <img width="946" alt="Screenshot 2025-03-04 at 15 46 36" src="https://github.com/user-attachments/assets/a50de0d2-ba95-46cd-8be5-c1839eba6001" /> |

fix(Banner): component not to have correct image size

---

.changeset/bright-pens-take.md
packages/ui/src/components/Radio/index.tsx

- Bug
Fix radio to have correct id on label

fix(Radio): to have correct id when the label is complexe

---

.changeset/social-buses-post.md
packages/form/src/components/SelectableCardOptionGroupField/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/SelectableCard/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/SelectableCard/index.tsx
packages/ui/src/components/SelectableCardOptionGroup/__tests__/__snapshots__/index.test.tsx.snap

- Bug
Fix the selectable card to make the layout work under any conditions

fix(SelectableCard): wrong layout

---

.changeset/soft-taxis-wink.md
packages/form/src/components/SelectInputFieldV2/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/SelectInputV2/Dropdown.tsx
packages/ui/src/components/SelectInputV2/__stories__/resources.tsx
packages/ui/src/components/UnitInput/__tests__/__snapshots__/index.test.tsx.snap

- Bug
Fix `SelectInputV2` not to force scroll in the dropdown
| url  | ![Screenshot 2025-03-12 at 18 21 11](https://github.com/user-attachments/assets/3cb2e01e-739a-43e1-9da9-0d913af77122) | ![Screenshot 2025-03-12 at 18 21 16](https://github.com/user-attachments/assets/6295a54e-fb76-42eb-86d0-b28aae6e728c) |

fix(SelectInputV2): change dropdown scroll to auto

---

.changeset/thick-insects-mate.md
packages/ui/src/components/Popover/index.tsx

- Bug
renove arrow down on the popover for tag list as we don't want it.

fix(TagList): better popover

---

packages/ui/src/components/TextInputV2/__stories__/Password.stories.tsx

Add example for the password variant of `TextInputV2 />` on storybook

feat(TextInputV2): add examples password

---

.changeset/stupid-cooks-study.md
packages/plus/src/components/Navigation/__tests__/__snapshots__/index.test.tsx.snap
packages/plus/src/components/Navigation/components/Item.tsx

- Bug
Navigation bug on alignement for pin / unpin following those changes: https://github.com/scaleway/ultraviolet/pull/4935
| url  | <img width="288" alt="Screenshot 2025-04-01 at 15 44 57" src="https://github.com/user-attachments/assets/75777f4a-833d-4b59-91bd-f5585903e92f" /> | <img width="270" alt="Screenshot 2025-04-01 at 15 45 09" src="https://github.com/user-attachments/assets/059d096e-5371-4e8f-b80b-ef312db2f738" /> |

fix(Navigation): wrong alignemenet on pin unpin buttons

---

.github/workflows/ci.yml

ci: increase e2e timeout

---

package.json
pnpm-lock.yaml

- Dependencies
The issue has been fixed we can rollback to normal: https://github.com/dperini/nwsapi/issues/139

chore: remove nswapi overriding

---

examples/next-app-router/package.json
packages/ui/package.json
pnpm-lock.yaml

ci: fix manypackages on main

---

.changeset/sharp-glasses-learn.md
packages/form/src/components/DateField/__stories__/Clearable.stories.tsx
packages/form/src/components/DateField/__stories__/index.stories.tsx
packages/form/src/components/DateField/__tests__/__snapshots__/index.test.tsx.snap
packages/form/src/components/DateField/__tests__/index.test.tsx
packages/form/src/components/DateField/index.tsx
packages/ui/src/components/DateInput/__stories__/Clearable.stories.tsx
packages/ui/src/components/DateInput/__stories__/index.stories.tsx
packages/ui/src/components/DateInput/index.tsx
utils/test/src/vitest/helpers/index.tsx

- Enhancement
-
Add clearable option to DateInputField and DateInput.
And forward tooltip from DateInput to DateIputField which was missing
Being able to clear a DateInput and accepting null or undefined value
| url  | screenshot | <img width="897" alt="Screenshot 2025-04-12 at 18 32 43" src="https://github.com/user-attachments/assets/34567530-11e1-443e-a1fd-ba4ecf5f9280" /> |

fix(date): datefield accept null and get clearable option

---

.changeset/lucky-jars-dress.md
packages/ui/src/components/Stack/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/Stack/__tests__/index.test.tsx
packages/ui/src/components/Stack/index.tsx

- Enhancement
new props `maxWidth` and `minWidth`

feat(Stack): new prop min and max width

---

.changeset/modern-chicken-train.md
packages/plus/src/components/FAQ/__tests__/__snapshots__/index.test.tsx.snap
packages/plus/src/components/SteppedListCard/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/Bullet/__stories__/Sizes.stories.tsx
packages/ui/src/components/Bullet/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/Bullet/__tests__/index.test.tsx
packages/ui/src/components/Bullet/index.tsx
packages/ui/src/components/StepList/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/Stepper/__tests__/__snapshots__/index.test.tsx.snap

- Feature
Add new sizes `xmsall` and `xxsmall` on `<Bullet />`
| url  | ![Screenshot 2025-04-18 at 11 35 27](https://github.com/user-attachments/assets/60fe82fa-58a8-40e5-8022-ad3629df10cb) | ![Screenshot 2025-04-18 at 11 37 33](https://github.com/user-attachments/assets/ac6498eb-45f6-4988-9478-261a602361c3) |

feat(Bullet): add new sizes xsmall and xxsmall

---

.changeset/true-mirrors-carry.md
packages/form/src/components/SelectInputFieldV2/__tests__/__snapshots__/index.test.tsx.snap
packages/form/src/components/SelectInputFieldV2/index.tsx

- Bug
Missing label and aria-label on select input field v2

fix(SelectInputFieldV2): re-add the label

---

.github/workflows/sync-main-to-beta.yml

ci: change github action

---

.changeset/sixty-beds-repair.md

Add changeset into beta branch

chore: changeset major release for beta

---

.changeset/modern-poems-lose.md
packages/form/README.md
packages/form/package.json
packages/plus/README.md
packages/plus/package.json
pnpm-lock.yaml

- Enhancement
In order to facilitate following versioning we made form and plus having ui as peer deps.

fix: plus and form to have ui ad peer deps

---

CONTRIBUTING.md
README.md

Fix readme and contributing guidelines

docs: update contributing documentation to include beta and releases

---

.changeset/silent-days-drum.md
packages/ui/src/components/PieChart/types.tsx

- Bug
Add `details` attribute to the `data` prop.

fix(PieChart): data prop type

---

.changeset/crazy-colts-accept.md
packages/ui/src/components/Notification/index.tsx

- Bug
Fix bug of notification not shown properly on some screen.

fix(Notification): improve display notification

---

vite.config.ts

- Bug
List is sometimes timing out bc it's a big test

ci: fix timeout vitests

---

packages/ui/src/components/SelectableCard/__stories__/Children.stories.tsx
packages/ui/src/components/SelectableCard/__stories__/Examples.stories.tsx
packages/ui/src/components/SelectableCard/__stories__/Illustration.stories.tsx
packages/ui/src/components/SelectableCard/__stories__/Template.stories.tsx
packages/ui/src/components/SelectableCardGroup/__stories__/Examples.stories.tsx

`SelectableCard` & `SelectableCardGroup`: update examples (text prominence) to match design

docs(SelectableCard): text weak

---

.changeset/nine-eyes-rescue.md
packages/ui/src/components/Banner/__stories__/Variants.stories.tsx
packages/ui/src/components/Banner/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/Banner/index.tsx
packages/ui/src/components/Breadcrumbs/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/EmptyState/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/GlobalAlert/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/Link/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/Link/index.tsx
packages/ui/src/components/PieChart/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/Tabs/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/Toaster/__tests__/__snapshots__/index.test.tsx.snap

- Bug
Visited state on `Link` was always the same color - which was problematic for the banner. Now, the color depends on the prominence.

fix(Link): visited state prominence

---

.changeset/spicy-aliens-relax.md
packages/themes/package.json
pnpm-lock.yaml

- Enhancement
Remove deepmerge dependency on theme as it is no longer used.

chore(remove): deep merge theme

---

.changeset/tiny-feet-throw.md
packages/ui/src/components/Banner/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/Breadcrumbs/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/EmptyState/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/GlobalAlert/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/Link/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/Link/index.tsx
packages/ui/src/components/Tabs/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/Toaster/__tests__/__snapshots__/index.test.tsx.snap

- Bug
`Link`: reduce space between link and icon

fix(Link): reduce space between link and icon

---

.changeset/fast-dingos-rest.md
.changeset/rotten-walls-argue.md
packages/form/src/components/DateField/__stories__/MinMaxDate.stories.tsx
packages/form/src/components/DateField/index.tsx
packages/form/src/components/NumberInputFieldV2/index.tsx
packages/form/src/components/SelectableCardField/index.tsx
packages/form/src/components/SelectableCardGroupField/__tests__/index.test.tsx
packages/form/src/components/SelectableCardGroupField/index.tsx
packages/form/src/components/TagInputField/index.tsx
packages/form/src/components/TextAreaField/index.tsx
packages/form/src/components/TextInputFieldV2/index.tsx
packages/form/src/components/TimeInputFieldV2/__tests__/__snapshots__/index.test.tsx.snap
packages/form/src/components/TimeInputFieldV2/index.tsx
packages/form/src/components/ToggleField/index.tsx
packages/form/src/components/ToggleGroupField/index.tsx
packages/form/src/components/UnitInputField/index.tsx
packages/form/src/components/VerificationCodeField/index.tsx
packages/ui/src/components/DateInput/index.tsx
packages/ui/src/components/TimeInputV2/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/TimeInputV2/index.tsx

- Refactor
- Spread props in form components
- Fix default size for `TimeInputV2`

refactor(Form): spread props

---

packages/form/src/components/DateField/index.tsx
packages/form/src/components/NumberInputFieldV2/index.tsx
packages/form/src/components/SelectableCardField/index.tsx
packages/form/src/components/SelectableCardGroupField/index.tsx
packages/form/src/components/TagInputField/index.tsx

fix: form values

---

.changeset/long-mangos-remain.md
packages/ui/src/components/Stepper/Step.tsx
packages/ui/src/components/Stepper/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/Stepper/index.tsx

- Bug
wrong alignement on small and label right
| url  | <img width="1038" alt="Screenshot 2025-06-12 at 17 53 47" src="https://github.com/user-attachments/assets/01954978-23b9-44bf-94b8-7c6339a150b5" /> | <img width="1034" alt="Screenshot 2025-06-12 at 17 53 52" src="https://github.com/user-attachments/assets/5a014801-1dbb-40ba-a9a8-cb277be8f2e5" /> |

fix(stepper): wrong alignement on small and label right

---

.changeset/wild-facts-hide.md
packages/form/src/components/SwitchButtonField/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/SwitchButton/Option.tsx
packages/ui/src/components/SwitchButton/__stories__/Disabled.stories.tsx
packages/ui/src/components/SwitchButton/__stories__/index.stories.tsx
packages/ui/src/components/SwitchButton/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/SwitchButton/__tests__/index.test.tsx
packages/ui/src/components/SwitchButton/index.tsx

- Enhancement
Add disabled state on SwitchButton

fix(SwitchButton): story and imports and disabled state

---

.changeset/brave-suns-speak.md
packages/plus/src/components/OrderSummary/NonScrollableContent.tsx
packages/plus/src/components/OrderSummary/__tests__/__snapshots__/index.test.tsx.snap
packages/plus/src/components/OrderSummary/__tests__/index.test.tsx
packages/plus/src/components/OrderSummary/index.tsx
packages/plus/src/components/OrderSummary/types.ts
packages/ui/src/components/SwitchButton/__tests__/__snapshots__/index.test.tsx.snap

- Enhancement
`OrderSummary`: new prop `additionalInfo`

feat(OrderSummary): new prop additional info

---

packages/form/src/components/SelectInputField/__tests__/index.test.tsx
packages/ui/src/components/NumberInput/__tests__/index.test.tsx
packages/ui/src/components/SelectInput/__tests__/index.test.tsx

- Bug
- Refactor
There was a lint issue with some tests

fix: tests lint

---

.changeset/ninety-coats-accept.md
packages/plus/src/components/InfoTable/__stories__/ComplexExample.stories.tsx
packages/plus/src/components/InfoTable/__tests__/__snapshots__/index.test.tsx.snap
packages/plus/src/components/InfoTable/components/Cell.tsx

- Enhancement
`InfoTable.Cell`: prop "title" is now a ReactNode

fix(InfoTable): title type

---

.changeset/rude-jokes-cheer.md
packages/ui/src/__stories__/Tools/ThemeGenerator/ThemeResult/CodeIntegration.tsx
packages/ui/src/__stories__/Tools/ThemeGenerator/ThemeResult/index.tsx
packages/ui/src/components/Dialog/__stories__/index.stories.tsx
packages/ui/src/components/Menu/types.ts
packages/ui/src/components/Toaster/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/Toaster/index.tsx
packages/ui/src/index.ts
packages/ui/src/theme/index.ts

- Refactor
Final touches before the release of V2

fix(beta): final step

---

.changeset/soft-pears-hammer.md
packages/plus/src/components/Navigation/__stories__/Playground.stories.tsx
packages/plus/src/components/Navigation/__tests__/__snapshots__/index.test.tsx.snap
packages/plus/src/components/Navigation/components/Item.tsx

- Enhancement
Add props `labelDescription` on `<Navigation.Item />` to allow more custom elements on items

feat(Navigation): add prop label description on item

---

.changeset/green-cobras-smash.md
packages/plus/src/components/OfferList/__tests__/__snapshots__/index.test.tsx.snap
packages/plus/src/components/OfferList/components/Banner.tsx
packages/plus/src/components/OfferList/components/Row.tsx
packages/ui/src/components/List/Row.tsx

- Bug
- `OfferList`: fix spacing between rows
- `List`: new props "onMouseLeave" and "onMouseEnter"

fix(OfferList): spacing between rows

---

.changeset/loud-eggs-smell.md
packages/ui/src/components/Table/HeaderCell.tsx
packages/ui/src/components/Table/HeaderRow.tsx
packages/ui/src/components/Table/__stories__/SelectableColumn.stories.tsx
packages/ui/src/components/Table/__tests__/__snapshots__/index.test.tsx.snap

- Bug
`Table`: fix padding on first column header

fix(Table): padding on first column header

---

.changeset/pre.json

chore: fix changeset

---

.changeset/plain-games-invite.md
packages/form/package.json
pnpm-lock.yaml
vite.config.ts

- Chore
Remove unused react-select package.

chore: remove unused react-select

---

packages/ui/src/components/SelectInput/__tests__/__snapshots__/index.test.tsx.snap

fix: select input ci

---

.changeset/deep-peas-live.md
packages/form/src/components/CheckboxField/__tests__/__snapshots__/index.test.tsx.snap
packages/form/src/components/CheckboxGroupField/__tests__/__snapshots__/index.test.tsx.snap
packages/form/src/components/DateInputField/__tests__/__snapshots__/index.test.tsx.snap
packages/form/src/components/Form/__tests__/__snapshots__/index.test.tsx.snap
packages/form/src/components/Form/index.tsx
packages/form/src/components/KeyValueField/__tests__/__snapshots__/index.test.tsx.snap
packages/form/src/components/NumberInputField/__tests__/__snapshots__/index.test.tsx.snap
packages/form/src/components/RadioField/__tests__/__snapshots__/index.test.tsx.snap
packages/form/src/components/RadioGroupField/__tests__/__snapshots__/index.test.tsx.snap
packages/form/src/components/SelectInputField/__tests__/__snapshots__/index.test.tsx.snap
packages/form/src/components/SelectableCardField/__tests__/__snapshots__/index.test.tsx.snap
packages/form/src/components/SelectableCardGroupField/__tests__/__snapshots__/index.test.tsx.snap
packages/form/src/components/SelectableCardOptionGroupField/__tests__/__snapshots__/index.test.tsx.snap
packages/form/src/components/SliderField/__tests__/__snapshots__/index.test.tsx.snap
packages/form/src/components/Submit/__tests__/__snapshots__/index.test.tsx.snap
packages/form/src/components/SubmitErrorAlert/__tests__/__snapshots__/index.test.tsx.snap
packages/form/src/components/SwitchButtonField/__tests__/__snapshots__/index.test.tsx.snap
packages/form/src/components/TagInputField/__tests__/__snapshots__/index.test.tsx.snap
packages/form/src/components/TextAreaField/__tests__/__snapshots__/index.test.tsx.snap
packages/form/src/components/TextInputField/__tests__/__snapshots__/index.test.tsx.snap
packages/form/src/components/TimeInputField/__tests__/__snapshots__/index.test.tsx.snap
packages/form/src/components/ToggleField/__tests__/__snapshots__/index.test.tsx.snap
packages/form/src/components/ToggleGroupField/__tests__/__snapshots__/index.test.tsx.snap
packages/form/src/components/UnitInputField/__tests__/__snapshots__/index.test.tsx.snap
packages/form/src/components/VerificationCodeField/__tests__/__snapshots__/index.test.tsx.snap
packages/form/src/providers/ErrorContext/__tests__/__snapshots__/index.test.tsx.snap

- Refactor
Remove usage of emotion within @ultraviolet/form

fix(form): remove all emotion usages

---

packages/ui/src/components/Button/styles.css.ts

- Bug
Button wrong sizes on medium and lower

fix(button): wrong sizes

---

.changeset/strong-cats-float.md
.storybook/preview.tsx
packages/ui/src/components/Banner/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/Banner/index.tsx
packages/ui/src/components/Banner/styles.css.ts

- Bug
- Refactor
- Refactor component `Banner` to use vanilla-extract instead of Emotion
- Fix dark/darker theme on stories with vanilla extract

refactor: vanilla extract banner and theme on stories

---

.changeset/rotten-coins-glow.md
packages/ui/src/components/Avatar/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/Avatar/index.tsx
packages/ui/src/components/Avatar/styles.css.ts
packages/ui/src/components/Avatar/variables.css.ts

- Refactor
Refactor component `Avatar` to use vanilla-extract instead of Emotion

feat(Avatar): use vanilla extract

---

.changeset/famous-stars-marry.md
packages/ui/src/components/Drawer/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/Drawer/index.tsx

- Bug
`Drawer`: fix animation on small

fix: drawer animation

---

.changeset/yummy-pets-draw.md
packages/ui/src/components/Breadcrumbs/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/Breadcrumbs/components/Item.tsx
packages/ui/src/components/Breadcrumbs/components/styles.css.ts
packages/ui/src/components/Breadcrumbs/index.tsx
packages/ui/src/components/Breadcrumbs/styles.css.ts
packages/ui/src/components/Button/index.tsx
packages/ui/vitest.setup.ts

- Refactor
- Refactor component `Breadcrumbs` to use vanilla-extract instead of emotion
- `Button`: Add prop "style"
- Re-enable style in testing (needed for breadcrumbs) for UI

refactor: breadcrumbs vanilla extract and prop style to button

---

.changeset/fine-buttons-call.md
packages/ui/src/components/ExpandableCard/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/ExpandableCard/index.tsx
packages/ui/src/components/ExpandableCard/styles.css.ts

- Refactor
Refactor expandable card to drop emotion and use vanille extract

refactor(ExpandableCard): to use vanilla extract and drop emotion

---

.changeset/wild-turkeys-mate.md
packages/form/src/components/SelectableCardField/__tests__/__snapshots__/index.test.tsx.snap
packages/form/src/components/SelectableCardGroupField/__tests__/__snapshots__/index.test.tsx.snap
packages/form/src/components/SelectableCardOptionGroupField/__tests__/__snapshots__/index.test.tsx.snap
packages/form/src/components/SwitchButtonField/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/SelectableCard/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/SelectableCard/index.tsx
packages/ui/src/components/SelectableCard/styles.css.ts
packages/ui/src/components/SelectableCard/variables.css.ts
packages/ui/src/components/SelectableCardGroup/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/SelectableCardOptionGroup/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/SwitchButton/Option.tsx
packages/ui/src/components/SwitchButton/__tests__/__snapshots__/index.test.tsx.snap

- Refactor
Refactor component `SelectableCard` to use vanilla extract instead of emotion

refactor(SelectableCard): migration vanilla extract

---

.github/CODEOWNERS

ci: update codeowner to avoid spam

---

.changeset/lazy-lights-invent.md
packages/form/src/components/TagInputField/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/TagInput/__stories__/Size.stories.tsx
packages/ui/src/components/TagInput/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/TagInput/index.tsx
packages/ui/src/components/TagInput/styles.css.ts
packages/ui/src/components/TagList/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/TagList/__tests__/index.test.tsx
packages/ui/src/components/TagList/constant.ts
packages/ui/src/components/TagList/index.tsx
packages/ui/src/components/TagList/styles.css.ts

- Refactor
- Refactor components `TagInput` and `TagList` to use vanilla-extract instead of emotion
- `TagList` : popover should be openable using keyboard keys (space or enter)

refactor: tagInput and tagList vanilla extract

---

.changeset/whole-actors-prove.md
packages/form/src/components/DateInputField/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/DateInput/__tests__/__snapshots__/index.test.tsx.snap
packages/ui/src/components/DateInput/components/CalendarContent.tsx
packages/ui/src/components/DateInput/components/CalendarDaily.tsx
packages/ui/src/components/DateInput/components/CalendarMonthly.tsx
packages/ui/src/components/DateInput/components/Popup.tsx
packages/ui/src/components/DateInput/components/styles.css.ts
packages/ui/src/components/DateInput/helpers.ts
packages/ui/src/components/DateInput/index.tsx
packages/ui/src/components/DateInput/styles.css.ts

- Refactor
Refactor component `DateInput` to use vanilla-extract instead of Emotion

refactor(DateInput): vanilla extract
