src/components/DateInput/__tests__/__snapshots__/index.test.js.snap, src/components/DateInput/index.js
- Bug
Little discrepancy between here and console
/?path=/docs/components-dateinput--controlled | <img width="325" alt="Screenshot 2021-04-12 at 14 43 42" src="https://user-images.githubusercontent.com/2802867/114396170-8779a880-9b9d-11eb-992e-301bf937a03d.png"> | <img width="353" alt="Screenshot 2021-04-12 at 14 43 15" src="https://user-images.githubusercontent.com/2802867/114396162-86487b80-9b9d-11eb-9c9e-65dd349d71ec.png">
=> fix(DateInput): correct colors

.github/workflows/ci.yml, .github/workflows/deploy.yml, .github/workflows/pull_request_title.yml, .github/workflows/teardown_pull_request.yml
- CI
As the repository is now public we can use Github Action public runners
=> ci: use github actions runners

src/components/Tooltip/index.js, src/components/TooltipIcon/__tests__/__snapshots__/index.js.snap
- Bug
We should spread props on ReakitTooltip not in his children. This can allow us to define a zIndex and so to be able to show a tooltip inside of a modal.
=> fix(tooltip): fixed prop spreading

src/components/RadioBorderedBox/__tests__/__snapshots__/index.js.snap, src/components/RadioBorderedBox/index.js
- Design
To use `#151A2D` for label color.
1. Added typography and color gray950
Before:
After:
=> fix: fixed radio bordered box label color

.github/workflows/deploy.yml
- CI
Apparently the GITHUB_TOKEN way of authenticating to GCR is not yet stable 
So back to using a PAT for now
https://github.community/t/403-error-on-container-registry-push-from-github-action/173071/10
Still won't work for dependabot PR but it's a start to have easier reviews
=> ci: correct deployment

src/components/Action/index.js
- Bug
When you use Action component as disclosure on modal, you will have an error on ref. Tooltip cannot forward ref if's not render.
1. Add ForwardRef to button
=> fix(action): add forwardRef to button

src/components/RichSelect/index.js
- Bug
RichSelect Option : no warning on render because it's an object
1. Fix RichSelect.Option component
=> fix: richselect option

src/components/Button/__stories__/index.stories.mdx, src/components/Button/__tests__/__snapshots__/index.js.snap, src/components/Button/__tests__/index.js, src/components/Button/index.js, src/components/Modal/__stories__/index.stories.mdx
…rrectly
- Bug
Disabled button with as=Link,a doesn't work
Checking if component is disabled before forward as property
In this case, Button is disabled.
=> fix(button): button with as link doesn t forward disabled property

src/components/Slider/index.js
- Bug
We currently have some exception thrown in the console because the setDragImage need an `img` element as first argument
To reproduce try to scroll via dragging the slider in the master deployment and there should be an error, there should be none in this branch
=> fix(Slider): correct drag image object

src/components/Menu/Item.js, src/components/Menu/__tests__/__snapshots__/index.js.snap
- Bug
The font weight was herited from Button component with a font-weight: 500
Before:
After:
=> fix(menu): item font-weight

src/components/Expandable/__stories__/index.stories.mdx, src/components/Expandable/index.js, src/components/ExtendedReminder/__stories__/index.stories.mdx, src/components/ExtendedReminder/index.js, src/components/Grid/Col.js, src/components/Grid/Grid.js, src/components/Grid/Row.js, src/components/Grid/__stories__/index.stories.mdx
Documentation on E and G components
1. Add documentation on proptypes
2. Update stories
=> docs: add e and g documentation

src/components/List/index.js
- Enhancement
Access pagination object from list render props
1. Add paginationRef.current in children function args
=> feat: access pagination from list render props

src/components/Alert/__stories__/index.stories.mdx, src/components/Menu/Item.js, src/components/Menu/__stories__/index.stories.mdx, src/components/Menu/__tests__/__snapshots__/index.js.snap, src/components/Menu/index.js
- Feature
Allow Menu to forward toggle props as children, it's useful in case you would like to close menu on click 
```js
{({ toggle }) => (
<>
<Menu.Item>default</Menu.Item>
<Menu.Item onClick={toggle} variant="danger">
Danger
</Menu.Item>
```
Fix:
Hover on Danger variant  use wrong color from our palette
=> fix(menu): allow toggle props

README.md, src/components/TabGroup/Tab.js, src/components/TabGroup/__tests__/TabGroup.test.js, src/components/TabGroup/__tests__/__snapshots__/Tab.test.js.snap, src/components/TabGroup/__tests__/__snapshots__/TabGroup.test.js.snap, src/components/TabGroup/index.js
Allow tabs keyboard navigation with `←` / `→` arrows. 
**Linked PR**
Same fix applied to [scaleway-lib README](https://github.com/scaleway/scaleway-lib/pull/306).
Enhancement
`Tab` key no longer allow navigation between tabs, only the selected tab can be navigated to with `Tab` key navigation.
Then to switch tabs, user can navigate with keyboard  using `←` / `→` arrows to rotate through tabs. 
The current focused tab (when using keyboard navigation) is outlined.
https://console.scaleway.com/organization | ![image](https://user-images.githubusercontent.com/62407/128012819-3d9be55f-5da8-4fbc-b3d0-25f5cabab36c.png) | ![image](https://user-images.githubusercontent.com/62407/128012968-c0429d7f-e325-4f3b-a32e-7da377956b2a.png)
=> feat(a11y): add tabs arrow navigation

src/components/Container/index.tsx
- Bug
This props should not be forward to the DOM as value
=> fix(container): some props was forward to the DOM

src/components/Tooltip/index.tsx
- Bug
Uses unstable_portal from Reakit Tooltip to avoid portal into modal and have tooltips working inside modals too.
1. Pass unstable_portal props to Reakit Tooltip
2. Defaulting to true so it doesn't change current behaviour
=> fix(tooltip): using unstable portal and set it to false

src/components/Tooltip/index.tsx
- Refactor
Removes zindex from tooltip component as it is not used anymore.
=> fix: removes zindex from tooltip component

package.json, rollup.config.mjs
Turns out webpack does not tree shake bundled esm modules (https://github.com/webpack/webpack/issues/9337#issuecomment-524966201)
- Enhancement
Before | After
:-:   | -:
=> feat: correct es module tree shaking by preserving modules on output

README.md, emotion.d.ts, src/index.ts, src/theme/index.ts, tsconfig.json
- Enhancement
Allows projects to define custom Theme typings
1. removed extended emotion Theme typings from exported typings
2. forces to localy extends emotion Theme
3. exports SCWUITheme for convenience
=> fix: avoid to declare emotion Theme typings

src/theme/colors.ts, src/theme/index.ts
Allow theme constants inspection in typescript
- Enhancement
Export theme values in typescript types
1. added [const assertion](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-4.html) in theme definition
=> fix(theme): allow theme constants inspection in typescript

src/components/TextBox/index.tsx
- Bug
possibility to have prop className with TextBox
=> fix: adds correct types to textbox

src/components/RadioBorderedBox/index.tsx
Just added XStyledProps to radioBorderedBox.
Edit: also changed `label` prop to accept not only string but any other complex children.
=> fix: radioborderedbox add xstyledprops

src/components/ExtendedReminder/__tests__/__snapshots__/index.tsx.snap, src/components/ExtendedReminder/__tests__/index.tsx, src/components/ExtendedReminder/index.tsx, src/components/Modal/__tests__/__snapshots__/index.tsx.snap, src/components/Modal/__tests__/index.tsx, src/components/Modal/index.tsx
- Refactor
**Modals**: added `onBeforeClose` prop that will be triggered before the modal is closed. This is useful when using disclosure and not onClose prop.
**ExtendedReminder**: added `CustomLink` prop that can take a node value. This is useful when wanting to put a modal with disclosure inside of ExtendedReminder without using default link and onClick prop.
=> fix(modal): onBeforeClose & ExtendReminder CustomLink

src/components/TextBox/__tests__/__snapshots__/index.test.tsx.snap, src/components/TextBox/index.tsx
- Feature
The padding-right has been reduced to `required` TextBox, and this PR adds an `inputProps` prop to TextBox which are forwarded to the input element.
-- | <img width="186" alt="Screenshot 2021-09-16 at 15 14 34" src="https://user-images.githubusercontent.com/43268759/133618831-25b93957-edd5-4171-a7a3-54ba44dd1c64.png"> | <img width="98" alt="Screenshot 2021-09-16 at 15 15 00" src="https://user-images.githubusercontent.com/43268759/133618851-4ba19b61-61ed-4ea9-8fd6-2664719949c9.png">
=> feat(textbox): reduce padding & add `inputProps`

src/theme/colors.ts
Removes const for colors so typescript works when overwriting base colors.
=> fix: colors not const

package.json, yarn.lock
- Refactor
Remove useless package babel-eslint is deprecated and replace by @babel/eslint-parser
=> chore(babel-eslint): remove useless package

src/components/DateInput/__tests__/__snapshots__/index.test.tsx.snap, src/components/Modal/__tests__/__snapshots__/index.tsx.snap, src/components/Stepper/__tests__/__snapshots__/index.tsx.snap, src/components/Tags/__tests__/__snapshots__/index.tsx.snap, src/components/TextBox/__tests__/__snapshots__/index.test.tsx.snap, src/components/Touchable/__tests__/__snapshots__/index.tsx.snap, src/components/Touchable/index.tsx
=> fix(Touchable): correct invalid css class

src/components/BarChart/__tests__/__snapshots__/index.tsx.snap, src/components/BarChart/index.tsx, src/components/BarStack/__tests__/__snapshots__/index.test.tsx.snap, src/components/BarStack/index.tsx, src/components/LineChart/__tests__/__snapshots__/index.tsx.snap, src/helpers/legend.ts
- Refactor
Migrate Badge, Barchart, BarStack with new theme
1. Update colors to use new theme
2. Drop chartColors
| Page |   Before   |  After  |
| :---: | :--------: |:---------: |
| BarChart  | <img width="1059" alt="Capture d’écran 2021-12-13 à 11 18 47" src="https://user-images.githubusercontent.com/24531136/145794381-84e9efc3-b10a-4c8d-b1d9-b4ae095f5a19.png"> | <img width="1029" alt="Capture d’écran 2021-12-13 à 11 19 14" src="https://user-images.githubusercontent.com/24531136/145794482-31cab608-35d5-40ef-8189-d688c5ac6cc1.png"> |
| BarStack  | <img width="1025" alt="Capture d’écran 2021-12-13 à 11 20 18" src="https://user-images.githubusercontent.com/24531136/145794623-abe9b396-28e6-4ce0-983a-ee506183eaeb.png"> | <img width="1038" alt="Capture d’écran 2021-12-13 à 11 20 42" …
=> feat: migrate badge, barchart, barstack to new colors

src/components/Typography/index.tsx, src/components/VerificationCode/__tests__/__snapshots__/index.tsx.snap, src/components/VerificationCode/index.tsx, src/components/VolumeSize/__tests__/__snapshots__/index.tsx.snap, src/components/VolumeSize/index.tsx
- Migration
Migration of:
- Typography
- VerificationCode
- VolumeSize
⚠️ Component Typography couldn't be fully migrated as we are using a lot of:
```js
<Typography color="gray550">
```
we still need to be retro-compatible until all typography usage have been changes.
| Typography  | ![Screenshot 2021-12-14 at 18 01 54](https://user-images.githubusercontent.com/15812968/146045629-4f3519db-8329-4dc3-af46-dd338ba567d2.png) | ![Screenshot 2021-12-14 at 18 02 00](https://user-images.githubusercontent.com/15812968/146045644-6b259d12-c670-4cef-8d31-6701f8a059be.png) |
| VerificationCode  | ![Screenshot 2021-12-14 at 18 02 26](https://user-images.githubusercontent.com/15812968/146045732-0a12e25d-701c-4e90-984b-4c42d9f1e9b3.png …
=> refactor(theme): migration colors of Typography, VerificationCode, VolumeSize

src/__tests__/a11y.test.tsx, src/components/Tag/index.tsx, src/components/Tags/__tests__/__snapshots__/index.tsx.snap, src/components/Tags/index.tsx
- Migration
Add `aria-label` to the close button on `Tag` and `Tags`.
I asked @ iManu, no need to add the name of the tag in the `aria-label`.
=> refactor(tags): add a11y

src/components/Toaster/index.tsx, src/components/Tooltip/__tests__/__snapshots__/index.test.tsx.snap, src/components/Tooltip/index.tsx, src/components/TooltipIcon/__tests__/__snapshots__/index.tsx.snap, src/components/UnitInput/index.tsx, src/theme/__tests__/index.ts, src/theme/colors/index.ts
- Refactor
Refactor Toaster, Tooltip, TooltipIcon, UnitInput to use the new colors.
As discussed with @matthprost, I had to change `backgroundStrongHover` to a pure black for tooltips background.
| Tooltip  | ![Screenshot 2021-12-20 at 14 44 28](https://user-images.githubusercontent.com/43268759/146776561-f4ccc052-efda-4cd2-891f-247e46ac4e16.png) | ![Screenshot 2021-12-20 at 14 44 04](https://user-images.githubusercontent.com/43268759/146776478-9610afb1-f221-41de-98bc-f623bff1359a.png) |
| Toaster  | ![Screenshot 2021-12-20 at 14 45 18](https://user-images.githubusercontent.com/43268759/146776675-d694ac0f-aaa5-4b52-bf76-9c4735f60158.png) | ![Screenshot 2021-12-20 at 14 45 …
=> refactor(theme): migrate colors for Toaster, Tooltip, TooltipIcon, UnitInput

src/components/Tags/index.tsx
- Bug
Update the `onChange` prop type definition so each tag is only a `string`, not a `string | null | undefined`
=> fix(tags): onChange prop type definition

src/components/Breadcrumbs/__tests__/__snapshots__/index.tsx.snap, src/components/Breadcrumbs/index.tsx, src/components/CreationProgress/__tests__/__snapshots__/index.test.tsx.snap, src/components/CreationProgress/index.tsx, src/components/NavigationStepper/__tests__/__snapshots__/index.test.tsx.snap, src/components/NavigationStepper/index.tsx
I got sick of seing this kind of errors
- Bug
=> fix: replace unsafe (first|last)-child by (first|last)-of-type

src/components/RadioBorderedBox/index.tsx
=> fix(RadioBorderedBox): enforce label as string and allow labelDescription to be a node

src/components/Box/index.tsx
- Bug
When we try to use directly type from component using Xstyled props  we have an issue on generated type
```
./src/index.ts → dist/index.d.ts...
src/components/TextBoxField/index.tsx(52,7): error TS4023: Exported variable 'TextBoxField' has or is using name 'XStyledProps' from external module "/root/dev/scaleway/team-console/scaleway-form/node_modules/@scaleway/ui/dist/index" but cannot be named.
src/components/CheckboxField/index.tsx(42,7): error TS4023: Exported variable 'CheckboxField' has or is using name 'XStyledProps' from external module "/root/dev/scaleway/team-console/scaleway-form/node_modules/@scaleway/ui/dist/index" but cannot be named.
[!] (plugin dts) Error: Failed to compile. Check the logs above.
src/index.ts
Error: Failed to compile. Check the logs above.
at error …
```
=> fix(type): allow extends of XstyledProps into scaleway form package

.github/workflows/deploy-storybook.yml, .github/workflows/teardown_pull_request.yml
- Bug
teardown was not based on the same dns
=> fix(teardown): dns env was not the same, use secret

src/components/RichSelect/index.tsx
- Bug
Same as Xstyled, to use correctly type of RichSelect we need a type and not an interface
=> fix(typescript): change typing export

src/components/Menu/__tests__/__snapshots__/index.tsx.snap, src/components/Menu/index.tsx
- Bug
Ability to add styled to  `<Menu>` component  ex: ```styled(Menu) more style here```
1. add className to menu props
2. pass className to Popper inside the Menu
3.apply styled on menuList instead of css attribute
=> fix(menu): add className to menu component

rollup.config.mjs
- Build
Add `preserveSymlinks` to rollup
=> build(rollup): add `preserveSymlinks` option

src/components/Switch/index.tsx
Clicking on label trigger an event which is bubbled up, we don't want that, event is already handled by the checkbox :)
- Bug
=> fix(Switch): avoid event bubbling on label click

src/components/Modal/index.tsx
- Enhancement
Modal props: 
onBeforeClose only accept promise on type why ?
=> fix(modal): type of onBeforeClose

src/components/TabGroup/Tab.tsx
Was used in relation with Counter which does no exists anymore
- Enhancement
=> chore(TabGroup): remove now useless prop

src/components/Link/index.tsx
- Bug
Added `onClick` on link component as it is required by react router to be able to work correctly.
=> fix(link): add on click for react router

src/components/Typography/__stories__/migration.stories.mdx
Made a mistake in documentation for migration of `Typography` to `Text`: `description` should become `bodyStrong`
=> docs: fixed description to bodyStrong migration

src/components/Breadcrumbs/__tests__/__snapshots__/index.tsx.snap, src/components/Button/__tests__/__snapshots__/index.tsx.snap, src/components/Button/index.tsx, src/components/Link/__tests__/__snapshots__/index.tsx.snap, src/components/Link/index.tsx, src/components/List/__tests__/__snapshots__/index.test.tsx.snap, src/components/MarkDown/__tests__/__snapshots__/index.tsx.snap, src/components/MarkDown/index.tsx, src/components/Menu/__tests__/__snapshots__/index.tsx.snap, src/components/Pagination/__tests__/__snapshots__/index.test.tsx.snap
- Bug
- Fixed button as link to make icon inline
- Fixed markdown link to inherit its size
| url  | <img width="139" alt="Screenshot 2022-08-02 at 18 04 15" src="https://user-images.githubusercontent.com/15812968/182422348-4781cb94-81cb-46cf-b08b-874fc958dd31.png"> | <img width="154" alt="Screenshot 2022-08-02 at 18 01 14" src="https://user-images.githubusercontent.com/15812968/182422372-c0647634-9ef2-4d71-bf19-9faf5fcef33d.png"> |
| url  | <img width="462" alt="Screenshot 2022-08-02 at 18 03 50" src="https://user-images.githubusercontent.com/15812968/182422420-2337eba6-98ab-4535-aec7-b71773d2da5a.png"> | <img width="457" alt="Screenshot 2022-08-02 at 18 01 53" …
=> fix(link): correct wrong behavior

src/components/PieChart/Tooltip.tsx
- Bug
To align text on left into PieChart tooltip.
| url  | <img width="607" alt="Screenshot 2022-08-09 at 11 48 19" src="https://user-images.githubusercontent.com/15812968/183619350-13a7caad-24e0-46f9-9f2e-0d9cef1d8e66.png"> | <img width="618" alt="Screenshot 2022-08-09 at 11 46 42" src="https://user-images.githubusercontent.com/15812968/183619374-541288b6-335f-41df-80fb-a64de03dd898.png"> |
=> fix(PieChart): tooltip alignement

src/components/DateInput/__tests__/__snapshots__/index.test.tsx.snap, src/components/Notice/__tests__/__snapshots__/index.tsx.snap, src/components/Notice/index.tsx, src/components/TextBox/__tests__/__snapshots__/index.test.tsx.snap, src/components/TextBox/index.tsx, src/components/UnitInput/__tests__/__snapshots__/index.tsx.snap
=> feat(Notice): migrate from Box to div

src/components/Radio/__tests__/__snapshots__/index.tsx.snap, src/components/Radio/index.tsx, src/components/RadioBorderedBox/__tests__/__snapshots__/index.tsx.snap, src/components/SelectableCard/__tests__/__snapshots__/index.tsx.snap, src/components/SelectableCard/index.tsx
- Bug
Avoid removing all svg children, only the one of the input.
| url  | <img width="264" alt="Screenshot 2022-08-16 at 11 45 48" src="https://user-images.githubusercontent.com/15812968/184853214-6e69f1cf-582e-451b-a382-d0cc836b6ea4.png"> | <img width="281" alt="Screenshot 2022-08-16 at 11 45 16" src="https://user-images.githubusercontent.com/15812968/184853227-7c0736fe-a9da-4fd5-be1d-42f6e26d165c.png"> |
=> fix(SelectableCard): avoid hidding all children svg

codecov.yml
- CI
Sometime CodeCov is flacky and shows a tiny change on code coverage while there is none. In order to avoir having this error in CI, I added a 0.1% threshold that should allow any PR to have 0.1% coverage difference and so solve this issue.
=> ci(codecov): fix very low coverage changes on ci

src/components/Radio/__tests__/__snapshots__/index.tsx.snap, src/components/Radio/index.tsx, src/components/RadioBorderedBox/__tests__/__snapshots__/index.tsx.snap, src/components/SelectableCard/__tests__/__snapshots__/index.tsx.snap, src/components/SwitchButton/__tests__/__snapshots__/index.tsx.snap
It makes sure that only the hovered container radio is highlighted and not **all** the radio contained in the parent
- Bug
=> fix(radio): nested radio container hover

src/components/Checkbox/__tests__/__snapshots__/index.tsx.snap, src/components/Checkbox/index.tsx, src/components/List/__tests__/__snapshots__/index.test.tsx.snap, src/components/Radio/__tests__/__snapshots__/index.tsx.snap, src/components/Radio/index.tsx, src/components/RichSelect/index.tsx, src/components/SelectableCard/__tests__/__snapshots__/index.tsx.snap, src/components/SwitchButton/__tests__/__snapshots__/index.tsx.snap, src/components/Tooltip/__tests__/__snapshots__/index.test.tsx.snap, src/components/Tooltip/index.tsx, src/components/UnitInput/__tests__/__snapshots__/index.tsx.snap, src/index.ts, src/utils/__tests__/__snapshots__/index.tsx.snap, src/utils/__tests__/index.tsx, src/utils/ids.ts
Closes #1790
- Refactor
Use React 18 `useId` hook instead of `useUUID`.
Remove the exports from index of `useUUID` and `getUUID`.
I could not delete `getUUID` because it's still used in places where we can't use `useId`
=> fix: use `useId` instead of `useUUID`

src/components/Text/__tests__/__snapshots__/index.test.tsx.snap, src/components/Text/index.tsx
- Bug
Fix `Text` italic and underline style that were missing a semicolon.
=> fix(Text): italic & underline missing semicolon

pnpm-lock.yaml, src/components/Tooltip/__stories__/index.stories.tsx, src/components/Tooltip/__tests__/index.test.tsx, src/components/Tooltip/helpers.ts, src/components/Tooltip/index.tsx
- Enhancement
To allow placement `auto` which will positionnante tooltip depending on its size and window size. 
The goal is to always display tooltip and avoid overflow. In the worst case scenario if the tooltip is too big for any position, it will be displayed on top.
Placement is computed again when window size changes or when user scroll. 
I also made tiny change in CSS: to use `transform3d` for using GPU while rendering and increase performance.
https://user-images.githubusercontent.com/15812968/189650226-e769b335-7726-41f4-ae48-35500a86dbd6.mov
=> feat(tooltip): dymanic position

src/components/List/SelectBar.tsx, src/components/List/index.tsx
Before:
```ts
<List<{ message: string }>>
{(list) => <list.SelectBar>{({selectedItems}) => {...}}</list.SelectBar>}
{/* ^ Record<string, unknown> */}
</List>
```
After:
```ts
<List<{ message: string }>>
{(list) => <list.SelectBar>{({selectedItems}) => {...}}</list.SelectBar>}
{/* ^ { message: string }[] */}
</List>
```
- Enhancement
=> feat(list): add correct type in SelectBar props

src/components/List/index.tsx, src/components/Pagination/usePagination.ts
Make sure that pagination isn't updated while the parent list is loading.
- Enhancement
=> fix(pagination): do not update max page when list is loading

src/components/Pagination/__stories__/index.stories.tsx, src/components/Pagination/index.tsx
Changed pagination to make it deprecated. In storybook too
=> docs: make pagination deprecated

.github/workflows/sync-design-tokens.yml
- Enhancement
Allow action sync tokens to be manually triggered if necessary.
=> ci: make sync tokens triggerable

src/components/PieChart/Legends.tsx, src/components/PieChart/__tests__/__snapshots__/index.tsx.snap
- Enhancement
Scroll bar is always displayed in PieChart even when legend is not long enough to have a scroll bar. I fixed it by changing prop from `scroll` to `auto`. This way it will show it only when necessary.
| PieChart  | ![Screenshot 2022-10-03 at 11 27 42](https://user-images.githubusercontent.com/15812968/193545762-b3c75a92-d80d-43a7-a508-01da51fa6fc5.png) | ![Screenshot 2022-10-03 at 11 27 59](https://user-images.githubusercontent.com/15812968/193545804-d7f6729c-652a-47cc-8a7f-55353c8c3a15.png) |
=> fix(PieChart): vertical scroll auto

src/components/Tabs/Tab.tsx, src/components/Tabs/__tests__/__snapshots__/index.test.tsx.snap
- Bug
Force counter to be centered. In our console other styles override the default behaviour
1. Add text-align: center
=> fix: force text align in counter

src/components/Tooltip/index.tsx
- Bug
Applied className on tooltip it self instead of its children.
=> fix(tooltip): apply className on tooltip instead of children

src/components/Container/index.tsx
- Bug
Sometimes in our console we need to pass an Element to the subtitle (like Badge)
1. Update type
=> fix: container props

src/__tests__/a11y.test.tsx
- CI
Some a11y tests are failing on CI so I increased the timeout value as TextBox sometimes take a little long to complete.
I also removed a snippet of code that has been fixed since last release of axe-jest.
=> ci: fix flacky ci and remove unsed code

src/components/List/LoadingPlaceholder.tsx, src/components/List/index.tsx
Show 3 placeholder rows when `data` is undefined and list is loading
- Enhancement
=> fix(list): show placeholder when data length is unknown

.eslintrc, src/components/Menu/__stories__/Variants.tsx
We don't need to disable `no-unused-vars` anymore as we figured out that our Storybook config automatically parse the code snippets for files ending with `stories.tsx`
But, we need to disable `react/no-unstable-nested-components` because for some case it is required to inline components in our stories
=> style: add inline nested component eslint rule

.storybook/components/DocsContainer.tsx
There was an issue with description in storybook. It seems like it wasn't displayed since I made custom storybook parameters and dark theme. I forgot to spread parameters in context, now it should work just fine.
Before:
After:
=> docs: fix description not display in storybook

src/components/PaginationV2/__tests__/__snapshots__/index.test.tsx.snap, src/components/PaginationV2/index.tsx, src/components/SelectNumber/__tests__/__snapshots__/index.tsx.snap, src/components/SelectNumber/index.tsx
Default button `type` prop is `submit` and it is not expected for our styled buttons
=> fix: add button type to styled buttons

src/__tests__/a11y.test.tsx
- CI
Since we changed structure of our stories, a11y script needed a little refreshment. We now categories each component with individual a11y test for each stories.
Before:
After:
=> ci: fix script with new storiesfile format

src/components/CopyButton/index.tsx
- Bug
Added `noBorder` to props that should not be forwarded to dom element
Remove warning in the console
1. Add `'noBorder'` string in `shouldForwardProp` exclusion list
=> fix(CopyButton): add noBorder to not forwarded props list

src/components/RichSelect/__stories__/index.stories.tsx, src/components/RichSelect/__tests__/__snapshots__/index.tsx.snap, src/components/RichSelect/__tests__/index.tsx, src/components/RichSelect/index.tsx
- Enhancement
To be able to customize empty state of the RichSelect.
Default empty state:
New customizable example:
=> feat(RichSelect): allow customization of empty state

src/components/StepList/__tests__/__snapshots__/index.tsx.snap, src/components/StepList/index.tsx
- Bug
Set padding-left for the `ul` of `StepList` to 0
`StepLists` comes now with 0 padding
| /docs/components-data-display-steplist--default  | 
| 
|
=> fix(StepList): set ul padding-left to 0

src/components/Menu/Item.tsx
- Bug
To avoid this kind or errors when using our Menu Item with our Modal components.
```js
instrument.js?bdb8:109 Can't determine whether the element is the current disclosure because `ref` wasn't passed to the component 
See https://reakit.io/docs/dialog
```
Add forward ref to Menu.Item component
=> fix(menu): add forward ref to menu item

.storybook/components/DocsContainer.tsx, .storybook/preview.tsx
There was an issue with fonts loading in storybook (check video). In fact fonts where loaded at every render of stories which made it "blink" while changing component story. I made the import of fonts globally to storybook so there is not that behavior.
When switch from one component to another this happen (now solved):
https://user-images.githubusercontent.com/15812968/204014765-40936bbe-491f-4a4f-a996-b6f5028ee5a8.mov
=> docs: remove fonts load at each story to make it global

src/components/Link/index.tsx, src/components/Text/index.tsx
- Enhancement
I added possibility to set and `id` for text to be able to anchor some titles.
I also added `aria-label` for links as apparently links should always have label: https://developer.mozilla.org/en-US/docs/Web/Accessibility/Understanding_WCAG/Text_labels_and_names#interactive_elements_must_be_labeled
=> fix: a11y parameters for text and link

src/components/List/__tests__/__snapshots__/index.test.tsx.snap, src/components/List/variants/variantExplorer.tsx, src/components/List/variants/variantProduct.tsx, src/components/List/variants/variantTable.tsx
- Bug
Tooltip is displayed still when hovering a disabled checkbox on a List. It was hard to find a reason why but it seems like svg  events are causing conflict with tooltip, I found this about the topic: https://github.com/facebook/react/issues/4492#issuecomment-426356566
Adding `pointer-event: none` to a disabled checkbox on List solved the issue.
Before:
https://user-images.githubusercontent.com/15812968/205882219-e166048c-2045-43bc-b7c3-cd58d56ea702.mov
After:
https://user-images.githubusercontent.com/15812968/205882253-f382e65a-214f-45c8-9de8-1e8dd8a58583.mov
=> fix(list): tooltip never disapear after hover on disabled checkbox

src/components/Tabs/index.tsx
- Bug
There is an issue with Tabs that scroll vertically when loading a page (like on website). This is because we have a scroll event on Tabs to make it go to selected tabs. As we don't want this effect on vertical scroll I blocked it on horizontal scroll avoiding to cause side effects.
Before:
https://user-images.githubusercontent.com/15812968/206156368-25956682-bcce-41c2-a0f0-895ccd5ce953.mov
After:
https://user-images.githubusercontent.com/15812968/206156428-3468d936-4c7b-47c2-8c9d-a635617d5550.mov
=> fix(tabs): vertical scroll triggred on page load

src/components/Toaster/__tests__/__snapshots__/index.tsx.snap, src/components/Toaster/index.tsx
- Bug
Wrong variant for toaster that display an orange color while it should be red.
| url  | ![Screenshot 2022-12-12 at 10 11 56](https://user-images.githubusercontent.com/15812968/207007913-27aa85c7-bd15-4a88-89e8-c57f5645a1e1.png) | ![Screenshot 2022-12-12 at 10 11 14](https://user-images.githubusercontent.com/15812968/207007934-31e31c4e-650c-458e-9bf8-b952c0d2d91e.png) |
=> fix(toaster): wrong variant for error

src/components/ListV2/ListContext.tsx, src/components/ListV2/__tests__/__snapshots__/index.test.tsx.snap, src/components/ListV2/__tests__/index.test.tsx
- Bug
There was a rerender loop by when having both onSelectedIdsChange and selectedIds prop. Instead it need to act like all html input : when there are onChange present use it instead of local onChange
1. Wrap the setSelectedIds in a function that choose between both of them
2.
3.
=> fix: rerender loop

packages/ui/src/components/List/index.tsx, packages/ui/src/components/List/types.ts, packages/ui/src/components/List/variants/variantExplorer.tsx, packages/ui/src/components/List/variants/variantProduct.tsx, packages/ui/src/components/List/variants/variantTable.tsx, packages/ui/src/utils/index.ts, packages/ui/src/utils/orderBy.ts
- Bug
The `sort` prop didn't allow `number` as the return value when we use a function. This PR uses `ComparableType` everywhere to allow for `number | string`.
=> fix(List): fix sort type to allow numbers

packages/ui/src/components/Button/__tests__/__snapshots__/index.tsx.snap, packages/ui/src/components/CopyButton/__tests__/__snapshots__/index.tsx.snap, packages/ui/src/components/List/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/PieChart/__tests__/__snapshots__/index.tsx.snap, packages/ui/src/components/SelectableCard/__tests__/__snapshots__/index.tsx.snap, packages/ui/src/components/Snippet/__tests__/__snapshots__/index.tsx.snap, packages/ui/src/components/SwitchButton/__tests__/__snapshots__/index.tsx.snap, packages/ui/src/components/TagsPoplist/__tests__/__snapshots__/index.tsx.snap, packages/ui/src/components/Tooltip/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/Tooltip/index.tsx, packages/ui/src/components/TooltipIcon/__tests__/__snapshots__/index.tsx.snap
- Bug
The button didn't have the same height when the prop `tooltip` was given in a flex element.
|   Before   |      After |
| --------: | ---------: |
|  ![Capture d’écran 2022-12-30 à 12 12 00](https://user-images.githubusercontent.com/1339931/210065254-2a72324e-2bc4-4941-8b10-3c4e6e7e0661.png) |  ![Capture d’écran 2022-12-30 à 12 12 43](https://user-images.githubusercontent.com/1339931/210065361-074f36f3-bb26-4e63-adbb-bdebed6fd4e0.png) |
=> fix(Button): manage flex display on tooltip

.storybook/preview.tsx, README.md, packages/form/README.md, packages/form/src/__stories__/Introduction.stories.mdx, packages/ui/README.md, packages/ui/src/__stories__/GetStarted.stories.mdx
I added a main README for Scaleway UI Core (all the packages in this monorepo) explaining how to install / test / build / etc. For usages it will redirect to README of each individual packages.
=> docs: add main README and updated documentation usages

packages/ui/src/components/ActionBar/__stories__/Ranks.stories.tsx, packages/ui/src/components/ActionBar/__stories__/Template.stories.tsx, packages/ui/src/components/ActionBar/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/ActionBar/index.tsx, packages/ui/src/components/List/SelectBar.tsx, packages/ui/src/components/List/__tests__/__snapshots__/index.test.tsx.snap
- Bug
ActionBar is having a padding of 16px inside of the component while the component shouldn't impose any padding it should be done in children. I removed it and added it into List, it should also fix the alignement issue present on every ActionBar.
| url  | <img width="618" alt="Screenshot 2023-01-03 at 15 07 08" src="https://user-images.githubusercontent.com/15812968/210379053-85be64b0-d6fa-4c2a-b20a-7bccddb0679d.png"> | <img width="632" alt="Screenshot 2023-01-03 at 15 31 42" src="https://user-images.githubusercontent.com/15812968/210379085-2023f6eb-4c74-46e2-a09b-4aea92ca28f6.png"> |
=> fix(actionBar): remove padding and center content from list action bar

packages/form/src/validators/regex.ts
- Enhancement
if a initialValue was set to an empty string,  the regex was considering field as invalid, preventing from submit field even if this field isn't required
```
<Form<{ email: string }>
errors={errrors}
initialValues={{ email: '' }} // email is not undefined but set with an empty string
onRawSubmit={() => {}}
>
<TextBoxField
name="email"
label="Email"
placeholder="test@test.fr"
regex={[emailRegex]}
/>
<SubmitErrorAlert />
<Submit>Submit</Submit>
</Form>
```
Instead of checking regex if value is not undefined, check regex only is value isn't undefined/emptyString/false
=> fix(form): regex validator now accepts an empty string

packages/ui/src/components/Button/__stories__/Extend.stories.tsx, packages/ui/src/components/Button/__tests__/__snapshots__/index.tsx.snap, packages/ui/src/components/Button/index.tsx
- Bug
Button with the `extend` prop could have an overflow issue if the font size was too big.
|   Before   |      After |
| :--------: | ---------: |
| ![Capture d’écran 2023-01-10 à 13 51 11](https://user-images.githubusercontent.com/1339931/211559604-5efdaf02-a105-47e1-baff-4473823d4272.png) | ![Capture d’écran 2023-01-10 à 13 51 37](https://user-images.githubusercontent.com/1339931/211559649-e8310bf0-0ce1-4680-8709-9db099af39c0.png) |
=> fix(Button): wrong overflow on extend

.prettierignore
Otherwise lerna runs on them when releasing, which results in conflict in further renovate/PR
=> ci: add lockfile and CHANGELOG to prettierignore

packages/ui/src/components/Text/index.tsx
- Bug
When using `oneLine` prop in Text it was using tooltip on hover even when not needed. I fixed it.
Before:
https://user-images.githubusercontent.com/15812968/211562821-fc998b9d-85cf-4aad-b0e8-dd1b6edc04e5.mov
After:
https://user-images.githubusercontent.com/15812968/211562889-440eae96-a8ae-48d2-8ac7-999a365ed0be.mov
=> fix(Text): show tooltip on ellipsis only when needed

packages/form/src/components/TextInputField/index.tsx, packages/ui/src/components/TextInput/index.tsx
- Bug
- 
Forward the `size` prop to `TextBox` inside `TextBoxField`
=> fix(TextBoxField): forward `size` prop to TextBox

packages/ui/src/components/Separator/__tests__/__snapshots__/index.tsx.snap, packages/ui/src/components/Separator/index.tsx
- Bug
- 
Background of separator icon is wrong.
| url  | ![Screenshot 2023-01-23 at 12 58 35](https://user-images.githubusercontent.com/15812968/214040510-59ce5aa6-c3d9-42fd-bcfa-4dd7166c13b3.png) | ![Screenshot 2023-01-23 at 12 58 39](https://user-images.githubusercontent.com/15812968/214040536-4827ee58-cf60-4b38-8d6f-1ff9ed488d4b.png) |
=> fix(Separator): background color in dark theme

packages/ui/src/components/Tooltip/index.tsx
- Enhancement
There was multiple issues with tooltip I fixed them and improved the opening / closing behavior:
- Fix: tooltip not closing on hover of disabled radio button (linked to: https://github.com/facebook/react/issues/18753)
- Fix: tooltip appearing at the top left of the screen
- Feat: added a debounce timer on tooltip avoid to flickering when hovering and unhovering fast
https://user-images.githubusercontent.com/15812968/213479952-19ad7f35-03ff-4e9c-b3ef-b3828836806d.mov
=> feat(tooltip): improve tooltip behavior and fix some issues

packages/ui/src/components/Markdown/__stories__/index.stories.tsx
Parmeters of Markdown deprecated where wrong, fixed them.
1.
2.
3.
| url  | <img width="1068" alt="Screenshot 2023-01-26 at 17 55 45" src="https://user-images.githubusercontent.com/15812968/214899324-bd2ba76f-6199-45b0-a8c5-0a16e394c6e4.png"> | <img width="1049" alt="Screenshot 2023-01-26 at 17 55 50" src="https://user-images.githubusercontent.com/15812968/214899348-a413f6f1-13e4-4999-b881-79c05bc8400b.png"> |
=> docs(Markdown): fix deprecated parmeters in storybook

packages/ui/src/__stories__/ComponentState/ComponentState.tsx
Add link to each component main story in component state doc page.
1. Add Link component on component name that refers to component story title
| url  | <img width="1021" alt="Screenshot 2023-02-14 at 15 21 25" src="https://user-images.githubusercontent.com/2362139/218765345-6d4f4987-ec72-4b92-9f30-b8bce02d99e5.png">  | <img width="1031" alt="Screenshot 2023-02-14 at 15 21 03" src="https://user-images.githubusercontent.com/2362139/218765434-cc7a3047-3323-47ec-8a42-a4201bb6c4ad.png"> |
=> docs(ComponentState): add link to each component main story

scripts/figma-synchronise-tokens.sh
- CI
We changed naming `others` to `other` on design side so it should be changed here too or the script will continue failing.
=> ci: fix tokens script by changing others to other

.storybook/components/DocsContainer.tsx, .storybook/components/Page.tsx, packages/ui/src/__stories__/ComponentState/ComponentState.tsx, packages/ui/src/components/BarChart/__stories__/index.stories.tsx, packages/ui/src/components/BarChart/index.tsx, packages/ui/src/components/LineChart/__stories__/index.stories.tsx, packages/ui/src/components/LineChart/index.tsx, packages/ui/src/components/PieChart/__stories__/index.stories.tsx, packages/ui/src/components/PieChart/index.tsx, packages/ui/src/components/StepList/__stories__/index.stories.tsx, packages/ui/src/components/StepList/index.tsx, packages/ui/src/components/TagInput/__stories__/index.stories.tsx, packages/ui/src/components/TagInput/index.tsx, packages/ui/src/components/TimeInput/__stories__/index.stories.tsx, packages/ui/src/components/TimeInput/index.tsx
Introducing new state for components: **Experimental**
This state defines components who are unstable and not prod ready, they also means no major when breaking change. This state exists to give us more flexibility and testing period for newly created component while adding a little warning on them for external users. There is also a `@experimental` that has been added in comment for each concerned component.
I also updated components states in storybook to have a clear definition of those states.
=> docs: new experimentals components in storybook

packages/ui/src/components/Text/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/Text/__tests__/index.test.tsx, packages/ui/src/components/Text/index.tsx
- Enhancement
Added htmlFor property on Text as we are going to remove Label component to use Text instead.
```tsx
// Old usage
<Label htmlFor="myinputid">My Label</Label>
// New usage
<Text as="label" variant="bodyStrong" htmlFor="myinputid">My Label</Text>
```
=> fix: text to accept hmtlFor

packages/ui/src/components/DateInput/__tests__/__snapshots__/index.test.tsx.snap
- Bug
CI is using last version of Node (18.15.0) while we usually use earlier version which leads to error on CI. I updated unit tests with last version of node.
=> fix: update snapshots with last node version

packages/ui/src/components/DateInput/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/index.ts, pnpm-lock.yaml
- Bug
EmptyState has not been added to the exported components
=> fix(EmptyState): export EmptyState component

packages/ui/src/index.ts
RowV2 is now exposed as library component (before that it was only available internally)
=> fix: expose rowV2 component

packages/form/package.json, pnpm-lock.yaml
- Bug
Downgrade final-form-arrays to 3.0.2.
The 3.1.0 version of final-form-arrays introduce the following change:
`Change remove and removeBatch behavior to set array value to undefined when all items have been removed.`
This change breaks forms when deleting all fields of a field array.
The 3.0.2 version set an empty array when all items are removed.
=> fix(deps): downgrade final-form-arrays to 3.0.2

.changeset/config.json
Make sure `@scaleway/ui` and `@scaleway/form` are bumped together, similar to what we had before.
Learn more about `fixed`: https://github.com/changesets/changesets/blob/main/docs/fixed-packages.md
=> chore: fixed releases for `@scaleway/ui` and `@scaleway/form`

.changeset/rare-hotels-try.md, packages/ui/src/components/Tooltip/helpers.ts, packages/ui/src/components/Tooltip/index.tsx
- Bug
This is an actual bug we have on Tooltip causing a flicker effect. This is because our animation is going back to its initial state once completed. In some cases this can cause the flickering.
To fix it I simply added `forwards` to the animation in CSS, forcing the animation to keep its last position at the end of the animation solving the issue.
| Before  | After |
| ------------- | ------------- |
|  ![Screen Recording 2023-03-30 at 17 57 44](https://user-images.githubusercontent.com/15812968/228898920-dd1b65f7-e880-4685-a2ee-823f63713352.gif) | ![ezgif-4-96aeef49aa](https://user-images.githubusercontent.com/15812968/228897483-c611fa9c-7fe7-4f84-8f11-5509a76cd742.gif) |
=> fix(tooltip): flickering effect due to animation going backwards

.changeset/config.json
Remove linked, changeset is capable of updating packages automatically.
=> chore: remove linked config

.changeset/shy-boxes-refuse.md, packages/ui/src/components/ButtonV2/__tests__/__snapshots__/index.tsx.snap, packages/ui/src/components/ButtonV2/index.tsx
- Enhancement
I added `aria-label` and `name` properties to buttonV2. `aria-label` is required is there is no content set for accessibility.
=> fix(ButtonV2): add `aria-label` and `name` properties

.changeset/quick-dodos-tan.md, packages/form/src/components/NumberInputField/index.tsx, packages/form/src/providers/ErrorContext/__tests__/index.spec.tsx, packages/form/src/types.ts
- Refactor
use the right type for meta FieldMetaState instead of FieldState.
This will avoid cast error like this: 
``` javascript
const { input, meta } = useField(`${name}-buffer`, {
type,
value: '',
validate: validateFn,
})
const error = getError({
meta: meta as FieldState<unknown>,
```
=> 
``` javascript
const { input, meta } = useField(`${name}-buffer`, {
type,
value: '',
validate: validateFn,
})
const error = getError({
meta,
```
=> fix(form): meta type error function

.changeset/calm-moons-judge.md, packages/ui/src/components/VerificationCode/__tests__/__snapshots__/index.tsx.snap, packages/ui/src/components/VerificationCode/index.tsx
- Refactor
I remove `data-id` in `VerificationCode` as it was confusing and not type safe. This prop was used to manage state of the input, instead I'm passing `index` directly in the functions who needs it.
=> refactor(VerificationCode): change state management

.changeset/eighty-owls-pretend.md, packages/ui/src/components/PieChart/Legends.tsx, packages/ui/src/components/PieChart/__stories__/mockData.ts, packages/ui/src/components/PieChart/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/PieChart/index.tsx, packages/ui/src/components/PieChart/types.tsx
- Feature
PieChart integrate new chart colors we won't need to set them in data anymore they will be get from theme automatically making theme dark theme compatible.
=> feat(PieChart): using new data color

.changeset/four-queens-buy.md, packages/ui/src/components/Button/__tests__/__snapshots__/index.tsx.snap, packages/ui/src/components/CopyButton/__tests__/__snapshots__/index.tsx.snap, packages/ui/src/components/List/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/PieChart/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/Popover/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/SelectableCard/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/Snippet/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/SwitchButton/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/TagList/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/Tooltip/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/Tooltip/__tests__/index.test.tsx, packages/ui/src/components/Tooltip/index.tsx
- Enhancement
Tooltip wrapper can now be focused using the keyboard, once the tooltip wrapper is focused the tooltip itself is shown. It can then be removed  with `Escape` key.
Here are the specifications:
> A tooltip typically becomes visible, after a short delay of generally one to five seconds, in response to a mouse hover, or after the owning element receives keyboard focus. Just as it is opened automatically, without user request, it is closed automatically when the focus is lost or on mouse out. It should also close when the user presses the Escape key.
[https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/tooltip_role](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/tooltip_role)
We have to keep in mind an important statement:
> Because the …
=> fix(Tooltip): improve accessibility the wrapper can now be focused for voiceover

.changeset/odd-queens-pump.md, packages/ui/src/components/Alert/__stories__/Button.stories.tsx, packages/ui/src/components/Alert/__stories__/Closable.stories.tsx, packages/ui/src/components/Alert/__stories__/LongChildren.stories.tsx, packages/ui/src/components/Alert/__stories__/Variants.stories.tsx, packages/ui/src/components/Alert/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/Alert/__tests__/index.test.tsx, packages/ui/src/components/Alert/index.tsx, packages/ui/src/components/Banner/__stories__/Variants.stories.tsx, packages/ui/src/components/Banner/__stories__/index.stories.tsx, packages/ui/src/components/Banner/__tests__/index.tsx, packages/ui/src/components/Banner/index.tsx
- Refactor
- In `Alert` rename `onButtonClick` into `onClickButton`
- In `Banner` rename prop `type` into `variant`
=> fix: component props names

.changeset/nasty-seas-bake.md, packages/ui/src/components/Alert/index.tsx
- Enhancement
Display close button when `onClose` property is given.
=> fix(Alert): show close button when on close is given

.changeset/angry-crabs-relate.md, packages/ui/src/components/BarChart/__stories__/PositiveNegative.stories.tsx, packages/ui/src/components/BarChart/__tests__/__snapshots__/index.tsx.snap, packages/ui/src/components/BarChart/index.tsx, packages/ui/src/components/LineChart/CustomLegend.tsx, packages/ui/src/components/LineChart/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/LineChart/index.tsx, packages/ui/src/components/PieChart/index.tsx, packages/ui/src/helpers/legend.ts
- Enhancement
New data colors on `BarChart` and `LineChart`
| url  | <img width="1025" alt="Screenshot 2023-04-27 at 18 08 45" src="https://user-images.githubusercontent.com/15812968/234924205-b6dda4b6-2d55-486a-93e1-14f8cab1f9ce.png"> | <img width="1019" alt="Screenshot 2023-04-27 at 18 08 51" src="https://user-images.githubusercontent.com/15812968/234924347-2c2c2b19-0032-4d75-ab96-ce190f007050.png"> |
| url  | <img width="1023" alt="Screenshot 2023-04-27 at 18 09 10" src="https://user-images.githubusercontent.com/15812968/234924714-ac0aad1c-0c31-4f2c-8b27-ea663ac4edee.png"> | <img width="1012" alt="Screenshot 2023-04-27 at 18 09 24" src="https://user-images.githubusercontent.com/15812968/234924793-c1d8b367-0b5d-4150-b7 …
=> fix(Charts): update barchart and linechart to have new data colors

.changeset/weak-donuts-tickle.md, packages/ui/src/components/ListV2/Row.tsx
- Bug
Even if React manages to reconciliate expandable at each render, the prop itself is consider as different for useEffect, when parent component was re-render, the prop looks different and the row was register again, bringing an unwanted collapse of the row
=> fix: expandable row registering

packages/form/src/components/SubmitErrorAlert/__tests__/__snapshots__/index.spec.tsx.snap, packages/ui/src/components/Separator/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/Separator/__tests__/index.test.tsx, packages/ui/src/components/Separator/index.tsx
- Bug
Set the correct color of the icon (if one is set) on `<Separator />`
| url  | <img width="1141" alt="Screenshot 2023-05-03 at 09 53 07" src="https://user-images.githubusercontent.com/43268759/235859992-b5bb94c9-426b-4fd8-aba0-9744a7bca180.png"> | <img width="929" alt="Screenshot 2023-05-03 at 09 54 23" src="https://user-images.githubusercontent.com/43268759/235860206-e2973009-10a4-46d2-9052-73fe0ddf8674.png"> |
=> fix(Separator): icon color

.changeset/six-snails-hope.md, packages/form/src/components/NumberInputField/__tests__/__snapshots__/index.spec.tsx.snap, packages/form/src/components/NumberInputField/__tests__/index.spec.tsx, packages/form/src/components/ToggleField/__tests__/__snapshots__/index.spec.tsx.snap, packages/ui/src/__tests__/a11y.test.tsx, packages/ui/src/components/CopyButton/__tests__/__snapshots__/index.tsx.snap, packages/ui/src/components/CopyButton/index.tsx, packages/ui/src/components/EmptyState/__stories__/index.stories.tsx, packages/ui/src/components/NumberInput/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/NumberInput/__tests__/index.test.tsx, packages/ui/src/components/NumberInput/index.tsx, packages/ui/src/components/Snippet/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/Snippet/__tests__/index.test.tsx, packages/ui/src/components/Snippet/index.tsx, packages/ui/src/components/Toggle/__stories__/Template.stories.tsx, packages/ui/src/components/Toggle/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/Toggle/index.tsx, packages/ui/src/components/VerificationCode/__stories__/Template.stories.tsx, packages/ui/src/components/VerificationCode/__tests__/__snapshots__/index.tsx.snap, packages/ui/src/components/VerificationCode/index.tsx
- Enhancement
- Add unique `id` into `<Toggle />` component
- Add `aria-label` into `<Snippet />` component on copy button
- Add unique `id` into `<VerificationCode />` component
- Add `label`, `aria-label` and `aria-labelledby` into `<NumberInput />` component
- Enable a11y testing on:  Tooltip, VerificationCode, DatInput, NumberInput, Toggle, Snippet, SwitchButton
=> fix: improve accessibility on components and enable more a11y testing

.changeset/nice-singers-shout.md, packages/ui/src/components/VerificationCode/index.tsx
- Bug
Verification code correct focus on paste
1. Go to verification code
2. Paste something
3. It should focus on next available input or last one
https://github.com/scaleway/scaleway-ui/assets/3360430/7f381378-4dd3-4a66-a4e7-3c6cdaa3b260
=> fix: verification code focus on paste

packages/ui/src/components/Link/__stories__/OneLine.stories.tsx, packages/ui/src/components/Link/__stories__/index.stories.tsx, packages/ui/src/components/Text/__stories__/Dir.stories.tsx, packages/ui/src/components/Text/__stories__/OneLine.stories.tsx
Fix documentation of Link and Text.
| link  |  <img width="1022" alt="Screenshot 2023-05-30 at 17 00 22" src="https://github.com/scaleway/scaleway-ui/assets/15812968/151adc2e-072a-4730-bae7-3c76b3396099"> | <img width="1016" alt="Screenshot 2023-05-30 at 17 00 27" src="https://github.com/scaleway/scaleway-ui/assets/15812968/238c880c-9c79-4452-8c3f-0235da652414"> |
| text  | <img width="1025" alt="Screenshot 2023-05-30 at 17 01 18" src="https://github.com/scaleway/scaleway-ui/assets/15812968/2e51171a-9d71-4b99-a04f-8b9a7616d6be"> | <img width="1027" alt="Screenshot 2023-05-30 at 17 01 29" src="https://github.com/scaleway/scaleway-ui/assets/15812968/2fb80ac6-f0f6-46a0-b435-bd3fb5813fd7"> |
=> docs: update text and link documentation

.changeset/wise-mayflies-try.md, packages/form/src/components/NumberInputField/index.tsx
- Bug
The `NumberInputField` min/max was not used in the form validation.
=> fix(NumberInputField): min max validation

.changeset/modern-mangos-fry.md, packages/ui/src/components/Button/__stories__/Tooltip.stories.tsx, packages/ui/src/components/Button/__tests__/__snapshots__/index.tsx.snap, packages/ui/src/components/CopyButton/__tests__/__snapshots__/index.tsx.snap, packages/ui/src/components/PieChart/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/Popover/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/SelectableCard/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/Snippet/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/SwitchButton/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/Tag/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/TagList/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/Tooltip/__stories__/MaxWidth.stories.tsx, packages/ui/src/components/Tooltip/__stories__/Playground.stories.tsx, packages/ui/src/components/Tooltip/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/Tooltip/index.tsx
- Bug
Tooltip is not always align with content when content isn't a block (which take all available width)
=> fix(Tooltip): alignment

.changeset/ten-socks-repeat.md, packages/ui/src/components/Button/index.tsx
- Bug
`iconOnly` prop is added into DOM while it shouldn't as it is an internal prop of Button component used for styling.
=> fix(Button): remove `iconOnly` from dom

.changeset/chatty-countries-draw.md, packages/ui/src/components/Button/__tests__/__snapshots__/index.tsx.snap, packages/ui/src/components/CopyButton/__tests__/__snapshots__/index.tsx.snap, packages/ui/src/components/List/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/PieChart/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/Popover/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/SelectableCard/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/Snippet/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/SwitchButton/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/Table/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/Tag/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/TagList/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/Tooltip/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/Tooltip/index.tsx
- Bug
Rollback on `width: fit-content` as it changes the width of tooltip children and that's no what we want. Tooltip should be as much neutral as possible and do no change children behavior.
=> fix(Tooltip): rollback alignement

.changeset/renaming-deprecated-ultraviolet.md
This PR has one and only purpose: make one last version bump before renaming so we can log in changelog that the package is deprecated and will be seen in renovate easily.
=> fix: make old package deprecated for one last release

packages/themes/README.md
Fix example where `<Global />` component is not auto closing.
=> docs(themes): fix auto closing global in readme

packages/ui/package.json
- Bug
```
packages/ui                              |  WARN  The field "pnpm" was found in /Volumes/Dev/scaleway/team-console/ultraviolet/packages/ui/package.json. This will not take effect. You should configure "pnpm" at the root of the workspace instead.
```
=> fix(pnpm): remove useless field pnpm peerDeps

.changeset/wise-berries-poke.md, packages/ui/src/components/TagInput/index.tsx
- Bug
On TagInput it was impossible to navigate outside of the component because we were catching the Tab input.
=> fix(TagInput): not to block focus while pressing key tab

.changeset/violet-weeks-appear.md, packages/ui/src/components/Button/index.tsx
- Enhancement
Add props `aria-controls`, `aria-expanded` and `aria-haspopup` to Button component
=> fix(Button): add more aria props for better compatibility

.changeset/dry-snails-reflect.md, packages/ui/src/components/Pagination/index.tsx
- Enhancement
`page` prop could be outside the range "1 <-> page count", with a useEffect we simply check that the value is in the range otherwhile we called onChange with a better value, allowing component user to update page value
=> fix: pagination page value

.changeset/sour-buttons-carry.md, packages/ui/src/components/List/Row.tsx, packages/ui/src/components/List/__stories__/Example.stories.tsx
- Bug
Add a stop propagation for kewdown on the expandable content of a List.Row. It can avoid strange behavior when we need to type something inside an expandable content.
=> fix(List): avoid propagation outside Expandable

.changeset/eleven-bikes-kneel.md, packages/ui/src/components/List/Cell.tsx
- Bug
We add preventClick to avoid conflict with expand/collapse when clicking/keyDown on  row. However keyDown event was still propagated.
Naming stays a bit strange but since we plan to modify expand/collapse behavior it sounds ok
=> fix: prevent keyDown propagation on List.Cell

.changeset/lovely-worms-give.md, .storybook/preview.tsx, examples/next-advanced/tsconfig.json, examples/next-simple/tsconfig.json, package.json, packages/form/package.json, packages/themes/package.json, packages/ui/package.json, packages/ui/src/components/LineChart/CustomLegend.tsx, pnpm-lock.yaml, tsconfig.json
Following https://github.com/scaleway/scaleway-lib/pull/1380 in scw-lib, needs `@scaleway/tsconfig@1.1.1`
=> fix: use `exports` field and `type: module`

.changeset/mean-candles-bow.md, packages/ui/src/components/Button/__tests__/__snapshots__/index.tsx.snap, packages/ui/src/components/CopyButton/__tests__/__snapshots__/index.tsx.snap, packages/ui/src/components/List/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/PieChart/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/Popover/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/Popover/index.tsx, packages/ui/src/components/SelectableCard/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/Snippet/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/SwitchButton/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/Table/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/Tag/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/TagList/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/Tooltip/__tests__/index.test.tsx, packages/ui/src/components/Tooltip/index.tsx, packages/ui/src/internalComponents/Popup/__tests__/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/internalComponents/Popup/__tests__/__tests__/index.test.tsx, packages/ui/src/internalComponents/Popup/helpers.ts, packages/ui/src/internalComponents/Popup/index.tsx, packages/ui/src/internalComponents/index.ts
- Refactor
Creation of a new folder `src/internalComponents`. This folder will contains all components that are being used within the package and will never be exported outside of it. The goal is to have a centralised place for reusable components.
In this PR we created `Popup` a component that show on screen as popup depending on the location of the children. This component is used by `Tooltip` but also by `Popover` and will later be used for `SelectInput`, `Menu` and any other components needing `Popup` behavior.
=> refactor(Popup): create first internal component popup used by tooltip and popover

.changeset/wet-shoes-sneeze.md, packages/icons/src/components/ProductIcon/__tests__/__snapshots__/index.tsx.snap, packages/themes/src/themes/console/light.ts
- Enhancement
Token color for product icon was wrong in warning sentiment so we fixed it.
| url  | <img width="1052" alt="Screenshot 2023-07-21 at 11 29 00" src="https://github.com/scaleway/ultraviolet/assets/15812968/8093030c-f792-4987-830c-6c5e458c5809"> | <img width="1039" alt="Screenshot 2023-07-21 at 11 29 05" src="https://github.com/scaleway/ultraviolet/assets/15812968/ebe68e18-6489-4904-aa11-9de534a9d605"> |
=> fix(tokens): update tokens for product icon warning sentiment

.github/auto_assign.yml, .github/workflows/action.yml
- CI
In our current workflow the creator of the PR is the assigned to it. With this rule we can safely put a github action that auto assign the PR to the author in case we forget to do it.
=> ci: add github action to auto assign when pull request is created

.changeset/seven-pens-rescue.md, packages/ui/src/components/Modal/Disclosure.tsx, packages/ui/src/components/Modal/Modal.tsx, packages/ui/src/components/Modal/__tests__/index.test.tsx, packages/ui/src/components/Modal/types.ts
- Bug
Shoudlnt drop hide but make it deprecated
1.
2.
3.
=> fix: reintroduce hide function

.changeset/loud-moose-remember.md, packages/ui/src/components/ActionBar/index.tsx, packages/ui/src/components/Modal/Dialog.tsx, packages/ui/src/components/Modal/Disclosure.tsx, packages/ui/src/components/Modal/__tests__/__snapshots__/index.test.tsx.snap
- Enhancement
Modal should have aria-modal=true but actionar shouldn't. Additionally pass more aria props to disclosure
1.
2.
3.
=> fix: dialog add attributes

.github/renovate.json
Renovate is not updating dependencies into folder examples which is not good. We need to maintain those as much as packages.
=> ci: fix renovate to check examples folder

.changeset/seven-kings-serve.md, packages/ui/src/components/Modal/Dialog.tsx, packages/ui/src/components/Modal/Disclosure.tsx, packages/ui/src/components/Modal/__tests__/__snapshots__/index.test.tsx.snap
- Bug
We cant implement 100% accessibility on Modal because when Menu change on Modal close the focus cant be restored and cause menu to be clause
1.
2.
3.
=> fix: modal restore focus

.changeset/config.json, .changeset/renovate-9a9c9a8.md
There is an issue with changeset trying to release a new version for examples while it shouldn't. I remove the changeset md file mentioning it and I added into ignore of config file.
=> ci: fix changeset by removing examples folder in changeset

.changeset/shaggy-chairs-dress.md, packages/form/src/components/CheckboxField/__tests__/__snapshots__/index.spec.tsx.snap, packages/form/src/components/CheckboxGroupField/__tests__/__snapshots__/index.spec.tsx.snap, packages/ui/src/components/Checkbox/__tests__/__snapshots__/index.tsx.snap, packages/ui/src/components/Checkbox/index.tsx, packages/ui/src/components/CheckboxGroup/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/LineChart/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/List/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/SelectableCard/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/Table/__tests__/__snapshots__/index.test.tsx.snap
- Bug
Since the last update checkbox we were using wrong tokens, leading to errors when changing theme colors.
=> fix(Checkbox): wrong tokens usages

.changeset/config.json
There is an issue when renovate tries to update package in examples folder it generate a changeset out of it while it shouldn't. To avoid that I added those projects into ignore of the config file.
=> ci(changeset): add examples project into ignore

.changeset/happy-squids-design.md, packages/ui/src/components/Modal/Dialog.tsx
- Bug
Dialog should only update the `overflow-y` property of the body (to prevent scrolling)
=> fix(modal): dialog should use overflow y

packages/icons/src/components/CategoryIcon/__stories__/Documentation.md, packages/icons/src/components/CategoryIcon/__stories__/index.stories.tsx, packages/icons/src/components/Icon/__stories__/Documentation.md, packages/icons/src/components/Icon/__stories__/index.stories.tsx, packages/icons/src/components/ProductIcon/__stories__/Documentation.md, packages/icons/src/components/ProductIcon/__stories__/index.stories.tsx, packages/ui/src/__stories__/Changelog/Changelog.stories.tsx
I added more documentation about `CategoryIcon`, `ProductIcon` and `Icon`. Those documentation have been added to the doc page of each components.
=> docs(Icons): add documentation about product category and icons

.changeset/spotty-islands-unite.md, packages/ui/src/components/Button/__tests__/__snapshots__/index.tsx.snap, packages/ui/src/components/Button/index.tsx, packages/ui/src/components/Checkbox/__tests__/__snapshots__/index.tsx.snap, packages/ui/src/components/CopyButton/__tests__/__snapshots__/index.tsx.snap, packages/ui/src/components/List/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/PieChart/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/Popover/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/Radio/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/SelectableCard/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/Snippet/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/SwitchButton/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/Table/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/Tag/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/TagList/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/Toggle/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/Tooltip/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/Tooltip/__tests__/index.test.tsx, packages/ui/src/internalComponents/Popup/__tests__/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/internalComponents/Popup/__tests__/__tests__/index.test.tsx, packages/ui/src/internalComponents/Popup/index.tsx
- Enhancement
We use to have ESC key handled on tooltip but only on focus, it is now handled without focus too. The same features is implemented in Popover as it uses Popup.
=> fix(Tooltip): implement esc key without focus

.changeset/cool-buttons-pump.md, packages/ui/src/internalComponents/Popup/index.tsx
- Bug
We use to break all words on tooltip in case the content is too big but it cause problems as it will also break words in the middle of them as reported here:
To solve this we removed CSS property `word-break: break-all` and replaced it by `overflow-wrap: anywhere`. This is the correct way to do this for this kind of situation.
Examples:
=> fix(Tooltip): avoid breaking all words and break only when necessary

.changeset/green-sheep-grin.md, packages/ui/src/components/Popover/__tests__/index.test.tsx, packages/ui/src/components/Popover/index.tsx, packages/ui/src/internalComponents/Popup/index.tsx
- Enhancement
Improvement of the accessibility of Popover component. It should open on focus with space key and close with escape key. Also, the focus should follow inside of the component when it opens and go back on the container when it closes.
https://github.com/scaleway/ultraviolet/assets/15812968/ebfa1987-f58d-446f-a7e3-64daa1d2fb9a
=> fix(Popover): improve accessibility of the component

.changeset/sharp-rockets-search.md, packages/ui/src/components/Badge/__tests__/__snapshots__/index.tsx.snap, packages/ui/src/components/Badge/index.tsx, packages/ui/src/components/Tabs/__tests__/__snapshots__/index.test.tsx.snap
- Enhancement
Current badge is invalid as it has a paragraph (block element) inside a span (inline element). It also has 2 tags while it could ne simplified in one and make the dom less heavy.
Before:
After:
=> fix(Badge): simplify and correct badge tags in the dom

.changeset/pretty-cameras-push.md, packages/form/src/components/TextInputField/__tests__/__snapshots__/index.spec.tsx.snap, packages/ui/src/components/Notice/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/Notice/index.tsx, packages/ui/src/components/TextInput/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/TextInput/index.tsx
- Refactor
Current Notice is a paragraph while it should be a span avoiding the margin top and bottom of the paragraph. Plus we reduced the size of the icon fitting better into a TextInput.
| url  | <img width="1023" alt="Screenshot 2023-09-19 at 16 32 01" src="https://github.com/scaleway/ultraviolet/assets/15812968/22398137-ea50-4cbd-8dd0-efb446e0fb97"> | <img width="1038" alt="Screenshot 2023-09-19 at 16 32 12" src="https://github.com/scaleway/ultraviolet/assets/15812968/c9305358-e5d8-4a89-b094-ba86b227183e"> |
| url  | <img width="1032" alt="Screenshot 2023-09-19 at 16 32 35" src="https://github.com/scaleway/ultraviolet/assets/15812968/b27945b7-67c3-41e3-8157-feaadf7ca625"> | <img width="1038" alt="Screenshot …
=> refactor(Notice): changed to span and reduced icon size

.changeset/renovate-7410c46.md
Following the fix in https://github.com/scaleway/scaleway-lib/pull/1531, this removes the example packages in changeset.
=> fix: changesets

.changeset/violet-flowers-move.md, examples/next-simple/emotion.d.ts, packages/icons/src/emotion.d.ts, packages/ui/README.md, packages/ui/src/components/Row/index.tsx, packages/ui/src/components/Stack/index.tsx, packages/ui/src/emotion.d.ts, packages/ui/src/index.ts, packages/ui/src/theme/index.ts
- Enhancement
Old type `SCWUITheme` is now deprecated as the naming of the project changed. You should use `UltravioletUITheme` type in all your projects. This type will be removed in the next major.
=> fix(theme): deprecated theme name and replaced by new one

.changeset/thick-penguins-explain.md, packages/form/src/components/CheckboxField/__tests__/__snapshots__/index.spec.tsx.snap, packages/form/src/components/CheckboxGroupField/__tests__/__snapshots__/index.spec.tsx.snap, packages/ui/src/components/Checkbox/__tests__/__snapshots__/index.tsx.snap, packages/ui/src/components/Checkbox/index.tsx, packages/ui/src/components/CheckboxGroup/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/LineChart/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/List/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/SelectableCard/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/Table/__tests__/__snapshots__/index.test.tsx.snap
- Bug
Checkbox appeared too big because of the svg, fixed it!
| url  | ![Screenshot 2023-10-04 at 16 55 13](https://github.com/scaleway/ultraviolet/assets/15812968/2c59db95-d503-4ee7-840c-a28510175f2c) | ![Screenshot 2023-10-04 at 16 55 17](https://github.com/scaleway/ultraviolet/assets/15812968/c4063f1e-95a5-4841-b100-68a7f6a7159f) |
=> fix(checkbox): decrease the size of the svg

.changeset/green-toes-reflect.md, packages/icons/src/components/ProductIcon/__tests__/__snapshots__/index.tsx.snap, packages/icons/src/components/ProductIcon/index.tsx
- Bug
Some ProductIcon where not working properly because the className is applied on `<g />` and not on `<path />`. I fixed the CSS selector to apply the style on all children `<path />` when `<g />` has the className.
| url  | ![Screenshot 2023-10-13 at 11 03 49](https://github.com/scaleway/ultraviolet/assets/15812968/70327fdc-315a-4673-ba4f-4f8873188991) | ![Screenshot 2023-10-13 at 11 03 54](https://github.com/scaleway/ultraviolet/assets/15812968/fa059890-9c2a-444a-b58c-5bf898f05070) |
| url  | ![Screenshot 2023-10-13 at 11 04 06](https://github.com/scaleway/ultraviolet/assets/15812968/c46a9cc5-fcb3-402b-ba5d-bf49714500e0) | ![Screenshot 2023-10-13 at 11 04 …
=> fix(ProductIcon): color not correctly applied on some icons

.changeset/popular-years-own.md, packages/ui/src/components/Banner/__tests__/__snapshots__/index.tsx.snap, packages/ui/src/components/Banner/index.tsx
- Bug
Fix banner to vertically align in center description and title when content is too little.
| url  | <img width="976" alt="Screenshot 2023-10-17 at 15 20 22" src="https://github.com/scaleway/ultraviolet/assets/15812968/2651b3e6-77fc-43b2-a39e-80013a5be4a8"> | <img width="980" alt="Screenshot 2023-10-17 at 15 20 32" src="https://github.com/scaleway/ultraviolet/assets/15812968/aaaaed23-a90e-4ec1-9675-cf1d3cc341c8"> |
=> fix(Banner): alignement issue when description is too little

.changeset/moody-items-lie.md, packages/ui/src/components/Popover/index.tsx
- Bug
Popover color was incorrect
| url  | ![Screenshot 2023-10-18 at 11 37 48](https://github.com/scaleway/ultraviolet/assets/15812968/521515c8-e9ad-4fa5-9c19-3d1868b46d14) | ![Screenshot 2023-10-18 at 11 37 52](https://github.com/scaleway/ultraviolet/assets/15812968/b1cbb456-3b0b-4d2c-a0a2-4654d1ecdabd) |
=> fix(Popover): text to be correct color

.changeset/moody-lies-call.md, packages/ui/src/components/Popup/index.tsx
- Bug
When resizing the screen the popover and menu doesn't re-compute the position due to popup behavior.
Before:
https://github.com/scaleway/ultraviolet/assets/15812968/f1a43440-cfbe-4daf-b24f-624a78535f74
After:
https://github.com/scaleway/ultraviolet/assets/15812968/5a8fa290-e04b-4f9a-9e10-671cebabbd09
=> fix(Popup): popup to re-compute position when screen resize or when width changes

.changeset/tasty-dolphins-peel.md, packages/ui/src/components/TextInput/index.tsx
- Bug
min and max prop should be pass to input tag on TextInput
1. add min and max in input props
=> fix(ui): textinput should pass min and max prop

.changeset/sixty-gorillas-approve.md, packages/ui/src/components/MenuV2/index.tsx
- Bug
`requestIdleCallback` isn't defined yet in stable Safari (https://caniuse.com/requestidlecallback), but we have to wait for the `popupRef` to be defined before focusing the content when opening a menu. This PR replaces `requestIdleCallback(cb)` by `setTimeout(cb, 1)`
=> fix(MenuV2): focus when opening error

.changeset/strong-pumpkins-buy.md, packages/ui/src/components/Popover/index.tsx
- Bug
The color inside the popover is inherited from parents which makes the next white. To avoid this I forced the color to be text neutral.
| url  | ![Screenshot 2023-10-25 at 14 10 38](https://github.com/scaleway/ultraviolet/assets/15812968/27d90721-d82a-491b-ae11-02132fc0fe17) | ![Screenshot 2023-10-25 at 14 10 51](https://github.com/scaleway/ultraviolet/assets/15812968/252cb533-51d4-4642-8860-8f43136fa350) |
=> fix(Popover): set a default color in content to avoid inherit from parent

package.json, packages/ui/src/components/Popover/__tests__/index.test.tsx
- CI
As we had some issues with popover and more generally nested component inside of it. I created a new advanced test, it has a Modal within a Popover and both have text input and select input with interaction with all of them. The goal is to check that neither the modal or the popover closes when we interact with it.
=> ci(Popover): add advanced unit testing with modal within popover

.changeset/lovely-socks-yawn.md, packages/ui/src/components/MenuV2/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/MenuV2/index.tsx, packages/ui/src/components/Popover/index.tsx, packages/ui/src/components/Popup/__tests__/__tests__/index.test.tsx, packages/ui/src/components/Popup/index.tsx
- Bug
On some browser setting a `maxHeight` and animation create a glitch making the popup blured until scrolled. To avoid this we remove animation on component having `maxHeight` set.
Changes in component `<Popup />`:
- Add new prop `maxHeight` and disable animation when set
- Add new prop `disableAnimation` to disable animation on popup
Changes in component `<MenuV2 />`:
- Add new prop `maxHeight` and disable animation when set
- Add new prop `maxWidth`
Changes in component `<Popover />`:
- Add new prop `maxHeight` and disable animation when set
- Add new prop `maxWidth`
=> fix(Popup): new props and remove animation when max height is set

.github/workflows/ci.yml
Improve the flow of the CI by needing lint and typecheck for build and tests
=> ci: make build and tests needs typecheck and lint

.changeset/shiny-dogs-confess.md, packages/illustrations/rollup.config.mjs
Rollup file size limit is reach by some of them like documentDB breaking the export and usage.
=> fix: rollup file size limit

.changeset/sweet-bees-joke.md, packages/plus/src/components/ContentCard/__tests__/__snapshots__/index.test.tsx.snap, packages/plus/src/components/ContentCard/index.tsx
- Bug
Make the title / subtitle and description vertically centered, so when there is a title only the structure makes actual sense.
| url  | <img width="976" alt="Screenshot 2023-11-09 at 10 26 11" src="https://github.com/scaleway/ultraviolet/assets/15812968/ebd3fb83-3826-4d85-8ca7-2c28742b3c00"> | <img width="985" alt="Screenshot 2023-11-09 at 10 26 16" src="https://github.com/scaleway/ultraviolet/assets/15812968/9f14d047-769a-4147-aea6-b830ebca633c"> |
| url  | <img width="970" alt="Screenshot 2023-11-09 at 10 26 25" src="https://github.com/scaleway/ultraviolet/assets/15812968/0f66335c-383f-4efc-a0dc-d6882f151667"> | <img width="970" alt="Screenshot 2023-11-09 at 10 26 32" …
=> fix(ContentCard): to have title and subtitle vertically centered

.changeset/six-toys-hammer.md, packages/form/src/components/CheckboxField/index.tsx, packages/form/src/components/Form/index.tsx, packages/form/src/components/RadioField/index.tsx, packages/form/src/components/RadioGroupField/index.tsx, packages/form/src/components/SelectableCardField/index.tsx, packages/form/src/components/Submit/index.tsx, packages/form/src/components/TagInputField/index.tsx, packages/form/src/components/TextInputField/index.tsx, packages/form/src/providers/ErrorContext/index.tsx, packages/ui/src/components/BarStack/index.tsx, packages/ui/src/components/Carousel/index.tsx, packages/ui/src/components/Meter/index.tsx, packages/ui/src/components/Pagination/index.tsx, packages/ui/src/components/PasswordStrengthMeter/index.tsx, packages/ui/src/components/Separator/index.tsx, packages/ui/src/components/Status/index.tsx, packages/ui/src/components/TagInput/index.tsx, packages/ui/src/components/TagList/index.tsx, packages/ui/src/components/TextInput/index.tsx, packages/ui/src/components/VerificationCode/index.tsx
- Refactor
I removed all useless `JSX.Element` when it is implicit for components and imported others from `React` directly as `JSX.Element` global is deprecated.
=> refactor: remove jsx element when not needed and imported others from react

packages/ui/src/components/DateInput/index.tsx
- Bug
For some reason the type coming from ReactDate are wrong an forcing usage of many optional props.
=> fix(DateInput): types broken

packages/plus/src/components/ContentCardGroup/__stories__/index.stories.tsx, packages/ui/src/components/Breadcrumbs/__stories__/index.stories.tsx, packages/ui/src/components/Carousel/__stories__/index.stories.tsx, packages/ui/src/components/Table/__stories__/index.stories.tsx, packages/ui/src/components/Tabs/__stories__/index.stories.tsx
Improvement of the clarity of storybook by adding correct sub component name. I can't fix the issue with snippet as Storybook doesn't seems to support it. There is an open issue about it here: https://github.com/storybookjs/storybook/issues/11919
Before:
After:
=> docs(storybook): add more clarity into storybook about sub components

.changeset/pink-dolphins-approve.md, packages/form/src/components/TagInputField/__tests__/__snapshots__/index.spec.tsx.snap, packages/ui/src/components/Tag/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/Tag/index.tsx, packages/ui/src/components/TagInput/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/TagList/__tests__/__snapshots__/index.test.tsx.snap
- Enhancement
When the tag is too long we are hiding the text but we never show it with a tooltip.
Before:
After:
=> fix(Tag): to display tooltip when tag content is too long

.changeset/rotten-wolves-compete.md, packages/form/src/components/DateField/__tests__/__snapshots__/index.tsx.snap, packages/ui/src/components/DateInput/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/DateInput/index.tsx
- Bug
DateInput was not using the font from tokens which lead to wrong font family.
Before:
After:
=> fix(DateInput): to use tokens from theme for font

.changeset/stupid-glasses-film.md, packages/ui/src/components/Banner/__tests__/__snapshots__/index.tsx.snap, packages/ui/src/components/Breadcrumbs/__tests__/__snapshots__/index.tsx.snap, packages/ui/src/components/Button/index.tsx, packages/ui/src/components/EmptyState/__tests__/__snapshots__/index.tsx.snap, packages/ui/src/components/GlobalAlert/GlobalAlertLink.tsx, packages/ui/src/components/GlobalAlert/__stories__/Button.stories.tsx, packages/ui/src/components/GlobalAlert/__stories__/Closable.stories.tsx, packages/ui/src/components/GlobalAlert/__stories__/Link.stories.tsx, packages/ui/src/components/GlobalAlert/__stories__/Playground.stories.tsx, packages/ui/src/components/GlobalAlert/__stories__/Template.stories.tsx, packages/ui/src/components/GlobalAlert/__stories__/Variants.stories.tsx, packages/ui/src/components/GlobalAlert/__stories__/index.stories.tsx, packages/ui/src/components/GlobalAlert/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/GlobalAlert/__tests__/index.test.tsx, packages/ui/src/components/GlobalAlert/index.tsx, packages/ui/src/components/Link/__stories__/Variants.stories.tsx, packages/ui/src/components/Link/__stories__/index.stories.tsx, packages/ui/src/components/Link/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/Link/__tests__/index.test.tsx, packages/ui/src/components/Link/index.tsx, packages/ui/src/components/Tabs/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/index.ts
- Enhancement
- New `<GlobalAlert />` component
- New prop `variant` for `<Link />` component:
- `variant="standalone"` (default): renders a standalone link without underline
- `variant="inline"`: renders an inline link with underline
=> feat(GlobalAlert): new component and update of Link

.changeset/green-guests-yell.md, packages/ui/.jest/helpers.tsx, packages/ui/src/components/Modal/__stories__/WithTooltip.stories.tsx, packages/ui/src/components/Text/index.tsx, packages/ui/src/hooks/__tests__/useIsOverflowing.test.tsx, packages/ui/src/hooks/useIsOverflowing.ts, pnpm-lock.yaml
- Bug
Text with prop `oneLine` were not working on modals due to the fact that it wasn't detecting properly the overflow. This is because modals appears later in the render and the `clientWidth` and `scrollWidth` are at 0 until the component is mounted. 
To fix this I created a `useIsOverflowing` hook that will detect overflow and wait the DOM to be painted and so the ref to be correctly set before calculating if overflow is happening.
I added test on the hook with 100% coverage.
=> fix(Text): one line prop to be working on modals

package.json
- CI
Size limit is throwing an error since we exported EstimateCost as it increased the bundle size. We do not want to limit the size of `@ultraviolet/plus` as it is supposed to contains heavy components but we do want to keep this limit on `@ultraviolet/ui` made out of simple components.
=> ci: fix size limit to ignore ultraviolet plus

.changeset/wet-terms-again.md, .changeset/wet-terms-repeat.md, packages/form/src/components/CheckboxField/__stories__/index.stories.tsx, packages/ui/src/components/Checkbox/__tests__/index.tsx, packages/ui/src/components/Checkbox/index.tsx
- Bug
Checkbox was not working properly when using space bar as only the internal state was updated. To do so I used the ref of the input and simulate a click on the input when space bar is pressed. This way we ensure the same events occur when space bar is clicked.
1. Go to storybook > CheckboxField
2. Focus the checkbox input and press space bar
3. You should see the form values updating correctly and the icon the change 
Before:
https://github.com/scaleway/ultraviolet/assets/15812968/dda953ca-cf4c-4544-abdc-1431a26c8765
After:
https://github.com/scaleway/ultraviolet/assets/15812968/c3db9412-4a79-4dcf-bde1-f61738124910
=> fix(Checkbox): trigger a on change on space bar pressed

.changeset/shiny-flowers-invent.md, packages/plus/src/components/EstimateCost/EstimateCostContent.tsx, packages/plus/src/components/EstimateCost/__stories__/GlobalDiscount.stories.tsx, packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Regular.spec.tsx.snap, packages/plus/src/components/EstimateCost/__tests__/__snapshots__/index.spec.tsx.snap
- Bug
Estimate cost is showing wrong values when setting discount to 0.
| url  | ![Screenshot 2023-12-08 at 17 28 35](https://github.com/scaleway/ultraviolet/assets/15812968/daa633e3-0572-4cd2-8711-ba4c2ff04f63) | ![Screenshot 2023-12-08 at 17 27 51](https://github.com/scaleway/ultraviolet/assets/15812968/944a0ca0-7c1f-4c7c-b19c-954d39e28b4a) |
=> fix(EstimateCost): when discount is set to 0 display correct values

.changeset/moody-goats-remain.md, packages/form/src/components/SelectableCardField/__tests__/__snapshots__/index.spec.tsx.snap, packages/ui/src/components/SelectableCard/__stories__/Examples.stories.tsx, packages/ui/src/components/SelectableCard/__stories__/ShowTick.stories.tsx, packages/ui/src/components/SelectableCard/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/SelectableCard/index.tsx, packages/ui/src/components/SwitchButton/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/SwitchButton/__tests__/index.test.tsx, packages/ui/src/components/SwitchButton/index.tsx
- Bug
The `SelectableCard` is a complex component that uses both a `Checkbox` and `Radio` behind the hood. Both of those input are wrapped into a `Card` that is clickable and changes the value of the input.
The issue here is that when you click on the label or the checkbox, it bubble up the change event to the parent container triggering 2 changes. To avoid this I added a `pointer-event: none;` on both the checkbox and radio inside `SelectablecCard`. 
This way we ensure that when you click on the `Card` it's the `SelectableCard` that changes the state.
Before:
https://github.com/scaleway/ultraviolet/assets/15812968/78aee77f-dfc5-4851-9e64-9865104ab8a2
After:
https://github.com/scaleway/ultraviolet/assets/15812968/e5c2d5bc-38dc-4c61-8fac-691002f6a5d3
=> fix(SelectableCard): type checkbox to work properly when clicking on both card and checkbox

.changeset/chilly-cobras-bathe.md, .changeset/curvy-kiwis-turn.md, .changeset/purple-ads-jam.md, packages/form/src/components/TextInputField/__tests__/__snapshots__/index.spec.tsx.snap, packages/plus/src/components/EstimateCost/Components/Unit.tsx, packages/plus/src/components/EstimateCost/__stories__/Unit.stories.tsx, packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Unit.spec.tsx.snap, packages/ui/src/components/DateInput/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/TextInput/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/TextInput/index.tsx
- Bug
Current `<TextInput />` has an issue when we have too long unit lenght. The padding inside the input follows the size of the elements on the right it includes the unit length. So far we were just checking how many element there was on the right without counting the number of character in unit creating overflow issue as you can see on screenshots. 
It has been solve to take in account the unit size. It also fixe `<EstimateCost.Unit />` and I increased slightly the size of the unit.
| TextInput  | <img width="1056" alt="Screenshot 2023-12-20 at 11 15 24" src="https://github.com/scaleway/ultraviolet/assets/15812968/e2378ffb-17e6-48ec-a3cd-ed7883fce84e"> | <img width="1061" alt="Screenshot 2023-12-20 at 11 15 17" …
=> fix(TextInput): input padding to follow unit length

.changeset/silent-ladybugs-provide.md, packages/plus/src/components/EstimateCost/Components/UnitInput.tsx, packages/plus/src/components/EstimateCost/__tests__/CustomUnitInput.spec.tsx, packages/plus/src/components/EstimateCost/__tests__/helper.spec.ts, packages/plus/src/components/EstimateCost/helper.ts
- Bug
UnitInput in EstimateCost is kinda buggy. We cannot remove completly the value set inside, this is because we always set the change if the value exists. When you remove all the value is empty and so the onChange is not triggered. I fixed it by using onBlur and set min / max value when use gets out of the input.
Before
https://github.com/scaleway/ultraviolet/assets/15812968/0c18e414-9160-486b-b9a8-9b953dea7782
After
https://github.com/scaleway/ultraviolet/assets/15812968/842d1021-c6ea-4400-b269-2f1ba588a6dc
=> fix(EstimateCost): unit input to be clearable in time amount

.changeset/brown-otters-repair.md, packages/ui/src/components/Banner/__tests__/__snapshots__/index.tsx.snap, packages/ui/src/components/Banner/index.tsx
- Bug
There is an issue with banner and the default image, it seems not to be displayed correctly. This is because now svg files are considered as React Component and should be used like that.
| Banner  | <img width="1041" alt="Screenshot 2024-01-09 at 10 01 51" src="https://github.com/scaleway/ultraviolet/assets/15812968/e7e3458b-2605-42c0-bd70-53e1ff87c869"> | <img width="1019" alt="Screenshot 2024-01-09 at 10 01 59" src="https://github.com/scaleway/ultraviolet/assets/15812968/a60ad3cb-3188-4e0c-8613-91dee9b3cde6"> |
=> fix(Banner): default illustration to be correctly imported

.changeset/cuddly-hotels-ring.md, packages/form/src/components/TextInputField/__tests__/index.spec.tsx, packages/form/src/components/TextInputFieldV2/__tests__/index.spec.tsx, packages/ui/src/components/NumberInput/index.tsx, packages/ui/src/components/TextInput/index.tsx, packages/ui/src/components/TextInputV2/index.tsx
- Bug
When an input is controlled, the `value` should be not empty or `''`
=> fix: input value for controlled fields

packages/ui/README.md
Readme was not fully up to date with the new fonts, I fixed it.
=> docs: fix readme to include space grotesk fonts

packages/form/src/components/NumberInputFieldV2/__stories__/index.stories.tsx, packages/form/src/components/TextInputFieldV2/__stories__/index.stories.tsx, packages/ui/src/components/Breadcrumbs/__stories__/To.stories.tsx
- Fix documentation of `NumberInputV2` and `TextInputV2` to have all props in form in a snippet
- Fix breadcrumbs to remove legacy documentation that is not true anymore
| TextInput  | ![Screenshot 2024-01-15 at 17 03 43](https://github.com/scaleway/ultraviolet/assets/15812968/ce2fc32f-4b80-45b1-9375-4a64f60f50f3) | ![Screenshot 2024-01-15 at 17 03 46](https://github.com/scaleway/ultraviolet/assets/15812968/da1dc775-69dc-4d1e-9335-53411274e922) |
| NumberInput  | ![Screenshot 2024-01-15 at 17 21 18](https://github.com/scaleway/ultraviolet/assets/15812968/a548ff5b-90ce-40ad-b143-92bb60c94fc0) | ![Screenshot 2024-01-15 at 17 21 21](https://github.com/scaleway/ultraviolet/assets/15812968/b10de6b4-b1f2-4ad8-8 …
=> docs: fix number and text input fields v2 to have better documentation

.changeset/quick-panthers-punch.md, packages/form/src/components/NumberInputFieldV2/__tests__/__snapshots__/index.spec.tsx.snap, packages/form/src/components/TextAreaField/__tests__/__snapshots__/index.spec.tsx.snap, packages/form/src/components/TextInputFieldV2/__tests__/__snapshots__/index.spec.tsx.snap, packages/ui/src/components/NumberInputV2/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/NumberInputV2/index.tsx, packages/ui/src/components/TextArea/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/TextArea/index.tsx, packages/ui/src/components/TextInputV2/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/TextInputV2/index.tsx
- Enhancement
The old labels of input use to have bodyStrong, in order to avoid having different labels size and style during the migration we decided to set the same to V2 components:`NumberInputV2`, `TextInputV2` and `TextArea` 
| url  | ![Screenshot 2024-01-19 at 16 38 17](https://github.com/scaleway/ultraviolet/assets/15812968/dccc70c9-884a-46ce-9dae-e88d05ab8f28) | ![Screenshot 2024-01-19 at 16 38 20](https://github.com/scaleway/ultraviolet/assets/15812968/bf8c2334-e419-4fbf-be1f-0a53840aa45f) |
=> fix: v2 inputs to have body strong variant

.changeset/fluffy-rules-talk.md, packages/form/src/index.ts
- Refactor
Export `NumberInputV2` and `TextInputV2`
=> fix: export number input and text input v2

.changeset/grumpy-phones-own.md, packages/ui/src/components/CheckboxGroup/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/CheckboxGroup/index.tsx, packages/ui/src/components/RadioGroup/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/RadioGroup/index.tsx
- Bug
Fix `CheckboxGroup` and `RadioGroup` to have the correct helper size, font and color.
| RadioGroup  | <img width="168" alt="Screenshot 2024-01-23 at 16 17 07" src="https://github.com/scaleway/ultraviolet/assets/15812968/c5f1f960-2a22-4905-9f45-b8a39ab45611"> | <img width="164" alt="Screenshot 2024-01-23 at 16 17 12" src="https://github.com/scaleway/ultraviolet/assets/15812968/9f7a32d6-1999-440c-800f-5af3f87c5281"> |
| CheckboxGroup  | <img width="387" alt="Screenshot 2024-01-23 at 16 18 01" src="https://github.com/scaleway/ultraviolet/assets/15812968/b1416deb-faee-4450-9318-42c6a2941a06"> | <img width="368" alt="Screenshot 2024-01-23 at 16 18 06" src="https://github.com/scaleway/ultraviolet/assets/15812968/72068cf2 …
=> fix: radio group and checkbox group to have the correct style

.changeset/chatty-snakes-vanish.md, packages/ui/src/components/MenuV2/index.tsx
- Bug
MenuV2 misses the spread of onClick from disclosure when you want to add some custom actions.
=> fix(MenuV2): to spread onclick of the disclosure

.changeset/long-parents-bathe.md, packages/themes/src/themes/console/dark.ts, packages/themes/src/themes/console/darker.ts, packages/themes/src/themes/console/deprecated/dark.ts, packages/themes/src/themes/console/deprecated/darker.ts, packages/themes/src/themes/console/deprecated/light.ts, packages/themes/src/themes/console/light.ts, packages/ui/src/components/Banner/index.tsx, packages/ui/src/components/GlobalAlert/index.tsx
- Enhancement
Gradients have been updated, the structure and access to it had been improved. Here is what changed:
- Previously you were accessing to this token: `color.other.gradient.background.fuschia` and now you can access it like this: `color.other.gradient.background.linear.fuschia`. The same applies to all other gradients. 
Keep in mind that for now the old way still works as this update is NOT breaking change but it will be removed in the future.
- New gradient have been added and are accessible via `color.other.gradient.background.radial`.
=> feat(themes): update gradient structure and new radial gradients

.changeset/khaki-cows-flash.md, packages/plus/src/components/EstimateCost/Components/CustomUnitInput.tsx, packages/plus/src/components/EstimateCost/Components/UnitInput.tsx, packages/plus/src/components/EstimateCost/__tests__/__snapshots__/CustomUnitInput.spec.tsx.snap, packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Item.spec.tsx.snap, packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Region.spec.tsx.snap, packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Regular.spec.tsx.snap, packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Stepper.spec.tsx.snap, packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Strong.spec.tsx.snap, packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Unit.spec.tsx.snap, packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Zone.spec.tsx.snap, packages/plus/src/components/EstimateCost/__tests__/__snapshots__/index.spec.tsx.snap
- Bug
Fix `<EstimateCost />` time unit spacing on firefox that was too small for unit part.
| |   Before   |      After |
|  | ![Screenshot 2024-01-22 at 17 08 32](https://github.com/scaleway/ultraviolet/assets/15812968/c32bf495-1ba6-4c86-a16a-e2ed747aed0f) | ![Screenshot 2024-01-22 at 17 08 32](https://github.com/scaleway/ultraviolet/assets/15812968/5eb72ba8-7527-4b1f-b5a3-cdb6e473635a) |
|  | ![Screenshot 2024-01-22 at 17 12 16](https://github.com/scaleway/ultraviolet/assets/15812968/3a8e9a03-3c95-4bbf-ab16-610204bd9572) | ![Screenshot 2024-01-22 at 17 12 35](https://github.com/scaleway/ultraviolet/assets/15812968/40cc7cdb-385e-4836-aabc-82961865b18a) |
=> fix(EstimateCost): time unit spacing to be auto for fixing firefox

.changeset/brave-guests-brake.md, packages/ui/package.json, packages/ui/src/components/Toaster/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/Toaster/index.tsx, pnpm-lock.yaml
- Bug
Toaster is not working properly since the last major update, the close button doesn't work. I fixed it by defining a default positioning but also by changing the class properties in custom style as they changed. I also updated react-toastify to the last patched version.
Before:
https://github.com/scaleway/ultraviolet/assets/15812968/3ecb5325-3596-4575-8ae0-91e17e5e03fc
After:
https://github.com/scaleway/ultraviolet/assets/15812968/649ea24d-83ba-4949-a616-f059896545b5
=> fix(Toaster): breaking change since last major

.changeset/large-trains-speak.md, packages/ui/src/components/Breadcrumbs/__tests__/__snapshots__/index.tsx.snap, packages/ui/src/components/Breadcrumbs/index.tsx
- Bug
In some cases breacrumbs children are miss aligned vertically to avoid it I added `align-items: center;` on the parent.
=> fix(Breadcrumbs): to be vertically center aligned

.changeset/wild-carrots-deliver.md, packages/form/src/components/TextInputField/__tests__/__snapshots__/index.spec.tsx.snap, packages/ui/src/components/TextInput/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/TextInput/index.tsx
- Bug
Fix `<TextInput />` component to spread required in the DOM
=> fix(TextInput): to spread required prop to the dom

.changeset/loud-spies-brake.md, .storybook/preview.tsx, packages/form/src/components/CheckboxField/__tests__/__snapshots__/index.spec.tsx.snap, packages/ui/src/components/Checkbox/__tests__/__snapshots__/index.tsx.snap, packages/ui/src/components/Checkbox/index.tsx, packages/ui/src/components/Radio/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/Radio/index.tsx, packages/ui/src/components/SelectableCard/__tests__/__snapshots__/index.test.tsx.snap
- Bug
Helper / error and success should always be caption variant and helper should always be weak prominence. Also there was some margin missing on radio story due to global style applied on all stories.
| url  | ![Screenshot 2024-02-05 at 15 48 57](https://github.com/scaleway/ultraviolet/assets/15812968/6d86e65f-5e75-4b44-bcb0-8c1053c181bc) | ![Screenshot 2024-02-05 at 15 49 00](https://github.com/scaleway/ultraviolet/assets/15812968/dbce5b26-c998-4ed4-b985-b74d8baad43c) |
| url  | ![Screenshot 2024-02-05 at 15 49 34](https://github.com/scaleway/ultraviolet/assets/15812968/3f419769-ca4d-4ac4-8f71-e9a4ba597900) | ![Screenshot 2024-02-05 at 15 50 32](https://github.com/scaleway/ultraviolet/assets/15812968/93d086a7-c4bb-4 …
=> fix: radio and checkbox to have correct sentiment and variant

.changeset/stupid-shoes-report.md, packages/ui/src/components/MenuV2/Item.tsx, packages/ui/src/components/MenuV2/__stories__/Sentiments.stories.tsx, packages/ui/src/components/MenuV2/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/Tabs/__tests__/__snapshots__/index.test.tsx.snap
- Bug
On MenuV2.Item if you set a tooltip the structure can be visually broken. I fixed it by adding a `div` wrapper around the tooltip so it inherit the correct display.
| url  | <img width="130" alt="Screenshot 2024-02-01 at 16 14 53" src="https://github.com/scaleway/ultraviolet/assets/15812968/596bb578-2b29-4ca0-bad2-ba571fa325c2"> | <img width="130" alt="Screenshot 2024-02-01 at 16 15 08" src="https://github.com/scaleway/ultraviolet/assets/15812968/dabbd50e-bd16-4440-92a6-f67b558656cc"> |
=> fix(MenuV2): fix tooltip on menu item

.changeset/eighty-rockets-explode.md, packages/ui/src/__stories__/migrations/MigrationTextInputV2.stories.mdx, packages/ui/src/components/DateInput/index.tsx, packages/ui/src/components/NumberInputV2/index.tsx, packages/ui/src/components/TextInputV2/__stories__/Template.stories.tsx, packages/ui/src/components/TextInputV2/index.tsx
- Enhancement
- Fix `TextInputV2` to implement more props and remove `iconName`
- Add documentation to migrate `TextInput` to `TextInputV2`
=> fix(TextInputV2): remove some props and add some others

.changeset/odd-dancers-study.md, packages/form/src/index.ts
- Bug
`TextAreaField` is missing form exports because we forgot to do it, to avoid this mistake I exported all components.
=> fix(form): export all components

.changeset/popular-chairs-laugh.md, packages/form/src/components/SelectInputField/index.tsx
- Bug
Fix `<SelectInputField />` component to have `emptyState` prop instead of `noOptionsMessage`
=> fix(SelectInput): to have prop empty state

.changeset/friendly-clouds-approve.md, packages/plus/src/components/EstimateCost/OverlayComponent.tsx, packages/plus/src/components/EstimateCost/__tests__/__snapshots__/index.spec.tsx.snap
- Bug
Discount value was'nt showing in overlay
1.
2.
3.
=> fix(estimatecost): missing discount value

.changeset/real-spoons-cough.md, packages/form/src/components/TextInputFieldV2/index.tsx
- Bug
The prop "type" in `TextInputField` is now working.
When choosing a type for an text input field, it can be a password (with the style of a TextInputV2 field), email, url or text. 
1. Edit the component (add type)
=> fix(TextInputFieldV2): fix type prop

.changeset/three-suits-nail.md, packages/plus/src/components/ContentCard/index.tsx
- Bug
Component should have link role instead of button when href is provided with onClick.
1. Edit the component
2.
3.
=> fix(ContentCard): fix role when onClick and href is provided

.changeset/purple-ducks-impress.md, packages/ui/src/components/Breadcrumbs/__stories__/Template.tsx, packages/ui/src/components/Breadcrumbs/__tests__/__snapshots__/index.tsx.snap, packages/ui/src/components/Breadcrumbs/index.tsx
Add a flex-wrap to the breadcrumb `ol`
- Bug
on mobile device, the breadcrumb should be wrapped gracefully
| Page | Before | After |
| :--- | :-----:| -----:|
| [url](https://storybook.ultraviolet.scaleway.com/?path=/docs/components-navigation-breadcrumbs--docs) | ![Capture d’écran 2024-02-14 à 16 52 25](https://github.com/scaleway/ultraviolet/assets/25226974/3881f713-9406-4f0f-9e4f-25ac02a35b6b) | ![Capture d’écran 2024-02-14 à 16 54 00](https://github.com/scaleway/ultraviolet/assets/25226974/40d9b2d1-37fa-4479-b622-567162197eb4) |
=> fix: add flex-wrap to breadcrumb list

.changeset/cyan-rocks-hug.md, packages/form/src/components/NumberInputField/__stories__/index.stories.tsx, packages/form/src/components/NumberInputField/index.tsx, packages/form/src/components/RadioField/__stories__/index.stories.tsx, packages/form/src/components/RadioField/index.tsx, packages/form/src/components/RadioGroupField/__stories__/Required.stories.tsx, packages/form/src/components/RadioGroupField/__stories__/Template.stories.tsx, packages/form/src/components/RadioGroupField/__stories__/index.stories.tsx, packages/form/src/components/RadioGroupField/__tests__/__snapshots__/index.spec.tsx.snap, packages/form/src/components/TextInputField/__stories__/index.stories.tsx, packages/form/src/components/TextInputField/index.tsx, packages/ui/src/components/NumberInput/__stories__/index.stories.tsx, packages/ui/src/components/NumberInput/index.tsx, packages/ui/src/components/RadioGroup/__stories__/Controlled.stories.tsx, packages/ui/src/components/RadioGroup/__stories__/Template.stories.tsx, packages/ui/src/components/RadioGroup/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/RadioGroup/index.tsx, packages/ui/src/components/TextInput/__stories__/index.stories.tsx
- Enhancement
- `RadioGroup.Radio` use to have the name as required while we don't need it, it's his parent `RadioGroup` who will spread the name among it's children. This only works because in a context of a radio we only need one value and so one key associated with it.
- Mark as deprecated `TextInput`, `TextInputField`, `NumberInput`, `NumberInputField` and `RadioField`
=> fix(RadioGroup): children radio name optional as parent spread it

.changeset/dull-cougars-appear.md, .changeset/dull-cougars-disappear.md, packages/icons/src/components/ProductIcon/__stories__/Disabled.stories.tsx, packages/icons/src/components/ProductIcon/__stories__/Playground.stories.tsx, packages/icons/src/components/ProductIcon/__stories__/Variants.stories.tsx, packages/icons/src/components/ProductIcon/__stories__/index.stories.tsx, packages/icons/src/components/ProductIcon/index.tsx, packages/themes/src/themes/console/dark.ts, packages/themes/src/themes/console/darker.ts, packages/themes/src/themes/console/light.ts
- Feature
- New token `theme.colors.other.icon.product.original`, it contains all colors for the new product icon variant `original`.
- New `<ProductIcon />` variant available: `original`
=> feat(ProductIcon): new product icon variant original

.changeset/lemon-cooks-press.md, packages/form/src/components/TextInputFieldV2/index.tsx
- Bug
Add missing `loading` prop in `TextInputFieldV2`.
=> fix(TextInputFieldV2): add missing loading prop

.changeset/strange-doors-study.md, packages/form/src/components/DateField/__tests__/__snapshots__/index.tsx.snap, packages/form/src/components/NumberInputFieldV2/__tests__/__snapshots__/index.spec.tsx.snap, packages/form/src/components/TagInputField/__tests__/__snapshots__/index.spec.tsx.snap, packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Stepper.spec.tsx.snap, packages/ui/src/components/NumberInputV2/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/NumberInputV2/index.tsx, packages/ui/src/components/TagInput/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/TagInput/index.tsx, packages/ui/src/components/TextArea/index.tsx, packages/ui/src/components/TextInputV2/__stories__/Template.stories.tsx, packages/ui/src/components/TextInputV2/__stories__/index.stories.tsx, packages/ui/src/components/TextInputV2/index.tsx
- Bug
The new inputs had an issue, when setting required and label it was leaving the required icon on to of it, I fixed it.
| url  | <img width="962" alt="Screenshot 2024-02-21 at 15 06 35" src="https://github.com/scaleway/ultraviolet/assets/15812968/1d8b8ae2-0448-4144-a9b6-5cfc9b25296d"> | <img width="966" alt="Screenshot 2024-02-21 at 15 06 45" src="https://github.com/scaleway/ultraviolet/assets/15812968/18f5aa96-c5f3-4109-994c-e700e34b6d18"> |
| url  | <img width="960" alt="Screenshot 2024-02-21 at 15 07 23" src="https://github.com/scaleway/ultraviolet/assets/15812968/0b841b5a-e813-4f4c-85fd-e742b184b13c"> | <img width="968" alt="Screenshot 2024-02-21 at 15 07 33" …
=> fix(inputs): multiple inputs issue with required icon and no label

.changeset/gorgeous-insects-build.md, packages/form/src/components/SelectableCardField/__tests__/__snapshots__/index.spec.tsx.snap, packages/ui/src/components/SelectableCard/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/SelectableCard/index.tsx, packages/ui/src/components/SwitchButton/__tests__/__snapshots__/index.test.tsx.snap
- Feature
Selectable card now include indentation on children and a spacing between label and children to give clarity. This is a common pattern we were already using but that wasn't implemented natively in the component.
| url  | <img width="964" alt="Screenshot 2024-02-26 at 11 07 43" src="https://github.com/scaleway/ultraviolet/assets/15812968/b1d49874-2d92-4e74-82bd-04ae339be6df"> | <img width="962" alt="Screenshot 2024-02-26 at 11 07 49" src="https://github.com/scaleway/ultraviolet/assets/15812968/8eed56d4-076e-40e8-9dc7-6e9d53afec72"> |
=> feat(SelectableCard): native indentation for children and spacing with label

.changeset/seven-mangos-end.md, .changeset/tiny-geckos-happen.md, packages/form/src/components/TextInputFieldV2/index.tsx, packages/ui/src/components/DateInput/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/TextInputV2/index.tsx
- Bug
- Add prop `autoComplete` on `<TextInputV2 />` component
- Fix `<TextInputV2Field />` to add missing props : `prefix`, `suffix`, `size`, `onRandomize`, `aria-label`, `aria-labelledby`, `autoComplete`.
=> fix(TextInputV2): add auto complete and missing props

.changeset/olive-readers-chew.md, packages/ui/src/components/MenuV2/Item.tsx, packages/ui/src/components/MenuV2/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/Tabs/__tests__/__snapshots__/index.test.tsx.snap
- Bug
Now the border of elements in MenuV2 will always be full width.
| :--: | :--------: | :--------: |
| example  | <img width="257" alt="Capture d’écran 2024-03-07 à 15 15 29" src="https://github.com/scaleway/ultraviolet/assets/106706307/b1eed8db-3de6-4a6e-97bb-668251c6d19c"> | <img width="243" alt="Capture d’écran 2024-03-07 à 15 15 15" src="https://github.com/scaleway/ultraviolet/assets/106706307/7efce094-589d-42e7-a46e-ffa17e626850">|
=> fix(MenuV2.Item): item full width

.changeset/tender-cats-mix.md, packages/ui/src/components/Notification/__stories__/ContainerId.tsx, packages/ui/src/components/Notification/__stories__/index.stories.tsx, packages/ui/src/components/Notification/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/Notification/__tests__/index.test.tsx, packages/ui/src/components/Notification/index.tsx, packages/ui/src/components/Toaster/__stories__/ContainerId.tsx, packages/ui/src/components/Toaster/__stories__/index.stories.tsx, packages/ui/src/components/Toaster/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/Toaster/__tests__/index.test.tsx, packages/ui/src/components/Toaster/index.tsx
- Enhancement
Added a prop `containerId` to toaster and notification components to be able to use multiple Containers simultaneously. 
1. new prop to `NotificationContainer`, `notification`, `ToastContainer`and `toast` 
2. Stories to showcase the prop
=> fix: add container id to toaster and notification

.changeset/clean-guests-stare.md, packages/plus/src/components/EstimateCost/Components/Region.tsx
`hideFromOverlay` is not forward from `EstimateCost.Region` to the `EstimateCost.Item` base component
- Enhancement
=> fix(EstimateCost): forward hideFromOverlay in Region

.changeset/stale-cooks-boil.md, packages/plus/src/components/EstimateCost/OverlayComponent.tsx, packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Item.spec.tsx.snap, packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Region.spec.tsx.snap, packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Regular.spec.tsx.snap, packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Stepper.spec.tsx.snap, packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Strong.spec.tsx.snap, packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Unit.spec.tsx.snap, packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Zone.spec.tsx.snap, packages/plus/src/components/EstimateCost/__tests__/__snapshots__/index.spec.tsx.snap
=> fix(estimate-cost): remove z-index from Overlay

.changeset/old-kangaroos-shake.md, packages/ui/src/components/List/Row.tsx, packages/ui/src/components/List/__stories__/Example.stories.tsx, packages/ui/src/components/List/__stories__/ExpandButton.stories.tsx, packages/ui/src/components/List/__stories__/Expandable.stories.tsx, packages/ui/src/components/List/__stories__/ExpandableAutocollapse.stories.tsx, packages/ui/src/components/List/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/List/constants.tsx, packages/ui/src/components/List/index.tsx, packages/ui/src/components/Table/Row.tsx
- Enhancement
- Row expandable content has a background
- props `expandButton` has been renamed `expandable`
- Adding a dedicated column (and CTA) to expand/collapse a row with expandable content now replace row click behavior (it's not an addition anymore)
- Select checkbox is now always visible, even if none is selected
=> fix(List): update expandable behavior

.changeset/brave-bats-join.md, packages/form/src/components/NumberInputFieldV2/__stories__/Required.stories.tsx, packages/form/src/components/NumberInputFieldV2/index.tsx, packages/plus/src/components/EstimateCost/Components/NumberInput.tsx, packages/ui/src/components/NumberInputV2/__stories__/MinMax.stories.tsx, packages/ui/src/components/NumberInputV2/index.tsx
- Enhancement
- **NumberInputV2/NumberInputV2Field** : Allow empty value (will return null as value)
- **NumberInputV2Field** : forward `required` prop to `NumberInputV2`
=> fix(NumberInputV2): empty value behavior

.changeset/strange-cars-retire.md, packages/ui/src/components/SelectableCardGroup/index.tsx
- Bug
Fix `<SelectableCardGroup />` to hide required icon when there is no legend set
Before:
After:
=> fix(SelectableCardGroup): to hide required icon when there is no legend

.changeset/tiny-cows-smile.md, packages/form/src/components/KeyValueField/__stories__/Environnement.stories.tsx, packages/form/src/components/KeyValueField/__stories__/Playground.stories.tsx, packages/form/src/components/KeyValueField/__tests__/__snapshots__/index.spec.tsx.snap, packages/form/src/components/KeyValueField/index.tsx
- Refactor
Refactor `<KeyValueField />` component to have correct spacing and use `<TextInputFieldV2 />`
Before:
After:
=> refactor(KeyValueField): new spacing and text input v2 usage

.changeset/five-rats-unite.md, .changeset/late-books-shop.md, packages/icons/src/components/CategoryIcon/__stories__/List.stories.tsx, packages/icons/src/components/CategoryIcon/index.tsx, packages/plus/src/components/Navigation/__stories__/Playground.stories.tsx, packages/plus/src/components/Navigation/components/Item.tsx, packages/themes/src/themes/console/dark.ts, packages/themes/src/themes/console/darker.ts, packages/themes/src/themes/console/light.ts
- Feature
- New prop `categoryIconVariant` in `<Navigation />`
- New `neutral` and `disabled` states on `<CategoryIcon />` component
=> feat(CategoryIcon): new state disabled and variant primary

.changeset/short-toes-relax.md, packages/plus/src/components/Navigation/components/Item.tsx
- Bug
Fix `<Navigation />` to have correct text color on hover
Before:
After:
=> fix(Navigation): correct color on hover for weak text

.changeset/honest-moles-notice.md, packages/ui/src/components/Stepper/index.tsx
- Bug
Fix `<Stepper />` component to clean null or undefined children before rendering
Not working example that now works:
```ts
<Stepper selected={0} labelPosition="right" size="small">
{null}
<Text as="span" variant="bodySmall">
test2
</Text>
<Text as="span" variant="bodySmall">
test3
</Text>
</Stepper>
```
Before:
After:
=> fix(Stepper): clean null or undefined children before render

.changeset/tricky-beans-compare.md, packages/plus/src/components/Navigation/components/Item.tsx
- Bug
Fix `<Navigation />` category icon variant on collapsed version
Before:
After:
=> fix(Navigation): category icon variant on collasped version

.changeset/lazy-squids-press.md, packages/ui/src/components/Popup/index.tsx
- Bug
Fix Popup to correctly set portalTarget, if the role is something else than dialog.
=> fix(Popup): to correctly set portal taget prop

.changeset/tall-seahorses-grow.md, packages/plus/src/components/Navigation/components/Item.tsx
- Bug
Text in `Navigation.Item` should be textDefault and not textWeak
=> fix: change navitem text color

.changeset/dry-icons-punch.md, packages/ui/src/components/MenuV2/index.tsx
- Enhancement
Current menuv2 has a debounce delay of 350ms, we changed it to be 250ms so the menu will appear faster on hover.
=> fix(Menu): to have smaller debounce delay

.changeset/nice-rules-collect.md, packages/form/src/components/SelectableCardGroupField/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/SelectableCardGroup/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/SelectableCardGroup/index.tsx
- Bug
Inside a `SelectableCardGroup` if a `SelectableCard` have a `label` or a `content`  (children),  it kind of overflows the space allocated by the `Row`
| Component |   Before   |      After |
| SelectableCardGroup  |
=> fix(SelectableCardGroup): force item to follow grid

.changeset/strange-years-fly.md, packages/form/src/components/SelectInputFieldV2/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/MenuV2/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/MenuV2/index.tsx, packages/ui/src/components/Popover/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/Popover/index.tsx, packages/ui/src/components/Popup/helpers.ts, packages/ui/src/components/Popup/index.tsx, packages/ui/src/components/SelectInputV2/SearchBarDropdown.tsx, packages/ui/src/components/SelectInputV2/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/Tabs/__tests__/__snapshots__/index.test.tsx.snap
- Enhancement
- Fix `<Popup />` component to set initial position to 0 avoiding scroll on top when appearing and if an input has `autoFocus` inside
- New prop `dynamicDomRendering` to define if the popup will be rendered dynamically in the DOM or if it should be rendered at first render. Default is `true` to keep the current retro compatibility.
- Fix `<SelectInputV2 />` to remove timeout on search bar focus
=> fix(Popup): new prop and improve initial positioning of the popup

.changeset/neat-badgers-juggle.md, packages/plus/src/components/Navigation/NavigationProvider.tsx, packages/plus/src/components/Navigation/__stories__/Playground.stories.tsx, packages/plus/src/components/Navigation/components/Group.tsx, packages/plus/src/components/Navigation/components/Item.tsx, packages/plus/src/components/Navigation/components/PinnedItems.tsx, packages/plus/src/components/Navigation/constants.ts, packages/plus/src/components/Navigation/locales/en.ts
- Enhancement
Navigation is nice for traveling around in your website but it lacked some customization. Pinned feature is here to overcome this issue and provide a new way to customize your navigation. This feature can be enabled adding `pinnedFeature` on your `<NavigationProvider />`
Pinned feature allows you to pin / unpin your favorite items until it reach the limit you've set using `pinLimit` on your `<NavigationProvider />`.
It also allows you to re-order your pinned items by using drag n drop and placing it in the order you like.
All your pinned items can be accessed with the hook `useNavigation()`:
```tsx
// pinnedItems = ['myitem1', 'myitem2']
const { pinnedItems } = useNavigation()
// Save in local storage to keep the pinned items on refresh
useEffect(() => { …
```
=> feat(Navigation): new pinned feature and reorder

.changeset/silly-chairs-do.md, packages/plus/src/components/EstimateCost/EstimateCost.tsx, packages/plus/src/components/EstimateCost/EstimateCostContent.tsx, packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Regular.test.tsx.snap, packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Stepper.test.tsx.snap, packages/plus/src/components/EstimateCost/__tests__/__snapshots__/index.test.tsx.snap, packages/plus/src/components/EstimateCost/types.ts
- Enhancement
Add `onTotalPriceChange` prop on `<EstimateCost />` this function will provide `total` and `totalMax when the total price is re-computed allowing users to get that value.`
```tsx
<EstimateCost {...} onTotalPriceChange={({ total, totalMax}) => {
console.log(total, totalMax)
}}>
...
</EstimateCost>
```
You will notice that `total` defines the total price and `totalMax` defines the maximum price when there is a range. 
For example if estimate cost shows a total of 100€-200€
- `total = 100` where `100` is a type `number`
- `totalMax = 200` where `200` is a type `number`
=> feat(EstimateCost): add on total price change providing total and total max

.changeset/cuddly-planes-exercise.md, packages/form/src/components/DateField/__tests__/__snapshots__/index.test.tsx.snap, packages/form/src/components/DateField/index.tsx, packages/form/src/components/NumberInputFieldV2/__tests__/__snapshots__/index.test.tsx.snap, packages/form/src/components/TagInputField/__tests__/__snapshots__/index.test.tsx.snap, packages/form/src/components/TextInputFieldV2/__tests__/__snapshots__/index.test.tsx.snap, packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Stepper.test.tsx.snap, packages/ui/src/components/DateInput/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/NumberInputV2/__stories__/Sizes.stories.tsx, packages/ui/src/components/NumberInputV2/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/NumberInputV2/index.tsx, packages/ui/src/components/SelectInputV2/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/SelectInputV2/__tests__/index.test.tsx, packages/ui/src/components/TagInput/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/TagInput/index.tsx, packages/ui/src/components/TextInputV2/__stories__/Size.stories.tsx, packages/ui/src/components/TextInputV2/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/TextInputV2/index.tsx
- Refactor
Font-size changes for small and medium inputs : 14px instead of 16px
1. Changed font-size front "body" to "bodySmall" for inputs & their label when size="medium" or "small"
| Page |   TextInputV2  |
| :--- | :--------: 
| Before | <img width="1228" alt="Capture d’écran 2024-05-14 à 12 02 08" src="https://github.com/scaleway/ultraviolet/assets/106706307/056a8508-888d-4bad-9a95-513062527d83"> | 
| After | <img width="890" alt="Capture d’écran 2024-05-14 à 12 01 39" src="https://github.com/scaleway/ultraviolet/assets/106706307/f6f16fb3-a5ba-483c-874e-d0afa8de0163"> |
=> fix: font size on inputs

.changeset/healthy-squids-sin.md, packages/plus/src/components/Navigation/NavigationContent.tsx, packages/plus/src/components/Navigation/NavigationProvider.tsx, packages/plus/src/components/Navigation/components/PinnedItems.tsx
- Enhancement
New prop `initialAllowNavigationResize` on `<NavigationProvider />` and serving `allowNavigationResize` and `setAllowNavigationResize` through `useNavigation()`
without changing any props (can resize):
using `initialAllowNavigationResize={false}` (cannot resize):
Also small fix, before:
After:
=> fix(Navigation): add functionality to disable expand

.storybook/preview.tsx, packages/form/src/components/CheckboxField/__stories__/index.stories.tsx, packages/form/src/components/CheckboxGroupField/__stories__/index.stories.tsx, packages/form/src/components/DateField/__stories__/index.stories.tsx, packages/form/src/components/KeyValueField/__stories__/index.stories.tsx, packages/form/src/components/NumberInputField/__stories__/index.stories.tsx, packages/form/src/components/NumberInputFieldV2/__stories__/index.stories.tsx, packages/form/src/components/RadioField/__stories__/index.stories.tsx, packages/form/src/components/RadioGroupField/__stories__/index.stories.tsx, packages/form/src/components/SelectInputField/__stories__/index.stories.tsx, packages/form/src/components/SelectableCardField/__stories__/index.stories.tsx, packages/form/src/components/SelectableCardGroupField/__stories__/index.stories.tsx, packages/form/src/components/TagInputField/__stories__/index.stories.tsx, packages/form/src/components/TextAreaField/__stories__/index.stories.tsx, packages/form/src/components/TextInputField/__stories__/index.stories.tsx, packages/form/src/components/TextInputFieldV2/__stories__/index.stories.tsx, packages/form/src/components/TimeField/__stories__/index.stories.tsx, packages/form/src/components/ToggleField/__stories__/index.stories.tsx, packages/form/src/components/ToggleGroupField/__stories__/index.stories.tsx, packages/ui/src/components/PieChart/__stories__/index.stories.tsx, packages/ui/src/components/Popover/__stories__/index.stories.tsx, packages/ui/src/components/Skeleton/__stories__/index.stories.tsx
- Bug
There is an issue since storybook v8 with some stories (especially form ones) with the following error:
> [!CAUTION]
> Storybook preview hooks can only be called inside decorators and story functions.
It seems like this comes from `@storybook/addon-themes` plugins, an issue is open about it here: https://github.com/storybookjs/storybook/issues/24625
To fix this adding an empty tag around general decorator seems to work and remove the error.
=> docs(storybook): fix broken stories on form

.changeset/tender-walls-relate.md, packages/ui/src/components/SelectInput/index.tsx
- Bug
Fix `<SelectInput />` description and inline description spacings
| url  | <img width="973" alt="Screenshot 2024-05-21 at 17 45 36" src="https://github.com/scaleway/ultraviolet/assets/15812968/965c3f00-0361-4def-845c-30e7eac4cc8c"> | <img width="979" alt="Screenshot 2024-05-21 at 17 49 22" src="https://github.com/scaleway/ultraviolet/assets/15812968/724888b3-80b7-4a97-bbed-329b51cf0794"> |
=> fix(SelectInput): description and inline description spacing

.changeset/thin-maps-drum.md, packages/ui/src/components/SelectInputV2/SearchBarDropdown.tsx, packages/ui/src/components/SelectInputV2/__tests__/__snapshots__/index.test.tsx.snap
- Bug
There is still some issues with `SelectInputV2` and the searchbar having `autoFocus` onto it. When opening the select input it scroll on top of the page. To fix that we temporarily added a `setTimeout` that will focus when search bar appear, replacing `autoFocus` behavior.
=> fix(SelectInputV2): auto focus on search bar

.changeset/forty-pumpkins-wink.md, packages/plus/src/components/EstimateCost/EstimateCostContent.tsx, packages/plus/src/components/EstimateCost/EstimateCostProvider.tsx, packages/plus/src/components/EstimateCost/types.ts, packages/plus/src/components/Navigation/NavigationProvider.tsx
- Bug
Fix typing on prop `locales` from `<Navigation />` component
=> fix(Navigation): bad typing on locales

.changeset/pretty-bats-beam.md, .changeset/twenty-badgers-boil.md, packages/form/src/components/SelectInputFieldV2/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/SelectInputV2/DropdownOption.tsx, packages/ui/src/components/SelectInputV2/__stories__/resources.tsx, packages/ui/src/components/SelectInputV2/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/SelectInputV2/__tests__/resources.tsx, packages/ui/src/components/SelectInputV2/types.ts, packages/ui/src/components/UnitInput/__tests__/__snapshots__/index.test.tsx.snap
- Enhancement
- description of an option can be a ReactNode not just a string
- tooltip can be added on an option
1. Improve types
2. Improve component
3. Update snapshots
=> feat(SelectInputV2): allow description as ReactNode and tooltip

.changeset/quick-masks-accept.md, packages/form/src/components/TextInputFieldV2/index.tsx
- Bug
`shouldUnregister` prop was not forwarded.
=> fix(TextInputFieldV2): add shouldUnregister prop

scripts/create-css-variables.mjs
- Bug
Some tokens had duplicated `;` at the end of the line
=> fix: duplicated semicolon in css tokens

.changeset/soft-bats-train.md, packages/ui/src/components/MenuV2/Item.tsx, packages/ui/src/components/MenuV2/__stories__/Playground.stories.tsx, packages/ui/src/components/MenuV2/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/Tabs/__tests__/__snapshots__/index.test.tsx.snap
- Bug
MenuV2 : the text was centered instead of being on the left
| :--- | :--------: | :--------: |
| url  | <img width="199" alt="Capture d’écran 2024-06-12 à 14 56 22" src="https://github.com/scaleway/ultraviolet/assets/106706307/9f59f1fd-9683-4f51-a017-cd32557bea9d"> | <img width="199" alt="Capture d’écran 2024-06-12 à 14 56 04" src="https://github.com/scaleway/ultraviolet/assets/106706307/77cb4681-b0b5-4c76-a571-a0c343626f08"> |
=> fix: menu alignment

.github/workflows/release.yml
- CI
This PR should fix CI not running on release PR. By using PAT tokens instead of github tokens.
=> ci: fix ci not running on release pr

.github/workflows/ci.yml, .storybook/components/DocsContainer.tsx, biome.json, package.json, tsconfig.json
- CI
Currently we have no check on CI on format so anyone can push it's own format and it will work just fine. I added a new CI job that will run `biome ci .` which will check there is no format errors.
=> ci: add new action checking format using biome ci

.changeset/funny-sloths-divide.md, packages/ui/src/components/SelectInputV2/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/SelectInputV2/index.tsx
- Bug
`SelectInputV2` was missing `sentiment` on it's label. By default text inherit the color from a parent.
=> fix(SelectInputV2): label to have correct color

.changeset/lemon-pots-try.md, packages/form/src/components/DateField/__tests__/__snapshots__/index.test.tsx.snap, packages/form/src/components/TextInputFieldV2/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/DateInput/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/SearchInput/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/SelectInputV2/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/TextInputV2/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/TextInputV2/index.tsx
- Bug
With an error,  the width of `<TextInputFieldV2 />` changed.
| url  | <img width="559" alt="Capture d’écran 2024-06-21 à 12 02 20" src="https://github.com/scaleway/ultraviolet/assets/106706307/9a911ba9-3295-427d-a553-491ee7ea738d"> | <img width="559" alt="Capture d’écran 2024-06-21 à 12 02 28" src="https://github.com/scaleway/ultraviolet/assets/106706307/d2c0fa43-d30f-443f-87a1-70c8e3c3f3f3"> |
=> fix(TextInputV2): width with error prop

.changeset/silly-penguins-heal.md, packages/ui/src/components/SearchInput/Key.tsx, packages/ui/src/components/SearchInput/KeyGroup.tsx, packages/ui/src/components/SearchInput/__stories__/Disabled.stories.tsx, packages/ui/src/components/SearchInput/__stories__/Error.stories.tsx, packages/ui/src/components/SearchInput/__stories__/Shortcut.stories.tsx, packages/ui/src/components/SearchInput/__stories__/index.stories.tsx, packages/ui/src/components/SearchInput/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/SearchInput/__tests__/index.test.tsx, packages/ui/src/components/SearchInput/index.tsx, packages/ui/src/components/SearchInput/types.ts, packages/ui/src/components/TextInputV2/index.tsx
- Feature
Design update and new features on `<SearchInput />`:
- New design for the input with a simpler and cleaner look.
- New prop `shortcut`, when set to true the input will be focusable with `Ctrl + K` on Windows and Linux and `Cmd + K` on macOS. It also add the shortcut into the input placeholder.
| url  | ![Screenshot 2024-06-28 at 10 46 09](https://github.com/scaleway/ultraviolet/assets/15812968/9b0fa199-bd02-4b23-bea6-54be0fcd01b6) | ![Screenshot 2024-06-28 at 10 46 14](https://github.com/scaleway/ultraviolet/assets/15812968/bd5d0723-993f-4db0-a9c7-559766d3614b) |
=> feat(SearchInput): redesign and new shortcut feature

.changeset/tough-pianos-agree.md, packages/form/src/components/SelectInputFieldV2/index.tsx
- Bug
Add missing `tooltip` prop to `SelectInputFieldV2`.
=> fix(SelectInputFieldV2): add tooltip

.changeset/seven-laws-pump.md, packages/ui/src/components/Modal/Disclosure.tsx, packages/ui/src/components/Modal/index.tsx, packages/ui/src/components/Modal/types.ts
- Bug
`<Modal />`: when a modal is closed, focus should be on disclosure 
This also fixes the issue for MenuV2.item when it is used with a modal.
=> fix(Modal): focus on close

.github/workflows/teardown_pull_request.yml
- Bug
Seems like the secret tokens we have doesn't have the right permission to remove deployment. Let's use the one provided by Github directly.
=> ci: fix teardown error

.changeset/sharp-suits-knock.md, packages/ui/src/components/SearchInput/index.tsx
- Bug
Only handle `KeyboardEvent` in `SearchInput`.
When an user click on a autocomplete item, an `Event` with type `keydown` is dispatched.
Now the `SearchInput` component doesn't handle these events.
=> fix(SearchInput): only handle keyboard event

.github/workflows/deploy-storybook.yml, .github/workflows/teardown_pull_request.yml
- Enhancement
DNS deployment is quite long with serverless and we don't really need it in preprod. So I added a condition to remove it when the branch is not main.
=> ci: remove dns deployement on preprod env

.changeset/young-berries-dress.md, packages/form/src/components/KeyValueField/__tests__/index.test.tsx, packages/form/src/components/KeyValueField/index.tsx, packages/form/src/components/TextAreaField/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/TextArea/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/TextArea/index.tsx, packages/ui/src/components/UnitInput/index.tsx
- Bug
`KeyValueField` :  prop `readonly` becomes `readOnly` to fit React standard
`TextArea`: `data-readOnly` becomes `data-readonly` to fit standard
=> fix: readOnly case

.changeset/curvy-rocks-film.md, packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Regular.test.tsx.snap, packages/plus/src/components/EstimateCost/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/Badge/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/Badge/index.tsx, packages/ui/src/components/Tabs/__tests__/__snapshots__/Tab.test.tsx.snap, packages/ui/src/components/Tabs/__tests__/__snapshots__/index.test.tsx.snap
- Bug
Fix `<Badge />` font weight on each sizes
| url  | <img width="251" alt="Screenshot 2024-07-18 at 14 20 19" src="https://github.com/user-attachments/assets/1e9b9576-d308-411b-a7ff-71a7742028c4"> | <img width="283" alt="Screenshot 2024-07-18 at 14 20 25" src="https://github.com/user-attachments/assets/e303230c-325a-463f-ace8-c2f54b7f8807"> |
=> fix(badge): font weight and sizes

.github/workflows/ci.yml
It seems that setting root zone alias doesn't work properly. The alias already exists and we try to add it again throwing that error: 
> http error 409: ALIAS has to be unique and cannot have multiple values(ALIAS:ultravioletjxvhzygy-main.functions.fnc.fr-par.scw.cloud. and ALIAS:ultravioletjxvhzygy-main.functions.fnc.fr-par.scw.cloud.)
I'm disabling `root_zone` from github action. The root alias will be defined manually (only once is needed) in the DNS until the github action is fixed.
=> ci: fix dns setting not working properly with github action

.changeset/poor-scissors-talk.md, packages/ui/src/components/TagList/__stories__/ParentWithWidth.stories.tsx, packages/ui/src/components/TagList/__stories__/Template.stories.tsx, packages/ui/src/components/TagList/__stories__/index.stories.tsx, packages/ui/src/components/TagList/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/TagList/__tests__/index.test.tsx, packages/ui/src/components/TagList/index.tsx, packages/ui/src/components/Text/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/Text/__tests__/index.test.tsx
- Enhancement
Allow TagList component to to not overflow it's parent by ignoring the provided threshold in this case.
When we have only one tag to show, we show and we ellipsis it with a tooltip so the TagList dosen't overflow as well.
|   Before   |      After |
| :--------: | ---------: |
| ![before](https://github.com/user-attachments/assets/0fe1004a-1a4c-4a5c-862d-45b508d0776c) | ![after](https://github.com/user-attachments/assets/07b04a87-7edc-4cd7-8746-88368fc19009) |
=> refactor: improve tagslist component

.changeset/weak-buckets-build.md, packages/icons/src/components/Icon/__stories__/Size.stories.tsx, packages/icons/src/components/Icon/index.tsx
- Bug
- Fix story of icon for sizes
- Fix default name being restored to "alert"
Before:
After:
=> fix(Icon): update docs and restore default name to alert

.changeset/breezy-boats-complain.md, packages/ui/src/components/DateInput/index.tsx
There is a type issue with `showMonthYearPicker` apparently being required.
=> fix(DateInput): wrong type

.changeset/lovely-terms-roll.md, packages/ui/src/components/CopyButton/__stories__/Children.stories.tsx, packages/ui/src/components/CopyButton/__stories__/index.stories.tsx, packages/ui/src/components/CopyButton/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/CopyButton/__tests__/index.test.tsx, packages/ui/src/components/CopyButton/index.tsx
- Enhancement
Add prop `children` to `<CopyButton />` component to set a text into the button
=> feat(CopyButton): add children prop

.changeset/nasty-ads-tap.md, packages/form/src/components/SubmitErrorAlert/__tests__/__snapshots__/index.test.tsx.snap, packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Regular.test.tsx.snap, packages/ui/src/components/Alert/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/Alert/index.tsx
- Refactor
Changed spacing of Alert title from 4px to 12px.
| url  | <img width="967" alt="Screenshot 2024-07-24 at 14 15 17" src="https://github.com/user-attachments/assets/ae94864d-2063-471a-900e-f46966ac7734"> | <img width="962" alt="Screenshot 2024-07-24 at 14 15 23" src="https://github.com/user-attachments/assets/87615b53-e738-43fc-bbc3-a664d6428ad3"> |
=> fix(Alert): change title gap

.changeset/bright-bottles-pay.md, packages/form/src/components/TagInputField/index.tsx
- Bug
TagInputField no checking each values independently when using `regex` parameter.
=> fix(TagInputField): regex to work with array of string value

.changeset/young-toes-rescue.md, packages/form/src/components/DateField/__tests__/__snapshots__/index.test.tsx.snap, packages/form/src/components/SelectInputFieldV2/__tests__/__snapshots__/index.test.tsx.snap, packages/form/src/components/TextInputFieldV2/__tests__/__snapshots__/index.test.tsx.snap, packages/form/src/components/UnitInputField/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/DateInput/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/SearchInput/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/SelectInputV2/SelectBar.tsx, packages/ui/src/components/TagInput/index.tsx, packages/ui/src/components/TextInputV2/__stories__/Template.stories.tsx, packages/ui/src/components/TextInputV2/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/TextInputV2/index.tsx, packages/ui/src/components/UnitInput/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/UnitInput/index.tsx
- Refactor
Refactor all inputs to have `8px` padding in `small` size instead of `16px`
| url  | <img width="952" alt="Screenshot 2024-07-25 at 14 52 37" src="https://github.com/user-attachments/assets/b506089f-2e02-426c-92e3-62de9042433f"> | <img width="955" alt="Screenshot 2024-07-25 at 14 52 42" src="https://github.com/user-attachments/assets/89b6b435-f5f4-4074-a635-d232c9ea7a9a"> |
| url  | <img width="793" alt="Screenshot 2024-07-25 at 15 04 07" src="https://github.com/user-attachments/assets/25398053-3e7c-4811-afd5-452e4aa26881"> | <img width="785" alt="Screenshot 2024-07-25 at 15 04 12" src="https://github.com/user-attachments/assets/8c77a784-86d4-4dc5-b4b9-fa8a51e6e8a4"> |
| url  | <img width="963" …
=> refactor(inputs): to have 8px padding instead of 16px in small sizes

.changeset/itchy-buckets-enjoy.md, packages/form/src/components/DateField/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/DateInput/__stories__/Months.stories.tsx, packages/ui/src/components/DateInput/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/DateInput/index.tsx
- Bug
Fix `<DateInput />` colors when having both props `selectsRange` and `showMonthYearPicker`
| url  | <img width="329" alt="Screenshot 2024-07-26 at 11 14 49" src="https://github.com/user-attachments/assets/b56218dc-ac99-4fd2-9f67-323761720752"> | <img width="342" alt="Screenshot 2024-07-26 at 11 15 18" src="https://github.com/user-attachments/assets/2ce6a15d-506e-4cd7-a093-8eaf264e63b5"> |
=> fix(DateInput): to have correct color when month only and range

.changeset/chatty-cups-drive.md, packages/form/src/components/SelectInputFieldV2/__tests__/__snapshots__/index.test.tsx.snap, packages/form/src/components/UnitInputField/__tests__/__snapshots__/index.test.tsx.snap, packages/icons/src/components/Icon/index.tsx, packages/ui/src/components/Button/index.tsx, packages/ui/src/components/UnitInput/__tests__/__snapshots__/index.test.tsx.snap
- Enhancement
add `aria-label` to `Icon` for accessibility purpose.
=> feat: add aria label to svg for accessibility purpose

.changeset/mean-trainers-mate.md, packages/form/src/components/TextInputFieldV2/index.tsx
- Bug
minLength not transmitted to errors
1.
2.
3.
=> fix(textinputv2): reset minLength in errors

.changeset/lucky-islands-worry.md, packages/ui/src/components/Modal/components/Dialog.tsx
- Bug
Stop propagation on mousedown in Modal.
=> fix(Modal): stop propagation on mousedown

.changeset/large-cycles-visit.md, packages/form/src/components/SelectableCardField/__tests__/__snapshots__/index.test.tsx.snap, packages/form/src/components/SelectableCardField/__tests__/index.test.tsx, packages/form/src/components/SelectableCardGroupField/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/Radio/index.tsx, packages/ui/src/components/SelectableCard/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/SelectableCard/__tests__/index.test.tsx, packages/ui/src/components/SelectableCard/index.tsx, packages/ui/src/components/SelectableCardGroup/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/SwitchButton/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/SwitchButton/index.tsx
- Refactor
Our current `SelectableCard` and `SwitchButton` doesn't show a proper outline border when tab is used on them. I fixed it.
| url  | <img width="1048" alt="Screenshot 2024-08-29 at 15 47 36" src="https://github.com/user-attachments/assets/db96523e-1a8e-4438-a3c9-1bac3d93a55b"> | <img width="1055" alt="Screenshot 2024-08-29 at 15 47 22" src="https://github.com/user-attachments/assets/7e054613-3203-4bd0-ad94-6d84ea6e40a5"> |
=> refactor: improve accessibility focus on selectable card

.changeset/many-bottles-exercise.md, examples/next-login/src/constants.tsx, packages/form/src/components/NumberInputFieldV2/__stories__/Required.stories.tsx, packages/form/src/components/NumberInputFieldV2/index.tsx, packages/form/src/mocks/mockErrors.ts, packages/form/src/types.ts, packages/form/src/validators/isInteger.ts, packages/ui/src/__stories__/Tools/ThemeGenerator/index.tsx, utils/test/src/vitest/helpers/index.tsx
- Enhancement
When step is set, if step is an integer or not we do not check the value depending. We could make the thing a little more precise and block the submit if the step is not an integer and neither the value. We do not check the precision of the float but only if it's an integer or not.
=> fix(NumberInputFieldV2): to validate or not depending if step is integer

.changeset/many-grapes-rule.md, packages/form/src/components/SubmitErrorAlert/__tests__/__snapshots__/index.test.tsx.snap, packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Regular.test.tsx.snap, packages/ui/src/components/Alert/__stories__/Link.stories.tsx, packages/ui/src/components/Alert/__stories__/index.stories.tsx, packages/ui/src/components/Alert/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/Alert/index.tsx
- Bug
Make children of alert take full width for cases like links. It will be easier to do so. I added an example in the storybook.
=> fix(Alert): take full with for link case

.changeset/fuzzy-jokes-press.md, packages/ui/src/components/Snippet/__stories__/LongMultiline.stories.tsx, packages/ui/src/components/Snippet/__stories__/LongMultilineExpanded.stories.tsx, packages/ui/src/components/Snippet/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/Snippet/index.tsx
- Bug
Snippet didn't take in account new lines in it's children.
| url  | <img width="1049" alt="Screenshot 2024-09-11 at 16 21 49" src="https://github.com/user-attachments/assets/90517e8f-df43-47b6-8bdb-a6dc43cff6dd"> | <img width="1092" alt="Screenshot 2024-09-11 at 16 21 57" src="https://github.com/user-attachments/assets/5718cfbc-9bbd-4223-ba47-5cd85652fd8c"> |
=> fix(Snippet): to respect carriage return

.changeset/real-walls-own.md, packages/ui/src/components/Card/__stories__/Active.stories.tsx, packages/ui/src/components/Card/__stories__/AdvancedHeader.stories.tsx, packages/ui/src/components/Card/__stories__/Disabled.stories.tsx, packages/ui/src/components/Card/__stories__/SubHeader.stories.tsx, packages/ui/src/components/Card/__stories__/index.stories.tsx, packages/ui/src/components/Card/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/Card/__tests__/index.test.tsx, packages/ui/src/components/Card/index.tsx
- Enhancement
`<Card />`: new prop `subHeader`, deprecated prop `isActive` (use instead prop `active`) and various enhancements
/!\ **Please note that the styling of the header and subHeaders are incorrect in storybook due to global styling. Please see advanced header/subHeaders for an accurate styling** /!\
Card:
1. Added prop `subHeader` (ReactNode)
2. `isActive` (deprecated) => `active` 
3. Color fixes (header, disabled state)
=> feat(Card): new prop subHeader

.changeset/stupid-bats-brake.md, packages/form/src/components/SelectInputFieldV2/__tests__/__snapshots__/index.test.tsx.snap, packages/form/src/components/UnitInputField/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/SelectInputV2/Dropdown.tsx, packages/ui/src/components/SelectInputV2/DropdownOption.tsx, packages/ui/src/components/SelectInputV2/SelectBar.tsx, packages/ui/src/components/SelectInputV2/__stories__/EmptyState.stories.tsx, packages/ui/src/components/SelectInputV2/__stories__/Grouped.stories.tsx, packages/ui/src/components/SelectInputV2/__stories__/resources.tsx, packages/ui/src/components/UnitInput/__tests__/__snapshots__/index.test.tsx.snap
- Bug
1. No empty group name (container hidden)
2. Dropdown positioning (resize with select bar)
3. LoadMore appear at the end of the dropdown (not at the end of every group)
4. Truncation in dropdown and select bar (ellipsis)
5. Various style enhancement (group name color, states success, neutral, error, disabled, read-only when hover/focus/active)
| Truncation  | <img width="277" alt="Capture d’écran 2024-09-16 à 16 58 08" src="https://github.com/user-attachments/assets/0006fc71-f388-4be1-8f68-810c65568250"> | <img width="212" alt="Capture d’écran 2024-09-16 à 16 57 14" src="https://github.com/user-attachments/assets/95d558b0-859e-42ec-b006-4fd829973024"> |
=> fix: bug fixes on selectinputV2

.changeset/perfect-balloons-tell.md, .changeset/quiet-files-camp.md, packages/form/src/components/TextAreaField/__stories__/SubmitOnEnter.stories.tsx, packages/form/src/components/TextAreaField/__stories__/index.stories.tsx, packages/form/src/components/TextAreaField/__tests__/__snapshots__/index.test.tsx.snap, packages/form/src/components/TextAreaField/__tests__/index.test.tsx, packages/form/src/components/TextAreaField/index.tsx, packages/ui/src/components/TextArea/index.tsx
- Enhancement
Add props `onKeyDown` and `submitOnEnter` on `<TextAreaField />`
=> fix(TextArea): add new props for allowing submit on enter pressed

.changeset/dirty-planes-breathe.md, packages/ui/src/components/SelectInputV2/Dropdown.tsx
- Bug
Fix `<SelectInputV2 />` resize issue in a modal
| url  | ![Screenshot 2024-09-30 at 09 04 17](https://github.com/user-attachments/assets/4fde431a-ae66-4db7-b4f6-b44a0a801d59) | ![Screenshot 2024-09-30 at 09 13 36](https://github.com/user-attachments/assets/8dcbb003-bd9d-4054-90e4-0b7e3e2dffa8) |
=> fix(SelectInputV2): resize issue in a modal

packages/icons/src/components/ProductIcon/Icon.tsx, packages/icons/src/components/ProductIcon/__stories__/Sizes.stories.tsx
Display all available sizes on storybook for ProductIcon components.
| url  | ![Screenshot 2024-09-30 at 09 25 45](https://github.com/user-attachments/assets/f082d949-f575-4155-9781-f89de2a7c5c7) | ![Screenshot 2024-09-30 at 09 25 48](https://github.com/user-attachments/assets/487cdd6d-a553-420f-a1b5-0b5016005003) |
=> docs(ProductIcon): display all sizes on storybook

.changeset/nasty-stingrays-retire.md, packages/form/src/components/TextAreaField/index.tsx, packages/ui/src/components/TextArea/index.tsx
- Bug
Fix `<TextArea />` to have either label or aria-label as required prop
=> fix(TextArea): make label or aria label required

.changeset/sixty-ladybugs-know.md, packages/ui/src/components/SelectableCard/__stories__/Illustration.stories.tsx, packages/ui/src/components/SelectableCard/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/SelectableCard/index.tsx
- Bug
Bug on selectable card when illustration is set and content is too small the alignement is wrong.
| url  | <img width="956" alt="Screenshot 2024-10-09 at 11 21 04" src="https://github.com/user-attachments/assets/f75a5100-12ba-47ab-ab9d-588d66edfb35"> |  <img width="978" alt="Screenshot 2024-10-09 at 11 20 49" src="https://github.com/user-attachments/assets/5c9070f3-c787-4d1f-85fd-f4bf9157417f"> |
=> fix(SelectableCard): illustration not aligned on the right when small content

.changeset/wet-hairs-search.md, packages/ui/src/components/SelectInputV2/Dropdown.tsx, packages/ui/src/components/SelectInputV2/__stories__/Multiselect.stories.tsx, packages/ui/src/components/SelectInputV2/__stories__/resources.tsx
- Bug
SelectInputV2 regression: the group name is shown while its content is empty. It shouldn't.
| url  | <img width="2207" alt="Screenshot 2024-10-09 at 14 30 26" src="https://github.com/user-attachments/assets/a7574b09-7f90-49fa-9474-9ba41bd14fdb"> | <img width="2213" alt="Screenshot 2024-10-09 at 14 30 34" src="https://github.com/user-attachments/assets/08891f7a-7000-48d8-aa2c-24388b963f60"> |
=> fix(SelectInputV2): group shown when empty

.changeset/slimy-birds-dream.md, packages/ui/src/components/SelectInputV2/SelectBar.tsx, packages/ui/src/components/UnitInput/__tests__/__snapshots__/index.test.tsx.snap
- Bug
SelectInputV2 should display the placeholder if none of selected values match in options 
1. Improve the condition in SelectBar
2.
3.
=> fix(SelectInputV2): display placeholder if no values match in options

.changeset/moody-parrots-clean.md, packages/form/src/components/SelectInputFieldV2/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/SelectInputV2/Dropdown.tsx, packages/ui/src/components/UnitInput/__tests__/__snapshots__/index.test.tsx.snap
- Bug
Div with option role should be accessible when testing but by changing for a div instead of button the prop disabled is not valid anymore.
I replaced disabled for aria-disabled and the data-selected for aria-selected which is valid for multi select or single select
=> fix(SelectInputV2): accessibility for selected and disabled on div with option role

packages/plus/src/components/Conversation/__stories__/Message.stories.tsx, packages/plus/src/components/Conversation/__stories__/Playground.stories.tsx
Conversation documentation was a bit broken with the avatar not working. Also I improved the view by adding a "real" conversation example.
| url  | ![Screenshot 2024-10-16 at 14 36 12](https://github.com/user-attachments/assets/e5e54f70-141c-4728-905e-bd8639538756) | ![Screenshot 2024-10-16 at 14 36 17](https://github.com/user-attachments/assets/262e8844-a3b1-4b70-b22a-fe71ef51508f) |
=> docs: fix conversation avatar and implement real talks

.changeset/forty-eyes-argue.md, packages/form/src/components/CheckboxField/__tests__/__snapshots__/index.test.tsx.snap, packages/form/src/components/CheckboxField/index.tsx
- Bug
Bug on CheckboxField not adding children
=> fix(CheckboxField): no working properly with children

.changeset/nice-pigs-hang.md, packages/form/src/components/SelectInputFieldV2/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/SelectInputV2/Dropdown.tsx, packages/ui/src/components/SelectInputV2/__stories__/Playground.stories.tsx, packages/ui/src/components/UnitInput/__tests__/__snapshots__/index.test.tsx.snap
- Enhancement
To set minimum of 320px on select input v2
| url  | ![Screenshot 2024-10-21 at 14 34 16](https://github.com/user-attachments/assets/e5ee74e5-aecc-48f6-bc2e-5de9148ecf56) | ![Screenshot 2024-10-21 at 14 34 22](https://github.com/user-attachments/assets/47f36fc5-91b5-4ad4-a095-5f8240ad3941) |
=> fix(SelectInputV2): dropdown to be at least 320px

.changeset/gorgeous-plants-reflect.md, packages/form/src/components/TextInputFieldV2/index.tsx, packages/ui/src/components/TextInputV2/index.tsx
- Bug
forward onKeyUp/onKeyDown to TextInput
1.
2.
3.
=> fix(textinput): onKeyUp/Down not forwarded

.changeset/quick-elephants-retire.md, packages/ui/src/components/TagList/__stories__/ParentWithWidth.stories.tsx, packages/ui/src/components/TagList/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/TagList/index.tsx
- Bug
fix TagList not adding ellipsis to single long tag
| Before | After |
| ----- | ----- |
| ![Screenshot 2024-10-29 at 00 19 40](https://github.com/user-attachments/assets/1c292a8e-8426-4739-831e-ba2a536cf646) | ![Screenshot 2024-10-29 at 00 16 36](https://github.com/user-attachments/assets/b6dd3063-4c0a-416b-942a-9e968927af31) |
=> fix: taglist not adding ellipsis to single long tag

.changeset/honest-eggs-sleep.md, packages/form/src/components/TagInputField/index.tsx
- Bug
`ariaLabel` was not forwarded from TagInputField to TagInput
=> fix: forward aria-label

.changeset/wicked-baboons-dream.md, packages/ui/src/components/SwitchButton/index.tsx
- Bug
fix SwitchButton not updating local value when value prop change
https://github.com/user-attachments/assets/01820de3-1720-4f54-a2b1-8cd2c7460695
=> fix(SwitchButton): not updating local value when value prop change

.changeset/soft-swans-cry.md, packages/ui/src/components/MenuV2/index.tsx, packages/ui/src/components/Popover/index.tsx, packages/ui/src/components/Popup/helpers.ts, packages/ui/src/components/Popup/index.tsx, packages/ui/src/components/SelectInputV2/Dropdown.tsx, packages/ui/src/components/SelectInputV2/__stories__/Playground.stories.tsx
- Bug
- Fix SelectInputV2 to align left dropdown when the dropdown is bigger than the input
- Implement `align` into `Popup` to choose to align the popup depeding on children (only `start` and `center` available for now)
| using align `start` on popover  | <img width="873" alt="Screenshot 2024-11-05 at 11 28 23" src="https://github.com/user-attachments/assets/5af1e1fc-4217-431e-a613-473d26b1ef92"> | <img width="695" alt="Screenshot 2024-11-05 at 11 26 44" src="https://github.com/user-attachments/assets/974a382f-c6c7-4da6-935f-d5e93a9ca005"> |
| SelectInputV2  | <img width="1056" alt="Screenshot 2024-11-05 at 11 43 39" src="https://github.com/user-attachments/assets/a628cb8d-633c-4cca-ab88-6fb262482d08"> | <img …
=> fix(SelectInputV2): fix dropdown align on left

.github/workflows/ci.yml, package.json, packages/form/package.json, packages/icons/package.json, packages/illustrations/package.json, packages/plus/package.json, packages/themes/package.json, packages/ui/package.json, pnpm-lock.yaml, turbo.json
- CI
Implement Publint in our github action to check on package.json and avoid making mistakes while exporting packages.
=> ci: add publint to check on package json and avoid mistakes

.storybook/components/globalStyle.ts, packages/ui/src/components/SelectInputV2/__stories__/resources.tsx
Fix docs container not to apply global margin on stories.
| url  | <img width="332" alt="Screenshot 2024-11-12 at 14 25 31" src="https://github.com/user-attachments/assets/618b7980-3333-4164-8f2c-750496a17101"> | <img width="353" alt="Screenshot 2024-11-12 at 14 25 35" src="https://github.com/user-attachments/assets/601d4e5c-acd2-423f-9173-f84667893951"> |
=> docs(storybook): fix margins set by docs container

.changeset/weak-kings-taste.md, packages/plus/src/components/Navigation/__stories__/Playground.stories.tsx, packages/plus/src/components/Navigation/components/Item.tsx
- Bug
Bug on Navigation allowing users to pin more product than the limit.
Before:
https://github.com/user-attachments/assets/9307563d-6372-4026-8ea2-7c54895a06c1
After:
https://github.com/user-attachments/assets/76b485bf-7515-469d-b0d0-527d67af587c
=> fix(Navigation): pin button disabled still working

.changeset/orange-pots-explain.md, packages/plus/src/components/ContentCard/__tests__/__snapshots__/index.test.tsx.snap, packages/plus/src/components/ContentCardGroup/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/List/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/Skeleton/Donut.tsx, packages/ui/src/components/Skeleton/Line.tsx, packages/ui/src/components/Skeleton/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/Table/__tests__/__snapshots__/index.test.tsx.snap
- Bug
Due to px to rem migration the skeleton is broken, I fixed it.
| url  | <img width="1036" alt="Screenshot 2024-11-19 at 11 25 51" src="https://github.com/user-attachments/assets/96470d9e-2c38-49f6-ad2a-177bab9f8f24"> | <img width="1030" alt="Screenshot 2024-11-19 at 11 25 57" src="https://github.com/user-attachments/assets/b98f0347-2574-4833-8db3-bf5368c08295"> |
=> fix(Skeleton): due to px to rem migration skeleton is broken

.changeset/strong-dancers-repeat.md, packages/form/src/components/DateField/__stories__/MinMaxDateRange.stories.tsx, packages/form/src/components/DateField/__stories__/index.stories.tsx, packages/form/src/validators/maxDate.ts, packages/form/src/validators/minDate.ts
- Bug
`minDateValidator` and `maxDateValidator` were not supporting dates range causing a validation error each time we were using DateField with both `selectRanges` and `minDate/maxDate`
=> fix(Form): fix minDate and maxDate validators

.changeset/spicy-months-sniff.md, packages/plus/src/components/EstimateCost/Components/CustomUnitInput.tsx, packages/plus/src/components/EstimateCost/Components/Item.tsx, packages/plus/src/components/EstimateCost/Components/Region.tsx, packages/plus/src/components/EstimateCost/Components/Regular.tsx, packages/plus/src/components/EstimateCost/Components/Strong.tsx, packages/plus/src/components/EstimateCost/Components/Zone.tsx, packages/plus/src/components/EstimateCost/EstimateCostContent.tsx, packages/plus/src/components/EstimateCost/__stories__/Unit.stories.tsx, packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Item.test.tsx.snap, packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Regular.test.tsx.snap, packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Stepper.test.tsx.snap, packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Strong.test.tsx.snap, packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Unit.test.tsx.snap, packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Zone.test.tsx.snap, packages/plus/src/components/EstimateCost/__tests__/__snapshots__/index.test.tsx.snap
- Enhancement
Improving estimate cost render that can cost a lot on a big page. 
Before:
https://github.com/user-attachments/assets/bc30dfda-d566-4504-a2bd-983577c8201d
After:
https://github.com/user-attachments/assets/96608e9a-a265-4299-9109-37c6722a836f
You can see time unit and not related items is not re-rendering when changing one
=> refactor(EstimateCost): improve re-render performances

.changeset/hot-rockets-watch.md, packages/ui/src/components/Snippet/__stories__/Multiline.stories.tsx, packages/ui/src/components/Snippet/__stories__/Prefixes.stories.tsx, packages/ui/src/components/Snippet/__stories__/Rows.stories.tsx, packages/ui/src/components/Snippet/index.tsx
- Bug
Fix snippet height problem due to switch from pixels to rem
| Before  |  <img width="1124" alt="Capture d’écran 2024-11-25 à 14 36 49" src="https://github.com/user-attachments/assets/40ebfea9-b92f-42f7-8bdd-3a6b1c203539"> |  
| :--- | :--------: |
| After  | <img width="1124" alt="Capture d’écran 2024-11-25 à 14 36 15" src="https://github.com/user-attachments/assets/f78ca66a-86ad-4f88-a00f-717783b0738f">  |
=> fix(Snippet): snippet height

.storybook/main.ts, .storybook/manager.ts, package.json, packages/form/src/components/NumberInputField/__stories__/index.stories.tsx, packages/form/src/components/SelectInputField/__stories__/index.stories.tsx, packages/form/src/components/TextInputField/__stories__/index.stories.tsx, packages/ui/src/__stories__/ComponentState/ComponentState.tsx, packages/ui/src/components/Avatar/__stories__/index.stories.tsx, packages/ui/src/components/Dialog/__stories__/index.stories.tsx, packages/ui/src/components/LineChart/__stories__/index.stories.tsx, packages/ui/src/components/Menu/__stories__/index.stories.tsx, packages/ui/src/components/NumberInput/__stories__/index.stories.tsx, packages/ui/src/components/NumberInputV2/__stories__/index.stories.tsx, packages/ui/src/components/PasswordStrengthMeter/__stories__/index.stories.tsx, packages/ui/src/components/PieChart/__stories__/index.stories.tsx, packages/ui/src/components/Row/__stories__/index.stories.tsx, packages/ui/src/components/Row/index.tsx, packages/ui/src/components/SelectInput/__stories__/index.stories.tsx, packages/ui/src/components/SelectInputV2/__stories__/index.stories.tsx, packages/ui/src/components/Slider/__stories__/index.stories.tsx, packages/ui/src/components/StepList/__stories__/index.stories.tsx, packages/ui/src/components/TextInput/__stories__/index.stories.tsx, packages/ui/src/components/TextInputV2/__stories__/index.stories.tsx, packages/ui/src/components/TimeInput/__stories__/index.stories.tsx, pnpm-lock.yaml
Update component state page to make it work and add tags so they are visible in the menu.
| url  | <img width="1025" alt="Screenshot 2024-11-19 at 18 18 15" src="https://github.com/user-attachments/assets/c330b18e-8746-4cdf-87d1-cf6b510184b6"> | <img width="1039" alt="Screenshot 2024-11-19 at 18 18 03" src="https://github.com/user-attachments/assets/f54c4242-b210-4ce4-b4dd-d8f84787d520"> |
=> docs(storybook): add tags and fix component state

.changeset/smooth-cougars-bake.md, packages/fonts/src/fonts.css
One of the link for font is wrongly written, my bad.
=> fix(fonts): wrongly written semi bold

.changeset/five-radios-tie.md, packages/ui/src/components/Banner/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/Banner/index.tsx
- Enhancement
Refactor `image` prop in `<Banner />` component. If the prop is a string, it will be displayed inside img tag so you can set a url to simply set the image.
=> refactor(Banner): add image in a img tag when is a string

.changeset/short-balloons-fetch.md, examples/next-advanced/next-env.d.ts, examples/next-login/next-env.d.ts, examples/next-simple/next-env.d.ts, packages/ui/package.json, packages/ui/src/components/List/ListContext.tsx, packages/ui/src/components/List/Row.tsx, packages/ui/src/components/List/SkeletonRows.tsx, packages/ui/src/components/List/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/List/index.tsx, packages/ui/src/components/List/types.ts, packages/ui/src/components/Table/Row.tsx, packages/ui/src/components/Table/TableContext.tsx, packages/ui/src/components/Table/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/Table/index.tsx, packages/ui/src/components/Table/types.ts
- Bug
- Add a container around List and Table to handle overflow X with a scroll. If not the table and list are overflowing their parents which is not good.
- Add `columns` into the provider so we can set `width`, `min-width` and `max-width` to each `td` in the table. Not only for the `th`. This enforce consistent aspect of the table / list.
=> fix: table and list with a container around for overflow

.changeset/nice-dots-pull.md, packages/ui/src/components/Slider/__stories__/Options.stories.tsx, packages/ui/src/components/Slider/components/DoubleSlider.tsx, packages/ui/src/components/Slider/components/SingleSlider.tsx
- Bug
Slider options are not updating because we are using `useRef` in stead of `useCallback` on the `onChange` causing trouble for `SliderField`.
=> fix(Slider): bug when options are changing

.changeset/dry-cats-hope.md, packages/ui/src/components/List/HeaderRow.tsx, packages/ui/src/components/List/Row.tsx, packages/ui/src/components/List/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/List/constants.tsx, packages/ui/src/components/List/index.tsx, packages/ui/src/components/Table/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/Table/index.tsx
- Bug
Hide scroll bar on overflow x if there is no overflow.
| url  | ![Screenshot 2024-12-16 at 08 55 32](https://github.com/user-attachments/assets/3f86c8f4-4886-449a-b1db-5ad81d648fbd) | ![Screenshot 2024-12-16 at 08 55 39](https://github.com/user-attachments/assets/64be13e4-fcd6-4113-8dcf-d8d67fb54447) |
| url | ![Screenshot 2024-12-16 at 11 19 17](https://github.com/user-attachments/assets/7cba74ea-7414-4b79-8560-db6382508604) | ![Screenshot 2024-12-16 at 11 19 25](https://github.com/user-attachments/assets/68f76d53-3204-4195-9353-49277a0eeba2) |
=> fix: table and list to hide scroll bar is no overflow

.changeset/mean-ways-drum.md, packages/ui/src/components/List/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/List/index.tsx, packages/ui/src/components/Table/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/Table/index.tsx
- Bug
Table and List are taking more than 100% of the container sometimes.
=> fix: table and list to take 100% of container

.changeset/strong-trains-rule.md, packages/ui/src/components/CheckboxGroup/index.tsx, packages/ui/src/components/RadioGroup/index.tsx, packages/ui/src/components/SelectableCardGroup/index.tsx, packages/ui/src/components/ToggleGroup/index.tsx
- Enhancement
`<RadioGroup />`, `<SelectableCardGroup />`, `<CheckboxGroup />` and `<ToggleGroup />` to accept `ReactNode` as `legend` type.
=> fix: all groups input to accept react node as legend

.changeset/beige-houses-own.md, packages/ui/src/components/Slider/__tests__/__snapshots__/doubleSlider.test.tsx.snap, packages/ui/src/components/Slider/components/DoubleSlider.tsx
- Bug
- 
The thumb of the double slider was not centered on firefox when there was a tooltip. Fixed it
Before : 
After :
=> fix(Slider): thumb position

.changeset/stupid-teachers-jump.md, packages/form/src/components/DateField/__tests__/__snapshots__/index.test.tsx.snap, packages/form/src/components/SelectInputFieldV2/__tests__/__snapshots__/index.test.tsx.snap, packages/form/src/components/UnitInputField/__tests__/__snapshots__/index.test.tsx.snap, packages/icons/src/components/Icon/Icon.tsx, packages/icons/src/components/Logo/Icon.tsx, packages/icons/src/components/ProductIcon/Icon.tsx, packages/plus/src/components/FAQ/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/AvatarV2/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/Chip/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/DateInput/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/List/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/SearchInput/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/SelectableCard/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/Table/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/TextInputV2/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/UnitInput/__tests__/__snapshots__/index.test.tsx.snap
- Feature
Migrate icons on new rem size instead of px.
=> feat(icons): use rem on icons

.storybook/main.ts, package.json, pnpm-lock.yaml
- Bug
For some reasons the CI building storybook takes 6h (time out of github) due to not finishing process.
This issue seems to happen since Storybook 8.4.6.
An issue is opened in storybook having the exact same problem: https://github.com/storybookjs/storybook/issues/29828
Going from react-docgen-typescript to react-docgen is not the best as we loose most of our documentation in the args table. Instead I will try the solution to override @joshwooding/vite-plugin-react-docgen-typescript in my package.json.
=> ci(storybook): fix not finishing build on ci

.storybook/preview.tsx
I added a real background on storybook stories. This seems only cool but it actually has a purpose: indicated whenever we have a background or not on our components. Our theme being full white in background we can never differentiate if we see the background of storybook or of the component.
| url  | <img width="1059" alt="Screenshot 2025-01-08 at 18 01 31" src="https://github.com/user-attachments/assets/8aa0e7e1-9fcb-43b8-8353-cc81798a3e7b" /> | <img width="1053" alt="Screenshot 2025-01-08 at 18 12 02" src="https://github.com/user-attachments/assets/28ec1f3a-85fe-418f-869f-e6ccd3fc36ff" /> |
| url  | <img width="1056" alt="Screenshot 2025-01-08 at 18 12 34" …
=> docs(storybook): add dots in background for better visual

.changeset/dirty-fishes-flash.md, packages/ui/src/components/Pagination/PaginationButtons.tsx, packages/ui/src/components/Pagination/PerPage.tsx, packages/ui/src/components/Pagination/__stories__/Controlled.stories.tsx, packages/ui/src/components/Pagination/__stories__/PerPage.stories.tsx, packages/ui/src/components/Pagination/__stories__/Playground.stories.tsx, packages/ui/src/components/Pagination/__stories__/index.stories.tsx, packages/ui/src/components/Pagination/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/Pagination/__tests__/getPageNumbers.test.ts, packages/ui/src/components/Pagination/__tests__/index.test.tsx, packages/ui/src/components/Pagination/getPageNumbers.ts, packages/ui/src/components/Pagination/index.tsx
- Refactor
Refactor and enhancement of `<Pagination />` : 
- Number of results on the bottom left 
- Number of items to display
- Styling
| url  | <img width="553" alt="Capture d’écran 2024-12-04 à 16 00 36" src="https://github.com/user-attachments/assets/c686a38f-cd04-4afc-ab9c-1432c660fc6b">|  <img width="517" alt="Capture d’écran 2024-12-04 à 16 00 02" src="https://github.com/user-attachments/assets/7f5873f2-9d46-45dd-b181-c70452d13b6b"> |
| url  | <img width="537" alt="Capture d’écran 2024-12-04 à 16 02 06" src="https://github.com/user-attachments/assets/c2816a6a-3eef-4ffb-935c-1f53d08ae8ec"> |  <img width="516" alt="Capture d’écran 2024-12-04 à 16 01 17" …
=> refactor: pagination

.changeset/thirty-glasses-rush.md, packages/form/src/components/NumberInputFieldV2/__tests__/__snapshots__/index.test.tsx.snap, packages/form/src/components/SliderField/__tests__/__snapshots__/index.test.tsx.snap, packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Stepper.test.tsx.snap, packages/ui/src/components/NumberInputV2/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/NumberInputV2/index.tsx, packages/ui/src/components/Slider/__tests__/__snapshots__/doubleSlider.test.tsx.snap, packages/ui/src/components/Slider/__tests__/__snapshots__/singleSlider.test.tsx.snap
- Bug
There was a problem with the border of `NumberInputV2` when it was disabled or read-only.
Before: 
After:
=> fix(NumberInputV2): styling when disabled

.changeset/weak-peas-marry.md, packages/ui/src/components/Slider/components/DoubleSlider.tsx, packages/ui/src/components/Slider/components/SingleSlider.tsx
- Bug
Now, when a slider is disabled, its related input(s) is(are) in a disabled state : it is still not possible to edit the slider value(s) anymore.
=> fix(Slider): disable input on disabled sliders

.changeset/angry-pears-obey.md, .changeset/blue-rules-turn.md, packages/form/src/components/VerificationCodeField/__tests__/__snapshots__/index.test.tsx.snap, packages/form/src/components/VerificationCodeField/index.tsx, packages/ui/src/components/VerificationCode/__stories__/Disabled.stories.tsx, packages/ui/src/components/VerificationCode/__stories__/Error.stories.tsx, packages/ui/src/components/VerificationCode/__stories__/Fields.stories.tsx, packages/ui/src/components/VerificationCode/__stories__/Helper.stories.tsx, packages/ui/src/components/VerificationCode/__stories__/InitialValue.stories.tsx, packages/ui/src/components/VerificationCode/__stories__/LabelDescription.stories.tsx, packages/ui/src/components/VerificationCode/__stories__/OnComplete.stories.tsx, packages/ui/src/components/VerificationCode/__stories__/Placeholder.stories.tsx, packages/ui/src/components/VerificationCode/__stories__/Required.stories.tsx, packages/ui/src/components/VerificationCode/__stories__/Size.stories.tsx, packages/ui/src/components/VerificationCode/__stories__/Success.stories.tsx, packages/ui/src/components/VerificationCode/__stories__/Type.stories.tsx, packages/ui/src/components/VerificationCode/__stories__/index.stories.tsx, packages/ui/src/components/VerificationCode/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/VerificationCode/__tests__/index.test.tsx, packages/ui/src/components/VerificationCode/index.tsx
- Refactor
Refactor VerificationCode and VerificationCodeField to follow the same props are new inputs.
=> refactor(VerificationCode): implement norm of inputs

.changeset/tasty-tables-help.md, packages/ui/src/components/Popup/helpers.ts
- Bug
Arrow of the tooltip is sometimes miss aligned with the tooltip itself.
| url  | <img width="1000" alt="Capture d’écran 2024-12-18 à 10 54 41" src="https://github.com/user-attachments/assets/609eea8e-8f9d-43b6-8cb0-d174ff137e6d" /> | ![Screenshot 2025-01-20 at 11 32 43](https://github.com/user-attachments/assets/4590b54a-3def-44ff-9b61-215f89764d10) |
=> fix(Tooltip): wrong arrow alignement due to popup

.changeset/thick-olives-refuse.md, packages/form/src/components/SelectInputFieldV2/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/Pagination/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/SelectInputV2/Dropdown.tsx, packages/ui/src/components/SelectInputV2/SearchBarDropdown.tsx, packages/ui/src/components/SelectInputV2/SelectBar.tsx, packages/ui/src/components/UnitInput/__tests__/__snapshots__/index.test.tsx.snap
- Bug
- Enhancement
`<SelectInputV2 />`: 
- onChange handle on checkboxes fix
- visual indication of focused item for keyboard users (if the element was already selected, it was not possible to see that the element had focus)
- no automatic scroll when using "enter" to select an item
Before ("Venus" has focus) : 
After (when navigating with keyboard) :
=> fix: onchange and border

.changeset/eight-pugs-share.md, packages/ui/src/components/DateInput/components/Popup.tsx
- Bug
There was an issue with max-date: since months are 0-indexed, there shouldn't be a +1 when creating a date to compute wether the "next" button is disabled or not.
Before : 
https://github.com/user-attachments/assets/8de19009-fac4-4133-9354-c78415e38157
After : 
https://github.com/user-attachments/assets/e40fd5b7-7015-4d57-9367-272d85f5a28c
=> fix(DateInput): max date bug

.changeset/witty-pumas-cheat.md, packages/ui/src/components/BarChart/index.tsx, packages/ui/src/components/LineChart/Tooltip.tsx, packages/ui/src/components/LineChart/__tests__/__snapshots__/Tooltip.test.tsx.snap, packages/ui/src/components/LineChart/index.tsx
- Bug
Fix `<BarChart />` and `<LineChart />` colors for legends and some other bugs
| url  | <img width="932" alt="Screenshot 2025-02-04 at 10 22 39" src="https://github.com/user-attachments/assets/2e153633-dd09-46be-a78a-b5177b1c898e" /> | <img width="941" alt="Screenshot 2025-02-04 at 10 22 48" src="https://github.com/user-attachments/assets/5eee882b-7a9b-4f4f-ac85-573d71b92788" /> |
| url  | <img width="949" alt="Screenshot 2025-02-04 at 10 27 05" src="https://github.com/user-attachments/assets/e4e64cc0-fc4e-4e72-a9a8-2eca42d6532c" /> | <img width="963" alt="Screenshot 2025-02-04 at 10 27 10" src="https://github.com/user-attachments/assets/bdc2e108-a0d2-424e-b247-0b0e002c3c8b" /> |
=> fix(charts): issues with dark and darker mode

.changeset/seven-insects-look.md, packages/ui/src/components/Dialog/index.tsx
- Bug
Fix `<Dialog />` component to have correct icon when sentiment is warning or danger
=> fix(Dialog): to have correct icon with sentiment danger and warning

.changeset/nervous-rings-add.md, packages/plus/src/components/Navigation/__tests__/__snapshots__/index.test.tsx.snap, packages/plus/src/components/Navigation/components/Item.tsx
- Bug
Fix `<Navigation />` icons
| url  | <img width="266" alt="Screenshot 2025-02-11 at 16 12 11" src="https://github.com/user-attachments/assets/828e22a3-3760-4fe3-b6e8-9c78ee0a412b" /> | <img width="267" alt="Screenshot 2025-02-11 at 16 12 20" src="https://github.com/user-attachments/assets/7eb4333f-ec0f-4020-8597-6ed07ce6a843" /> |
=> fix(Navigation): wrong icons and wrong size

.changeset/curvy-beers-roll.md, packages/ui/src/__stories__/migrations/MigrationIconUsages.mdx, packages/ui/src/components/Badge/__stories__/Icon.stories.tsx, packages/ui/src/components/Badge/index.tsx, packages/ui/src/components/Banner/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/Breadcrumbs/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/EmptyState/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/GlobalAlert/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/Link/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/Link/index.tsx, packages/ui/src/components/Separator/__stories__/Icon.stories.tsx, packages/ui/src/components/Separator/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/Separator/__tests__/index.test.tsx, packages/ui/src/components/Separator/index.tsx, packages/ui/src/components/Tabs/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/Toaster/__tests__/__snapshots__/index.test.tsx.snap
- Refactor
In `<Badge />` component, `icon` props is deprecated. You can directly use the imported icon you need in the children.
```tsx
// Before
import { Badge } from '@ultraviolet/ui'
<Badge icon="pencil">
Edit
</Badge>
```
```tsx
// After
import { Badge } from '@ultraviolet/ui'
import { PencilOutlineIcon } from '@ultraviolet/icons'
<Badge>
Edit <PencilOutlineIcon />
</Badge>
```
=> refactor: remove some more legacy icons and deprecated others

.changeset/cyan-pants-search.md, .changeset/slimy-laws-grab.md, packages/plus/src/components/Navigation/__stories__/Playground.stories.tsx, packages/plus/src/components/Navigation/components/Item.tsx, packages/ui/src/components/MenuV2/components/Item.tsx
- Enhancement
Improve `<Navigation.Item />` component by adding props `rel` and `target`. Previously a `href` item meant external link, it has now changed. Take this in consideration as your links might not open in a new browser and not have the external icon anymore.
New props `rel` and `target` on `<MenuV2.Item />`
=> fix(Navigation): allow better links on navigation items

.changeset/brave-guests-thank.md, e2e/tests/componentsWithinModal/test.spec.ts, packages/ui/src/components/Modal/components/Dialog.tsx
- Bug
Select input doesn't close properly in a modal (like before) this is because of a change of behavior in select input. I fixed it by removing a stop propagation in modal and limit the close on click oustide pour nested modals. Only the modal in first plan will apply the click on outside.
I also added a use case in e2e tests so we cover this case better.
=> fix(Modal): select input not closing inside modal when clicking outside

.changeset/orange-olives-search.md, packages/ui/src/components/MenuV2/MenuContent.tsx, packages/ui/src/components/MenuV2/__stories__/Playground.stories.tsx, packages/ui/src/components/MenuV2/types.ts, packages/ui/src/components/Tabs/__stories__/Showcase.stories.tsx, packages/ui/src/components/Tabs/__tests__/__snapshots__/index.test.tsx.snap
- Enhancement
- `<MenuV2 />`: now have a min and max width instead of a fixed width, `size` is deprecated
- Updated a story of Tab to show the automatic sizing of MenuV2
=> fix(Menuv2): min/max width

.changeset/little-lions-report.md, packages/ui/src/components/ProgressBar/__stories__/Label.stories.tsx, packages/ui/src/components/ProgressBar/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/ProgressBar/index.tsx
- Bug
Label not correctly set on progressBar
| url  | <img width="978" alt="Screenshot 2025-02-20 at 15 50 26" src="https://github.com/user-attachments/assets/95ad9fe0-a8e8-4aa3-b8dd-2dfbfd483c1b" /> | <img width="964" alt="Screenshot 2025-02-20 at 15 50 38" src="https://github.com/user-attachments/assets/3268983b-ce8c-4685-926c-d089dfa83640" /> |
=> fix(ProgressBar): label not correctly set in row mode

.changeset/thick-pandas-hunt.md, packages/ui/src/components/CheckboxGroup/index.tsx, packages/ui/src/components/RadioGroup/index.tsx, packages/ui/src/components/ToggleGroup/index.tsx
- Bug
When no legend is set there is a blank space
| url  | <img width="1043" alt="Screenshot 2025-02-20 at 16 07 29" src="https://github.com/user-attachments/assets/19d50724-7040-4251-81d2-6e6d84d59f48" /> | <img width="1043" alt="Screenshot 2025-02-20 at 16 07 09" src="https://github.com/user-attachments/assets/070e67c5-a7d0-4ae8-8350-14e3014b390d" /> |
=> fix: all group inputs

.changeset/sixty-nights-grab.md, packages/form/src/components/SelectInputField/__tests__/__snapshots__/index.test.tsx.snap, packages/plus/src/components/EstimateCost/__tests__/__snapshots__/CustomUnitInput.test.tsx.snap, packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Item.test.tsx.snap, packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Region.test.tsx.snap, packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Regular.test.tsx.snap, packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Stepper.test.tsx.snap, packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Strong.test.tsx.snap, packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Unit.test.tsx.snap, packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Zone.test.tsx.snap, packages/plus/src/components/EstimateCost/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/SelectInput/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/SelectInput/index.tsx
- Bug
Wrong icon size for SelectInput which can lead to display issues.
| url  | ![Screenshot 2025-03-03 at 15 18 27](https://github.com/user-attachments/assets/9fbbc3b1-66a3-4841-90c1-a930e9a56eaf) | ![Screenshot 2025-03-03 at 15 23 48](https://github.com/user-attachments/assets/0f5f369f-ec21-4a86-a8e1-a5614ee0419f) |
=> fix(SelectInput): wrong arrow size

.changeset/strange-socks-beam.md, packages/form/src/components/SliderField/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/List/ListContext.tsx, packages/ui/src/components/List/Row.tsx, packages/ui/src/components/List/__stories__/Selectable.stories.tsx, packages/ui/src/components/List/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/List/index.tsx, packages/ui/src/components/Slider/__tests__/__snapshots__/doubleSlider.test.tsx.snap, packages/ui/src/components/Slider/__tests__/__snapshots__/singleSlider.test.tsx.snap, packages/ui/src/components/Table/Row.tsx, packages/ui/src/components/Table/__stories__/Selectable.stories.tsx, packages/ui/src/components/Table/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/Table/__tests__/index.test.tsx, packages/ui/src/components/Table/index.tsx
- Enhancement
Have a more intuitive behavior when shift+click on a selectable list/table (see 2. #4625) 
1. Removed hover behavior to replace with indexes
Before: 
https://github.com/user-attachments/assets/47b96313-03f4-44d7-bf40-53895e08d137
After : 
https://github.com/user-attachments/assets/7ce7d241-69b5-449a-b329-dbcb74e407e3
=> fix: shift select

.changeset/brown-months-repeat.md, packages/form/src/components/SelectableCardField/__tests__/__snapshots__/index.test.tsx.snap, packages/form/src/components/SelectableCardGroupField/__tests__/__snapshots__/index.test.tsx.snap, packages/form/src/components/SelectableCardOptionGroupField/__tests__/__snapshots__/index.test.tsx.snap, packages/form/src/components/SwitchButtonField/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/Checkbox/index.tsx, packages/ui/src/components/Radio/index.tsx, packages/ui/src/components/SelectableCard/__stories__/Examples.stories.tsx, packages/ui/src/components/SelectableCard/__stories__/Illustration.stories.tsx, packages/ui/src/components/SelectableCard/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/SelectableCard/__tests__/index.test.tsx, packages/ui/src/components/SelectableCard/index.tsx, packages/ui/src/components/SelectableCardGroup/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/SelectableCardOptionGroup/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/SelectableCardOptionGroup/__tests__/index.test.tsx, packages/ui/src/components/SelectableCardOptionGroup/components/Option.tsx, packages/ui/src/components/SwitchButton/__tests__/__snapshots__/index.test.tsx.snap
- Bug
Current SelectableCard is hard to test especially when you try to click on the label. This was due to the `pointer-events: none;` set on checkbox and radio in order to avoid having double state change.
I fixed this issue by no triggering the event 2 times when the click is specifically on the label / input. This way we only generate one change and we don't need to add `pointer-events: none;`. I also needed to change to add an extra layer of style inside `SelectableCard` for `Checkbox` and `Radio` as we remove pointer events. We don't want the hover effects etc.
I have also reformatted internal testing to test both checkbox and radio on the same series of tests as both should work the same.
Before this was not working, it now works.
```tsx
test(`should trigger onChange when click on …
```
=> fix(SelectableCard): make label clickable by removing pointer events to none

.changeset/early-cameras-work.md, packages/ui/src/components/InfiniteScroll/__stories__/Playground.stories.tsx, packages/ui/src/components/InfiniteScroll/__stories__/SelectInput.stories.tsx, packages/ui/src/components/InfiniteScroll/__stories__/Table.stories.tsx, packages/ui/src/components/InfiniteScroll/__stories__/Template.stories.tsx, packages/ui/src/components/InfiniteScroll/__stories__/data.ts, packages/ui/src/components/InfiniteScroll/__stories__/index.stories.tsx, packages/ui/src/components/InfiniteScroll/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/InfiniteScroll/__tests__/index.test.tsx, packages/ui/src/components/InfiniteScroll/index.tsx, packages/ui/src/components/Loader/index.tsx, packages/ui/src/components/Stack/index.tsx, packages/ui/src/components/index.ts
- Feature
New component `<InfiniteScroll />` that allows you to scroll and load data infinitely.
Example with a SelectInputV2:
https://github.com/user-attachments/assets/8c70e2a8-3db0-4fd9-a972-b19f769c9ad6
Example with a Table:
https://github.com/user-attachments/assets/12362637-109c-498e-8eda-6ff583a2f66c
This pull request introduces a new `InfiniteScroll` component and includes various related updates across multiple files. The changes encompass the addition of the component, its stories, tests, and supporting data.
=> feat(InfiniteScroll): new component

.changeset/solid-socks-hunt.md, packages/plus/src/components/Navigation/components/Item.tsx, packages/plus/src/components/Navigation/components/ItemProvider.tsx, packages/plus/src/components/Navigation/components/PinnedItems.tsx
- Enhancement
Fix `Navigation.Item` not to spread `hasParent` prop into the children. Instead I made an `ItemProvider` that will act just the same. If the item detects that provider is initialised then it means it has a parent with `ItemProvider` giving same value as `hasParent`
=> fix(Navigation): implement item provider to detect parents

packages/ui/src/components/SelectableCard/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/SelectableCard/__tests__/index.test.tsx
- Tests
Add one more test for SelectableCard to test that it should also work when we get by role and with the correct name.
=> ci(SelectableCard): add test to get by role checkbox or radio

.changeset/every-pianos-hide.md, packages/ui/src/components/MenuV2/__stories__/Searchable.stories.tsx, packages/ui/src/components/MenuV2/components/Group.tsx
- Enhancement
Add prop `emptyState` on `<MenuV2.Group />` that can be usefull when searching
| url  | ![Screenshot 2025-03-14 at 16 48 49](https://github.com/user-attachments/assets/e2029917-1269-410d-9030-fb3469260743) | ![Screenshot 2025-03-14 at 16 48 41](https://github.com/user-attachments/assets/2526ef81-16d8-46e3-82ab-91d0adef93de) |
=> feat(MenuV2): add empty state on groups

.changeset/smooth-bottles-agree.md, packages/ui/src/components/InfiniteScroll/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/InfiniteScroll/index.tsx
- Enhancement
Improve InfiniteScroll accessibility
=> fix(InfiniteScroll): improve accessibility

.changeset/ripe-webs-shine.md, packages/form/src/components/SelectInputFieldV2/index.tsx
- Bug
We want to call `onChange` after the field changed.
=> fix(SelectInputFieldV2): call on change after field value change

.changeset/afraid-yaks-happen.md, packages/form/src/components/SelectableCardOptionGroupField/__stories__/OptionName.stories.tsx, packages/form/src/components/SelectableCardOptionGroupField/__stories__/index.stories.tsx, packages/form/src/components/SelectableCardOptionGroupField/__tests__/index.test.tsx, packages/form/src/components/SelectableCardOptionGroupField/index.tsx, packages/form/src/components/UnitInputField/__stories__/OptionName.stories.tsx, packages/form/src/components/UnitInputField/__stories__/index.stories.tsx, packages/form/src/components/UnitInputField/__tests__/index.test.tsx, packages/form/src/components/UnitInputField/index.tsx
- Enhancement
Add `optionName` on SelectableCardOptionGroupField to allow customising it.
=> fix(SelectableCardOptionGroupField): add new prop option name

.changeset/afraid-mails-raise.md, packages/ui/src/components/DateInput/__stories__/Size.stories.tsx, packages/ui/src/components/DateInput/index.tsx, packages/ui/src/components/TimeInputV2/__tests__/helper.test.ts, packages/ui/src/components/TimeInputV2/helpers.ts, packages/ui/src/components/TimeInputV2/index.tsx
Before DateInput was accepting string, it should be the responsibility of the form to provide a Date as a value and not a string. And should accept null, such as for TimeInput
- Bug
=> fix(dateinput): harmonized props with time input

.changeset/eager-times-watch.md, packages/form/src/components/SelectableCardField/__tests__/__snapshots__/index.test.tsx.snap, packages/form/src/components/SelectableCardGroupField/__tests__/__snapshots__/index.test.tsx.snap, packages/form/src/components/SelectableCardOptionGroupField/__tests__/__snapshots__/index.test.tsx.snap, packages/form/src/components/SwitchButtonField/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/SelectableCard/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/SelectableCard/index.tsx, packages/ui/src/components/SelectableCardGroup/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/SelectableCardOptionGroup/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/SwitchButton/__tests__/__snapshots__/index.test.tsx.snap
- Bug
In some case the parent of the selectable card is not relative and the component inherit from it. Causing issues displaying radio and checkboxes ticks.
=> fix(SelectableCard): make parent container relative

.changeset/dark-kings-travel.md, packages/ui/src/components/Toaster/index.tsx
- Enhancement
Remove option that makes the toaster not close when out of window or when hovered and remove draggable option.
=> fix(ui): toaster remove blocking auto closing options

.changeset/moody-books-care.md, packages/ui/src/components/List/HeaderRow.tsx, packages/ui/src/components/List/SkeletonRows.tsx, packages/ui/src/components/List/__tests__/__snapshots__/index.test.tsx.snap
- Bug
There was a `<div>` inside a `<tr>`, which is not allowed
=> fix(List): error div in tr

.changeset/late-coins-love.md, packages/form/src/components/SwitchButtonField/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/SwitchButton/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/SwitchButton/index.tsx
- Bug
SwitchButton wrong style due to SelectableCard changes.
| url  | ![Screenshot 2025-04-14 at 11 26 26](https://github.com/user-attachments/assets/b0dc8517-a167-48a7-8ffb-a6ddc65d7415) | ![Screenshot 2025-04-14 at 11 26 29](https://github.com/user-attachments/assets/bd310901-b645-4779-afd0-d7b476585048) |
=> fix(SwitchButton): relative card is breaking the display

.changeset/thin-pugs-drive.md, packages/ui/src/components/UnitInput/index.tsx
- Bug
Unit input select is disabled when there is only one option
=> fix(UnitInput): not to be disabled when only one option

.changeset/warm-wombats-kiss.md, packages/ui/src/components/UnitInput/index.tsx
- Bug
UnitInput not changing value when controlled as `useEffect` is missing for it.
=> fix(UnitInput): value to change in controlled

utils/test/src/vitest/setup.ts
Fix ci by forcing UTC time zone for vitest
=> ci: fix date field to force utc zone in vitest

.changeset/big-candies-dream.md, packages/ui/src/components/SelectInputV2/SearchBarDropdown.tsx
- Bug
Remove uncaught input error due to special characters
Sanitize `SearchBarDropdown` by escaping special characters
| url  | ![image](https://github.com/user-attachments/assets/ffe28952-08d7-4c90-8c7c-1dccd75e3811) |  |
=> fix(SelectInputV2): sanitize SearchBarDropdown

.changeset/wicked-nights-slide.md, packages/form/src/components/SelectInputFieldV2/__tests__/__snapshots__/index.test.tsx.snap, packages/form/src/components/SelectInputFieldV2/index.tsx
Forgotten `portalTarget` on `SelectInputV2`. I added prop spread so we can't forget to add the props in the field components. FYI a migration onto that is coming for fields to always spread props.
=> fix(SelectInputFieldV2): spread props to avoid missing some of them

.changeset/wicked-yaks-clap.md, packages/plus/src/components/EstimateCost/Components/Unit.tsx, packages/plus/src/components/EstimateCost/__stories__/Unit.stories.tsx, packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Unit.test.tsx.snap
- Bug
`EstimateCost.Unit` doesn't change the state according to it's `EstimateCost.Item` parent.
Before:
https://github.com/user-attachments/assets/c3d3065b-8abb-4a55-a959-8b989ac52405
After:
https://github.com/user-attachments/assets/abaa194e-ee7d-4692-9cd8-21f7e3ec9eb1
=> fix(EstimateCost): fix unit state

.changeset/five-bars-yawn.md, packages/plus/src/components/Navigation/__stories__/Playground.stories.tsx, packages/plus/src/components/Navigation/components/Item.tsx
- Enhancement
Improve performances on Navigation when pinned feature is off.
=> fix(Navigation): do not register item if pinned items feature is off

.changeset/proud-things-live.md, packages/plus/src/components/CodeEditor/CodeEditor.tsx, packages/plus/src/components/CodeEditor/__stories__/CopyButton.stories.tsx, packages/plus/src/components/CodeEditor/__stories__/Disabled.stories.tsx, packages/plus/src/components/CodeEditor/__stories__/Template.stories.tsx, packages/plus/src/components/CodeEditor/__stories__/index.stories.tsx, packages/plus/src/components/CodeEditor/__tests__/index.test.tsx
- Enhancement
- Migration
- Refactor
`<CodeEditor />`: 
- **BREAKING** Rename prop `title` to `label` and change style
- New prop `helper`
- New prop `disabled`
- New prop `copyButton`
- Update component style to match ultraviolet theme (the component always uses Dark Theme colors)
Before : 
After :
=> feat(CodeEditor): various improvements

.github/workflows/release.yml, .github/workflows/sync-main-to-beta.yml
- CI
- New job that will create a PR when an update is available on main and beta branch needs to be sync. It will only be triggered if the beta branch exists.
- Added beta branch in the release github action so it will open a PR when something is merged into it and release when the release PR is merged.
=> ci: beta sync with main and releases

.changeset/nine-teeth-wave.md, packages/plus/src/components/Navigation/__stories__/Playground.stories.tsx, packages/plus/src/components/Navigation/__tests__/__snapshots__/index.test.tsx.snap, packages/plus/src/components/Navigation/__tests__/index.test.tsx, packages/plus/src/components/Navigation/components/Item.tsx, packages/plus/src/components/Navigation/components/PinnedItems.tsx
- Refactor
⚠️ BREAKING CHANGES:
`Navigation.Item`: change in the types and deprecated category icon props:
- `categoryIcon`: type switch from union type to react node to allow you adding your own category icon.
```tsx
// Before
<Navigation.Item categoryIcon="useCase" />
// After
import { UseCaseCategoryIcon } from '@ultraviolet/icons/category'
<Navigation.Item categoryIcon={<UseCaseCategoryIcon />} />
```
- `categoryIconVariant`: has been removed. Use the variant of the icon component itself.
```tsx
// Before
<Navigation.Item categoryIcon="useCase" categoryIconVariant="neutral" />
// After
import { UseCaseCategoryIcon } from '@ultraviolet/icons/category'
<Navigation.Item categoryIcon={<UseCaseCategoryIcon variant="neutral" />} />
```
=> refactor(Navigation): deprecated and change some types category icon items

.changeset/polite-keys-crash.md, packages/form/package.json, pnpm-lock.yaml
Revert react hook form failing since 7.56.X
=> revert(react-hook-form): useless re-render

.changeset/flat-kids-like.md, packages/form/src/components/TextInputField/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/Notice/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/Notice/index.tsx, packages/ui/src/components/TextInput/__tests__/__snapshots__/index.test.tsx.snap
- Bug
There was a small alignement issue with the icon on Notice component
| url  | ![Screenshot 2025-05-09 at 11 01 33](https://github.com/user-attachments/assets/0e68f843-c883-47a3-9b7e-c6166f8ef802) | ![Screenshot 2025-05-09 at 11 01 37](https://github.com/user-attachments/assets/4a829454-51f3-4938-85ea-f98a35071c96) |
=> fix(Notice): icon size

examples/next/src/components/GithubAndDocumentationButtons.tsx, examples/next/src/components/Header.tsx, examples/next/src/pages/_app.tsx, examples/next/src/pages/advanced/OpenSource.tsx, examples/next/src/pages/login/login.tsx, examples/next/src/pages/login/signup.tsx
Fix examples to use new icons.
=> docs(next): update example with next

.changeset/plenty-peas-smoke.md, packages/ui/src/components/TextInputV2/index.tsx
- Bug
Allow clearable for uncontrolled TextIputv2
=> fix(TextInputV2): allow clearable for uncontrolled

.changeset/tidy-comics-talk.md, packages/form/src/components/SelectInputFieldV2/__tests__/__snapshots__/index.test.tsx.snap, packages/form/src/components/SelectableCardOptionGroupField/__tests__/__snapshots__/index.test.tsx.snap, packages/form/src/components/UnitInputField/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/Pagination/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/Popup/index.tsx, packages/ui/src/components/SelectInputV2/SelectBar.tsx, packages/ui/src/components/SelectInputV2/__stories__/SelectAll.stories.tsx, packages/ui/src/components/SelectInputV2/__stories__/resources.tsx, packages/ui/src/components/SelectInputV2/types.ts, packages/ui/src/components/SelectableCardOptionGroup/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/UnitInput/__tests__/__snapshots__/index.test.tsx.snap
- Bug
Fix overflow with multiselect.
Now it:
- takes the correct size of the tag (instead of computing an approx. one)
-  adds ellipses instead of hiding tags when possible (ellipsis for the last element when it can be large enough and not overflow) 
-  never adds  a "+1" tag when only one element is selected (will add ellipsis if the element can not be shown completely)
=> fix(SelectInputV2): overflow

.changeset/cold-icons-stick.md, packages/ui/src/components/MenuV2/__stories__/Searchable.stories.tsx, packages/ui/src/components/MenuV2/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/MenuV2/__tests__/index.test.tsx, packages/ui/src/components/MenuV2/components/Item.tsx, packages/ui/src/components/MenuV2/helpers.ts
- Enhancement
Add props `searchText` on `MenuV2` and add limitation on searchable of this component.
=> fix(menuV2): search text prop

.changeset/fancy-mice-start.md, packages/ui/src/components/Modal/components/Disclosure.tsx, packages/ui/src/components/Modal/index.tsx, packages/ui/src/components/Modal/types.ts
- Bug
`Modal`: return focus to disclosure element when closing the modal
=> fix(Modal): focus on disclosure

.changeset/dirty-breads-joke.md, packages/ui/src/components/List/HeaderRow.tsx, packages/ui/src/components/List/Row.tsx, packages/ui/src/components/List/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/List/index.tsx
- Bug
Issue with List on safari the border is not correctly set. This is because safari doesn't support absolute pseudo element within the Table. To fix this I had to add the border on each table cell instead.
| Safari  | ![Screenshot 2025-06-17 at 17 00 13](https://github.com/user-attachments/assets/98be45b3-01c0-4777-a8d5-719d1a810296) | ![Screenshot 2025-06-17 at 17 00 32](https://github.com/user-attachments/assets/dd93f542-988a-4332-ae2b-229b76581e3e) |
| Safari  | ![Screenshot 2025-06-17 at 17 00 25](https://github.com/user-attachments/assets/11f32933-4d1e-4d87-b56c-10ca31641c87) | ![Screenshot 2025-06-17 at 17 00 39](https://github.com/user-attachments/assets/6905a567-21b4-42a0-a4c9-12009a25f01d) |
=> fix(list): border issues on safari

.changeset/rude-paths-stick.md, packages/plus/src/components/Navigation/components/Item.tsx
- Bug
`Navigation`: active state should work when the Item is wrapped in a Link/NavLink (React router)
Before : <img width="209" alt="Capture d’écran 2025-06-18 à 17 31 05" src="https://github.com/user-attachments/assets/8c1bc0da-d896-4751-bf30-0dfcdd3cde5f" />
After: <img width="209" alt="Capture d’écran 2025-06-18 à 17 31 28" src="https://github.com/user-attachments/assets/67dfa1d1-4fe7-479e-b730-5029bcb1c5dc" />
=> fix(Navigation): active state

.changeset/tender-regions-share.md, packages/ui/src/components/Expandable/__stories__/NestedExpandable.stories.tsx, packages/ui/src/components/Expandable/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/Expandable/index.tsx, packages/ui/src/components/Snippet/__tests__/__snapshots__/index.test.tsx.snap
- Bug
`Expandable`: no animation on first render
Before: 
https://github.com/user-attachments/assets/989e6072-39b3-41b8-8606-f9b9739ae855
After: 
https://github.com/user-attachments/assets/768433e4-8109-4a40-9382-af3a36dc0767
=> fix(Expandable): animation on first render

.changeset/spotty-weeks-unite.md, packages/ui/src/components/Button/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/Button/__tests__/index.test.tsx, packages/ui/src/components/Button/index.tsx, packages/ui/src/components/List/Row.tsx
- Bug
Allow DND kit to work with `List` and `Button` : 
- `List.Row` now supports "style" and "data-dragging" props ;
- For Security group we don't display header but the List component add to much spaces ;
- Can disable overlay with `pointer-events: none` on `List.Row` ;
- List.Row do not allow data-dragging prop
- `Button` can have props "aria-describedby", "aria-disabled", "aria-pressed", "aria-roledescription", "onPointerDown" and "onKeyDown" to work with DND kit
=> fix: add prop to allow dnd

.changeset/fast-results-run.md, packages/ui/src/components/Modal/components/Disclosure.tsx
- Bug
`Modal`: disclosure onClick should work even when it changes
Before: 
https://github.com/user-attachments/assets/03d49b79-6bb5-47dd-a506-931fa2e789c9
After: 
https://github.com/user-attachments/assets/d98fd8b0-becd-48cb-9869-d55d243f6013
=> fix(Modal): disclosure onClick

.changeset/great-tables-kick.md, packages/ui/src/components/Link/index.tsx
- Enhancement
add prop `aria-current` on Link.
=> fix(link): add aria current

.changeset/little-badgers-go.md, packages/form/src/components/CheckboxField/__tests__/__snapshots__/index.test.tsx.snap, packages/form/src/components/CheckboxGroupField/__tests__/__snapshots__/index.test.tsx.snap, packages/form/src/components/SelectableCardField/__tests__/__snapshots__/index.test.tsx.snap, packages/form/src/components/SelectableCardGroupField/__tests__/__snapshots__/index.test.tsx.snap, packages/form/src/components/SelectableCardOptionGroupField/__tests__/__snapshots__/index.test.tsx.snap, packages/form/src/components/SwitchButtonField/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/Card/__stories__/Active.stories.tsx, packages/ui/src/components/Card/index.tsx, packages/ui/src/components/Checkbox/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/Checkbox/__tests__/index.test.tsx, packages/ui/src/components/Checkbox/index.tsx, packages/ui/src/components/CheckboxGroup/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/CopyButton/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/CopyButton/__tests__/index.test.tsx, packages/ui/src/components/CopyButton/index.tsx, packages/ui/src/components/LineChart/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/List/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/SelectableCard/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/SelectableCardGroup/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/SelectableCardOptionGroup/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/Skeleton/Slider.tsx, packages/ui/src/components/Skeleton/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/SwitchButton/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/Table/__tests__/__snapshots__/index.test.tsx.snap
- Refactor
**BREAKING CHANGES**
Deprecated props removed:
- `Card`: prop "isActive" removed -> use "active" instead
- `Checkbox`: props "progress" and "size" removed
- `CopyButton`: prop "noBorder" removed -> use "bordered" instead
=> feat: remove deprecated props Card, Checkbox and Copybutton

.changeset/eighty-walls-greet.md, packages/form/package.json, pnpm-lock.yaml
This reverts commit ce31fd7bca3b9243b6254e0d60999d26cf51c8f5.
The update of react hook form create issues.
=> Revert "fix(deps): update dependency react-hook-form to v7.56.3 (#5097)"

.changeset/whole-wasps-cough.md, packages/ui/src/components/CheckboxGroup/__stories__/Template.stories.tsx, packages/ui/src/components/CheckboxGroup/index.tsx
- Bug
Fix add missing `tooltip` prop on `CheckboxGroup.Checkbox`
=> fix(checkbox): add missing tooltip prop

.changeset/heavy-toys-tap.md, packages/ui/src/components/TextArea/index.tsx
- Bug
`TextArea`: height should adapt even without prop value
=> fix(TextArea): height without prop value

.changeset/shaky-kings-deny.md, packages/ui/src/components/Menu/MenuContent.tsx
=> fix(Menu): menu closes when hover leaves

.changeset/tasty-tables-type.md, packages/ui/src/components/Drawer/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/Modal/ModalProvider.tsx, packages/ui/src/components/Modal/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/Modal/components/Dialog.tsx, packages/ui/src/components/SelectInput/Dropdown.tsx
- Bug
Removing the id on modal backdrop and use the context with ref instead.
=> fix(Modal): remove id on modal and select input scrolll

biome.json
- Bug
Fix includes to avoid checking format on coverage files
=> chore: do not check format on autogenerated files in coverage

.changeset/two-goats-doubt.md, packages/form/src/components/SelectInputField/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/SelectInput/Dropdown.tsx, packages/ui/src/components/SelectInput/SelectBar.tsx, packages/ui/src/components/SelectInput/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/SelectInput/__tests__/index.test.tsx
- Enhancement
SelectInput is polluting the dom with hidden tag element in order to calculate the size. Instead I remove it once the size is calculated and to avoid blinks I used `useLayoutEffect`.
| url  | <img width="1082" height="110" alt="Screenshot 2025-07-31 at 14 57 59" src="https://github.com/user-attachments/assets/e95e3056-7715-4944-bebf-792c34d5f125" /> |  <img width="1098" height="120" alt="Screenshot 2025-07-31 at 14 58 10" src="https://github.com/user-attachments/assets/41b69777-65f1-4f7f-b60c-a1c674b1706c" /> |
=> fix(SelectInput): handle better tag display

.changeset/neat-regions-repair.md, packages/ui/src/theme/ThemeProvider.tsx
- Bug
There is an issue with the current theme provider, it will add the styles only at the level of the children it is being called at. The main issue is that modals and other portal elements are at the same level and cannot get the correct styles.
| url  | <img width="559" height="331" alt="Screenshot 2025-08-06 at 16 08 33" src="https://github.com/user-attachments/assets/1e6375a2-bdc4-4474-80e7-59ee9e4c4a81" /> | <img width="504" height="324" alt="Screenshot 2025-08-06 at 16 08 46" src="https://github.com/user-attachments/assets/4416f59a-57a5-46bc-abf9-030285aa8e03" /> |
=> fix: theme provider to inject theme in head

.changeset/fluffy-bananas-type.md, packages/ui/src/components/Snippet/__stories__/Multiline.stories.tsx, packages/ui/src/components/Snippet/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/Snippet/index.tsx
- Enhancement
Remove `::after` element on most of the line in multiline to improve selection
=> fix(Snippet): remove after element on most of the lines

.storybook/preview.tsx
- Bug
Style with Vanilla-Extract did not work on individual stories
Before: 
After:
=> fix: style on individual stories

.changeset/many-items-wear.md, packages/plus/src/components/CodeEditor/CodeEditor.tsx
- Feature
add a prop to show/hide line numbers
| url  | <img width="1174" height="403" alt="Screenshot 2025-08-14 at 13 43 49" src="https://github.com/user-attachments/assets/5e733a01-fe49-49d1-a6a4-eb0990090621" /> | <img width="1174" height="403" alt="Screenshot 2025-08-14 at 13 43 34" src="https://github.com/user-attachments/assets/734c5daa-a758-4f87-9aa7-deccee03d2a8" /> |
=> feat(CodeEditor): add lineNumbers prop

.changeset/eight-wings-add.md, packages/ui/src/components/NumberInput/index.tsx
- Bug
NumberInput bug on max disabled and min disabled on re-render
=> fix(NumberInput): side buttons not working on re-render

.changeset/good-hoops-invite.md, packages/plus/src/components/Navigation/__tests__/__snapshots__/index.test.tsx.snap, packages/plus/src/components/Navigation/components/Item.tsx, packages/ui/src/components/ExpandableCard/index.tsx, packages/ui/src/components/Stack/index.tsx, packages/ui/src/components/Stack/types.ts
- Bug
Navigation needs to use polymorphic component such as Stack in order to provide a more accurate tag in it's content.
With the migration of vanilla extract it is now hard to achieve that, so I added a prop `as` only for this component.
| url  | <img width="950" height="811" alt="Screenshot 2025-09-16 at 16 17 00" src="https://github.com/user-attachments/assets/45e2b504-c55c-4ebe-aa53-1588a1f86815" /> | <img width="955" height="812" alt="Screenshot 2025-09-16 at 16 17 05" src="https://github.com/user-attachments/assets/9d721c58-d8e3-4a89-9d9a-ab4a1234478d" /> |
=> fix(Navigation): add as prop on stack polymorphic component

.changeset/wild-houses-camp.md, packages/form/src/components/TagInputField/__tests__/__snapshots__/index.test.tsx.snap, packages/plus/src/components/Conversation/__tests__/__snapshots__/index.test.tsx.snap, packages/plus/src/components/FAQ/__tests__/__snapshots__/index.test.tsx.snap, packages/plus/src/components/SteppedListCard/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/Card/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/Card/index.tsx, packages/ui/src/components/Card/styles.css.ts, packages/ui/src/components/DateInput/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/SelectInput/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/Tag/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/Tag/index.tsx, packages/ui/src/components/Tag/styles.css.ts, packages/ui/src/components/TagInput/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/TagList/__tests__/__snapshots__/index.test.tsx.snap
- Refactor
Refactor components `Tag` and `Card` to use vanilla-extract instead of Emotion
=> refactor: card and tag vanilla extract

.changeset/plain-windows-add.md, packages/form/src/components/SelectInputField/__tests__/__snapshots__/index.test.tsx.snap, packages/form/src/components/SelectableCardOptionGroupField/__tests__/__snapshots__/index.test.tsx.snap, packages/form/src/components/UnitInputField/__tests__/__snapshots__/index.test.tsx.snap, packages/plus/src/components/EstimateCost/__tests__/__snapshots__/CustomUnitInput.test.tsx.snap, packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Item.test.tsx.snap, packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Region.test.tsx.snap, packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Regular.test.tsx.snap, packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Stepper.test.tsx.snap, packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Strong.test.tsx.snap, packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Unit.test.tsx.snap, packages/plus/src/components/EstimateCost/__tests__/__snapshots__/Zone.test.tsx.snap, packages/plus/src/components/EstimateCost/__tests__/__snapshots__/index.test.tsx.snap, packages/plus/src/components/OrderSummary/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/Pagination/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/SelectInput/SelectBar.tsx, packages/ui/src/components/SelectInput/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/SelectableCardOptionGroup/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/UnitInput/__tests__/__snapshots__/index.test.tsx.snap
- Bug
`SelectInput`: placeholder should be a `span` instead of a `p`
=> fix(SelectInput): html tag options

.changeset/public-fans-dance.md, packages/form/src/components/DateInputField/__tests__/__snapshots__/index.test.tsx.snap, packages/form/src/components/Submit/__tests__/__snapshots__/index.test.tsx.snap, packages/form/src/components/TextInputField/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/DateInput/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/SearchInput/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/SearchInput/index.tsx, packages/ui/src/components/SelectInput/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/TextInput/__stories__/Size.stories.tsx, packages/ui/src/components/TextInput/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/TextInput/constants.ts, packages/ui/src/components/TextInput/index.tsx, packages/ui/src/components/TextInput/styles.css.ts
- Refactor
Refactor text input to vanilla extract
=> refactor(TextInput): migrate to vanilla extract

.changeset/ten-wolves-battle.md, packages/form/src/components/SwitchButtonField/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/SwitchButton/FocusOverlay.tsx, packages/ui/src/components/SwitchButton/Option.tsx, packages/ui/src/components/SwitchButton/__tests__/__snapshots__/index.test.tsx.snap, packages/ui/src/components/SwitchButton/index.tsx, packages/ui/src/components/SwitchButton/styles.css.ts
- Refactor
Refactor component `SwitchButton` to use vanilla extract instead of Emotion
=> refactor(SwitchButton): vanilla extract
